### ISSUE TITLE
[1.10.2]  Mapped chunks being overwritten by those of other dimensions.

### ISSUE THREAD

**Issue by InThayne** [TeamJM/journeymap#10]
Mod Pack:  Age of Engineering 1.1.2 
JourneyMap Version:  1.10.2-5.5.2
Forge Version:  12.18.3.2511

Random chunks in the overworld maps are being visually overwritten by chunks from the Aroma mining dimension (and vice versa).  Both sides are team claimed and at least some of the chunks are also loaded (FTBUtils).  These chunks will swap back and forth on occasion, switching between showing one dimension or the other.

**Comment by techbrew-mc** [comment]
I have yet to be able to recreate this behavior in a dev environment (running a server on the same machine).  Could you whitelist me on your server so I can see it in action?

**Comment by techbrew-mc** [comment]
The issue was with chunkloaded chunks. Fixed in 5.6.0b1
