### ISSUE TITLE
remove support for pixelmon sprites -_-

### ISSUE THREAD

**Issue by KhaozFrost** [TeamJM/journeymap#101]
In most recent versions of Journeymap you added support for pixelmon sprites and we're not able to remove this support or turn it off. It was perfectly fine when they  were just dots, but even in the server sided settings we can't disable this correctly. It will still show them the sprites on their first login; but if they relog it will disable them based on the settings on the server.

**Comment by mysticdrew** [comment]
You can turn them to dots in the settings. Mob Display: Icons or Dots. You turned them to Icons, not us. They are default Dots. 
Secondly, the next version servers side disabling will work again.
