### ISSUE TITLE
[1.12.2] [Beta] Random disconnect from server, ConcurrentModificationException GetAllPlayersThread

### ISSUE THREAD

**Issue by Chicken-Bones** [TeamJM/journeymap#102]
#### JourneyMap Version:

`journeymap-1.12.2-5.5.5b4`

#### Forge Version:

`1.12.2-14.23.5.2836`

#### Describe the problem in repeatable steps:

1. Connect to server with multiple players (happens more frequently with 3 than 2)
2. Play for anywhere from 30 seconds to 45 minutes
3. Get disconnected with https://pastebin.com/MymPPuLU in the log
4. Reconnect (game doesn't crash) and return to step 2

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

None

**Comment by mysticdrew** [comment]
This will be fixed in b5. 
If you wish to get a test version of b5 before it is released on curse please ping me in our discord.
