### ISSUE TITLE
[Feature Request] Add ability to save online maps

### ISSUE THREAD

**Issue by DedMaxim** [TeamJM/journeymap#104]
I don't know if it's even possible, but i came out with idea to input online-map into client. All the servers use the same api to make online-maps, so I thought that it's possible to import it into client by pasting link into the mod.
Example of such online-map map.slimeside.ru

**Comment by mysticdrew** [comment]
I don't fully understand.

**Comment by DedMaxim** [comment]
Sorry for my english. Um, ok, I'll try to explain. In Journeymap there is a button, which can create a page in real browser with map from minecraft. I believe it uses google maps api for that. Is it possible to reverse it? A lot of servers have such maps of their worlds on their web-sites. So, is it possible to put that online-map into JourneyMap?

**Comment by mysticdrew** [comment]
Not really possible with the way the map data is currently implemented.
