### ISSUE TITLE
[1.12.2] debug info of the mod blocks the view when in F3 debug screen

### ISSUE THREAD

**Issue by RazDavid5029** [TeamJM/journeymap#106]
#### JourneyMap Version:

1.12.2-5.5.4

#### Forge Version:

1.12.2-14.23.3.2655

#### Describe the problem in repeatable steps:

1. Click F3 to view the debug info screen
2. a bunch of info starting with [JM] will appear
3. the [JM] info lines will blocks your view

#### Relevant errors from .minecraft/journeymap/journeymap.log:
No relevant errors from the above.
-- When log level set to 'Off' do not display JM debug info in the debug(F3) screen.

**Comment by mysticdrew** [comment]
Added in 5.5.5 beta 6
