### ISSUE TITLE
[1.12.2] Please save Map data in World Save Folder

### ISSUE THREAD

**Issue by MeinKraft** [TeamJM/journeymap#107]
#### JourneyMap Version:

1.12.2-5.5.5b5

#### Forge Version:

1.12.2 - 14.23.5.2836

#### Describe the problem in repeatable steps:

1. Create a world, go explore a little
2. Delete the world
3. Map data remains in Journeymap/save/sp folder

Could you please save the SP map data in the World/Save folder. That way when we delete worlds the map data is deleted too.

Otherwise we have to go through the Journeymap/Data/SP folder and delete now unused maps.  This can cause newly created worlds to use the wrong map data. eg: Create a world called World1, go explore, delete it. Create a new world called World1 and it will load up old map data for the first World1. Make sense?

Thankyou for your time

**Comment by mysticdrew** [comment]
I will not do this. 
In the fullscreen map, there is an option to delete current map data. There is also an auto map (ssp only) button that will rebuild your map data. 

Or name your worlds differently.
