### ISSUE TITLE
Crash when setting keybind

### ISSUE THREAD

**Issue by Testo0987** [TeamJM/journeymap#108]
#### Instructions for Submitting an Issue
1. Ask for help on Discord (https://discord.gg/eP8gE69) #support if you're unsure this is a new issue.
2. Please search for existing issues before submitting a new one.
3. Please add the correct MC<version> label to your issue. Example: "[1.12.2] Waypoints are upside down"
4. Completely fill out the template below. Failure to do so is likely to get the issue closed immediately.
5. Prove you read these instructions by deleting this section before submitting. ;)
---
  
#### JourneyMap Version:

`Example: 1.12.1-5.5.0`

#### Forge Version: 1.12.2 v2815

`Example: 1.12.1-14.22.1.2478`

#### Describe the problem in repeatable steps:

1. I have the mod controlling installed
2. Set Journeymap keybind to "J"
3. Clicked done

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

https://pastebin.com/KiaCdBrc

**Comment by mysticdrew** [comment]
Remove Journeymap-api from your mods folder. IT IS NOT A MOD
