### ISSUE TITLE
[1.12.1] Feature Request: ability to select local time shown in 12h or 24h format on minimap.

### ISSUE THREAD

**Issue by 71Baker** [TeamJM/journeymap#11]
#### JourneyMap Version:

Any, from 1.12.1 if possible.

#### Forge Version:

As relevant.

#### Describe the problem in repeatable steps:

1. QOL

**Comment by BrainStone** [comment]
I'd apprechiate this feature too.

**Comment by Possemaster** [comment]
Yes please, and is it possible to have the time corrected.
Now **/Set Time 0** is setting the clock to 00:00 while it should be 06:00 or 06:00 AM.
A simple transcode of game time to actual morning/midday/evening/night would be a liitle more realistic.

**Comment by mysticdrew** [comment]
completed check #67 for details
