### ISSUE TITLE
journey map not working near spawn but if i go away from spawn a couple feet (minimap works fine) (its when u press j that it loads up blue screen near spawn)      1.12.2

### ISSUE THREAD

**Issue by zacharyhenry** [TeamJM/journeymap#110]
#### Instructions for Submitting an Issue
1. Ask for help on Discord (https://discord.gg/eP8gE69) #support if you're unsure this is a new issue.
2. Please search for existing issues before submitting a new one.
3. Please add the correct MC<version> label to your issue. Example: "[1.12.2] Waypoints are upside down"
4. Completely fill out the template below. Failure to do so is likely to get the issue closed immediately.
5. Prove you read these instructions by deleting this section before submitting. ;)
---
  
#### JourneyMap Version:

`Example: 1.12.1-5.5.0`

#### Forge Version:

`Example: 1.12.1-14.22.1.2478`

#### Describe the problem in repeatable steps:

1.
2.
3.

**Comment by mysticdrew** [comment]
Update Journeymap, update Forge. Add details the content, not the title.... makes it very hard to read.

**Comment by zacharyhenry** [comment]
forge is

**Comment by mysticdrew** [comment]
delete the api from your mods folder, it is not a mod. I will not help you anymore until you follow the template for issue reporting.
