### ISSUE TITLE
journeymap doesnt load in spawn area

### ISSUE THREAD

**Issue by zacharyhenry** [TeamJM/journeymap#113]
#### JourneyMap Version:

 1.12.2-5.5.5b6- being affected
testing  1.12.2-5.5.5b7
#### Forge Version:

 1.12.2-14.23.5.2838

#### Describe the problem in repeatable steps:

1.when i press J the map just loads bluescreen near spawn area
2.but when i go exploring it works fine

**Comment by mysticdrew** [comment]
Bluescreen means you have the journeymap-api in your mods folder or Optifine causes the issue also.

**Comment by zacharyhenry** [comment]
thanks

**Comment by zacharyhenry** [comment]
But it works fine when I'm a couple blocks away from the spawn area

**Comment by zacharyhenry** [comment]
Does it make a difference if I'm not connected to wifi

**Comment by zacharyhenry** [comment]
Map wont load until I'm 445m from my house

**Comment by mysticdrew** [comment]
Your issue is likely caused by Optifine.  You may want to come into discord if you need help removing it.

**Comment by zacharyhenry** [comment]
I'm changing everything in my base to minecraft blocks or biome of plenty

**Comment by zacharyhenry** [comment]
Does ur mod work with The Creeping Nether Mod

**Comment by zacharyhenry** [comment]
I found out the problem and its neither of what u told me it might be

I know this might be weird but I have a underground buildcraft mining area
and there was a water fall and it was making journey map lag when I got rid
of it journey map started working and optifine does to work with ur mod
because I'm still using it

**Comment by zacharyhenry** [comment]
Plus I used the journeymap v 1.12.2-5.5.4 when I changed everything

Now I'm going to download journeymap 1.12.2-5.5.5b7 to test everything to
make sure everything works

**Comment by zacharyhenry** [comment]
OptiFine v

1.12.2_HD_U_E3

**Comment by zacharyhenry** [comment]
Works fine now yea I fixed it no more bluescreen

Versions that I checked to make sure it works
1.12.2-5.5.4
1.12.2-5.5.5b6
1.12.2-5.5.5b7
