### ISSUE TITLE
Journeymap not working with buildcraft quarry

### ISSUE THREAD

**Issue by zacharyhenry** [TeamJM/journeymap#114]
#### JourneyMap Version:

1.12.2-5.5.5b7

#### Forge Version:
1.12.2-14.23.5.2838

#### Describe the problem in repeatable steps:

1.when I place down a buildcraft quarry and open Journeymap using J makes it go to bluescreen
3.Redstone engine
4.Stirling engine
5.Combustion engine
6.Creative engine
7.Item.volume_box.name (dont put this in ur world u cant get rid of it makes it where fullscreen map doesn't work at all)
8.Mining Well
9.Distiller

**Comment by zacharyhenry** [comment]
Do u want me to make a video to show u what its doing

**Comment by mysticdrew** [comment]
Sure

**Comment by zacharyhenry** [comment]
Ok buildcraft looking into it for yea

**Comment by zacharyhenry** [comment]
https://github.com/BuildCraft/BuildCraft/issues/4199

They already  had a issue so I'm in this issue now

**Comment by zacharyhenry** [comment]
had something to do with optifine
