### ISSUE TITLE
Waypoints Dimension scrollbar doesn't work

### ISSUE THREAD

**Issue by cmkaas** [TeamJM/journeymap#116]
Minecraft version 1.12.2

JourneyMap Version: 1.12.2-5.5.4

Forge Version: 14.23.5.2838

Describe the problem:

When trying to create a new waypoint or editing an existing one, the list to select in which dimension it should show up won't scroll at all. At the bottom of 'Manage Waypoints' I can click through some of the dimensions and there are indeed more that don't appear in the aforementioned list.
Sidenote: The scrollbar's lenght seems to change according to the number of avaliable dimensions.

Dimension mods uesd.

Aroma1997s Dimensional World
GalacticraftCore
Galacticraft-Planets
ExtraPlanets

**Comment by BrainStone** [comment]
Have you tried using the latest version?

**Comment by cmkaas** [comment]
yes same result

**Comment by mysticdrew** [comment]
Does this happen without extraplanets installed? I know in the past a couple mods broke the dimension scroll list.

**Comment by BrainStone** [comment]
Funnily enough, I can reproduce this issue too. Though also with extraplanets.

**Comment by mysticdrew** [comment]
Fixed in 5.5.5 Beta 8. 
Interestingly, this never scrolled. The logic was just not there, maybe it worked it older versions of MC but new versions required a simple call to handle mouse input.

**Comment by cmkaas** [comment]
thanks for fixing it :D

**Comment by mysticdrew** [comment]
The beta is on curse, enjoy :)
