### ISSUE TITLE
Suggestion for 1.12.2(!) Font Scale options!

### ISSUE THREAD

**Issue by ghost** [TeamJM/journeymap#118]
Hello there, 

My name is Nick and I want to issue a suggestion for the 1.12.2 version of Journeymap. 

With the font scale option you can set the font scale of the text under and on the minimap. 
https://gyazo.com/17363374718a8d50a00c23c74134b54b <-- like this. 

My new idea: 
Make a font scale for the under and above minimap placeholders (such as weather,time,fps etc). 
& Make an appart font scale for the player & entity names on the map itselfs. 

I want my FPS to be clearly visible, but I don't want player names to be that big... 
I was thinking of some kind of apart "Entity Font Scale" where you can Adjust font scaling on the minimap. 
& Alternative: Make the entity font scale as big as the icons/player heads are on the minimap. 

Thanks for reading!

**Comment by mysticdrew** [comment]
So separate font scales for the MiniMap InfoSlots and PlayerNames? I didn't realize they were tied together.

**Comment by Valtorian** [comment]
Yes they are tied together, Something which I don't like.

Btw: Sorry for my poor english, I live in the Netherlands! The mod is internationally famous :3

**Comment by mysticdrew** [comment]
This has been implemented
