### ISSUE TITLE
[Feature Request] Visualizing Loaded Chunks

### ISSUE THREAD

**Issue by Xiaminou** [TeamJM/journeymap#12]
I would like to have a way to see which chunk are loaded by the players, and which chunks are loaded by Chunk Loaders, similar to what Opis did for mapwriter back in 1.7.10.

**Comment by mysticdrew** [comment]
FTBUtils provides this feature with it's JM plugin

**Comment by Xiaminou** [comment]
Where would I find this "JM plugin"? I've tried FTB Utilities + Journeymap and I don't see any options to get loaded chunks.

**Comment by mysticdrew** [comment]
It shows chunks loaded by FTBUtilities. However, with the API we provide any developer can create the functionality that you want.

**Comment by Xiaminou** [comment]
I didn't see any indications of which chunks were loaded by FTBUtilities, but I don't really use it anyhow. If this is a "should be done by 3rd party" case, could we remove the "fixed" label and add a "addon" or "plugin" label?

**Comment by Lehrules** [comment]
Apologies for replying to such an old thread.

Is it possible to get this functionality natively to see which chunks are being loaded by /forceload?

Perhaps an admin-only toggle with right click functionality to remove and add chunks? Obviously controlled by the config as to not disregard modpacks with chunkloaders as part of their progression systems.
