### ISSUE TITLE
Journeymap creating massiv amount of threads

### ISSUE THREAD

**Issue by Flemmli97** [TeamJM/journeymap#120]
#### JourneyMap Version:
- 1.12.2-5.5.5b7
- 1.12.2-5.5.5b6 (also happens)

#### Forge Version:
- 1.12.2-14.23.5.2836

#### Describe the problem in repeatable steps:

Journeymap is creating massive amount of threads which leads then to crash. Issue doesnt happen without journeymap and was not present in previous used version (which was 5.5.3 i used) so its a recent problem. 

[https://imgur.com/a/RgBH9Hu](https://imgur.com/a/RgBH9Hu)

Mods that might be relevant to the issue includes:
Optifine 1.12.2-HD-U-E3
Pixelmon 1.12.2 - 7.0.6

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

[https://pastebin.com/cJdMuxn1](https://pastebin.com/cJdMuxn1)

---Update:
After removing optifine it was fine so it seems like an incompability with it. might be related to this line in the log: 
at net.optifine.player.CapeUtils.downloadCape(CapeUtils.java:64) ~[CapeUtils.class:?]

**Comment by mysticdrew** [comment]
Optifine does not play nice with a lot of mods sadly. 

The next beta will not create those threads at all as I am going a different route. 
Thanks for your report, I am going to close this issue though.
