### ISSUE TITLE
[1.12.2] Waypoint beacons bug out when you die in the void

### ISSUE THREAD

**Issue by aaronhowser1** [TeamJM/journeymap#121]
#### JourneyMap Version:

`journeymap-1.12.2-5.5.5b7`
but also tested with `journeymap-1.12.2-5.5.4`

#### Forge Version:

`14.23.5.2836`

#### Describe the problem in repeatable steps:

1. Jump into the void and die
2. The beacon will stay really close to you at all times and doesn't go away if you go to above where you died
![](https://cdn.discordapp.com/attachments/552245600721174528/591029193152659462/unknown.png)
![](https://s1.sunekaer.com/i/20-06-2019_00-23-10_javaw.png) 
3. When you move it also jitters a lot
[Gif one](https://s1.sunekaer.com/i/20-06-2019_00-20-20_%25pn.gif)
[Gif two](https://s1.sunekaer.com/i/20-06-2019_00-26-29_%25pn.gif)

It works perfectly fine when you die above the void. Maybe it's a thing with vertical distance?
![image](https://user-images.githubusercontent.com/15698722/59806111-e4b1b500-92b8-11e9-8f10-1aefb70ef7eb.png)

**Comment by Sunekaer** [comment]
Same issue for me

**Comment by mysticdrew** [comment]
In 5.5.5 Beta 8, the X will display low lower than y:2.
