### ISSUE TITLE
[1.12.2] Missing Player Names On LAN Host Map

### ISSUE THREAD

**Issue by Animalover609** [TeamJM/journeymap#122]
#### Describe the problem in repeatable steps:

1. Have JourneyMap installed
2. Open to LAN
3. Joined players will be able to see your name on the map, but you can't see theirs

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

No relevant error logs that I can see

**Comment by Caeas** [comment]
Same here on Server. The Server is running from the same Network we are playing.

Forge: 1.12.2 - 14.23.5.2838
Journeymap: journeymap-1.12.2-5.5.5

**Comment by amondohk** [comment]
Can confirm, as of today, the issue also happens on the same JourneyMap version, on Forge Version: 1.12.2-14.23.5.2816

**Comment by mysticdrew** [comment]
Closing because it is the same technical issue as #109
