### ISSUE TITLE
journeymap.client.model.ChunkMD.getBlockPos just grows and grows

### ISSUE THREAD

**Issue by TheRealDadbeard** [TeamJM/journeymap#123]
journeymap-1.12.2-5.5.5b7 
spongeforge-1.12.2-2838-7.1.7-RC3819
Forge: 2838

Wondered why RAM usage skyrocketed and after some profiling seeing *title* at the top of the list. I can't get it to profile any longer than a couple of seconds as minecraft crashes.

**Comment by mysticdrew** [comment]
Sounds like a mod interaction issue. 
Does this happen with ONLY journeymap installed?

**Comment by TheRealDadbeard** [comment]
It's more chill, 2nd top spot, but not suprised as there are way less blocks when I take over 100mods out. Trying it without and Xaeros minimap and see if it slowly crawls to 12gb too.

**Comment by TheRealDadbeard** [comment]
I think I hit the ceiling but the normal one. Heap is 6GB usage tops out at 8GB now after I removes this mod  https://www.curseforge.com/minecraft/mc-mods/phosphor 

You were right, Journeymap comes at the top but this seems to be causing it,

**Comment by TheRealDadbeard** [comment]
This is a snapshot right now as it was at 10GB ram usage
[leak.zip](https://github.com/TeamJM/journeymap/files/3343205/leak.zip)

**Comment by TheRealDadbeard** [comment]
seems to not be your mod, still looking for the culprit

**Comment by mysticdrew** [comment]
Sounds good, good luck finding the correct mod!
