### ISSUE TITLE
No Death waypoint created

### ISSUE THREAD

**Issue by GrimmKun** [TeamJM/journeymap#124]
#### Instructions for Submitting an Issue
1. Ask for help on Discord (https://discord.gg/eP8gE69) #support if you're unsure this is a new issue.
2. Please search for existing issues before submitting a new one.
3. Please add the correct MC<version> label to your issue. Example: "[1.12.2] Waypoints are upside down"
4. Completely fill out the template below. Failure to do so is likely to get the issue closed immediately.
5. Prove you read these instructions by deleting this section before submitting. ;)
---
  
#### JourneyMap Version:

`Example: 1.12.1-5.5.0`

#### Forge Version:

`Example: 1.12.1-14.22.1.2478`

#### Describe the problem in repeatable steps:

1.Went to nether on a server hosting my modpack to farm for skulls a bit
2.Flew back went into the portal to go home got kicked (my server is very laggy)
3.Died somehow, respawned after reconnecting and looked at my waypoints for a grave and found nothing despite the option being enabled to mark my death point

**Comment by mysticdrew** [comment]
If those version numbers are correct(which I doubt they are) get on a new version. 1.12.1 is not supported. If those are not correct version numbers, you did not follow the template correctly.
