### ISSUE TITLE
Is this project open source and is the code available?

### ISSUE THREAD

**Issue by christilden** [TeamJM/journeymap#125]
Hi,

I would really like to see this mod working on Minecraft 1.13.2!  I have recently ported another mod from 1.12.1 to 1.13.2 and I am willing to work on project as well.

Is the project open source and is the source code available for download?  I cannot locate it anywhere at the moment.

Thanks,
Chris

**Comment by mysticdrew** [comment]
No, there will not be a release for 1.13.2. We are skipping and going directly to 1.14.x

**Comment by christilden** [comment]
Thats fine, but is the project open source and is the source code available for download? I cannot locate it anywhere at the moment.

**Comment by BrainStone** [comment]
It is currently not avaiable. There are plans to open source it though. At least there were. mystic should know more.

**Comment by christilden** [comment]
Thanks for the information. I really like the mod, Minecraft isn’t the same without it!

**Comment by FlashlightET** [comment]
6 years later, are there still plans?

**Comment by mysticdrew** [comment]
1.7.10 source has been available for years.
