### ISSUE TITLE
[1.12.2] Terrain is entirely black except for liquids on v5.5.5b8

### ISSUE THREAD

**Issue by Seitz1** [TeamJM/journeymap#127]
https://i.imgur.com/6IPHKz2.png

This occurs on both the fullscreen map and minimap. Changing between day/night/cave mode does nothing.

Using Forge v14.23.5.2838. This issue only occurs on the latest version (v5.5.5b8) of JourneyMap; downgrading fixed the issue. It does _not_ occur with just a fresh install of JourneyMap and Forge, so there's some sort of mod conflict.

Mod list: https://i.imgur.com/Zcqspgt.png

**Edit: It seems to be a conflict with ConnectedTexturesMod.** I was able to replicate the issue with just Forge, JourneyMap, and ConnectedTexturesMod installed.

**Comment by wideblaze** [comment]
same -- map is defaulting to showing caves bottom layer when on the surface -- can't undo
http://prntscr.com/obj5dt

journeymap-1.12.2-5.5.5b8

**Comment by mysticdrew** [comment]
Well I need logs and does it happen when you're not using ConnectedTexturesMod?

**Comment by mysticdrew** [comment]
Did it happen with beta 7?

**Comment by cmkaas** [comment]
I'm having the same problem only water is showing on the surface level
I'm using the mod with the FTB Ultimate Reloaded modpack

here is my log
https://drive.google.com/open?id=1nSmYyx8-U9mmlZROH6Ow6BTFM7jEPbxO

**Comment by Seitz1** [comment]
My log: https://pastebin.com/ub4iHtvu

**Comment by TheRealDadbeard** [comment]
Same issue here

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/60784886-707b6c00-a116-11e9-9e85-f3ba0d4c7b80.png)
Same issue here
[journeymap.log](https://github.com/TeamJM/journeymap/files/3366769/journeymap.log)

**Comment by zacharyhenry** [comment]
mine shows cave in minimap fullscreen map doesnt work at all just bluee screen

**Comment by zacharyhenry** [comment]
known mods that are being a butt 

connectedtexturesmod(chisel unlimitedchiselworks immersive engineering immersive posts) which is disabled
buildcraft-all is being affected too also disabled

**Comment by mysticdrew** [comment]
@zacharyhenry completely different issue. 
Blue Screen is related to Optifine, uninstall it. That is the only solution.

**Comment by mysticdrew** [comment]
This is resolved in 5.5.5 Beta 9.

**Comment by sustained** [comment]
I was about to report this but it's fixed already, you work fast! :tada:
