### ISSUE TITLE
Zooming out

### ISSUE THREAD

**Issue by Ashiroth** [TeamJM/journeymap#129]
#### JourneyMap Version:1.12.2

`Example: 1.12.1-5.5.0`

#### Forge Version:1.12.2
![2019-07-19_21 23 45](https://user-images.githubusercontent.com/53104330/61572947-8882b200-aa6b-11e9-87c3-b0e39acc415e.png)

`Example: 1.12.1-14.22.1.2478`

#### Describe the problem in repeatable steps:

1.I can only zoom out a little bit. I've checked every option, and I can't find anyone with the same problem.
2.I've mapped an extremely large area thinking that would let me zoom out more but it won't.
3.There should be two files attached one is my map the other is his far more zoomed out map.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

![Zoom](https://user-images.githubusercontent.com/53104330/61572955-a6e8ad80-aa6b-11e9-9ebc-574cba61b908.png)

**Comment by mysticdrew** [comment]
Use pastebin for your log and I need your journeymap version.

**Comment by mysticdrew** [comment]
Waited 6 months, no reply. Closing
