### ISSUE TITLE
[1.12.2] Map not switching back to surface mode after going in cave mode

### ISSUE THREAD

**Issue by Snownee** [TeamJM/journeymap#13]
#### JourneyMap Version:

1.12.2-5.5.2

#### Forge Version:

1.12.2-14.23.1.2581

#### Describe the problem in repeatable steps:

1. Create a new world
2. Minimap have a chance to fixed in caves mode, and cannot work properly

**Comment by techbrew-mc** [comment]
I'm going to need more details.  Please test in 5.6.0b1 and confirm this is still an issue.

**Comment by Snownee** [comment]
Yes this issue still exists and I have no idea how it is caused

**Comment by alpal01** [comment]
ok @techbrew-mc, so the newest beta (5,6,0b1) have a bug where it doesn't show all entities when in mob icons mode, To @Snownee, is the mipmap available always in version 5.5.1?

**Comment by alpal01** [comment]
also happened in project ozone lite where the MC Version is 1.10.2 on JP-5.5.2

**Comment by alpal01** [comment]
CONFIRMED: the map is always appearing in version 5.5.1

**Comment by alpal01** [comment]
Ok sorry for leaving a lot of comments but, this issue is not random; if your world loaded with an older version of JourneyMap then loaded 5.5.2, it will not be broken; but in new worlds loaded it breaks everytime

**Comment by AuroraBTH** [comment]
Same issue in FTB Revelation running 5.5.2 (Forge 1.12.2-14.23.1.2573). Reset on settings/force-reload does nothing. Fullscreen map appears to be working as intentional.

**Comment by Snownee** [comment]
@BrainStone I don't think it is the same issue as @alpal01 's, so we don't have any evidence proving this will happen in MC 1.10.2.

**Comment by alpal01** [comment]
I have tested it on Project Ozone Lite on new worlds after the release
version of journey map and still happening on 1.10 versions as well

I have tested this issue on 1.10.2 and 1.12.2

**Comment by BrainStone** [comment]
I can also definately confirm that this issues is present.

**Comment by Sandriell** [comment]
Can also confirm that this happens

**Comment by Kekko961** [comment]
I can confirm too.

**Comment by alpal01** [comment]
@techbrew-mc can you change 5.5.2 status to beta and re-upload 5.5.1 so pack devs see this because most 1.12.x modpacks have this problem??

**Comment by Xiaminou** [comment]
still happening

**Comment by alpal01** [comment]
Still happens with All The Mods 3

**Comment by mysticdrew** [comment]
Is this still happening with JM 5.5.5 or any of the 5.5.6 betas on mc 1.12.2?

**Comment by Elvarion** [comment]
Just had this happen on JM 5.5.5
The Minimap got stuck in Cave mode.
Manage to fix it by going sub y64 into a cave and then back up again.

**Comment by mysticdrew** [comment]
This should be resolved in 5.5.9 and 5.7.0
