### ISSUE TITLE
Journeymap won't load

### ISSUE THREAD

**Issue by Cloudedsea442** [TeamJM/journeymap#131]
#### Describe the problem in repeatable steps:

1.Journeymap in download and in the mod folder
2.I play the forge installation
3.a message appears stating that journeymap won't load because its too old for forge.
4.can't find new version of journeymap

**Comment by BrainStone** [comment]
Please provide more info, Like which JM version, which MC and which Forge version.

**Comment by mysticdrew** [comment]
a message appears stating that journeymap won't load because its too old for forge.

.. update forge?
