### ISSUE TITLE
[Feature Requests] Auto map all layers

### ISSUE THREAD

**Issue by josh-65** [TeamJM/journeymap#132]
When I click auto map it should have the option to do all 15 layers.

**Comment by mysticdrew** [comment]
I've tinkered with this, and let me tell you... It is very slow.

**Comment by josh-65** [comment]
The same speed as doing every layer individually or is it slower?

**Comment by mysticdrew** [comment]
Similar to every layer individually. But if you played the map for any amount of time and had more than a few regions generated, it could easily take hours. It's really not viable.

**Comment by mysticdrew** [comment]
and it is very cheaty. i will not implement this, sorry.

**Comment by tajemniktv** [comment]
Hey, sorry for necroing this, but has anything changed during the past years when it comes to this or is this still not viable nor planned? Along with that - I'd like to talk about the subject of speed of the map rendering. Is it possible to make it faster by, let's say multithreading the load or something? As along with Distant Horizons it feels like it's even slower, as the CPU is under heavier load maybe? Not sure how all this works...

Cheers

**Comment by mysticdrew** [comment]
> I mean it's plenty viable it's just been stated as wontfix/rejected.. it would take all of a couple minutes to code a settings toggle or extra button that runs automap on subsequent layers instead of having to click 75 times by hand; they just don't want the feature implemented. The mod is ARR and closed source so if they don't want to play ball there's nothing further to discuss.

a couple minutes huh? well, aren't you optimistic.

**Comment by mysticdrew** [comment]
There is another feature request regarding the same request that I have revaluated and do plan to add... eventually.
Waypoint rewrite currently is my top priority.
