### ISSUE TITLE
Pixelmon Images Are Just Blobs

### ISSUE THREAD

**Issue by Brownie03** [TeamJM/journeymap#133]
#### Instructions for Submitting an Issue
1. Ask for help on Discord (https://discord.gg/eP8gE69) #support if you're unsure this is a new issue.
2. Please search for existing issues before submitting a new one.
3. Please add the correct MC<version> label to your issue. Example: "[1.12.2] Waypoints are upside down"
4. Completely fill out the template below. Failure to do so is likely to get the issue closed immediately.
5. Prove you read these instructions by deleting this section before submitting. ;)
---
  
#### JourneyMap Version:

`Example: 1.12.1-5.5.0`

#### Forge Version:

`Example: 1.12.1-14.22.1.2478`

#### Describe the problem in repeatable steps:

1. When I downloaded the journeymap mod I wasn't able to see the pixelmon as the image of the pixelmon.
2. When I open the journeymap mod in pixelmon they still don't appear as pixelmon but just as blobs. 
3.

**Comment by Brownie03** [comment]
Change the mob to icons and not dots.

**Comment by BrainStone** [comment]
The template exists for a reason, you know?
