### ISSUE TITLE
Waypoint teleport XYZ number Can't input decimal

### ISSUE THREAD

**Issue by ztllllll** [TeamJM/journeymap#134]
#### Describe the problem in repeatable steps:

1. Set one waypoint
2. Teleport
3. Mustly stuck in floor or wall get damage till death

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
N/A

Check waypoint XYZ number,find it can't type in decimal(Example,X number can only type 12 not 12.5),maybe this is the reason cause the problem. 
waiting for a fix ,love your guys work.JourneyMap best minecraft map mod ever.

**Comment by mysticdrew** [comment]
it is not intended to support decimal places.
