### ISSUE TITLE
[Feature Requests] Ability to reload waypoints and any "interface" in API to the ClientCommandInvoker

### ISSUE THREAD

**Issue by IVogel** [TeamJM/journeymap#135]
It will be really great to have such ability without any plugins/mods that will add one simple command to standard Journeymap `ClientCommandInvoker`.
Actually I have already did such a thing, but as I have mentioned earlier - it will be great to have this ability by default.

![gif](https://user-images.githubusercontent.com/14248019/62340802-1a190780-b4e1-11e9-9939-350bbd2d0a29.gif)

And about this small API addition. Maybe someone will find this useful to have dirrect access to the `ClientCommandInvoker`. (instead of getting it from Forge's `ClientCommandHandler` in `FMLPostInitializationEvent` event)

**Comment by mysticdrew** [comment]
added /jm wpreload client command. 
it will be in 1.16.5_5.7.2beta17 when published to curseforge.
