### ISSUE TITLE
Add option to only have X amount of deathpoints at a time

### ISSUE THREAD

**Issue by no-boot-device** [TeamJM/journeymap#136]
After playing (terribly) for a while, I usually end up with 6 or 7 or 10 deathpoints, all of which dot the map with beacons. 

Now, not to say I don't appreciate them being visible, but one of the few reasons I use an alternative mod for a minimap over JourneyMap when I'm making my modpack is because said alternative mod lets me pick only having 1 deathpoint as opposed to however many before I go through and wipe them manually, hoping I don't overshoot and remove the waypoints for my base or the end portal.

If you could have it so that I could limit the amount of deathpoints, it'd be a great feature, IMO.

**Comment by mysticdrew** [comment]
So like show the closest (user defined amount?).
Example, if set to 3, it will only show the beacons for the nearest 3? 
Or, more along if you have 3, you die again, it just deletes the oldest one?

**Comment by no-boot-device** [comment]
That last one, yes.

**Comment by mysticdrew** [comment]
Not implementing for 1.12.2, may consider it for future versions.
