### ISSUE TITLE
[all] Non-US date format

### ISSUE THREAD

**Issue by Paul17041993** [TeamJM/journeymap#138]
Surprised no one has requested it yet, but could we add an option to toggle the date format to DD-MM-YYYY instead of MM-DD-YYYY? This mostly applies to death waypoints.

**Comment by BrainStone** [comment]
That would be lovely. There are plenty other styles out there too.

But the minimum would be supporting the international format: YYYY-MM-DD

**Comment by mysticdrew** [comment]
Time format options will be in 5.5.6 beta 3.
I will look into this for beta 3 also.

**Comment by mysticdrew** [comment]
This is added in 5.5.6 beta 3.
