### ISSUE TITLE
[1.12.2] Grid in fullscreen map doesn't render on the full screen (possible in >1080p monitors?)

### ISSUE THREAD

**Issue by aaronhowser1** [TeamJM/journeymap#139]
#### JourneyMap Version:

`journeymap-1.12.2-5.5.5b9`

#### Forge Version:

`14.23.5.2838`

#### Describe the problem in repeatable steps:

1. Might only happen in UHD monitors, I'm using a 1440p one and #59 was using 4K
2. Open full screen map
3. At every level of zoom, the grid only shows on a portion of the screen.
![image](https://user-images.githubusercontent.com/15698722/62633085-35c54900-b8f9-11e9-9f41-dd50bc5c9176.png)
![image](https://user-images.githubusercontent.com/15698722/62633090-3827a300-b8f9-11e9-9526-666b1a1f8885.png)
If I pan right to try to hide it, the right side goes away.
![image](https://user-images.githubusercontent.com/15698722/62633335-8e94e180-b8f9-11e9-928d-8201f4ff646b.png)

Maybe the mod is rendering based on pixel count instead of like, percentage of window width or something?

**Comment by mysticdrew** [comment]
The grid sized is based on the window size, we get those values from minecraft internally, there are no hard coded screen size values. 

However, I cannot test or even attempt to find the issue or fix this as I do not have access to a 4k or any monitor larger than 1080p currently.

**Comment by mysticdrew** [comment]
This is fixed in 1.14.4 version for 1440, not sure about 4k as we have not had anyone test it  yet.

**Comment by VincyChannel** [comment]
@aaronhowser1 
I have a fix: https://www.curseforge.com/minecraft/mc-mods/journeymap-fixes
