### ISSUE TITLE
[1.12.2] Client crash when waypoint name field is blank

### ISSUE THREAD

**Issue by snaiperskaya** [TeamJM/journeymap#14]
#### JourneyMap Version:

1.12.2-5.6.0b1

#### Forge Version:

2582

#### Describe the problem in repeatable steps:

1. Add new waypoint
2. Clear name field
3. Instant crash to desktop

https://gist.github.com/snaiperskaya/9164d4c813fc1df72bbc8ca6bc0ea838

**Comment by sema1011** [comment]
I authorize on version 1.10.2

JourneyMap Version:

1.12.2-5.6.0b1
Forge Version:

2511

https://gist.github.com/sema1011/9ef4f2c22813bfb4b9235ce89e3634a6

**Comment by Xiaminou** [comment]
[crash-2018-01-02_15.51.11-client.txt](https://github.com/TeamJM/journeymap/files/1597830/crash-2018-01-02_15.51.11-client.txt)

**Comment by Boymann** [comment]
[crash-2018-01-10_17.30.03-client.txt](https://github.com/TeamJM/journeymap/files/1619642/crash-2018-01-10_17.30.03-client.txt)

Same here
MC:1.12.2 Forge Version: 2568

**Comment by Sandriell** [comment]
Another crash report for this.

https://gist.github.com/Sandriell/1399482faaf9b6641628f56803071c0e

minecraft-1.12.2
forge-14.23.1.2587
journeymap-1.12.2-5.6.0b1

**Comment by techbrew-mc** [comment]
Fixed in 5.6.0b2 and later.  Keeping open until 5.6.0b3 is put up.

**Comment by mysticdrew** [comment]
Closing all 5.6.0 issues. Please downgrade to 5.5.2 as 5.6.0 is no longer publicly available.
