### ISSUE TITLE
cannot create custom themes

### ISSUE THREAD

**Issue by STOKE-STER** [TeamJM/journeymap#140]
#### JourneyMap Version:

1.12.2-5.5.5

#### Forge Version:

forge-14.23.5.2838

#### Describe the problem in repeatable steps:

1. followed instructions at https://journeymap.info/UI_Themes to add custom theme
2.launched game after adding theme
3.theme unavailable to select in game

**Comment by mysticdrew** [comment]
If you can come into our discord, we can try to work through this issue and get your theme added!

**Comment by mysticdrew** [comment]
This is fixed in 5.5.6 beta 4 when it is put on curse.
