### ISSUE TITLE
NoClassDefFoundError involving JourneyMap's ColorPalette.class

### ISSUE THREAD

**Issue by darthvader45** [TeamJM/journeymap#142]
#### Describe the problem in repeatable steps:

1.  Open Minecraft.
2. Load up a world.
3. Exit the world and check the log.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:  N/A

Link to Minecraft log (I believe this is how latest.log is supposed to look): https://paste.ee/p/rvVnO

**Comment by mysticdrew** [comment]
You have a lot of issues happening. It looks like many mods are throwing exceptions. 

You need to dig into that, something is wrong with your JVM or your system as files cannot be written by the looks of it.

**Comment by mysticdrew** [comment]
Closing because this is not an issue with journeymap, you have 9 instances of mods, forge, and minecraft throwing NoClassDefFoundError errors. If you can resolve all of those and JM is still throwing that error, reopen this with a clean log.
