### ISSUE TITLE
[Feature Request] Automatic DeathPoint Removal

### ISSUE THREAD

**Issue by thegamerx1** [TeamJM/journeymap#144]
Method 1. Remove old deathpoints that have x time of life

Method 2. Option to choose how many deathpoints should be so if max deathpoints is 3 when there are 4 deathpoints the oldest one will get removed

**Comment by Hugobert** [comment]
Method 3: Option to auto-remove deathpoint once you reach it again.

**Comment by lilrichy** [comment]
Method 4: Button on the waypoint screen to remove all death markers.

**Comment by thegamerx1** [comment]
Do you really prefer needing to click a button on the map every fucking time you die

**Comment by lilrichy** [comment]
Well right now to remove the markers I have to click "Remove" on each one and when playing a hard pack where I die a lot this becomes a pain. Also while trying to not accidentally hit remove on one of my actual waypoints. It would be a lot easier to just click 1 button to remove all deaths.

**Comment by mysticdrew** [comment]
You guys die too much! Stop dying, no death markers, problem solved!! 😆 🤣 

I will see what I can come up with, something easy though since I will be rewriting much of the waypoint system for 1.14

**Comment by mysticdrew** [comment]
adding this to 5.5.6, you can test it in beta 3 when it comes out and let me know your thoughts. 

It removes them as you approach the deathpoint, there is an option to select the distance to remove it. The distance is a minimum of 2 or it will get removed right away when you die.
