### ISSUE TITLE
[Feature Request] Optiont to make waypoints smaller/bigger

### ISSUE THREAD

**Issue by thegamerx1** [TeamJM/journeymap#147]
Remove option to make ALL waypoints big and manage the size by each waypoint config so you can make your house waypoint big and a witch house for example small

**Comment by mysticdrew** [comment]
do you mean the waypoint beacon in game, or the icon on the map?

**Comment by thegamerx1** [comment]
in the map as of there is a dungeon mod that adds very big dungeons and i would like to add waypoints for each stair and spawner so the icons wont look as big.
Making waypoint groups would help this a lot, like making a main waypoint of a group and when you get near a customizable range from that waypoint the childs of the main waypoint will be visible.

**Comment by mysticdrew** [comment]
Grouping is not going to happen in 1.12.2. Please answer my question.

**Comment by thegamerx1** [comment]
in the map and in the game

**Comment by mysticdrew** [comment]
more scaling has been added for waypoints. Though the beacon is not scalable.
