### ISSUE TITLE
[1.12.2] Do not load more areas after playing for a while

### ISSUE THREAD

**Issue by Alvariun** [TeamJM/journeymap#148]
#### JourneyMap Version:

 1.12.2-5.5.5`

#### Describe the problem in repeatable steps:

1.start the minecraft
2.enter a world
3.play for a while

#### Relevant errors from `.minecraft/journeymap/journeymap.log`: There is nothing

Additional Image:![Problema](https://user-images.githubusercontent.com/54456831/63626580-1f4a0d80-c5da-11e9-83de-1954c396ca35.png)

**Comment by mysticdrew** [comment]
5.5.0 is very old, update to 5.5.5 and see if the problem persists.

**Comment by Alvariun** [comment]
> 5.5.0 is very old, update to 5.5.5 and see if the problem persists.

sorry I was wrong in the JourneyMap version I already have 5.5.5

**Comment by Alvariun** [comment]
the problem still persists loads the entities but not the new zones explored

**Comment by Alvariun** [comment]
waiting-for:response

**Comment by mysticdrew** [comment]
I need logs when this happens, please use pastebin. If you copy and paste the logs into this issue, I will delete and close the issue. 

Your Journeymap.log in minecraft/journeymap folder. 
Your forge-latest.log in minecraft/logs folder.

**Comment by mysticdrew** [comment]
lack of response
