### ISSUE TITLE
Unable to hide Waypoints

### ISSUE THREAD

**Issue by DreamingLamb** [TeamJM/journeymap#15]
JourneyMap Version: 1.12.1-5.6.0b1

Forge Version: 1.12.1-14.23.1.2582

Describe the problem in repeatable steps:

1. Set a waypoint and toggle it to Off.
2. Waypoint remains as On and visible.

I'm also seeing waypoint in other Dimensions, eg: I have waypoint that are set for only the Overworld but they are visible inside Aroma's Mining World and visa versa

![image](https://user-images.githubusercontent.com/14001645/34486844-9592137c-efc9-11e7-8fd9-414716533f55.png)

![image](https://user-images.githubusercontent.com/14001645/34486839-8c04abf8-efc9-11e7-8aeb-e35129efbe13.png)

No errors in .minecraft/journeymap/journeymap.log

**Comment by janagyjr** [comment]
Confirmed, JM 5.6.0b1, MC 1.12.2, Forge 2589
![2018-01-14_14 19 51](https://user-images.githubusercontent.com/23646259/34920309-7818287e-f936-11e7-9e15-f7a88f63f7eb.png)

**Comment by PurpleHel** [comment]
Same problem, 5.6.0b2

**Comment by janagyjr** [comment]
Also broken in 1.11.2 Forge 2516, JM 5.6.0b2. As an additional issue, when changing the coordinates of a beacon, the beacon doesn't move. You have to completely remove it and readd it.

**Comment by beanaboston** [comment]
I am also having this issue. Would downgrade but waypoint format was changed so waypoints aren't in game in old versions.

**Comment by markis007** [comment]
Hi All - I am having the same issue when running Journeymap  5.6.0b2 with MC 1.12.2 and forge 14.23.1.2601

**Comment by Dunkh4n** [comment]
Hi,
I am having the same issue

Modpack : All The Mods 3
JourneyMap Version: journeymap-1.12.2-5.6.0b2
Forge Version: 14.23.1.2587

**Comment by janagyjr** [comment]
Update: Log file from the last time I used JM on 1.11.2

https://gist.github.com/janagyjr/aedaecd70c3072a6bcd2730e69a6d607

**Comment by mysticdrew** [comment]
Closing all 5.6.0 issues. Please downgrade to 5.5.2 as 5.6.0 is no longer publicly available.
