### ISSUE TITLE
1.12.2 Save Journeymap data in savegame to preserve data after modpack updating

### ISSUE THREAD

**Issue by OuweMickey** [TeamJM/journeymap#150]
Journeymap data is overwritten when updating modpacks. To circumvent this, is it possible to change the location of the saved data to the save folder?

**Comment by mysticdrew** [comment]
I've been wanting to do this, it will not happen in 1.12.2 though. It will happen in 1.14.x update. Then I do not have to write code to migrate everyone's save files.
