### ISSUE TITLE
Issue with In-Game Time Display

### ISSUE THREAD

**Issue by IceT2** [TeamJM/journeymap#156]
#### JourneyMap Version: 1.12.2-5.5.5

`Example: 1.12.1-5.5.0`

#### Forge Version: 14.23.5.2847

`Example: 1.12.1-14.22.1.2478`

#### Describe the problem in repeatable steps:

1. It's just the ingame time display showing an incorrect time 
2. Please see attached picture for clarification.

![journeymap1122](https://user-images.githubusercontent.com/7529036/66264148-a7d1e580-e7f7-11e9-9012-f950a41e361f.png)

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
There are no error logs, I assume it may only be my game, but I didn't realise that you had an ingame time display option, which was on by default when I first loaded up a new game instance. I'd downloaded the CJB continuation mod for MC 1.12.2 and only loaded the 'moreinfo' part, since I just wanted to know the ingame time. I was initially using journeymap 1.12.2-5.5.4, but when I saw the time discrepancy, I updated to your latest version, and still got the same issue. In fact, its the CJB time at the top left that is the correct ingame time, journeymap is a few hours fast. I've also uploaded the journeymap log file in case its of use to you.
[journeymap.log](https://github.com/TeamJM/journeymap/files/3693941/journeymap.log)
.

**Comment by mysticdrew** [comment]
I don't know what cjb is.. 
There are different time slots in the "InfoSlot" section of the minimap options on how you want time calculated. There is the sunrise to sunrise 24hr clock(how minecraft calculates a new day), there is the real midnight to midnight clock, and a couple others.

**Comment by IceT2** [comment]
CJB created a mod back in the 'beta' days, anyway, here's a link to the forum page where it's currently being continued 👍 
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1287252-continue-of-cjb-mod-fml-modloader
It's not a time changing mod, it just displays the time, much like your journeymap does. Anyway, I took out every mod except for yours and started a new map. Journeymap time was showing 12:30 when the map was at dawn, so I'm not sure about interference from any other mod, since all that was in my session was Mincraft, Forge, and your mod. 
It's not critical, it would have been nice to be able to take out the CJB mod and just use your map's time, however, I can turn yours off and use the other, I just thoguht you'd like to know about it that's all ........ many thanks for the reply.

**Comment by BrainStone** [comment]
As he said there's a setting as to how JM calculates the time of day. Check that setting.

**Comment by IceT2** [comment]
Sincere apologies, but I've no idea what you mean ? 
What I've done is a clean install of 1.12.2, added forge, then added journeymap then started a new map and at the start of the day, journeymap ingame time was showing 12:30, which of course, is not correct. Now I've not changed anything, its a clean install via multimc. If there is a way to check a 'time setting' somewhere in minecraft, or in the journeymap config, I'd be very interested in knowing how to do that please?

**Comment by BrainStone** [comment]
You go in the fullscreen map, then to options and then there are options to customize the lines above and below the mini map. This includes the way time is calculated.

**Comment by mysticdrew** [comment]
You can also come into our discord for step by step help. 

In the minimap options, the option you are looking for is InfoSlot. There are 4 infoslots for the minimap two above, two below. Select which works best for you, you can display all kinds of things in the infoslot. 

Secondly, how do you know that other mod is correct, maybe they have it wrong?
Our time calculation is based on this https://minecraft.gamepedia.com/Day-night_cycle

**Comment by IceT2** [comment]
Well, I tried. the only settings I could find about time were those to set the clock to 12 or 24hrs, or to the System time, and if I change to system time, it shows the correct RLT and corresponds to my system tray clock. I tried with polling times and others, but nothing would set the ingame clock to the correct time. I still start a new map, and its instantly 13:00 on journeymap. I tried re-installing the CJP time mod and started a new map, and on CJP its 07:00 and journeymap its 13:00. 
Anyway, no problem, again many thanks for your assistance, I shall continue with both mods installed and switch off journeymap clock. I'm disappointed with myself for not being able to fix this, I had assumed things would be set to 'work-out-of-the-box' as it were, but its not a game stopper, and I've enjoyed using your mod for a long time now and I never knew about the clock until this version anyway, so no harm done.

**Comment by IceT2** [comment]
Apologies, I only just saw your other comment after I posted my last reply. Why do I know CJP is correct ? well, when starting any new map, the start time is always 07:00, which is what CJP displays, whilst journetmap is 13:00, which is 1 o'clock in the afternoon, and the new maps always start at dawn.

**Comment by IceT2** [comment]
As one last effort, I tried yet another fresh install of 1.12.2, then installed Forge, then installed journeymap. So now, as before, everything should be on default settings, then I started 2 brand new maps. In each case, journeymap showed the beginning time as 12:00. So, I installed the CJP time mod and started 2 more brand new maps. In each case, CJP showed the start time at 06:00 and journeymap showed the start time at 12:00, so there's a 6 hour descrepancy between the 2. Since the day starts at dawn and CJP is showing 6am in the morning, I take it that its showing the correct time. Anywy, I don't want to waste any more of your time, I just thought I'd have one last try before giving up ......... again, thanks for your assistance.

**Comment by mysticdrew** [comment]
So there is get GameTime and get GameTime12hr and GameTime24hr 

GameTime is 00:00:00 sunrise, 6am. Default minecraft time based on the link I posted earlier. 
GameTime12 and GameTime24 calculates 00:00:00 at midnight. 

Everything looks perfect to me.. 
![image](https://user-images.githubusercontent.com/5459941/66276633-a84f9800-e85a-11e9-91b8-ce5273df8f2b.png)


Journeymap Time around the minimap is set as such
Top:GameTime
2nd: GameTime12
minimap
3rd: GameTIme24
4th: SystemTime

As you can see it matches correctly with cjb. 

CJB says it is 7:02am and GameTime says 00:51, both technically correct. Though 11 seconds off because of update times. Update times are not instant. Journeymap's GameTime 00:00 is 6am, sunrise. CJB calculates based on a midnight is 00:00 as journeymap does for GameTime12 and GameTime24.

**Comment by IceT2** [comment]
Yes, I see the issue now, I am only seeing the top line in your journeymaps display - which on your screenshot is showing 00:51 daytime. I am not seeing the line below, and although I've tried, I can't seem to get that line displayed. Since my infoslot 2 is showing *gametime*, I assumed that the time display was the ingame time, but looking at your screenshot, I've got something wrong, however, that very top line appears as a default setting, and as I say, it appeared to be the ingame time. I will show a screenshot of my current settings, perhaps you could assist with which setting it should be please?
![journeymap2](https://user-images.githubusercontent.com/7529036/66276884-1c0b9800-e88f-11e9-9805-74bb9c970555.png)

**Comment by mysticdrew** [comment]
click on the infoslot to cycle through it.

**Comment by mysticdrew** [comment]
if you need more help, come into our discord. It will be much easier to assist you there. https://discord.gg/j6GyTQ

**Comment by IceT2** [comment]
Well, I changed infoslot 2 to the 24hr and got the same result as before. Screenshot below. I must assume that the problem is with me somewhere. I appreciate the discord assistance, but its something I've not used before, so again, thanks for the assistance, I think I'm just gonig to have to lvie with the problem.
![journeymap3](https://user-images.githubusercontent.com/7529036/66277022-8ec94300-e890-11e9-9e8f-662912f37db7.png)
