### ISSUE TITLE
Maps are not available for same server using different host connection string

### ISSUE THREAD

**Issue by artheus** [TeamJM/journeymap#157]
#### Instructions for Submitting an Issue
1. Ask for help on Discord (https://discord.gg/eP8gE69) #support if you're unsure this is a new issue.
2. Please search for existing issues before submitting a new one.
3. Please add the correct MC<version> label to your issue. Example: "[1.12.2] Waypoints are upside down"
4. Completely fill out the template below. Failure to do so is likely to get the issue closed immediately.
5. Prove you read these instructions by deleting this section before submitting. ;)
---
  
#### JourneyMap Version:
`1.12.2-5.5.5`

#### Forge Version:

`1.12.2-14.23.5.2836`

#### Describe the problem in repeatable steps:

1. Start a Minecraft Forge server on any machine
2. Setup a domain name for the server in your /etc/hosts file
3. Join server using domain name, using a client with journey map
4. Go around on the server map, to render pieces of the map. Also put some waypoints
5. Log out of server
6. Use same client to join server, but this time with the IP (not domain name)
7. Now you will see that the rendered map is no longer available, neither are the waypoints.

This is due to JourneyMap indexing server maps using the server host connection string.
There should be other means of uniquely identifying a server using server information gathered during the `login` or `play` parts of the game network protocol.

If uniquely identifying the server proves to be hard, one should be given the ability to link maps to mutliple server instances in the Multiplayer menu.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

No errors

**Comment by mysticdrew** [comment]
You can put Journeymap on the server and enable world ID to resolve the issue.
