### ISSUE TITLE
[Request] Map out to render distance

### ISSUE THREAD

**Issue by scribbler957** [TeamJM/journeymap#159]
While exploring, I find that I can often see things that don't appear on my map. In my single player world, I use the map missing command. On servers, I don't have that option. Can you use the player's render distance for revealing the map?

**Comment by mysticdrew** [comment]
You need to trinket with your journeymap options/configs. There already is a render distance option.

**Comment by scribbler957** [comment]
Is there a facepalm emoji? I can't believe how many times my eyes must have just scanned right past that.
Thank you for the quality of your mod and the respectfulness of your support. Journeymap is the only mod I won't go on without!
