### ISSUE TITLE
[1.12.2] Can mapping be disabled permanently for users.

### ISSUE THREAD

**Issue by josh-65** [TeamJM/journeymap#163]
On my server I want to only allow admins to map a world and completely disable it for other users so everyone would have the same map.
I know I can ingame but it can be turned on and off by all users and it turns back on after reload.

**Comment by mysticdrew** [comment]
In the admin screen, set all the mapping options to ops.

**Comment by mysticdrew** [comment]
You can come into discord and ask these kinds of questions, this is not the place for it.
