### ISSUE TITLE
[1.12.2] All waypoint randomly disappear until world reload

### ISSUE THREAD

**Issue by josh-65** [TeamJM/journeymap#164]
#### JourneyMap Version:
5.5.6

#### Forge Version:
14.23.5.2847

#### Relevant errors from logs:
[journeymap.log](https://github.com/TeamJM/journeymap/files/3994720/journeymap.log)

[latest.log](https://github.com/TeamJM/journeymap/files/3994728/latest.log)

**Comment by mysticdrew** [comment]
[ChatLog] JourneyMap: Mapping disabled.

**Comment by josh-65** [comment]
Disabling mapping shouldn't remove waypoint until i reload the world.
