### ISSUE TITLE
[1.12.2] Waypoint labels no longer visible

### ISSUE THREAD

**Issue by NillerMedDild** [TeamJM/journeymap#165]
#### JourneyMap Version:

`journeymap-1.12.2-5.5.6`

#### Forge Version:

`1.12.2-14.23.5.2847`

#### Describe the problem in repeatable steps:

1. Load any world, and create a waypoint near you
2. Open the worldmap (J)
3. See that the waypoint does not have a label

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
No relevant errors as far as I could see, but here's the log just in case:
https://gist.github.com/NillerMedDild/78977c3c62e6a06304f22d9c379f1471

Original issue: https://github.com/NillerMedDild/Enigmatica2Expert/issues/1458

**Comment by mysticdrew** [comment]
You disabled labels in the waypoint options. You can turn them back on in the options.

**Comment by mysticdrew** [comment]
Hmm, nevermind.

**Comment by mysticdrew** [comment]
Will be fixed in the next release

**Comment by NillerMedDild** [comment]
Thanks! :)
