### ISSUE TITLE
[1.12.2] Minor Waypoint Manager Issue

### ISSUE THREAD

**Issue by bolte-io** [TeamJM/journeymap#166]
Client version 1.12
Latest JourneyMap
Latest Forge  

Very minor issue I am sure just thought it was worth reporting.
I get around it with a double tap of escape.
When in the waypoint manager and you add a bookmark, pressing escape to get rid of the waypoint manager should return you to the game. As it happens it takes you to the fullscreen map screen, which can then be escaped out of. Doesn't happen if I am just looking at the bookmark manager, only when adding one in.

I don't expect it to be fixed any time quickly, just seems a bit off in terms of user experience.

**Comment by mysticdrew** [comment]
There is no such version as 'latest', 'latest' is not a number.

**Comment by mysticdrew** [comment]
If you were in the full screen map and got to the waypoint manager, press esc, it is intended to take you back to the full screen map. This is intended functionality, it always goes back to the previous screen. If you press ctrl+b to go to the waypoint manager from the game screen, pressing esc will take you back to the game and not to the fullscreen map.

**Comment by bolte-io** [comment]
I wasn't in the fullscreen map, I used keybind to enter waypoint manager, pressed new to add a new waypoint saved it, and pressed close. Then was presented with full screen map. I thought that was clear with my post, apologies.

Also, latest is a version number, since it is the latest version you have released it should be easy for you to remember.

**Comment by mysticdrew** [comment]
No, "latest" is not a number..  
90% of the time people say latest, they are not on it. So all inquiries with "latest" are ignored.
