### ISSUE TITLE
Saving a map

### ISSUE THREAD

**Issue by Macintosh-Fan** [TeamJM/journeymap#167]
#### Instructions for Submitting an Issue
1. Ask for help on Discord (https://discord.gg/eP8gE69) #support if you're unsure this is a new issue.
2. Please search for existing issues before submitting a new one.
3. Please add the correct MC<version> label to your issue. Example: "[1.12.2] Waypoints are upside down"
4. Completely fill out the template below. Failure to do so is likely to get the issue closed immediately.
5. Prove you read these instructions by deleting this section before submitting. ;)
---
  
#### JourneyMap Version:

`Example: 1.12.1-5.5.0`

#### Forge Version:

`Example: 1.12.1-14.22.1.2478`

#### Describe the problem in repeatable steps:

1. I want to save a map for the world
2. Takes 3 hours
3. And does not save correctly

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

1.12.2 latest file as of Dec 26, 2019

**Comment by Macintosh-Fan** [comment]
Actually, the previous version, not the one released in December 2019, but August 2019

**Comment by mysticdrew** [comment]
Use journeymap-tools on curse. Version 5.5.0 is no longer supported.
