### ISSUE TITLE
Use journeymap-tools on curse. Version 5.5.0 is no longer supported.

### ISSUE THREAD

**Issue by Macintosh-Fan** [TeamJM/journeymap#168]
Use journeymap-tools on curse. Version 5.5.0 is no longer supported.

_Originally posted by @mysticdrew in https://github.com/TeamJM/journeymap/issues/167#issuecomment-569244625_

But there is no version for 1.12.2

**Comment by mysticdrew** [comment]
It's not a mod

**Comment by Macintosh-Fan** [comment]
> It's not a mod

Where is the link then?

**Comment by mysticdrew** [comment]
https://lmgtfy.com/?q=journeymap+tools

**Comment by Macintosh-Fan** [comment]
> https://lmgtfy.com/?q=journeymap+tools

Only for 1.7.10?

**Comment by mysticdrew** [comment]
It's not a mod...

**Comment by Macintosh-Fan** [comment]
> It's not a mod...

https://www.curseforge.com/minecraft/mc-mods/journeymap-tools/files

**Comment by mysticdrew** [comment]
Read the description of it. This is not that complicated... Curse required a minecraft version.
