### ISSUE TITLE
Teleport fail

### ISSUE THREAD

**Issue by TheSnowyChickens** [TeamJM/journeymap#17]
#### JourneyMap Version:

1.12.2-5.6.0b2`

#### Forge Version:

1.12.2-14.23.1.2589

#### Describe the problem in repeatable steps:

1. go in a world
2. create a waypoint
3. press "teleport"

I re-installed Journeymap to 100%.
I deleted the old config and the other config in the config folder.
I allowed the player the teleport action with an edit from the global config.
I auto-map the "chunk 0" layer and the normal on 64+.

And yes, I wanted to teleport from the overworld to an overworld waypoint.

#### Relevant errors
![2018-01-14_23 10 18](https://user-images.githubusercontent.com/29357962/34921269-1a339d52-f980-11e7-959f-970333a3a92f.png)

![2018-01-14_23 13 03](https://user-images.githubusercontent.com/29357962/34921299-7cce8b7a-f980-11e7-9dec-0f288b1be1c2.png)

**Comment by beanaboston** [comment]
This happens to me too.

**Comment by border999** [comment]
me as well

**Comment by mysticdrew** [comment]
Closing all 5.6.0 issues. Please downgrade to 5.5.2 as 5.6.0 is no longer publicly available.
