### ISSUE TITLE
[1.12.2]Full-screen not working.

### ISSUE THREAD

**Issue by Maciejozaman** [TeamJM/journeymap#171]
JourneyMap Version(Client):

`1.12.2-5.5.6`

Forge Version:

`1.12.2-14.23.5.2847`

Describe the problem in repeatable steps:

When I open full-screen map, I see only a gray background and nothing more.

![fullscreen](https://user-images.githubusercontent.com/56502072/73010274-6e5acf80-3e12-11ea-8d50-b31a44c525d5.png)

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
No errors in there.

**Comment by mysticdrew** [comment]
Come to our discord and have your journeymap.log and latest.log ready. This is a mod interaction issue so I will close this.
