### ISSUE TITLE
Need help 1.12.2

### ISSUE THREAD

**Issue by Theangelito** [TeamJM/journeymap#173]
Cliente> 	at journeymap.common.version.VersionCheck$1.run(VersionCheck.java:131) [VersionCheck$1.class:1.12.2-5.5.7]
Cliente> 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_51]
Cliente> 	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_51]
Cliente> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_51]
Cliente> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_51]
Cliente> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
Cliente> Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Cliente> 	at sun.security.validator.PKIXValidator.doBuild(Unknown Source) ~[?:1.8.0_51]
Cliente> 	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source) ~[?:1.8.0_51]
Cliente> 	at sun.security.validator.Validator.validate(Unknown Source) ~[?:1.8.0_51]
Cliente> 	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source) ~[?:1.8.0_51]
Cliente> 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source) ~[?:1.8.0_51]
Cliente> 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source) ~[?:1.8.0_51]
Cliente> 	... 27 more
Cliente> Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Cliente> 	at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source) ~[?:1.8.0_51]
Cliente> 	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source) ~[?:1.8.0_51]
Cliente> 	at java.security.cert.CertPathBuilder.build(Unknown Source) ~[?:1.8.0_51]
Cliente> 	at sun.security.validator.PKIXValidator.doBuild(Unknown Source) ~[?:1.8.0_51]
Cliente> 	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source) ~[?:1.8.0_51]
Cliente> 	at sun.security.validator.Validator.validate(Unknown Source) ~[?:1.8.0_51]
Cliente> 	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source) ~[?:1.8.0_51]
Cliente> 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source) ~[?:1.8.0_51]
Cliente> 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source) ~[?:1.8.0_51]
Cliente> 	... 27 more
Cliente> [15:23:55] [Realms Notification Availability checker #1/INFO] [mojang/RealmsClient]: Could not authorize you against Realms server: Invalid session id
El juego termino de forma incorrecta (exit code -1073740940)
Borrando C:\Users\Jorge-PC\AppData\Roaming\.minecraft\versions\1.12.2-forge1.12.2-14.23.5.2847\1.12.2-forge1.12.2-14.23.5.2847-natives-54832899039300
Los archivos nativos serán removidos una vez que cierre el launcher

**Comment by gdude2002** [comment]
This problem is due to your Java install being out of date. Additionally, it will not impact your ability to play Minecraft or use JourneyMap.
