### ISSUE TITLE
Double-click on fullscreen

### ISSUE THREAD

**Issue by Lucprins** [TeamJM/journeymap#174]
Double-clicking anywhere on the screen creates a waypoint, even on the buttons. Would be great if there was an option to disable double-click waypoint on fullscreen for easier looking around.

**Comment by mysticdrew** [comment]
I will add a config option in 1.14.4

**Comment by Lucprins** [comment]
Great to hear!

**Comment by mysticdrew** [comment]
leave it open, it's not implemented yet. I need it open to track it.

**Comment by mysticdrew** [comment]
This has been implemented.
