### ISSUE TITLE
[Feature Request] Show coord deviation (a.k.a. delta x, y, z)

### ISSUE THREAD

**Issue by EzerArch** [TeamJM/journeymap#175]
Say we are on a server. There are two teams: each one building a tunnel or a railway through a mountain or can't see each other. Both need to meet at the same xyz cood, and then:

![](https://i.pinimg.com/originals/81/4c/6c/814c6c068c8eeda3de2ccf58add195bc.jpg)

JM could show the waypoint coods in a different format: coord deviation. How much you are off a waypoint.

If a waypoint is at 10,10,10 and you are at 15,3,10, that waypoint label will show [delta: +5,-7,0].

How do you know you are aligned with a waypoint? If 2 values are zero and only one is a non-zero value.

**Comment by mysticdrew** [comment]
Thoughts?
![image](https://user-images.githubusercontent.com/5459941/124156421-3d49ea00-da5d-11eb-978d-fb04db3d03fb.png)

**Comment by BrainStone** [comment]
I like it. Just hope there's a toggle for it. Ideally for each WP, but globally is fine as well :D

**Comment by mysticdrew** [comment]
> I like it. Just hope there's a toggle for it. Ideally for each WP, but globally is fine as well :D

Right now it is globally, I didn't think about per waypoint. I would need to redesign the edit waypoint screen or something.

**Comment by mysticdrew** [comment]
![YdavlGm4Vp](https://user-images.githubusercontent.com/5459941/124170515-227f7180-da6d-11eb-9929-dc6017284eb6.gif)
@BrainStone how about that? I will also add a hotkey to enable/disable the global setting.

**Comment by mysticdrew** [comment]
This will be in 1.16.5_5.7.2beta17 when it publish it to curseforge.
