### ISSUE TITLE
Issue with Death Waypoint Icons Sticking Around After Being Removed

### ISSUE THREAD

**Issue by DaggerIxur** [TeamJM/journeymap#178]
#### Describe the problem in repeatable steps:

The issue is as follows: the death waypoints that are set once I die do not disappear in the world itself once I delete them. The beacon disappears, the entry in the waypoints list disappears, and they aren't visible on the fullscreen map anymore. However, I can still see them in-game; they simply say "D" with the typical distance measurement thingy that normal waypoints use. I've scoured the Journeymap settings and I don't see anything that might fix this. It's getting annoying to have these icons cluttering my horizon. Thanks for any help you can render! 

It is not something one can repeat as far as I know. This issue simply began without any noticeable cause.  

![2020-02-21_21 18 16](https://user-images.githubusercontent.com/61339200/75085622-babc2c80-54f0-11ea-9351-be9581850c70.png)
![2020-02-21_21 26 35](https://user-images.githubusercontent.com/61339200/75085637-d8899180-54f0-11ea-8860-6a6d4769a7fa.png)

![2020-02-21_21 27 30](https://user-images.githubusercontent.com/61339200/75085658-ffe05e80-54f0-11ea-9139-7bbed60004e5.png)
To prove I didn't just forget to delete the death waypoints. ^

**Comment by mysticdrew** [comment]
I've seen this before, we are not sure what causes it. I suspect a mod interaction issue. One person previously had reported, removed journeymap. However, even after removing journeymap, they still remained. 

Is this the same case with you?

**Comment by DaggerIxur** [comment]
I haven't tried removing it yet. I do have a number of other mods, although as far as I know, none of them have anything relating to map functions, including waypoints.

**Comment by mysticdrew** [comment]
It's likely a mod that does some rendering. It's not a mapping issue at all. Anyways, tomorrow come in our discord and we can try to find the issue.

**Comment by DaggerIxur** [comment]
Okay, will do.

**Comment by mysticdrew** [comment]
This is caused by xaeros map, you probably have both installed. Those are not even journeymap waypoint icons.
