### ISSUE TITLE
Can the be an option to have server sync waypoints

### ISSUE THREAD

**Issue by josh-65** [TeamJM/journeymap#179]
Would be nice for spawn points or areas.

**Comment by gdude2002** [comment]
We get this request a lot, to be honest. I'd love to see a feature like this, but right now it's very out of scope for what we have in mind - once we've gotten a 1.14.x release out the door and we've rewritten our API, we may end up looking at this again - I'll move the idea to our internal issue tracker, to remind us about it.

Thanks for your issue, nonetheless!
