### ISSUE TITLE
the host player can't see other player on the fullscreen map in singleplayer open Lan port

### ISSUE THREAD

**Issue by ColaLiao** [TeamJM/journeymap#180]
JourneyMap Version: 1.12.2-5.5.9

Forge Version: 1.12.2-14.23.5.2847

Describe the problem:
in singleplayer game, open Lan port,
the host player can't see other player, but others can see all player on the fullscreen map.

**Comment by BrainStone** [comment]
Possible duplicate of #122

**Comment by mysticdrew** [comment]
Closing this because #200 if for a version that will get an update. 
Sorry this will not be addressed in 1.12.2.

**Comment by ColaLiao** [comment]
1.12.2 will no longer update?

**Comment by mysticdrew** [comment]
No
