### ISSUE TITLE
[1.15.2] Phantom biomes on the map when using PreGenForge and JourneyMap together

### ISSUE THREAD

**Issue by Quizer9O8** [TeamJM/journeymap#185]
#### JourneyMap Version: 
1.15.2-5.7.0-beta-1  

#### Forge Version: 
1.15.2-forge-31.1.18

#### Describe the problem in repeatable steps:

1.  Install **TerraForged, PreGenForge** and **Journeymap**.

2. Start up **Minecraft Launcher** Go to **Settings** and enable **Open output log while games are running** (you'll need this later on), go back to **Minecraft: Java Edition** and launch the game. Once in the main menu go to **Options**, **Video Settings** and crank up **Render Distance:** to **32 chunks**.

3. Exit  **Options**, go to **Singleplayer**, **Create a new world**, change **Gamemode:** to **Creative**, go to **More Options**, turn **Generate structures:** to **Off** and change the **World Type:** to **TerraForged**.

4. **Create a new world** and use the following commands in sequence: `/gamerule doDaylightCycle false`, `/gamerule doWeatherCycle false`, `/gamerule doMobSpawning false`, `/gamerule randomTickSpeed -1`, `/kill @e[type=!minecraft:player]` (do this twice), `/pregen start 0 0 50` (the **Minecraft game output** will tell you how far PreGen currently is).

5.  Once **PreGenForge** is done open in **JourneyMap** the **Fullscreen Map**, go to **Options**, open up **Cartography**, and disable the following features: **Blend Foliage, Blend Grass, Blend Water, Show Bathymetry, Show Crops, Show Plants**. Select the following features: **Reveal Shape : Square, Render Delay : 0, Cave Max Distance : 32, Surface Max Distance : 32**. Close **Options** click on **Auto-Map** and map all regions. 

6. Once automapping is done you'll see straight looking phantom biomes on the map like this Dark Forest here:

![afbeelding](https://user-images.githubusercontent.com/19509275/76125281-bae21f00-5ffc-11ea-8883-2d5937a1d6e3.png)

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

https://pastebin.com/BjLj5F9x

No sure if there are any errors but here is the log just in case.

**Comment by mysticdrew** [comment]
This is fixed in v.0.0.3 of TerraForged!
