### ISSUE TITLE
[1.15.2] JourneyMap keybind overrides every screens.

### ISSUE THREAD

**Issue by Bass2style** [TeamJM/journeymap#187]
#### Describe the problem in repeatable steps:

1. open a menu, an option or something else.
2. press the JourneyMap keybing
3. tada, JourneyMap appairs

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
idk if it's very revelant, but here's the latest journeymap log : https://pastebin.com/eAdHSFk9
but i have made a video of it : https://www.youtube.com/watch?v=KHXeHLIfQGU

**Comment by mysticdrew** [comment]
This will be fixed in beta 2
