### ISSUE TITLE
MC1.12.2 Unable to disable /jtp

### ISSUE THREAD

**Issue by DanTheDragon** [TeamJM/journeymap#190]
#### Instructions for Submitting an Issue
1. Ask for help on Discord (https://discord.gg/eP8gE69) #support if you're unsure this is a new issue.
2. Please search for existing issues before submitting a new one.
3. Please add the correct MC<version> label to your issue. Example: "[1.12.2] Waypoints are upside down"
4. Completely fill out the template below. Failure to do so is likely to get the issue closed immediately.
5. Prove you read these instructions by deleting this section before submitting. ;)
---
  
#### JourneyMap Version:

1.12.2-5.5.9

#### Forge Version:

1.12.2-14.23.5.2847

#### Describe the problem in repeatable steps:

1. Any user with no access on the server can use /jtp
2. The command works fine.
3. Everyone spams it.

**Comment by mysticdrew** [comment]
Disable waypoint teleporting in the server admin screen.

**Comment by DanTheDragon** [comment]
> 
> 
> Disable waypoint teleporting in the server admin screen.

The waypoing teleporting in the admin screen is disabled, still same result, with no permission on the server /jtp can still be used.
![2020-03-17_08 22 54](https://user-images.githubusercontent.com/36618807/76828033-c2899b00-6828-11ea-91fa-c739bd2cf35c.png)

**Comment by mysticdrew** [comment]
Are they oped? If they're oped, then they can use it. 
Otherwise it's impossible. 

Pastebin/gist your server's latest.log

**Comment by DanTheDragon** [comment]
https://pastebin.com/tMJ790jf

**Comment by mysticdrew** [comment]
Hmm, there is a sponge error after attempting to tp to dim 5. What is happening in the game when that happens? 

Also I think that I changed the permissions placement check in 5.7.0, try putting that on the server and see if it resolves the issue. It seems sponge may be interfering here.

**Comment by DanTheDragon** [comment]
On the server the comand sends me in overworld at some coordonates, sorry I don't know the exact cootrdinates now since I am not at my pc. 

Changing the version might not be a solution since the server is All the Mods 3 Remix v1.5.4 that would also require the client to change the version.

**Comment by mysticdrew** [comment]
You could try it temporarily just to see. 
I think the check to see if someone is an op is saying that they are when they are not. One of your permission mods/plugins may be causing it. 

Jm always lets ops use jtp, it uses the same permission properties as tp. Unless it's enabled for everyone.

**Comment by mysticdrew** [comment]
I'm out of town for about 24 hours still, but come into our discord and tomorrow we can try to figure out what's happening.

**Comment by DanTheDragon** [comment]
Ok so I tried, the 5.7.0 version for MC1.12.2 and still the same problem, I removed all my perms from LuckPerms, I've deoped myself and still could use the /jtp

**Comment by mysticdrew** [comment]
Well how about you come into our discord and I can help diagnose easier.
https://discord.gg/eP8gE69

**Comment by mysticdrew** [comment]
One thing I did think about, while tp is disabled globally, if you have it enabled for each dimension, that overrides the global settings for that dimension. 

In the server admin, there is an enabled check box. If that is checked, that dim's settings take precedence over the global settings.

**Comment by DanTheDragon** [comment]
I've checked every dim when I tested and none was enabled. I'm at work atm but I will come on discord later today or tomorrow.

**Comment by DanTheDragon** [comment]
It was my mistake, after disabling the teleport from Admin Panel, I removed my op and all access but I remained in creative while testing it. Creative mode gave me access to this command, after disabling creative the command was unavailable.

I am sorry for all the confusion and thank you for all the support!
