### ISSUE TITLE
[1.15.2] Fullscreen map opens when typing j on a sign

### ISSUE THREAD

**Issue by TheDutchMC** [TeamJM/journeymap#191]
#### Describe the problem in repeatable steps:
1. Place a sign
2. Type the letter j on the sign
3. The fullscreen map will open, also exiting out of the sign editor.
### Other mods:

- ClothConfig
- CraftingTweaks
- CraftTweaker
- Hwyla
- LightOverlay
- MouseTweaks
- ReAuth

None of these mods should affect this.

**Comment by mysticdrew** [comment]
Duplicate #187
