### ISSUE TITLE
[1.15.2] Feature request: hide spectator-mode players on map.

### ISSUE THREAD

**Issue by Quu1337** [TeamJM/journeymap#192]
#### JourneyMap Version:

1.15.2-5.7.0 beta 1

#### Forge Version:

31.1.25

#### Describe the problem in repeatable steps:

1. /gamemode spectator
2. other players can see you on map

Would like to have config option to make spectator-mode players to stay invisible while on spectator-mode.

**Comment by mysticdrew** [comment]
I am adding a client option and a server option. 
The client option if you as a user want to hide spectators for your own needs. 
The server option only works with expanded radar enabled. 

Will be available in 5.7.2 beta 12 for MC 1.16.5 should be on curseforge tonight/tomorrow
