### ISSUE TITLE
1.14.4 Server Crash

### ISSUE THREAD

**Issue by MokahTGS** [TeamJM/journeymap#193]
#### JourneyMap Version: 

journeymap-1.14.4-5.7.0b1

#### Forge Version:

28.2.0

#### Describe the problem in repeatable steps:

1. Dedicated Server Running with 3 people
2. Server crashes with log below.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

https://pastebin.com/mmBPPQF5

**Comment by mysticdrew** [comment]
How about the whole log? not just the crash section

**Comment by MokahTGS** [comment]
There is no journeymap log.

**Comment by MokahTGS** [comment]
Why was this closed?

**Comment by mysticdrew** [comment]
You gave part of a log, I asked for the whole thing. You said no.. I cannot do anything with this limited information. So I closed it.

**Comment by MokahTGS** [comment]
I didn't say no, I said it wasn't there.  That's not part of a log, that's the crash log from the server.

There are no journey map logs anywhere.

**Comment by mysticdrew** [comment]
Re-read what I asked

**Comment by MokahTGS** [comment]
I'm not sure what you are talking about...the pastebin link is a crash log...from our server.

**Comment by MokahTGS** [comment]
The local log from clients?

https://www.dropbox.com/s/g9115s4c7vgzdo0/journeymap.log?dl=0

**Comment by mysticdrew** [comment]
Never once did I mention journeymap.log... not once. 
The log in the pastebin link is only a small portion of the log. I want the whole latest.log!

**Comment by MokahTGS** [comment]
Well, that's not possible since our server has been restarted with another map mod.  I'll have to see if I can get the crash to happen again by reactivating Journeymap.

In every crash and bug report I've given for the past 5 years has been crash logs.  Not the latest log, which gets overwritten when the server restarts.

**Comment by mysticdrew** [comment]
That is just the generic template. For servers it is different, latest.log is what is needed for server crashes. 

The crash log you posted is just saying where it crashed. Not what or why, the latest.log has a lot more in it.

**Comment by mysticdrew** [comment]
Reopening while waiting for the full log

**Comment by mysticdrew** [comment]
So the temporary fix is to delete your ops.json in your minecraft directory. This crash happens because one of your ops changed their minecraft names and it is not updated in the ops.json by minecraft.

**Comment by mysticdrew** [comment]
Will be fixed in beta 2
