### ISSUE TITLE
[Bug] [1.15.2] Unable to save waypoint after disabling waypoint.

### ISSUE THREAD

**Issue by mjlmjl888** [TeamJM/journeymap#194]
JourneyMap Version: 1.15.2-5.7.0beta1
Minecraft Version: 1.15.2
Forge Version: 31.1.27

1. Open up the waypoint manager.
2. Edit a waypoint.
3. Disable the waypoint.
4. Now instead of being able to save it, you have to change the name first.

**Comment by mysticdrew** [comment]
The bug is being able to edit a disabled waypoint. 1.12.2 has the same behavior.

**Comment by mysticdrew** [comment]
This was fixed, looks like I forgot to close it. I verified in 5.7.1 for 1.16.5
