### ISSUE TITLE
Hide name on map with shift (bend)

### ISSUE THREAD

**Issue by ChukiStrike** [TeamJM/journeymap#195]
First of all, thank you for your great work.
Could you put that when a player shift (bend), the name is hidden on the map? It would be a great help to us! 
Thank you! 

1.12.2

**Comment by techbrew-mc** [comment]
This used to be the behavior in earlier versions- sounds like a regression

**Comment by ChukiStrike** [comment]
And there is no possibility to activate it if any server wants to? It would give us a lot of play :) It's not always good to be watched haha

**Comment by mysticdrew** [comment]
Have your server admin disable expanded player radar on your server and sneaking players will not show up on the radar.

**Comment by ChukiStrike** [comment]
I'm the manager, if I've seen this option and we've tried it. The problem is that when it is necessary to be seen on the map, for example to be revived then they can't, that's why I was saying about bending over. Thank you for your replies.

**Comment by mysticdrew** [comment]
Yes, there is an issue with the expanded radar that "shifting", "sneaking", or as you put it "bending over" does not hide the player. It will be fixed in 1.14.4 and 1.15.2. But to allow sneaking to hide on the map, expanded radar must be disabled. 

Which then you will only see players within your render range.

**Comment by ChukiStrike** [comment]
Could you tell me what configuration you edited and where it is located?

**Comment by mysticdrew** [comment]
If you have op on the server, Press J to open the fullscreen map, then press O to open the Journeymap options, on the bottom right there will be a button named "Server Admin" (it will only show if you have been given op) click that, in the first screen there will be a button called "Expanded Radar" click that until it displays "None" the press "Save"

**Comment by ChukiStrike** [comment]
This works, it is possible to do it with the extended map for version 1.12.2? Or to expand the radar area with the expanded map disabled? Thank you!

**Comment by mysticdrew** [comment]
Nope, 1.12.2 is no longer supported, it will receive no new updates. Sorry.
