### ISSUE TITLE
[1.15.2] Sharing waypoints doesn't work on spigot

### ISSUE THREAD

**Issue by Vergenter** [TeamJM/journeymap#196]
#### JourneyMap Version:

`journeymap-1.15.2-5.7.0beta1`

#### Forge Version:

`31.1.27`

#### Describe the problem in repeatable steps:

1. Running Spigot(Spigot-c574e08-37f32da) server.
2. Paste coordinates to chat: [x:-245, y:70, z:-395]
3. Now you cannot ctrl+lpm it.

**Comment by mysticdrew** [comment]
This is fixed and will be in 5.7.1 beta 4 for mc 1.16.x
1.15 is EOL and will not receive this fix.
