### ISSUE TITLE
[1.15.2] How to disable update checking? - Stacktrace when trying to check for updates.

### ISSUE THREAD

**Issue by ProsperCraft** [TeamJM/journeymap#197]
I turn off all update checking in modpacks to avoid loading delays, and stacktraces years down the road when the update sites are gone.

#### JourneyMap Version:

journeymap-1.15.2-5.7.0beta1

#### Forge Version: 

31.1.27

#### Describe the problem in repeatable steps:

1.  Journeymap doesn't obey to the fml.toml flag to not check for updates
2. Journeymap common config lacking option to turn off updates.
3. Stacktrace in the log when it tries to check for updates.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
Stacktrace in console- https://gist.github.com/ProsperCraft/a077ede466014be7c35aef0f7e42405f

**Comment by mysticdrew** [comment]
It is in the options, also update your java version and the error will go away.
