### ISSUE TITLE
[1.15.2]Chinese translation

### ISSUE THREAD

**Issue by EnterFor** [TeamJM/journeymap#198]
Hi~I added the Chinese translation, but I don't know where to submit it.
Will you consider merging if I send it here? Thank you in advance
[zh_cn.zip](https://github.com/TeamJM/journeymap/files/4398700/zh_cn.zip)

**Comment by mysticdrew** [comment]
Thanks, it will be in the next release.

**Comment by mysticdrew** [comment]
we just added this https://github.com/TeamJM/language-files
In the future please do a pull request for the changes, thanks!
