### ISSUE TITLE
[1.15.2]Text is too small

### ISSUE THREAD

**Issue by EnterFor** [TeamJM/journeymap#199]
#### JourneyMap Version:

`journeymap-1.15.2-5.7.0beta1`

#### Forge Version:

`1.15.2-31.1.30`

#### Describe the problem in repeatable steps:

1. Install the Mod
2. Start the game
3. The language setting is simplified Chinese
3. Check in-game text

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
[journeymap.log](https://github.com/TeamJM/journeymap/files/4399019/journeymap.log)

Screen capture
![image](https://user-images.githubusercontent.com/10114685/77851053-33f22200-7209-11ea-8b03-f59553291a25.png)
![image](https://user-images.githubusercontent.com/10114685/77851060-42403e00-7209-11ea-9521-cf4e5e9d6f58.png)
**I've tried all screen resolutions, and it's the same problem**

**Comment by mysticdrew** [comment]
Font scale in the options.... 
mini map font scale is broken in beta 1, it is already fixed for the next release.

**Comment by EnterFor** [comment]
> Font scale in the options....
> mini map font scale is broken in beta 1, it is already fixed for the next release.

Thanks!When will the new version be released?
Because I've had problems with maps that sometimes don't show up, but I didn't report it

**Comment by mysticdrew** [comment]
Hopefully within the next week. I still have a few more bugs to address. 
You can always come into our discord to ask about broken things or minor issues.
