### ISSUE TITLE
[1.12.2] Default Options and JourneyMap Compat Issue

### ISSUE THREAD

**Issue by SnowShock35** [TeamJM/journeymap#2]
#### JourneyMap Version:

1.12.2-5.5.2 (Latest at the time)

#### Default Options Version:

1.12.1-9.2.4 (Latest at the time)

#### Forge Version:

1.12.2-14.23.0.2537 (Latest at the time)

#### Describe the problem in repeatable steps:

1. Create a Minecraft Forge instance using the given mods (and their versions) above
2. Load the instance up
3. Go to controls and set all the journey map keybindings to `None` by clicking each one and pressing `Esc`
4. Then save the keybindings and create a new single player world
5. run the command `/defaultoptions saveAll`
6. save and exit the game (close the game down fully)
7. Delete `options.txt` in the instance folder
8. Start Minecraft back up and go to Options > Controls
9. When you scroll down to JoruneyMap you'll see all the key bindings are back to normal again

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

https://pastebin.com/7Qa7aYsw

***

Disclaimer: Reported the issue both here and https://github.com/blay09/DefaultOptions since it only happens w/ JourneyMap and all other mods have no trouble with it.

**Comment by BrainStone** [comment]
Related:
- blay09/DefaultOptions#19
- blay09/DefaultOptions#23

**Comment by SnowShock35** [comment]
Oops. Forgot labels. Thanks @BrainStone 👍

**Comment by BrainStone** [comment]
As far as I know you can't add labels. But don't worry, that's what I'm here for.

**Comment by SnowShock35** [comment]
I can. I am in the team 😛

**Comment by BrainStone** [comment]
My bad xD Still I'll just do it anyways so no big deal

**Comment by mysticdrew** [comment]
The Error in your pastebin has to do with the version checking, nothing to do with keybinds. That error would not cause any issues with keybindings.

**Comment by SnowShock35** [comment]
@mysticdrew I just posted it because you asked for it. I wouldn't of thought it would of contained anything to do with it. Also, I don't get why it doesn't work tbh. Because I'm pretty sure you're implementing the keybindings in the correct manor, are you not?

**Comment by techbrew-mc** [comment]
> you're implementing the keybindings in the correct manor, are you not?
AFAIK we are. Will have to investigate.

**Comment by techbrew-mc** [comment]
Moved keybinding registration to init instead of postInit.  Fixed in 5.6.0b1.
