### ISSUE TITLE
[1.12.2] missing theme?

### ISSUE THREAD

**Issue by PhoenixRiver** [TeamJM/journeymap#20]
#### JourneyMap Version:

journeymap-1.12.2-5.5.2.jar

#### Forge Version:

forge1.12.2-14.23.1.2587

#### Describe the problem in repeatable steps:

1. Run Minecraft from the Launcher.
2. Quit Minecraft.
3. Look at the log file produced and find this error that I couldn't find already here.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`

`[main/ERROR] [journeymap]: Default theme not found in /home/willow/.minecraft/journeymap/icon/theme/flat/OceanMonument.theme2.json: OceanMonument (SUPPRESSED)`

Hope this helps :)

P.S. In case you need the list of mods I'm running (even though it doesn't seem very relevant to this error):
AIImprovements-1.12-0.0.1b3.jar
animania-1.12.2-1.4.3.jar
AppleCore-mc1.12.2-3.1.0.jar
CarryOn MC1.12 v1.7.jar
Chameleon-1.12-4.1.3.jar
chameleoncreepers-1.4.1-1.12.jar
chickens-6.0.3.jar
CookingForBlockheads_1.12.1-6.3.17.jar
CraftStudio-1.0.0.93-mc1.12-alpha.jar
DynamicSurroundings-1.12.2-3.4.7.2.jar
DynamicTrees-1.12.2-0.7.2c.jar
Erosion-2.2.1.jar
GiacomosFishingNet-1.12.2-1.6.1.jar
hatchery-1.12.2-2.1.2.jar
Hwyla-1.8.23-B38_1.12.jar
iceandfire-1.3.1-1.12.2.jar
ImmersiveEngineering-0.12-76-core.jar
ImmersiveEngineering-0.12-76.jar
japaricraftmod-1.12-3.6.0.jar
jehc-1.12-1.3.1.jar
jei_1.12.2-4.8.5.132.jar
jeiintegration_1.12.2-1.5.1.36.jar
journeymap-1.12.2-5.5.2.jar
llibrary-1.7.9-1.12.jar
Mantle-1.12-1.3.1.21.jar
morechickens-1.12.2-3.0.0.jar
natura-1.12.2-4.3.2.42.jar
OptiFine_1.12.2_HD_U_C8.jar
Owls-1.12.2-1.0.1.jar
Pam's HarvestCraft 1.12.2f.jar
simplytea-1.4.jar
SpiceOfLife-mc1.12-1.3.11.jar
StorageDrawers-1.12.1-5.3.3.jar
Waddles-1.12.2-0.5.6.jar
WailaHarvestability-mc1.12-1.1.12.jar

**Comment by BrainStone** [comment]
Same issue in 5.6.0b1

**Comment by bobotje** [comment]
The theme is not missing but indeed the message shows.

**Comment by mysticdrew** [comment]
This is not a bug nor is it an issue. Nothing to worry about. I am removing the log output of it.
