### ISSUE TITLE
[1.15.2] No Player Dots/Names on Minimap or World Map

### ISSUE THREAD

**Issue by adamhayes2** [TeamJM/journeymap#200]
#### Instructions for Submitting an Issue

1. joined discord and didn't see a #support channel, just #issues channel that led me here 
2. also found some LAN related issues while browsing previously posted issues, but didn't find any related to 1.15.2 or the lack of player dots/names on both minimap and world map

#### JourneyMap Version:

https://www.curseforge.com/minecraft/mc-mods/journeymap/files/2894436

#### Forge Version:

1.15.2-forge-31.1.0

#### Describe the problem in repeatable steps:

1. installed the up-to-date journeymap jar on three machines with roommates
2. opened LAN server on one machine
3. everyone joined the LAN server
4. we realized we are unable to see eachothers player dots and names on minimap or world map

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

no errors

**Comment by FrightenedRabbit** [comment]
Any update on this issue?  I'm having the same issue.  Joined my wife's server on LAN, I cannot see her player icon on either world map or minimap but she can see mine.  She then joined my world and again the host could see the other player but the host's player icon was not visible.

**Comment by theluckybubba** [comment]
HI everyone, 

My first post so apologies if I have a lot to learn about this site. Using LAN or hosted server with logicservers and both ways having issues with some players not seeing the other players icons or dots in the minimap or the big map. Have tried turning on and off animals and other icons as indicated in other error reports but issue persists with some players not being able other see other players in the maps. Thanks for the great mod.

**Comment by mysticdrew** [comment]
Lan fixes are in the latest 1.16 version all other versions are EOL and will not receive the fix.
