### ISSUE TITLE
[1.15.2] Experience disappears on teleport

### ISSUE THREAD

**Issue by elind21** [TeamJM/journeymap#201]
#### JourneyMap Version:

1.15.2-5.7.0beta1

#### Forge Version:

1.15.2 forge 31.1.19

#### Describe the problem in repeatable steps:
When teleporting from the waypoint manager to a different dimension, the player's experience disappears, but reloads when more experience is gained.

1. Create a waypoint in the overworld *World Setting [cheats = true]*
2. Accrue some experience
3. Travel to the nether or other dimension
4. Open the waypoint manager and teleport to the waypoint in other dimension

Not the players experience bar is empty. If more experience is gained, the old experience is restored.

**Comment by mysticdrew** [comment]
This is a vanilla bug, I confirmed with the forge guys. Thanks
