### ISSUE TITLE
[1.15.2] Full Screen Map opens when editing a Sign

### ISSUE THREAD

**Issue by tristongilley** [TeamJM/journeymap#202]
#### JourneyMap Version:

journeymap-1.15.2-5.7.0beta1

#### Forge Version:

1.15.2-forge-31.1.35

#### Describe the problem in repeatable steps:

While editing a Sign, if you press a JourneyMap hotkey like "J" which would open the full screen map, it will open the full screen map even though you are editing a Sign.

1. Install JourneyMap into Mods folder
2. Load Minecraft, start new world
3. Place sign, Start typing and press a JourneyMap hotkey

**Comment by mysticdrew** [comment]
Duplicate #191 
This is fixed for beta 2
