### ISSUE TITLE
[1.15.2]

### ISSUE THREAD

**Issue by aolsen96** [TeamJM/journeymap#203]
#### JourneyMap Version:

1.15.2-5.7.0beta1

#### Forge Version:

1.15.2-31.1.9

#### Describe the problem in repeatable steps:

1. play the game
2. watch as memory used by java increase
3. your computer will now shut down everything
dont know how to reprodce but i have reinstald java, minecraft and jurneymap nothing has worked
nither is it consistent 

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
[crash-2020-04-08_18.21.36-client.txt](https://github.com/TeamJM/journeymap/files/4451621/crash-2020-04-08_18.21.36-client.txt)
[journeymap.log](https://github.com/TeamJM/journeymap/files/4451618/journeymap.log)

**Comment by gdude2002** [comment]
Can you confirm that this doesn't happen without JourneyMap installed? `GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT` doesn't seem to be related to anything we're doing.

**Comment by mysticdrew** [comment]
This does not look to be journeymap related. Closing

**Comment by aolsen96** [comment]
it does not happen when i remove journeymap
