### ISSUE TITLE
[1.14] Lag spikes when together with optifine

### ISSUE THREAD

**Issue by Solus-Prime** [TeamJM/journeymap#204]
#### JourneyMap Version:

journeymap-1.14.4-5.7.0b1

#### Forge Version:

28.2.0

Every 10-15 seconds the game will freeze up and then continue as normal only to repeat the cycle, the issue has only been observed when optifine [1.14.4 HD U F5] is also installed 

https://gist.github.com/Solus-Prime/2e3f7b19467b8225549081f8604ecee3-log from journeymap
https://gist.github.com/Solus-Prime/052768daf5db3d84ea500113528d2edd- log from multic mc

**Comment by gdude2002** [comment]
This is a known issue - it should be more or less addressed in the next beta.
