### ISSUE TITLE
1.12.2 pixelmon reforged . cant use special abilitys of pokemon .

### ISSUE THREAD

**Issue by Malefizz** [TeamJM/journeymap#205]
I cant use in this pixelmon reforged the special abilitys (with b , g ) and when i uninstall journeymap
it works . but i want to use journeymap . anyone has a idea what yu can do ?

**Comment by RodrigoTaipe93** [comment]
Switch the keyboard options! Check the control section, then keyboard. If you see buttons in red font, it means to mods are trying to use that keyboard button. Change it to something different. For example, if the Pokemon mod chooses the J button for petting a pokemon, change it to the keyboard button U, so it doesn't conflict with JM!
Hope this helps!

**Comment by BrainStone** [comment]
The template is there for a reason. Fill it out.
