### ISSUE TITLE
[1.15.2] Client crash on waypoint teleport

### ISSUE THREAD

**Issue by gdude2002** [TeamJM/journeymap#207]
#### JourneyMap Version:

`1.15.2-3.7.1-beta2`

#### Forge Version:

`1.15.1-31.1.46`

#### Describe the problem in repeatable steps:

Client crash on teleporting to waypoint in a dimension I haven't yet visited.

[Crash log](https://cdn.discordapp.com/attachments/329372521084223488/701177312627916861/crash-2020-04-18_22.07.20-client.txt)

**Comment by GatekeeperTDS** [comment]
I'm not sure this issue is closed. In the new Journeymap version (beta 3 for 1.15.2), I clicked on the "Downloads & Changelog" button on the splash screen and immediately got the same mouseclick client crash from before.

java.lang.NullPointerException: mouseClicked event handler

**Comment by ConnCraft** [comment]
Similar crash on closing menu after deleting death waypoints.

https://pastebin.com/ewA96YHS

**Comment by mysticdrew** [comment]
Please verify if this is still an issue in the latest journeymap version for minecraft 1.16. 
If it is, please reopen. I believe this issue was addressed with the port.
