### ISSUE TITLE
Stucked Dimension button 

### ISSUE THREAD

**Issue by DreadFenrir** [TeamJM/journeymap#208]
#### JourneyMap Version: 

1.15.2-5.7.0 

#### Forge Version:

1.15.2-31.1.41

#### Describe the problem in repeatable steps:

1. I opened the manage Waypoints windo on a server to try to add a new waypoint 
2. I clicked the “dimension” button, the one between “New...” and “close” 
3. The button is stuck at the “Dimension:Dimension 3” and no matter how much do I click the button, or even if I reboot minecraft, it keeps stucked, and I can’t see any other Dimension Waypoints):

**Comment by DreadFenrir** [comment]
![28AB2D62-3755-4EA8-A985-B55E973C5ED0](https://user-images.githubusercontent.com/64126503/79951823-0763ab80-843f-11ea-882c-b31b00057bac.jpeg)

**Comment by DreadFenrir** [comment]
![1CE95EE3-E510-42BA-AF2F-61A6E4D11615](https://user-images.githubusercontent.com/64126503/79951980-47c32980-843f-11ea-87ee-5e8700f14ae6.jpeg)

**Comment by DreadFenrir** [comment]
![83E7D754-4F24-4720-8AB1-C0657D886EF5](https://user-images.githubusercontent.com/64126503/79952019-59a4cc80-843f-11ea-9d3b-3cda64626843.jpeg)

**Comment by mysticdrew** [comment]
learn to use print screen button. I cannot even  see the text on the bottom screen shot.
Retest with beta 3. Closing unless it is still an issue then I will reopen.
