### ISSUE TITLE
JM freezes when updating the map - 1.12.2

### ISSUE THREAD

**Issue by RodrigoTaipe93** [TeamJM/journeymap#209]
This is basically a bug.

Whenever I try to update the map (the one you get pressing J), the screen freezes. This didn't happened with the previous versions of JM; even if I had a lot of mods.

My apologies for not using Pastebin but it didn't let me.

I updated the map when I was finishing my session, so you may want to look at the last part of the log

[latest.log](https://github.com/TeamJM/journeymap/files/4526784/latest.log)

**Comment by RodrigoTaipe93** [comment]
I want to add that it freezes for around 3 minutes, then it let's me play again.

**Comment by BrainStone** [comment]
The template provided is there for a reason.
