### ISSUE TITLE
Can't Teleport In Survival

### ISSUE THREAD

**Issue by beanaboston** [TeamJM/journeymap#21]
#### JourneyMap Version:

1.12.2-5.6.0b2

#### Forge Version:

1.12.2-14.23.1.2587

#### Describe the problem in repeatable steps:

1. Attempt to teleport to waypoint in survival.
2. Waypoint is in same dimesion and world has cheats enabled.
3. Message in chat says "journeymap has disabled JourneyMap teleporting by Players in this dimension in SURVIVAL." (copied from log file)
4. I went into creative and changed the features to what I assumed meant I could teleport in survival (dimension overworld, gamemode survival, teleport option is white) but when I go to teleport it shows that message and resets the changes I made.

**Comment by mysticdrew** [comment]
Closing all 5.6.0 issues. Please downgrade to 5.5.2 as 5.6.0 is no longer publicly available.
