### ISSUE TITLE
[1.15.2] slow fullscreen panning with extreme sound muffler mod installed

### ISSUE THREAD

**Issue by theboo** [TeamJM/journeymap#211]
#### JourneyMap Version:
1.15.2-5.7.0beta1

#### Forge Version:

31.1.47

#### Describe the problem in repeatable steps:

1.install journeymap
2.install extreme sound muffler mod
3. pan around in fullscreen map with mouse cursor
With this mod removed, fullscreen map pans at the speed of the mouse cursor as normal.

link to issue in ESM github
https://github.com/LeoBeliik/ExtremeSoundMuffler/issues/8#issue-606803332

**Comment by gdude2002** [comment]
Thanks for the report, I had noticed an exception being thrown but haven't had time to look into it yet. I doubt it's our fault, but we can check it out.

**Comment by theboo** [comment]
Extreme sound muffler devs were able to fix the issue, tested personally, should be in their next update. Thanks!
