### ISSUE TITLE
[1.14.4] Waypoint coordinate fields un-editable

### ISSUE THREAD

**Issue by wingzero54** [TeamJM/journeymap#212]
#### JourneyMap Version:

1.14.4-5.7.0b1

#### Forge Version:

Forge 1.14.4-28.2.4

(Note: I also verified the issue persists on Forge 1.14.4-28.2.0 which is the recommended Forge version for this JourneyMap version)

#### Describe the problem in repeatable steps:

Waypoint coordinate (X, Y, Z) fields and color (R, G, B) fields are unable to be edited. Only the name field can be edited. It doesn't matter whether you open a waypoint view the Create Waypoint hotkey or through the Waypoint Menu and hit Edit. 

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

I see lots of null pointer exceptions in the log but I'm not sure that's to do with the waypoint fields. 
[journeymap.log](https://github.com/TeamJM/journeymap/files/4534627/journeymap.log)

**Comment by mysticdrew** [comment]
This is fixed for the next release already

**Comment by wingzero54** [comment]
Oh very cool I looked at didn't see any tickets for this. Thank you for the awesome mod
