### ISSUE TITLE
Pixelmon Sprites

### ISSUE THREAD

**Issue by WeeabooOppa** [TeamJM/journeymap#213]
#### JourneyMap Version: 1.12.2-5.7.1

`Example: 1.12.1-5.5.0`

#### Forge Version: Not sure, I'm on techcnic Launcher. I know it's 1.12.2

`Example: 1.12.1-14.22.1.2478`

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
N/A

**Comment by mysticdrew** [comment]
no logs?
