### ISSUE TITLE
render problem with blocks

### ISSUE THREAD

**Issue by LearnerZ** [TeamJM/journeymap#214]
#### Describe the problem in repeatable steps:

1.installed journeymap,and as the picture shows <a href="https://imgchr.com/i/J4fTw8"><img src="https://s1.ax1x.com/2020/04/28/J4fTw8.png" alt="J4fTw8.png" border="0" /></a>,
block didnt  fully render.
2.press F3+A, problem fix temporarily. when i reach the edge,same problem again.(the thing is, the distance to the transparent block equal the number of render distance. )
3.Uninstall journeymap,the problem gone.(i tested couple hours last night, reinstall game,reset opti etc. )
4.is it  optifine render or  compatible problem?

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
[journeymap.log](https://github.com/TeamJM/journeymap/files/4543343/journeymap.log)

**Comment by mysticdrew** [comment]
This is an issue with optifine.
