### ISSUE TITLE
Foxes heads dont show in the map

### ISSUE THREAD

**Issue by AdrianDST** [TeamJM/journeymap#217]
#### JourneyMap Version:  1.15.2-5.7.0beta-1

#### Describe the problem in repeatable steps:

1.The fox head doesnt appear as an icon in the map but other mobs like rabbits yes
2.![Captura](https://user-images.githubusercontent.com/55557976/80853672-ca639a00-8c32-11ea-99c4-b37b5e96a28c.JPG)   (the white large dots are the foxes)

**Comment by mysticdrew** [comment]
if fox a vanilla mob, or is that from a mod?

**Comment by AdrianDST** [comment]
its from vanilla

**Comment by AdrianDST** [comment]
also the variant,the artic fox doesnt appear

**Comment by mysticdrew** [comment]
Great, thanks, I will look into it. I am not familiar with all the new things

**Comment by mysticdrew** [comment]
most of the new mob icons are added in 1.16, we are adding more as we find some that are missing.
