### ISSUE TITLE
Pressing [Show/Hide Fullscreen Map] opens map in any GUI

### ISSUE THREAD

**Issue by Partonetrain** [TeamJM/journeymap#218]
#### JourneyMap Version:

journeymap-1.15.2-5.7.0beta1

#### Forge Version:
31.1.60

#### Describe the problem in repeatable steps:

1. Have JourneyMap and Forge in 1.15.2
2. Create new world, pause by pressing ESC
3. press J (by default), game will unpause and mobs in map will move around

**Comment by mysticdrew** [comment]
This is resolved and will be in the next beta, please use the search function.
Duplicate #202
