### ISSUE TITLE
[1.15.2] Display is turned on: icons, static beam, rotating beam. When i turn off the display of a static beam and a rotating beam, the icon is also not visible.

### ISSUE THREAD

**Issue by well076** [TeamJM/journeymap#219]
#### JourneyMap Version:

`Example: 1.15.2-5.7.0beta1`

#### Forge Version:

`Example: 1.15.2-31.1.62`

#### Describe the problem in repeatable steps:
Hi. Beacon management enabled. Display is turned on: icons, static beam, rotating beam. When i turn off the display of a static beam and a rotating beam, the icon is also not visible. Previously, you could turn on the display of only one icon. Initially, i could leave the display only icon.

**Comment by mysticdrew** [comment]
This is addressed in the next release
