### ISSUE TITLE
[1.15.2] Installing optifine with forge breaks some chunks rendering

### ISSUE THREAD

**Issue by imodre** [TeamJM/journeymap#220]
#### JourneyMap Version:
1.15.2-5.7.0b2

#### Forge Version:
1.15.2-31.1.63

#### Describe the problem in repeatable steps:
1. Install journeymap + forge
2. Install optifine (w/ forge)
3. Join any world fast after game loading (or change servers fast)
You will get some chunks that are close to you invisible untill you do F3+A. Screenshots are posted by @evolfox and @jc-hiroto below and there: https://github.com/sp614x/optifine/issues/3731

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
It's clear (no errors at all there).

**Comment by MasterAslan** [comment]
I tried running this for the first time with optifine and the full map was like this.  I disabled optifine and then it started working.  

MC version 1.15.2
Forge version 1.15.2-31.1.63
Optifine Version preview_OptiFine_1.15.2_HD_U_G1_pre14.

**Comment by evolfox** [comment]
I also have a rendering problem with Forge 31.1.63 + OptiFine 1.15.2 HD U G1 pre15

![lNRBC3U 1](https://user-images.githubusercontent.com/16793885/80916249-ced5a300-8d57-11ea-990e-b95ac7eb0733.jpg)

**Comment by jc-hiroto** [comment]
@evolfox same problem using G1_pre13 Ultra

**Comment by clintmay** [comment]
having the same issue, had to revert back to the previous version until it's fixed

**Comment by LaminatedPotato** [comment]
This issue is also happening in Minecraft 1.14.4 with Optifine HD F5 Ultra and Forge 28.1.56

**Comment by imodre** [comment]
Unable to reproduce this bug anymore on pre16. Since there are more people confirming this on different mc versions, can't close this issue until they could confirm the same (I guess)

**Comment by jc-hiroto** [comment]
In my case, the problem still occurs in 
***MC1.15.2 / Optifine pre16 / Forge  31.1.76 / journeymap-1.15.2-5.7.0b2***

*Screenshot*
![Screenshot](https://user-images.githubusercontent.com/38657003/81277038-6c95de80-9086-11ea-8651-092688b520b9.png)

**Comment by imodre** [comment]
> In my case, the problem still occurs in
> _**MC 1.15.2 / Optifine pre16 / Forge 31.1.76 / journeymap-1.15.2-5.7.0b2**_
> 
> _Screenshot_
> ![](https://camo.githubusercontent.com/938ec49a20cf399eaf901a9eb3045e6739c20ac5/68747470733a2f2f692e696d6775722e636f6d2f6a7945734e46722e706e67)

Yup. This problem with rendering (transparent chunks when joining) still exist (there is even an issue at optifine repo - https://github.com/sp614x/optifine/issues/3731) but this issue was about breaking map rendering (glitched chunks at minimap) and that one seems to be fixed now.

**Comment by MasterAslan** [comment]
Updated to forge 31.1.77 and optifine preview 16 I am also no longer getting this issue.

**Comment by imodre** [comment]
So, instead of closing this issue I think it's better to make it about rendering problem that people experience now.

**Comment by jc-hiroto** [comment]
Btw my problem happened when I’ve reached the rendering distance (tested by modifying the render distance), so this situation mostly happened when I’m in a boat exploring or teleport to a rather far place.
Even if I use the default shader, this problem keeps happening as long as Optifine is installed as a mod. Kinda weird 🤔

**Comment by MasterAslan** [comment]
> 
> 
> Even if I use the default shader, this problem keeps happening as long as Optifine is installed as a mod. Kinda weird 🤔

Does it do that without journeymap?

**Comment by imodre** [comment]
> > 
> 
> > 
> 
> > Even if I use the default shader, this problem keeps happening as long as Optifine is installed as a mod. Kinda weird 🤔
> 
> 
> 
> Does it do that without journeymap?  
> 
> 

Nope. Tried this many times but couldn’t reproduce this without journeymap. So, I guess there is some conflict between jmp map renderer (or something else) and optimism e custom renderer. They wrote In discord and twitter about how much mc rendering code was rewritten in optifine. However, since there is no open source, we can’t tell what is really the problem there. But I think it’s more on optifine side.

**Comment by MasterAslan** [comment]
> > Does it do that without journeymap?
> 
> Nope. Tried this many times but couldn’t reproduce this without journeymap. 

So this ticket can probably be closed.  If another ticket isn't already open under optifine you could raise that there.

**Comment by ianmarder** [comment]
> Updated to forge 31.1.77 and optifine preview 16 I am also no longer getting this issue.

Can confirm.

Forge 31.1.77
OptiFine 1.15.2 HD U G1 pre16
JourneyMap 1.15.2-5.7.0b2

does not experience the chunk loading problem.

**Comment by clintmay** [comment]
This screenshot was taken using:

Forge 31.1.77
OptiFine 1.15.2 HD U G1 Pre16
Journeymap 1.15.2 5.7.0b2
SEUS Renewed 1.0.1 (Shader pack)

![image](https://user-images.githubusercontent.com/43228921/81490297-53d42700-9246-11ea-996f-e1dbd08f6223.png)

**Comment by ianmarder** [comment]
> This screenshot was taken using:
> 
> Forge 31.1.77
> OptiFine 1.15.2 HD U G1 Pre16
> Journeymap 1.15.2 5.7.0b2
> SEUS Renewed 1.0.1 (Shader pack)
> 
> ![2020-05-09_22 39 42](https://user-images.githubusercontent.com/43228921/81490308-8da52d80-9246-11ea-9183-90061942059b.png)

I didn't experience anything for a little while, but it was probably a fluke.

Now I'm experiencing it again.

Forge 31.1.77
OptiFine 1.15.2 HD U G1 Pre16
Journeymap 1.15.2 5.7.0b2
Sildurs Vibrant Shaders v1.27

**Comment by imodre** [comment]
Tried updating forge - there is a slight improvement (harder to reproduce the issue) but rejoining 2 different servers fast still causes some chunks to disappear. (with or without shaders enabled)

**Comment by Thamakil** [comment]
Same Problem with:
Forge 31.1.78
OptiFine 1.15.2 HD U G1 Pre16
Journeymap 1.15.2 5.7.0b2
If I remove either OptiFine or Journeymap everything works just fine.

Also I had the impression that it could have something to do with the client no longer communicating the players movements properly to the server when these two mods are active.
Because after walking around some time with the bug the server sent a message in chat that I was AFK which I was not.
Also after relogging I spawned at a different place as I had logged off.
But not 100% sure if that is really connected to the problem or not.

**Comment by shatteredhalo** [comment]
Same issuehere.

Minecraft 1.15.2
Forge 31.1.87
OptiFine 1.15.2 HD U G1 Pre16 (includes dependecies MixinBootstrap-1.0.3 , OptiForge-MC1.15.2-0.1.17)
journeymap-1.15.2-5.7.0b2

**Comment by crenexi** [comment]
Same issue. I had 1.15.2 setup (Forge + Optifine + JourneyMap). I rolled everything back to 1.14.4 and faced the same behavior. Can confirm it only occurs when I hit the rendering edge.

**Comment by ianmarder** [comment]
Does anyone have an update since the pre21 release?

**Comment by imodre** [comment]
@ianmarder Yup. Just installed this version, no changes in this bug. Still a lot of invisible chunks just after joining a server.

**Comment by JavierPAYTEF** [comment]
I'm also experiencing this issue. My versions are these:
Forge 3.1.20
journeymap-1.15.2-5.7.0b2
preview_OptiFine_1.15.2_HD_U_G1_pre19

This appears to happen when a lot of chunks are loaded quickly, like going through portals or fast on a boat. Some of the chunks fail to load and are "transparent". You still hit the blocks like they were there you just don't see them.

Pressing F3+A reloads everything and most of the times it works. But it's kind of annoying to be pressing it so often.

**Comment by HireSLH** [comment]
> I'm also experiencing this issue. My versions are these:
> Forge 3.1.20
> journeymap-1.15.2-5.7.0b2
> preview_OptiFine_1.15.2_HD_U_G1_pre19
> 
> This appears to happen when a lot of chunks are loaded quickly, like going through portals or fast on a boat. Some of the chunks fail to load and are "transparent". You still hit the blocks like they were there you just don't see them.
> 
> Pressing F3+A reloads everything and most of the times it works. But it's kind of annoying to be pressing it so often.

Same on Pre22

**Comment by Alojalia** [comment]
The problem continues to occur with the following versions:

forge-1.15.2-31.2.22
preview_OptiFine_1.15.2_HD_U_G1_pre30
OptiForge-MC1.15.2-0.1.26
journeymap-1.15.2-5.7.0b3

The best way to verify this is to cross the Nether portal to either side and the problem always occurs.

**Comment by Marcelo-Petrucelli** [comment]
Well, I guy says he managed to "fix" it. Since it may be a clue to a possible solution from JM part, I'll leave a link to that discussion:
https://github.com/sp614x/optifine/issues/3893

From his side, he seems to have found a connection between the bug and the way-point beacon functionality. I also seems to have something to do with rotating beacons.

**Comment by mysticdrew** [comment]
Closing this as 1.15.2 is EOL and no longer supported. 

If there is still an issue in 1.16 with Journeymap and Optifine, create a new issue.
Thanks.
