### ISSUE TITLE
[1.15.2] Crash when deleting a waypoint marker.

### ISSUE THREAD

**Issue by Gbergz** [TeamJM/journeymap#223]
#### JourneyMap Version:

`1.15.2-5.7.0b2`

#### Forge Version:

`1.15.2-31.1.74`

#### Describe the problem in repeatable steps:

1. Open up journey map waypoint manager
2. Try to delete a Waypoint (this was a deathmarker).
3. Game freezes, then crashes.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
No idea if there's errors in here but i'll post it anways: https://gist.github.com/Gbergz/b5abbf253716e6eccedaf48d7c5fd8db !

 And here's the Gameclient Crash-Report: https://gist.github.com/Gbergz/09f402b3789ba1612811ee9b52d5b3fa

- Gbergz

**Comment by mysticdrew** [comment]
Duplicate #207 Yes it is the same issue

**Comment by Gbergz** [comment]
Sorry, should've checked previous issue beforehand!

**Comment by mysticdrew** [comment]
it's all good, this bug appears when doing different things in the waypoint manager.
