### ISSUE TITLE
Waypoint label render and map lag

### ISSUE THREAD

**Issue by RepoDraghon** [TeamJM/journeymap#225]
The labels for the waypoints aren't rendering correctly...
Also, I noticed a lag on the full-screen map hovering over an area with the mouse. I have to wait for 2  or 3 seconds to see what biome is at that coordinate...

#### JourneyMap Version:

1.15.2-5.7.0b2

#### Forge Version:

1.15.2 --- 31.1.77

#### Describe the problem in repeatable steps:

1. Create a waypoint
2. step back a ways
3. look at waypoint

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
![2020-05-06_17 42 30](https://user-images.githubusercontent.com/8423696/81256358-1e7cce80-8fe5-11ea-9bff-d7cf7d4886c7.png)

**Comment by mysticdrew** [comment]
Do have optifine installed?

**Comment by RepoDraghon** [comment]
Nope...

**Comment by taj1994** [comment]
I'm having the same issue with and without OptiFine installed. Waypoint labels render fine when there are no blocks rendered between you and them, or if those blocks are glass, but not if there are any other blocks

JourneyMap version - 1.15.2-5.7.0b2
Forge version - 31.2.5

**With** OptiFine:
![2020-06-03_14 42 14](https://user-images.githubusercontent.com/1844822/83687299-cec00180-a5a8-11ea-9f1a-1474ab1ca30a.png)

**Without** OptiFine:
![2020-06-03_14 43 25](https://user-images.githubusercontent.com/1844822/83687347-dc758700-a5a8-11ea-9a76-5358fe1a61c1.png)

**Comment by mysticdrew** [comment]
I cannot replicate this issue, can you verify if it is still an issue with beta 3 and the latest forge? Closing for now, reopen if it is still an issue.

**Comment by taj1994** [comment]
I just updated to Forge 31.2.20, and JourneyMap 1.15.2-5.7.0b3, and I'm still getting this issue. Forge and JourneyMap are the only things installed

![2020-06-16_17 14 46](https://user-images.githubusercontent.com/1844822/84806413-ddec7980-afc2-11ea-9348-43eb193b6858.png)

**Comment by mysticdrew** [comment]
try without your resource pack please.

**Comment by taj1994** [comment]
> try without your resource pack please.

Didn't think of that... I'll try that when I'm back at my PC and get back to you

**Comment by taj1994** [comment]
Update. It works fine with the default textures, but has issues with most resource packs I just tried, not just BDCraft. It looks like this issue shows up with any packs that change the font from the default
