### ISSUE TITLE
1.15.2 mouseDragged event handler crash

### ISSUE THREAD

**Issue by frostfire50** [TeamJM/journeymap#226]
Basically I was deleting two waypoints and I tried to close out the waypoint tab then I froze, so I pressed the Esc button but I still was frozen so I started moving my mouse then after a couple of seconds the screen said "Saving world” and then my minecraft crashed.Here’s the crash report (https://hastebin.com/resiwazoku.php)   
JourneyMap Version:

1.15.2-5.7.0b2.jar

Forge Version:

1.15.2-31.1.62

 Describe the problem in repeatable steps:

1.Delete waypoints
2.Close waypoint tab
3.Press Esc
4.Move mouse around

Relevant errors from .minecraft/journeymap/journeymap.log: Couldn't locate icons for Default and Flat.

**Comment by mysticdrew** [comment]
Duplicate #207
