### ISSUE TITLE
[1.15.2] Client crash on mouseEvent from button 'Downloads and Changes'

### ISSUE THREAD

**Issue by wezu123** [TeamJM/journeymap#227]
#### Describe the problem in repeatable steps:

1. Launch the game
2. Open About menu
3. Click 'Downloads and Changes' button
[latest.log](https://github.com/TeamJM/journeymap/files/4600632/latest.log)
[crash-2020-05-08_19.30.33-client.txt](https://github.com/TeamJM/journeymap/files/4600633/crash-2020-05-08_19.30.33-client.txt)
[journeymap.log](https://github.com/TeamJM/journeymap/files/4600634/journeymap.log)

**Comment by JoeDiesAtTheEnd** [comment]
im having the same issue when i go to set a waypoint.

**Comment by JoeDiesAtTheEnd** [comment]
[crash-2020-05-08_16.10.18-client.txt](https://github.com/TeamJM/journeymap/files/4602120/crash-2020-05-08_16.10.18-client.txt)

**Comment by IchigoGames** [comment]
https://pastebin.com/Gv5ZA8px same issue as well

**Comment by XCaramellX** [comment]
https://paste.ubuntu.com/p/3SFRzDqt5z/ me too.

**Comment by Joren2087** [comment]
Same here, but sometimes also when I press other buttons such as 'new' in waypoints. It, causes client to crash. It's very annoying
[crashlog](https://paste.md-5.net/huvatubute.sql)

**Comment by mysticdrew** [comment]
This is fixed in beta 3 for 1.14.4 and 1.15.2 beta 3 will be on curse a little later today
