### ISSUE TITLE
[1.15.2] Block breaking particles is highlighted

### ISSUE THREAD

**Issue by mefusion** [TeamJM/journeymap#229]
#### Steps to reproduce:

1. Start new world in survival mode
2. Get some shovel or/and pickaxe
3. Go to the cave
3. Try to mine some stone or dig some dirt and observe

Video with bug: https://youtu.be/A8tPoojF9pE
It can't be reproduceable in vanilla or just Forge

**Comment by mysticdrew** [comment]
Is this with only journeymap or other mods as well?

**Comment by mefusion** [comment]
> Is this with only journeymap or other mods as well?

I tried to reproduce that
Vanilla - Can not reproduce
Just forge without any mods - Can not reproduce
Forge with only JM - Can reproduce
Forge with JM & Optifine (as jar) - Can reproduce

But yes, i'm sure that is JourneyMap bug

**Comment by mysticdrew** [comment]
I could not replicate this bug, I tried. Please verify this is still an issue with beta 3(should be on curse soonish).  Closing for now, if it is still an issue with beta 3 and the latest forge, reopen.
