### ISSUE TITLE
[1.12.2] random crash? / color palette issue

### ISSUE THREAD

**Issue by TobiPeterG** [TeamJM/journeymap#230]
#### JourneyMap Version:
1.12.2-5.7.1
#### Forge Version:
1.12.2-14.23.5.2854

#### Describe the problem in repeatable steps:
umm I don't know what caused the crash, so I really can't tell, but it seems to be related to a color palette
1. load world
2. wait for the crash caused by?
3. you can't interact with nothing afterwards

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
[Journeymap.log](https://pastebin.com/efUTFs5i)
[latest.log](https://pastebin.com/GgVufHkE)

**Comment by mysticdrew** [comment]
This is not journeymap related, looks like biomes of plenty
