### ISSUE TITLE
[1.15.2]  Waypoint manager hotkey force-exits signs

### ISSUE THREAD

**Issue by oiGhostt** [TeamJM/journeymap#232]
#### JourneyMap Version:

1.15.2 5.7.0 beta1

#### Forge Version:

`Example: 1.15.2-31.1.87

#### Describe the problem in repeatable steps:

1. Entered a sign and was typing in words and whatsoever.
2. Hit my hotkey for the waypoint manager (Which is ".")
3. Game exited sign and printed my text onto it as if I hit the "ENTER" key.

**Comment by mysticdrew** [comment]
update to beta 2
