### ISSUE TITLE
[1.12.2] Enabling waypoint across multiple dimensions causes "teleport" to target wrong dimension

### ISSUE THREAD

**Issue by Jack-McKalling** [TeamJM/journeymap#234]
#### JourneyMap Version:

- 1.12.2-5.5.5
- 1.12.2-5.7.1

#### Forge Version:

- 14.23.5.2838
- 14.23.5.2854

#### Describe the problem in repeatable steps:

1. From the overworld, create a new waypoint
2. Enable the waypoint for the Nether (which is sorted above overworld)
3. Click Save button
5. Click the teleport button of the waypoint in the Waypoint Manager
6. You will be teleported to the Nether
7. Works for other dimensions too

The teleport button is teleporting you to the first dimension of the list, for which the waypoint has been set to show up in, as opposed to the dimension it was actually created in. I tested with other dimensions enabled, and results seemed to match this theory.

Not knowing about this unintuitive behaviour, I literally ended up falling into lava, while under the impression I was saving myself from another situation... 

#### Possible solution:
Waypoints should save the dimension you create them in, and teleport to specifically that dimension, no matter from where you are clicking the teleport button.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
none

**Comment by gdude2002** [comment]
Please check this issue on the [latest available version (5.7.1)](https://www.curseforge.com/minecraft/mc-mods/journeymap/files/2916002).

**Comment by gdude2002** [comment]
Looking at the implementation right now, actually, it does seem like this is what should happen. I agree with you that it's unexpected, though - we'll discuss.

**Comment by mysticdrew** [comment]
That is intentional.

**Comment by mysticdrew** [comment]
If the waypoint is enabled in multiple dimensions in the edit waypoint list. The teleport will take you to the dimension that is listed in the button in the waypoint manager, if all is listed it should take you to the current dimension you are in.

**Comment by Jack-McKalling** [comment]
This does not seem to be the case. It always takes me to the first dimension the waypoint is enabled for, regardless of that dimension selection button, regardless of how many dimensions I enable the waypoint for, and whichever order I enable them in.

**Comment by Jack-McKalling** [comment]
Basically if you have Dimensions A, B and C and you create a waypoint in C.
If you then enable the waypoint for A and B as well.
Then if you go to dimension B, and teleport to the waypoint of C that shows up, it will teleport you to dimension A.

However the mechanism is intended to work, if the teleport option does not respect the dimension of origin of a waypoint, it will always be confusing.

**Comment by mysticdrew** [comment]
I am going to close this, since this how it works. 

If you have several dimensions enabled for a waypoint, we have no idea which dimension you are wanting to teleport to, so it gets the first in the list of enabled dimensions. I agree, it is not ideal, but we plan to rewrite waypoints in the future. 

Then we will address how to handle this better, maybe a popup when you click teleport that shows a list of enabled dims. Or a way to set a primary dimension teleport target in the dimension edit/create screen.

**Comment by Jack-McKalling** [comment]
Ok, thanks, I understand. It sounds like the dimension of origin is not saved at all, yet. Then it will be difficult without that rewrite.

The way I had this in mind, is that whenever you "create" a waypoint, it would just always target that exact location in that exact dimension. And when other dimensions are enabled for that waypoint, it would just allow you to teleport to its target from that dimension, without having to browse using the dimension button.
