### ISSUE TITLE
[1.12.2] [Suggestion] Add Fractional Scaling

### ISSUE THREAD

**Issue by kalsandbrook** [TeamJM/journeymap#236]
Add Fractional Font Sizes for the minimap (1 is too small but 2 is too big). Add options for font scales such as 1.25, 1.5 & 1.75

**Comment by mysticdrew** [comment]
Currently adding this, keep an eye out on our discord for details when this is released. Though it will not be in 1.12.2

**Comment by mysticdrew** [comment]
This has been implemented in 5.7.2 for 1.16.5 the beta is now on curseforge.
