### ISSUE TITLE
[1.12.2] Typo in JourneyMap Options

### ISSUE THREAD

**Issue by Tslat** [TeamJM/journeymap#237]
#### JourneyMap Version:

`Example: 1.12.1-5.7.1`

#### Forge Version:

`Example: 1.12.1-14.23.5.2846`

#### Describe the problem in repeatable steps:

1. Go into Journeymap ingame settings
2. Go into either minimap preset section
3. Find that "Real" is miss-spelt as "Ream" in "Ream Game Time Format:"

**Comment by mysticdrew** [comment]
This will not be fixed for 1.12.2, updates are done for that version. This however has already been resolved for 1.14+ as it was reported already. Thanks.

**Comment by BrainStone** [comment]
Also please fill out the template properly!

**Comment by Tslat** [comment]
That was the template? I'm confused

**Comment by BrainStone** [comment]
I mean you clearly didn't fill it out: 
![grafik](https://user-images.githubusercontent.com/4106544/84573382-70f99980-ada0-11ea-949e-7e5b17196b11.png)

**Comment by Tslat** [comment]
Oh I forgot to remove "Example" - the version numbers I did put there
