### ISSUE TITLE
[1.15.2] crash when making waypoint ?

### ISSUE THREAD

**Issue by IchigoGames** [TeamJM/journeymap#238]
#### JourneyMap Version:

journeymap-1.15.2-5.7.0b2

#### Forge Version:

forge 1.15.2 31.2.0

#### Describe the problem in repeatable steps:
this did not happen to me but to some one playing my modpack.

1.make a waypoint 
2.game saves
3.crash

**Comment by mysticdrew** [comment]
duplicate #207
