### ISSUE TITLE
[1.15.2] Crash when opening Waypoint List containing no waypoints

### ISSUE THREAD

**Issue by Tazmania40** [TeamJM/journeymap#239]
#### Describe the problem in repeatable steps:
1. Open Waypoints list before death waypoint or other waypoint created.
2. Crash game

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
Appears not useful as it was overwritten: https://gist.github.com/Tazmania40/8e10a43d3083c2fd75a00fab06aa6da2

Hello Dev Team!

I have successfully found a crashing bug, which was repeated twice both by me and a friend of mine.
In essence, the crash happens when opening the waypoint menu that contains no waypoints. It causes a IndexOutOfBoundsException: Index: 0, Size: 0 when trying to lookup the list.

Thanks for reading!

Crash Logs attached: 
Mine: https://gist.github.com/Tazmania40/676f1e7c96da82fc4003ac2af2134242
My Friend: https://gist.github.com/coalman321/66aa5b61b4d4b7cf7cd194c9ee90ef17

**Comment by JakeMoe** [comment]
I came to report a similar issue; in my instance, twice now when I've only got one waypoint (death marker from Corpse both times), and I remove that waypoint, I get a similar crash. 
 I presume it's the same bug.

https://gist.github.com/JakeMoe/d8db05abd4060338e109574adff19282

**Comment by mysticdrew** [comment]
duplicate #207
