### ISSUE TITLE
[1.15.2] Deleting death waypoints then pressing escape crashes the game (inconsistant)

### ISSUE THREAD

**Issue by cerveau23** [TeamJM/journeymap#240]
#### Describe the problem in repeatable steps:

1. Open the waypoints' list
2. Delete all death waypoints
3. Press escape
4. Crash your game

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
I don't have the crash's log right now, but I will add it as soon as I have it.

**Comment by mysticdrew** [comment]
duplicate #207
