### ISSUE TITLE
[1.15.2] mouseClicked Error in Menus

### ISSUE THREAD

**Issue by GatekeeperTDS** [TeamJM/journeymap#241]
I'm not sure this issue is closed. In the new Journeymap version (beta 3 for 1.15.2), I clicked on the "Downloads & Changelog" button on the splash screen and immediately got the same mouseclick client crash from before.

java.lang.NullPointerException: mouseClicked event handler

_Originally posted by @GatekeeperTDS in https://github.com/TeamJM/journeymap/issues/207#issuecomment-645068099_

**Comment by mysticdrew** [comment]
#207 was not closed.... this is a duplicate closing
