### ISSUE TITLE
Vanilla Forceload overview

### ISSUE THREAD

**Issue by Lehrules** [TeamJM/journeymap#242]
Is it possible to get this functionality natively to see which chunks are being loaded by /forceload?

Perhaps an admin-only toggle with right click functionality to remove and add chunks? Obviously controlled by the config as to not disregard modpacks with chunkloaders as part of their progression systems.

_Originally posted by @Lehrules in https://github.com/TeamJM/journeymap/issues/12#issuecomment-648076682_

**Comment by mysticdrew** [comment]
make your own with our api, we will not be adding this.
