### ISSUE TITLE
[1.15.2] Flowers and wheat incorrectly rendered on the map

### ISSUE THREAD

**Issue by SilentDepth** [TeamJM/journeymap#243]
#### JourneyMap Version:

1.15.2-5.7.0b3
1.15.2-5.7.0b1
1.14.4-5.7.0b3
1.14.4-5.7.0b1

#### Forge Version:

1.15.2-31.2.0
1.14.4-28.2.0

#### Describe the problem in repeatable steps:

1. Create a world, plant some wheat somewhere, and bonemeal it till fully-grown.
2. Check the minimap or fullscreen map, the color of the wheat is light green like newly-planted (but should be yellow).
3. Plant some flowers elsewhere or find a flower forest.
4. Check the minimap or fullscreen map, no colorful flowers could be spotted (only the grass ground is rendered).
5. Set `mapPlants` to `true`, all the plants rendered in lime color (no matter what the actual color is, i.e. the red of roses/poppies).

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

No error occurs, just the color is not right.

**Comment by mysticdrew** [comment]
Can you verify this is still the case with minecraft 1.16?
1.15.2 is no longer supported, I will close this ticket. Please reopen if it is still an issue for you in 1.16

**Comment by SilentDepth** [comment]
@mysticdrew I tried JourneyMap 1.16.5-5.7.1b3 with Forge 1.16.5-36.0.42, and the issue exists.

![CleanShot 2021-02-22 at 21 18 36](https://user-images.githubusercontent.com/7194254/108714151-28f85c80-7554-11eb-9e53-f77e8fc2dfa0.png)

**Comment by mysticdrew** [comment]
While this wont help with 1.15 or 1.14. This is fixed in Journeymap 5.7.1 beta 4, will be on curse in a day or two from the time of posting.
