### ISSUE TITLE
Client crash on deathpoint delete. 

### ISSUE THREAD

**Issue by aetherpirate** [TeamJM/journeymap#244]
journeymap-1.15.2-5.7.0b3.jar
forge-1.15.2-31.2.5

1) Delete a deathpoint
2) Crash
[crash-2020-06-26_08.24.54-client.txt](https://github.com/TeamJM/journeymap/files/4836904/crash-2020-06-26_08.24.54-client.txt)

**Comment by aetherpirate** [comment]
[journeymap.log](https://github.com/TeamJM/journeymap/files/4852904/journeymap.log)

**Comment by mysticdrew** [comment]
Can you verify this is still the case with minecraft 1.16?
1.15.2 is no longer supported, I will close this ticket. Please reopen if it is still an issue for you in 1.16
