### ISSUE TITLE
JourneyMap load causes Minecraft crash

### ISSUE THREAD

**Issue by UserUnk** [TeamJM/journeymap#246]
#### Describe the problem in repeatable steps:

1. Update Minecraft to current release version (1.16.1)
2. Update Forge to newest version (1.16.1-32.0.24)
3. Launch Forge installation with no additional mods - works fine
4. Add JourneyMap mod per instructions
5. Launch Forge installation again
   - process begins normally, shows "Loading world" screen through 100%
   - screen changes to "Saving world" and crashes out of application
   - returns the following error (see attached crash report for full information)

Description: Unexpected error
java.lang.NoSuchFieldError: field_71093_bK

[crash-2020-06-28_19.36.10-client.pdf](https://github.com/TeamJM/journeymap/files/4843288/crash-2020-06-28_19.36.10-client.pdf)

**Comment by UserUnk** [comment]
Closed why?  Issue is not a duplicate, and has no resolution that I can find...

**Comment by gdude2002** [comment]
You may notice from the version numbers of Forge and JM that you provided, but you're running a mod for 1.15.2 on Forge for 1.16.1 - that's not going to work, and we will not be supporting 1.16.1 until we see more stable builds.
