### ISSUE TITLE
dead link in readme

### ISSUE THREAD

**Issue by axcsds** [TeamJM/journeymap#248]
DEAD

**Comment by gdude2002** [comment]
All the README links are working as expected.

**Comment by axcsds** [comment]
in link goes to 400 ERROR

**Comment by axcsds** [comment]
url says bitbucket

**Comment by gdude2002** [comment]
Yeah, I see Bitbucket is having issues - it's not a dead link, they're just having problems.

**Comment by axcsds** [comment]
my cache is good expect bitbucket

**Comment by axcsds** [comment]
is problem is the SERVER?

**Comment by gdude2002** [comment]
It's irrelevant really since JourneyMap is currently closed-source anyway. There's nothing we can do to help you with the Bitbucket link.
