### ISSUE TITLE
Full-screen map not working

### ISSUE THREAD

**Issue by Geozuk** [TeamJM/journeymap#249]
#### JourneyMap Version:

1.12.2-5.7.1`

#### Forge Version:

 1.12.2-14.23.5.2854

#### Describe the problem in repeatable steps:

1.Everything works fine until I try to use the full map

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

[11:08:46] [Client thread/WARN] [FileHandler] Couldn't copy color palette html: java.lang.NullPointerException
[11:08:46] [Client thread/ERROR] [ColorPalette] Can't write colorpalette.html: java.lang.NullPointerException
[11:08:46] [Client thread/WARN] [ColorPalette] Existing color palette's mods no longer match current loadout.

![2020-07-10_11 33 24](https://user-images.githubusercontent.com/68118567/87171958-71068f80-c2a1-11ea-96da-8d2dca4c621e.png)
![2020-07-10_11 33 28](https://user-images.githubusercontent.com/68118567/87171969-7532ad00-c2a1-11ea-942e-7ddbe4547c14.png)
![2020-07-10_11 33 32](https://user-images.githubusercontent.com/68118567/87171972-75cb4380-c2a1-11ea-8bfa-1d781469f2a4.png)

**Comment by mysticdrew** [comment]
Looks like a mod conflict, those errors have nothing to do with this issue. If you are using optifine try disabling fast render

**Comment by Geozuk** [comment]
Yes, it is a problem with first aid mod (I solved it by disabling the overlay) thx

**Comment by BrainStone** [comment]
I'd recommend you reach out to that mod's dev.
