### ISSUE TITLE
[1.12.2] OptiFine_1.12.2_HD_U_C8 breaks fullscreen map.

### ISSUE THREAD

**Issue by seeker2921** [TeamJM/journeymap#25]
#### JourneyMap Version:

1.12.2-5.5.2

#### Forge Version:

1.12.2-14.23.1.2555

#### Describe the problem in repeatable steps:

1. Have forge, Journeymap, and OptiFine_1.12.2_HD_U_C8 installed on client in above versions (no other versions tested).
2. hit "J" to open map. You will see nothing. Just the background (in the themes color).
3. All other features work (even minimap). The only way to pull up options in from the waypoint manager.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
No error's given.

This problem goes away with OptiFine_1.12.2_HD_U_C7 installed. As I have not encountered any other mods or noticeable problems I am reporting here rather than with optifine.

**Comment by MauveCloud** [comment]
I am able to use JourneyMap fullscreen map with Optifine_1.12.2_HD_U_C8, although I am using JourneyMap 1.12.2-5.6.0b2 and Forge build 2604 (I also had it working with jm 1.12.2-5.5.2).  I notice in the changelog for Optifine C8 that it says "compatible with Forge #2587", so maybe trying to run it with Forge build 2555 is the real problem.

**Comment by seeker2921** [comment]
Update: 
As it turns out, my problem is not resolved by downgrading Optifine. It is similar to the server crash issue experienced by some people. After the first launch, it works fine. And subsequent launches this problem is present. To resolve, The journeymap folder must be deleted.

This is present on Windows 7 & 10, Ubuntu 17.10 and on 5 different computers (Two homebuilt and three HP AIO's) So I don't think it is driver or computer related.

Using the versions MauveCloud listed causes the server crash issue on a restart, so that is not an option.

What information can I provide to help?

**Comment by mysticdrew** [comment]
Optifine is not compatible with many mods.

**Comment by BloodCaster** [comment]
It's a Fast Render issue. Disable it and reload the game.
