### ISSUE TITLE
[1.15.2] Other players don't show on either map with animals unchecked

### ISSUE THREAD

**Issue by Snaitf** [TeamJM/journeymap#250]
#### JourneyMap Version:

1.15.2-5.7.0b3

#### Forge Version:

1.15.2-31.2.31

#### Describe the problem in repeatable steps:

1. Turn off *either* show animals, *or* show players and other players will not show on either the mini or full map.
2. Turn on *both* show players *and* show animals to get other players to show again.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

n/a

**Comment by mysticdrew** [comment]
Can you verify this is still the case with minecraft 1.16?
1.15.2 is no longer supported, I will close this ticket. Please reopen if it is still an issue for you in 1.16

**Comment by Scratchman** [comment]
Yes, this is still a thing, and until i saw this issue i didn't know why "show player" wasn't working.

journeymap-1.16.5-5.7.1

**Comment by mysticdrew** [comment]
Oops sorry, never stated it. I investigated and I had fixed it in the internal build. Beta for 5.7.2 contains this fix, it will be public soonish hopefully less than a week. 

Closing as Fixed

**Comment by mysticdrew** [comment]
Actually, reopening. i will close it when it is released.

**Comment by mysticdrew** [comment]
This is fixed in 5.7.2 beta now on curseforge.
