### ISSUE TITLE
[1.16] Can't send chat coordinates from full map

### ISSUE THREAD

**Issue by Snaitf** [TeamJM/journeymap#251]
#### JourneyMap Version:

1.15.2-5.7.0b3

#### Forge Version:

1.15.2-31.2.31

#### Describe the problem in repeatable steps:

1.  Open the full screen map
2.  Move mouse over coords you want to share in chat
3.  Press 'c' to open chat with mouse coords automatically pasted in
4.  Can't press enter to send the chat message.  We can type other characters, but not send the message (or use the backspace key, for some reason)

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

n/a

**Comment by mysticdrew** [comment]
Fixed in 5.7.1 beta 4 for MC 1.16.5 when available on curse.
