### ISSUE TITLE
[1.15.2] [Suggestion] Add an 'Enhanced Cave Lighting' cartography option

### ISSUE THREAD

**Issue by Snaitf** [TeamJM/journeymap#252]
#### JourneyMap Version:

1.15.2-5.7.0b3

#### Forge Version:

1.15.2-31.2.31

#### Describe the problem in repeatable steps:

Currently, in the cartography options, you can toggle on/off 'Cave Lighting'

With it disabled, you can see all surrounding caves, at full lighting.  Seeing everywhere you can go, the downside being you can't tell if you've been there before and lit it up properly.

With it enabled, you can see the surrounding caves with their actual lighting, the downside being if they're completely dark, they aren't visible on the map at all.

We'd love to see an option for a blend of those two, something like 'Enhanced Cave Lighting' that will allow you to see all caves, even if they are completely dark, but also be able to tell if you've been there and lit them up.  Perhaps just using actual cave lighting, but increased by a few levels, not to full light.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

n/a

**Comment by mysticdrew** [comment]
The only way to know if you have been in that exact cave is if the chunks have been mapped my journeymap, that is all based on your render settings how far it goes out. 

I could add a slider for cave brightness, but the best way to know if you have been in a cave is by using torches which journeymap will display the light of the torches.
