### ISSUE TITLE
[1.15.2] Waypoint coordinates incorrect when created by double-click in fullscreen map

### ISSUE THREAD

**Issue by BBXMax** [TeamJM/journeymap#254]
#### JourneyMap Version:

`1.15.2-5.7.0b3`

#### Forge Version:

`1.15.2-31.2.33`

#### Describe the problem in repeatable steps:

1. Press "J" to open the fullscreen map.
2. Double-click any point on the fullscreen map (e.g. house) to create a waypoint there.
3. The waypoint will be created way off from where it was double-clicked (e.g house) in both the x and z axis.
4. Drag the fullscreen map over slightly.
5. Double-click that same point again (e.g house).
6. The waypoint will be created in a different spot than the first time but still way off. 

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

[Render thread/WARN] [Constants] Message key not found: jm.debug.region_info_toggle

Throws this every time the fullscreen map is opened AND every time a waypoint is created as described in the above steps.

**Comment by mysticdrew** [comment]
[Render thread/WARN] [Constants] Message key not found: jm.debug.region_info_toggle
Is not an error, nor does it have anything to do with your issue. 
Please provide more detail. With what cords should be and what they are.

**Comment by mysticdrew** [comment]
Can you verify this is still the case with minecraft 1.16?
1.15.2 is no longer supported, I will close this ticket. Please reopen if it is still an issue for you in 1.16
