### ISSUE TITLE
[1.15.2] Deathpoints not saving when killed in horizontal motion

### ISSUE THREAD

**Issue by BBXMax** [TeamJM/journeymap#255]
#### JourneyMap Version:

`1.15.2-5.7.0b3`

#### Forge Version:

`1.15.2-31.2.33`

#### Describe the problem in repeatable steps:

1. Get into a situation where, when you die, you are still moving horizontally.  
2. In my case, I got killed by a punch-enchanted bow while in the air.
3. The deathpoint will not be saved.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

The log will say "Deathpoint created: true", but that's a lie, no deathpoint appears in my waypoints.

**Comment by mysticdrew** [comment]
Can you verify this is still the case with minecraft 1.16?
1.15.2 is no longer supported, I will close this ticket. Please reopen if it is still an issue for you in 1.16
