### ISSUE TITLE
[1.13-1.16] Mark mod as clientside only

### ISSUE THREAD

**Issue by phit** [TeamJM/journeymap#256]
#### JourneyMap Version:

any 1.13 to 1.16

#### Forge Version:

any

#### Describe the problem in repeatable steps:

1. install journeymap on a client
2. run a forge server without journeymap
3. look at server in serverlist of client
4. see red X next to server

Please mark the mod as client only via
https://mcforge.readthedocs.io/en/latest/concepts/sides/#writing-one-sided-mods
Thanks!

edit: just noticed JM isn't out for 1.16 but it will apply anyway once it's out ;)

**Comment by mysticdrew** [comment]
Journeymap is optional on both sides.
However, this is fixed in 1.16
