### ISSUE TITLE
Journeymap causes the game to load slowly before crashing

### ISSUE THREAD

**Issue by Hiderlink20** [TeamJM/journeymap#259]
Minecraft: 1.15.2
Journeymap: .15.2-5.7.0b2.jar
forge: 31.2.1
Terraforged: 0.0.14

1. As of early June 2020 (whatever versions were available then), Journeymap, forged & terraforged were all working fine with the version of minecraft I am currently using.  That changed when I made the mistake of updating both journeymap & terraforged.
2. Now, whenever I try to use Journeymap, the game crashes on startup.  Without journeymap, it works fine but I would prefer to use journeymap.
3. I tried getting previous versions of both the mods and altering the contents of the journeymap file in file explore but now whenever I use journeymap, the game takes a long time to load only to crash before finishing.
4. The only possible solution I can think of is trying to download an old version of forge.  Is there a better solution than this?

Crash reports:
[crash-2020-08-08_12.43.09-client.txt](https://github.com/TeamJM/journeymap/files/5079511/crash-2020-08-08_12.43.09-client.txt)
[crash-2020-08-08_12.18.51-client.txt](https://github.com/TeamJM/journeymap/files/5079512/crash-2020-08-08_12.18.51-client.txt)

Please let me know if there is any information I need to provide.  I attempted to follow the format of these issues to the best of my ability so I am sorry if it isn't done correctly.

**Comment by mysticdrew** [comment]
Update to beta3

**Comment by Hiderlink20** [comment]
I was using beta2 when it was working.  When I updated to beta3, that's when the problem started.  could it be an incompatibility issue?

**Comment by mysticdrew** [comment]
You listed beta2 as having the issue. I know for a fact beta2 has a memory leak because I fixed it in beta3

**Comment by mysticdrew** [comment]
also, nothing in the logs you posted have anything to do with journeymap

**Comment by Hiderlink20** [comment]
Ok then.   Ill try redownloading beta3.

**Comment by mysticdrew** [comment]
delete your journeymap_server.cfg file in ./minecraft/config too see if that helps. The crash has something to do with your configs.

**Comment by Hiderlink20** [comment]
I did that and goes someplace else, which I found helpful.  Now it shows me this.
[crash-2020-08-15_17.28.21-client.txt](https://github.com/TeamJM/journeymap/files/5079525/crash-2020-08-15_17.28.21-client.txt)

**Comment by mysticdrew** [comment]
There is nothing in any of the logs that indicate this is a journeymap related issue. Have you tried going back to an older version of terraforged?

What does this mean? 
`altering the contents of the journeymap file in file explore`
