### ISSUE TITLE
1.12.2 - The game crashed whilst updating screen events

### ISSUE THREAD

**Issue by wesker1213** [TeamJM/journeymap#26]
I will occasionally crash when trying to add a way point. The steps are reproducable in the pack I play.

Step 1 : Press J to open your journeymap
Step 2: Click new
Step 3: In the coordinates field click, the backspace up. The crash occurs.

Pack: Direwolf20 1.12.2
Forge Version: 14.23.1.2355
Journeymap version: 1.12.2-5.6.0b1

**Comment by Dunkh4n** [comment]
hi,
it the same issue as this one..
https://github.com/TeamJM/journeymap/issues/14
