### ISSUE TITLE
[1.12.2] [Suggestion] Command: Creation of Waypoints by Command

### ISSUE THREAD

**Issue by Xarmat-GitHub** [TeamJM/journeymap#260]
Hello all together, I have a feature suggestion for Journeymap to shear.

### Creation of Waypoints for Players / Servers by Command
**Features:**
- Command that adds way points to players

**Example**
/jm
playername: (required)
name:  (optional) (when not set, will take x / y cord as name)
dim:  (optional) (when not set, will take the DIM the player is in) (can have more values/DIM IDs [0,-1,1,7]
,x:  (required)
,y:  (required)
,z:  (required)
colorred; (optional) (hex useable?) (else random)
colorgreen: (optional) (hex useable?) (else random)
colorblue: (optional) (hex useable?) (else random)
enabeld: (optional) (default "true")
silent: (optional) (give chat message to the player) (default: "false")

/jm playername: @p, name:"Thaumcraft Evil Castle", dim: 0, x: -2500, y: 64, z: 3200, hex: ff1a00, enabeld: true, silent: false

**Opportunities**
- New players on a server will get basic waypoints for orientation
- Game Stages can unlock this
- Command Blocks can be used with this
- Structure Spawn can have a command block in it to give the player the right underground structure position

**Infos**
- I have read [https://journeymap.info/Waypoint_Sharing](https://journeymap.info/Waypoint_Sharing), this suggestion will generate on top of that

**Extra Idea**
- Command to delete a waypoint
- /jm @p, delete: "Thaumcraft Evil Castle", silent: true

**Last One**
- Tanks for a awesome mod guys ;)

_Stay in Contact_
Discord: #7574 Xarmat

**Comment by williamsmc** [comment]
Hey when I tried to join the server it didn't work even though I got on through the modpack.

**Comment by BrainStone** [comment]
> 
> 
> Hey when I tried to join the server it didn't work even though I got on through the modpack.

Why on earth are you commenting on this issue?

**Comment by mysticdrew** [comment]
I have added this command that will be available with 5.7.1 Beta 4 for minecraft 1.16.2-1.16.5 when it is posted on curseforge.
