### ISSUE TITLE
Follow Button Doesn't Follow Player

### ISSUE THREAD

**Issue by AgentCPU0** [TeamJM/journeymap#261]
JourneyMap Version
1.12.2-5.7.1

Minecraft Forge Version
14.23.5.2847

Steps To Duplicate
1. Open the fullscreen map
2. Click the follow button
3. Nothing happens

Relevant Error Logs
N/A

Additional Notes
I am well aware this will more than likely be marked as a duplicate report. That said, I'd like to ask why this issue still exists and any duplicate reports regarding this issue are being ignored. Shouldn't that mean this is a major issue in need of fixing?

**Comment by mysticdrew** [comment]
duplicate #36 

yes it is a duplicate report.

First off, this is likely a mod interaction issue as I was unable to replicate it when I initially investigated it. 
Second off, it is not a major issue nor has it been ignored. It affects a small number of users and no one as been able to tell me what mod is causing it so I could address it. 

Furthermore, Journeymap 1.12.2 is no longer in development. The following logic in later versions is different so it is unlikely to be an issue.
