### ISSUE TITLE
Feature Request - Toggle coordinates on fullmap

### ISSUE THREAD

**Issue by iLLiCiTgames** [TeamJM/journeymap#262]
Forge 1.12.2 - 14.23.5.2854

If it would be possible to toggle off your coordinates on the fullmap the ones above and below the map
or make them changeable to show region, time, biome ect

![Untitled](https://user-images.githubusercontent.com/14254633/93727148-a0bdf780-fb6e-11ea-8361-77eb59ad9ddd.jpg)

**Comment by BrainStone** [comment]
1.12.2 doesn't receive updates anymore.

**Comment by mysticdrew** [comment]
added in 5.7.2 beta 12 for mc 1.16.5
