### ISSUE TITLE
[1.7.10] Client crash by illegal char in creating journeymap path

### ISSUE THREAD

**Issue by AykaSova** [TeamJM/journeymap#263]
#### Instructions for Submitting an Issue
1. Ask for help on Discord (https://discord.gg/eP8gE69) #support if you're unsure this is a new issue.
2. Please search for existing issues before submitting a new one.
3. Please add the correct MC<version> label to your issue. Example: "[1.12.2] Waypoints are upside down"
4. Completely fill out the template below. Failure to do so is likely to get the issue closed immediately.
5. Prove you read these instructions by deleting this section before submitting. ;)
---
  
#### JourneyMap Version:

`journeymap-1.7.10-5.1.4p2-unlimited`

#### Forge Version:

`forge-1.7.10-10.13.4.1614-1.7.10`

#### Describe the problem in repeatable steps:

1. Normally loading client
2. Open multiserver list, entering remote server normally
3. After using any key referring to JourneyMap (open map, mini-map, options etc) — client immediately crashes

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

FROM CRASH-2020-09-22_12.46.49-CLIENT.TXT
Description: Unexpected error

java.nio.file.InvalidPathException: Illegal char <:> at index 55: D:\Games\AyCraft\new\journeymap\data\mp\192.162.246.240:25565\DIM0
	at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source) etc.

**Comment by gdude2002** [comment]
1.7.10 is unsupported. Please reproduce this in the latest version of JM.

**Comment by AykaSova** [comment]
It's great! But whole internet is full of screams about this bug. So i need cancel my project, letting down my customers, clean up whole server, install 1.12.2 server, ask customers to by and reinstall new client-side software... And than to read you message "Strange... wait for nexte release, please!"
Right?

**Comment by gdude2002** [comment]
It's completely unreasonable to expect developers to support a version of Minecraft that is six and a half years old. Please grow up.

**Comment by BrainStone** [comment]
> "Strange... wait for nexte release, please!"

No, as there won't be a next release for 1.7.10.  
Even 1.12.2 is no longer supported.

Now to prevent the bug from happening, try to specify a server address without ``:``. So consequently no port.  
You can use a SRV DNS record if you don't use the standard port.
