### ISSUE TITLE
Journey map bug when using multiple mods on a server.

### ISSUE THREAD

**Issue by ZexAuburn** [TeamJM/journeymap#265]
I am using MC version 1.15.2 with journey map version 1.0.0 and I found that using mods with Ice and fire caused issues. However when I brought it up with their devs and provided the crash log they found this.

"bug with journeymap,

    journeymap.client.ui.component.ScrollListPane.getSlot

report it to their devs."

They stated it was a bug with the journey map and that is what caused my Java stackoverflow error. Below is the crash logs you can take a look at yourself.

https://pastebin.com/xXeDGYdc

**Comment by BrainStone** [comment]
What JourneryMap version are you talking about? 1.0.0 most certainly doesn't work on 1.15.2, assuming you still somehow managed to find it.

**Comment by ZexAuburn** [comment]
journeymap-1.15.2-5.7.0b3.jar Sorry about that lol.

**Comment by mysticdrew** [comment]
Can you verify this is still the case with minecraft 1.16?
1.15.2 is no longer supported, I will close this ticket. Please reopen if it is still an issue for you in 1.16
