### ISSUE TITLE
[1.12.2] JourneyMap Bug

### ISSUE THREAD

**Issue by AnimalLover567** [TeamJM/journeymap#267]
#### Instructions for Submitting an Issue
1. Ask for help on Discord (https://discord.gg/eP8gE69) #support if you're unsure this is a new issue.
2. Please search for existing issues before submitting a new one.
3. Please add the correct MC<version> label to your issue. Example: "[1.12.2] Waypoints are upside down"
4. Completely fill out the template below. Failure to do so is likely to get the issue closed immediately.
5. Prove you read these instructions by deleting this section before submitting. ;)
---
  
#### JourneyMap Version:

`1.12.2-5.7.1

#### Forge Version:

forge-14.23.5.2854

#### Describe the problem in repeatable steps:

1. Load into world
2. Open JourneyMap
3. See all blue

I don't know if this is because I'm using a flat world or not, but when I open the full-screen map all I see is blue, no map nothing just blue, it's also happening in another pack I'm making. Can somebody figure it what's happening

**Comment by mysticdrew** [comment]
disable optifine's fast render
