### ISSUE TITLE
[1.12.2] Player names/dots not following players

### ISSUE THREAD

**Issue by syntience** [TeamJM/journeymap#271]
#### JourneyMap Version:

1.12.2-5.7.0

#### Forge Version:

1.12.2-14.23.5.2847

#### Describe the problem in repeatable steps:

1. use curseforge to download mc eternal
2. add the most recent 1.12.2 versions of mrcrayfish's furnature mod, extra bit manipulation, placeable items, dynamic lights and lost cities. 
3. make/join a server with this modpack
4. world type = lostcities_bop, generator settings = {"profile"\:"realistic"}

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

unsure

Made a server. Player names and icons don't move on the minimap or fullscreen map. Haven't changed any journeymap configuration, can't think of anything i did that could've caused this, not sure what other information/files to provide. What should I do?

edit: guess i'll post this. can't tell if anything in here relates to this bug. [https://pastebin.com/gDs54uqZ](https://pastebin.com/gDs54uqZ)

**Comment by mysticdrew** [comment]
Can you verify this is still the case with minecraft 1.16?
1.12.2 is no longer supported, I will close this ticket. Please reopen if it is still an issue for you in 1.16
