### ISSUE TITLE
[Suggestion] [1.16.x] Adding an option for a "Anitque Atlas" color filter onto the minimap and a UI theme to match it.

### ISSUE THREAD

**Issue by Corvus20** [TeamJM/journeymap#272]
I am looking forward to the 1.16.x port of this mod, although it may still be a ways off. This minimap mod is one of my favorites in terms of functionality, but I love the aesthetic of Antique Atlas too, and now that Antique Atlas has shifted to a fabric only development focus, It leaves forge users without a similar map mod.

I am proposing a "color filter" that will make the colors of the minimap resemble the "parchment and ink" style that Antique Atlas had, along with a UI theme that would suit it. If this feature was implemented, it would fit a lot of the more "medieval" modpacks out there, and will fill the gap that Antique Atlas left in many people.

I am by no means a mod developer, I have no idea how difficult this would be to implement, and I don't know where the mod is currently in a development standpoint, I just figured I should send this idea your way, even if it in fact is too difficult to implement.

Loving the mod, keep it up!

**Comment by mysticdrew** [comment]
While this sounds cool, we have documentation on how to create custom themes in our wiki. If you create the theme, I will add it to journeymap. 

We will have to discuss adding another map mode. Though, it is unlikely at this time.

**Comment by techbrew-mc** [comment]
The UI can be themed as you describe.  Currently the map colors themselves are determined by the resource pack.  A sepia overlay could be added, I suppose, but that's a really niche feature request.  Keeping this open for now as a low-priority maybe, and making a note that the way to support it would be to add a UI theme option to add a color filter atop the map..

**Comment by mysticdrew** [comment]
No theme yet, but we have a new Filters option. 
![image](https://github.com/TeamJM/journeymap/assets/5459941/e9cd89df-2ea7-4963-969c-aca1b4d2c89c)

This will be added in 6.0.
