### ISSUE TITLE
y=10 and below loads black chunks.

### ISSUE THREAD

**Issue by ItsRiftzy** [TeamJM/journeymap#273]
#### JourneyMap Version: 1.12.2-5.7.1`

`Example: 1.12.1-5.5.0`

#### Forge Version: 1.12.2-14.23.5.2854

`Example: 1.12.1-14.22.1.2478`

#### Describe the problem in repeatable steps:

1. I'm playing on Terra 1:1 mod and whenever i enter a chunk that is around y=10 or below it only loads black chunks.

**Comment by mysticdrew** [comment]
I Noticed this in 1.16.5 messing around in a default flat world when I used tnt to blow up a village! The bedrock showed up as void.

**Comment by mysticdrew** [comment]
This is fixed in Journeymap 5.7.1 beta 4, will be on curse in a day or two from the time of posting.
But it will be broken again in 1.17 due to world height and depth changes.
