### ISSUE TITLE
[1.16.5] weird visual issue

### ISSUE THREAD

**Issue by Bass2style** [TeamJM/journeymap#276]
this is, for me, a conflict with another mod, but it's really weird.
i have tryed this with some basic mods (ToP, JEI, MouseTweaks, ...), and its not happening, so, its clearly a conflict with another mod.
 
#### JourneyMap Version:

`1.16.5-5.7.1b2`

#### Forge Version:

`1.16.5-36.0.42`

#### Describe the problem in repeatable steps:

1. run a map,
2. try to set a quick waypoint by pressing B or via JMap's menu
3. waypoint window closes automaticly, and some weird things happens :
 - your hands disapair (not F5 checked if it's steve, or only the hands)
 - mining animations and dropped items aren't showing (but mined items appairs in the inventory)
 - placing a bed make it invisible. (pressing B near it creates also that glitch.)
 
to "resolve" this, it's needed to reload the whole pack, only quit/joining world isn't working

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
installed mods : https://gist.github.com/Bass2style/7710c4f5f652d8089a6a4acb97d54b7b
journeymap.log : https://gist.github.com/Bass2style/a7ad15df153a5a74fd4b336c919d6691
vidéo record : https://youtu.be/5L95vpLqeqM

**Comment by mysticdrew** [comment]
Known issue.
This already fixed and beta 3 will the fix, hopefully it will be public in a couple hours.
Thanks.

**Comment by Bass2style** [comment]
okay, thanks for your quick reaction.

**Comment by BrainStone** [comment]
I had experienced that as well and was hella confused xD

Since I installed a few experimental mods I wasn't sure which one it was. Glad to know which it is ^^

And thanks for fixing it.

**Comment by Sickjuicy** [comment]
I play on the 1.16.3 with the jouneymap version 5-5.7.1b2 but also have the problem on the beta 3.

When I try to open the gui for waypoints or the settings, the gui is not displayed or disappears quickly when I press B.
[journeymap.log](https://github.com/TeamJM/journeymap/files/6022652/journeymap.log)
