### ISSUE TITLE
Is it possible to add "data" folder on server side to keep map by user UUID ?

### ISSUE THREAD

**Issue by AntoineMazoyer** [TeamJM/journeymap#279]
#### JourneyMap Version:

1.12.2

#### Forge Version:

forge-1.12.2-14.23.5.2854

#### Describe the problem in repeatable steps:

1. My map has been deleted because i removed accidently my data folder in client side.
2. So I've got a new question : it is possible to save this data in the server side ? (get map data by user UUID and save it on the server to prevent the loss of data)
3. If it is possible. How ?

Thank you in advance for your help.

![Local save](https://user-images.githubusercontent.com/35558783/109489365-0c45b280-7a87-11eb-8293-6a49944e5ddd.PNG)
![Server save](https://user-images.githubusercontent.com/35558783/109489368-0cde4900-7a87-11eb-93d6-4c4c8a1bb0b7.PNG)

**Comment by BrainStone** [comment]
1.12.2 won't receive any updates anymore.

Also it's your resposibility to keep the data save. It's local data that doesn't belong on the server. Just imagine how quickly you could get the server in trouble by sending TBs of data that's supposed map data. Essentially impossible for the server to verify.
