### ISSUE TITLE
Feature Request: Grouped Waypoints

### ISSUE THREAD

**Issue by bjendrick** [TeamJM/journeymap#28]
#### JourneyMap Version:

`Example: 1.12.2-5.5.2`

#### Forge Version:

`Example: 1.12.2-14.23.1.2555`

#### Feature Request

1. Our server heavily uses maps for our over 25K x 25K world.
2. By combining Dynmap for live mapping, and JourneyMap for client mapping, we have a lot of power over navigation in our large world.
3. Based on that, we would love the ability to group waypoints inside JM to make it easier to hide / show certain sets of waypoints.  Whether they be server created & shared, or for each individual user's grouping of bases, mob farms, etc.

Keep up the great work, and wanted this to have some visibility if it hasn't been addressed already.  Thank you!

**Comment by TomSputz** [comment]
I'm a tad worried about that removal? I would love this feature - It is the one thing stopping me from using this mod. Are there any plans to put in a waypoint grouping system?

**Comment by mysticdrew** [comment]
This will be implemented in the future, the waypoint system is being redesigned post 1.14

**Comment by ejm554** [comment]
Hello. This feature request was closed four years ago, but I cannot find this feature in a recent version of JM (5.10.0). Could someone tell me how to access it, or LMK if it wasn't actually implemented?

**Comment by mysticdrew** [comment]
It's been added in 6.0.0 for 1.21+

**Comment by ejm554** [comment]
Ah, cool. Might it eventually be added to older versions also?

**Comment by mysticdrew** [comment]
Nope, sorry
