### ISSUE TITLE
Narrator is toggled if you open the waypoint manager

### ISSUE THREAD

**Issue by Bimi124** [TeamJM/journeymap#282]
#### JourneyMap Version:

`1.16.5-5.7.1`

#### Forge Version:

`1.64.5-36.1.0`

#### Describe the problem:

The keyboard shortcuts for the Waypoint Manager and the narrator are the same (`Ctrl + B`). This means both are toggled.

**Comment by Bimi124** [comment]
Suggestion: Use `Alt + B` instead

**Comment by mysticdrew** [comment]
you can set your own hotkeys.

**Comment by DeleteMetaInf** [comment]
You can use the mod [RebindNarrator](https://www.curseforge.com/minecraft/mc-mods/rebindnarrator) ([Fabric version](https://www.curseforge.com/minecraft/mc-mods/rebind-narrator), [Fabric version for 1.19.X](https://www.curseforge.com/minecraft/mc-mods/rebindnarrator-fabric)) to change the key bind for the narrator toggle.
