### ISSUE TITLE
[1.16.5] Minimap opacity could use some improvement

### ISSUE THREAD

**Issue by steven-archer** [TeamJM/journeymap#283]
#### JourneyMap Version:

1.16.5 - 5.7.1

#### Forge Version:

1.16.5 - 36.1.0

#### Describe the problem in repeatable steps:

This is more of a suggestion than an 'issue' - though it could be considered an issue since the behavior shown makes the feature a bit awkward to use.

1. Slide the "Map Opacity" slider.
![image](https://user-images.githubusercontent.com/23382181/113172675-a3349480-9216-11eb-8dc1-04a2d2d36ba4.png)

2. Map draws with solid background outside of mapped areas, making opacity kinda pointless in this use-case.
![image](https://user-images.githubusercontent.com/23382181/113172853-d5de8d00-9216-11eb-8016-7f72b51a4729.png)

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

Not an error

**Comment by mysticdrew** [comment]
Interesting. I will look into it.

**Comment by BrainStone** [comment]
I'd argue there should be a setting for it, as I can see there being a use case for either behavior.

**Comment by mysticdrew** [comment]
> I'd argue there should be a setting for it, as I can see there being a use case for either behavior.

I agree, if I were to add something it would be a separate "Background Opacity" slider.

**Comment by mysticdrew** [comment]
![mUVFXiNBUN](https://user-images.githubusercontent.com/5459941/124177709-3380b080-da76-11eb-844d-171942b56370.gif)
Will be in 1.16.5_5.7.2beta17 when published to curseforge
