### ISSUE TITLE
[Feature Request] (1.12.2) PLEASE let us zoom out farther. Zooming out shouldn't be limited.

### ISSUE THREAD

**Issue by Orvngex** [TeamJM/journeymap#284]
#### JourneyMap Version:

1.12.2-5.7.1

#### Forge Version:

1.12.2-forge1.12.2-14.23.5.2847

#### Describe the problem in repeatable steps:

1. Open full screen map.
2. Try to zoom out a lot.
3. You can't zoom out very far.

**Comment by gdude2002** [comment]
Use the webmap. Zooming out further is something we're looking into for the ingame map, but it's not trivial to implement. This issue is not a new report.
