### ISSUE TITLE
1.16.5 Journeymap waypoint beacon does not match physical coordinates of waypoint itself 

### ISSUE THREAD

**Issue by ClaudiusMinimus** [TeamJM/journeymap#285]
#### JourneyMap Version:

1.16.5-5.7.1

#### Forge Version:

1.16.5: 36.1.0

#### Describe the problem in repeatable steps:
I had a player of my modpack [Create on a Potato PC](https://www.curseforge.com/minecraft/modpacks/create-on-a-potato) report the following 
> When attempting to navigate to a waypoint the beacon is 100-300 meters off usually to the Southwest. and the beacon itself moves closer to you as you walk towards it. (I the speed the beacon moves is the same as your walk speed, so you meet the beacon at the at the halfway point if you started at the waypoint coordinates.) (see https://github.com/ClaudiusMinimus/Create_Potato/issues/4)

1. Place a Waypoint.
2. Walk away from the Waypoint placement point (20+ meters).
3. Turn back towards the Waypoint and walk towards it.
4. The Waypoint will be shown in an incorrect location as shown in the Minimap of the screenshot. The Waypoint was created at -145, 175. However, the Waypoint is shown to be at -73, 89.
![2021-04-06_10 41 51](https://user-images.githubusercontent.com/17887664/113748993-5b09ec00-96c6-11eb-9b46-7825634be5f1.png)

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
[journeymap.log](https://github.com/TeamJM/journeymap/files/6266353/journeymap.log)

**Comment by mysticdrew** [comment]
I need a better log. 
The Journeymap.log resets when you restart minecraft. This log, the user joined the game and sent the log. As you can see the last line is "mapping started". I need more please. Have the user explore the world a bit. 

Also, is this issue only replicated by the one user or have you been able to replicate it also?

**Comment by ClaudiusMinimus** [comment]
The example I sent was from a test SP world and I was able to replicate this issue, but only in my modpack. I tried a fresh install of 1.16.5 with only JourneyMap loaded and it worked fine. I will ask my player to send me his log file and I will forward post it here

**Comment by mysticdrew** [comment]
https://github.com/legobmw99/Allomancy/issues/52 fixes this issue, wait for the 4.3.0 release
