### ISSUE TITLE
[Feature Request] Automatically hide waypoints of the dimensions the player is not in.

### ISSUE THREAD

**Issue by CapitanCrk** [TeamJM/journeymap#286]
It would be a nice quality of life feature to have a label in dimensions called Automatically, for example.

This label would only show the waypoints of the dimension you are currently playing, so you don't have to see the Nether/End/Other waypoints that only occupy space on the screen, and can get kind of annoying when you have a lot of WP.

**Comment by mysticdrew** [comment]
Adding Implementation Details for my notes. 

- Add checkbox next to dimension button in the wp manager to enable "Open in Current Dimension". default: unchecked
- When enabled dimension manager will always open in your current dimension. 
- Manually Paging through the dimensions in the waypoint manager will not be affected.

**Comment by mysticdrew** [comment]
This has been added in 1.16.5_5.7.2beta14, will be available on curseforge shortly. 
The checkbox to enable/disable is in the Waypoint options, not on the waypoint manager screen.
