### ISSUE TITLE
Waypoints in modded dimensions cannot be teleported to

### ISSUE THREAD

**Issue by centhusiastx2** [TeamJM/journeymap#287]
#### JourneyMap Version:

journeymap-1.16.5-5.7.1

#### Forge Version:

forge-36.1.2 (1.16.5)

#### Describe the problem in repeatable steps:

1. Waypoints in modded dimensions cannot be teleported to
2. Waypoints work fine in other vanilla dimensions
3. They are still visible

https://streamable.com/d6xh4p

[journeymap.log](https://github.com/TeamJM/journeymap/files/6315599/journeymap.log)

**Comment by mysticdrew** [comment]
fixed in 5.7.2, it is on curse.
