### ISSUE TITLE
[1.16.5] Kelp and Seagrass does not honor the "Show Plant" option in Cartography

### ISSUE THREAD

**Issue by axaka** [TeamJM/journeymap#288]
#### JourneyMap Version:
5.7.1

JourneyMap API: v1.16.5-1.6-SNAPSHOT. Built 2021-03-01-09:22:10.

#### Forge Version:
36.1.0

#### Describe the problem in repeatable steps:

1. Kelp and Seagrass are still mapped when plants are disabled in the cartography settings.
2. Kelp shows as bright green pixels if it is on the top layer of the water.

**Comment by mysticdrew** [comment]
Seagrass is getting a fix, but kelp is not. 
Kelp grows to the surface, if we ignore kelp by disabling plants you see dirt/sand blocks instead of green kelp blocks. So it just changes it from green to brown/light brown. 

This will be in 5.7.2 beta 12 on curseforge sometime today.
