### ISSUE TITLE
Feature request - automatically adjust chunk mapping radius

### ISSUE THREAD

**Issue by someretical** [TeamJM/journeymap#289]
Currently you have to adjust the slider in the cartography options menu to set the chunk radius you want to map. This means that you have to increase the slider value if you increase your render distance (when you decrease your render distance, journeymap automatically decreases the chunk mapping radius). 

It would be nice to have an option at the right end of the slider that simply maps whatever chunks you have loaded around yourself  instead of setting a certain radius. Or the chunk mapping radius could be automatically increased if the render distance is increased.

**Comment by mysticdrew** [comment]
This is added in 5.7.2 beta 12 for mc 1.16.5. 
Setting journeymap's render distance (cave or surface) to 0 will then default to using the minecraft's game render distance.
