### ISSUE TITLE
Minimap not working with LabyMod

### ISSUE THREAD

**Issue by ExagonoIZI** [TeamJM/journeymap#290]
#### JourneyMap Version:
1.12.1-5.5.5`
#### Forge Version:
1.12.2-14.23.5.2855

When i join a server or singleplayer, the minimap makes my screen become black with white in the borders.
If i press CTRL + J (Button for disable minimap), the black screen dissapear and works fine, without the minimap.
I disabled all my mods, and tested just with journey and the labymod, so i found the problem. I was not using texture.

![2021-04-17_23 20 09](https://user-images.githubusercontent.com/82740606/115132107-81d3f680-9fd3-11eb-8b57-b0376676ca44.png)

![2021-04-17_23 21 32](https://user-images.githubusercontent.com/82740606/115132124-adef7780-9fd3-11eb-8cdf-97a9569f2d43.png)

**Comment by mysticdrew** [comment]
Use journeymap 5.7.1, I had fixed their breaking it.
