### ISSUE TITLE
Journey-Map Max. Chunk Capacity?

### ISSUE THREAD

**Issue by Aroshley** [TeamJM/journeymap#292]
#### JourneyMap Version: 

`JourneyMap 1.16.5-5.7.1 for Minecraft 1.16.5`

#### Forge Version:

`1.16.4-forge-35.1.36`

#### Describe the problem in repeatable steps:

1. I have the giantic map: 'Le Monde' from 'Planet Minecraft'
2. This map has 12000X16000 Blocks, so it's quite big!
3. I flew up and down because the auto-mapping don't work, but that's not my problem.
4. After finishing the half of the map to my Journey map (so I flew up and down) minecraft has stopped working with chunks...
5. 'waiting for chunk'
6. No possibility to tap something in chat
7. No possibitlity so save my game
8. Np possibility to end my game (Just with Task Manager)
9. At all, my map has round about 130000 Chunks...
10. I would guess, that Journey-map has a max. amount for chunks...
11. Without this mod, there is no problem and all the issues are away...
12. I use followings mods, if you're interested:

Architects-Palette-1.16.3-1.0.0
AutoRegLib-1.6-47
byg-1.1.6
CalemiUtils-1.16.4-1.0.2
Chimes-1.16.4-0.9.4
citadel-1.5.3
comforts-forge-1.16.4-4.0.1.0
ender-chested-1.16.4-1.0.2
evolved_RPG_1.16.2_v0.1.0
iceandfire-2.1.5-1.16.4
ironchest-1.16.4-11.2.10
jei-1.16.4-7.6.1.65
Journey-Map-1.16.5-5.7.1
MoreFlowerBushes-1.0
morevanillaarmor-1.16.2-1.2
morevanillalib-1.16.2-1.2.14
morevanillatools-1.16.3-2.1.5
NexXpOre_MC_1.16.4_Vers.1.0
OptiFine_1.16.5_HD_U_G7
QuarkOddities-1.16.3
Quark-r2.4-294
StorageDrawers-1.16.3-8.2.1
supplementaries-0.9.19
u_team_core-1.16.4-3.1.17.191
useful_railroads-1.16.4-1.4.6.34
Waystones_1.16.3-7.3.1
worldedit-mod-7.2.3

Ps: (sry for my English, I'm from Germany, but I hope, that I didn't make a mistake ;)

**Comment by mysticdrew** [comment]
do you mean 'waiting for chunk'?

**Comment by mysticdrew** [comment]
To be clear this has nothing to do with a chunk capacity, as journeymap is not limited by it. 
I see no logs provided either, so not sure how much help we can provide.

**Comment by Aroshley** [comment]
For no reason, the problem is right now away...
But thanks, that you aswered so quickly, I'm appreciating it.
And yes i meant waiting for chunk.

**Comment by mysticdrew** [comment]
What says waiting for chunks? Where do you see that?

**Comment by Aroshley** [comment]
I saw it when I press F3 at the left. There you can see: biom: forest.
And some other informations.
When a chunk don't exist/load, you'll see instead of biom:forest, 'waiting for chunk'

**Comment by mysticdrew** [comment]
It sounds like it was not a journeymap issue at all, but a minecraft chunk loading issue. Which can happen when generating chunks really fast.

**Comment by Aroshley** [comment]
Okay, thanks for the help, have a nice day!
