### ISSUE TITLE
Talk it over

### ISSUE THREAD

**Issue by chimu99** [TeamJM/journeymap#294]
Hello, my name is Chi Wu, can I forward your mod to Minecraft China, in China Minecraft belongs to netease, so there are not so many mods, we players especially want to play this mod.

**Comment by BrainStone** [comment]
Please don't close your issue, just to create essentially the same one.

The question label is just for organization. It has nothing to do with your actual question. It's not denying, nor approving it.

**Comment by chimu99** [comment]
How does it get approved

**Comment by chimu99** [comment]
When is it approved.
We really need this mod

**Comment by BrainStone** [comment]
Don't get your hopes up. They check these issues here around once a week.  
And if I remember correctly they don't approve posts in Chinese forums.

**Comment by chimu99** [comment]
Not Chinese forum, it is Chinese edition, minecraft China edition belongs to netease

**Comment by mysticdrew** [comment]
We talked it over, and due to legal concerns. It will be a no for now.
