### ISSUE TITLE
[1.16.5] [Feature Request] Surface Nether Mapping

### ISSUE THREAD

**Issue by joshthebossxl** [TeamJM/journeymap#295]
JourneyMap Version:

journeymap-1.16.5-5.7.1.jar

Forge Version:

1.16.5-forge-36.0.43.jar

Other Mods:

torohealth-1.16.4-forge-4.jar
OptiFine_1.16.5_HD_U_G7.jar

Describe the problem in repeatable steps:
1. Placing Blocks on the nether surface above Y128 for example a strip of quartz
2. JourneyMap (World Map option) renders these blocks on the nether surface as black or grey
3. JourneyMap (Mini Map option) Renders these blocks on the nether surface as black and grey until a height of Y146 where it renders all of the nethers in full colour beneath 

My Feature request is to have an option where it can render the top of the nether with all its blocks in the same colour that the block is displayed, rather than white and grey
[journeymap.log](https://github.com/TeamJM/journeymap/files/6447705/journeymap.log)

**Comment by mysticdrew** [comment]
This is complete for the next major release.

**Comment by joshthebossxl** [comment]
thanks for your patience it's been like 2 years xD, but good things come to those who wait

**Comment by mysticdrew** [comment]
Cleaning up the issue tracker
Closing as this is completed for JourneyMap v6 when it is released.
