### ISSUE TITLE
[1.16.5] OpenGL console error spam

### ISSUE THREAD

**Issue by Peca21** [TeamJM/journeymap#296]
#### JourneyMap Version:
journeymap-1.16.5-5.7.1

#### Forge Version:
1.16.5-36.1.18

#### Describe the problem in repeatable steps:
1. Open chat
2. Press alt-tab to switch to another window
3. Console spam

Also
1. Open fullscreen map
2. Press alt-tab to switch to another window
3. Other console spam

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
Just a ton of these: [23:17:50] [Render thread/WARN] [TileDrawStep] GL Error in TileDrawStep: 1281

Also alt-tabbing in chat spams this:
23:29:25.244
net.minecraft.client.renderer.GlDebugTextUtils
Render thread
OpenGL debug message, id=1281, source=API, type=ERROR, severity=HIGH, message=GL_INVALID_VALUE error generated. View frustum must not have a zero values of: (right-left), (top-bottom), or (zFar-zNear).
23:29:25.245
journeymap
Render thread
GL Error in TileDrawStep: 1281

Alt-tabbing in fullscreen map spams the same thing BUT WITHOUT:
journeymap Render thread GL Error in TileDrawStep: 1281
It only spams the first message

Video: https://streamable.com/lu6o3a

**Comment by mysticdrew** [comment]
as per discord, fixed in 5.7.2, beta should be out few days to a week.
