### ISSUE TITLE
[1.16.5] Request to add all ground decor blocks from Project: Vibrant Journeys to the exceptions list.

### ISSUE THREAD

**Issue by Corvus20** [TeamJM/journeymap#299]
#### JourneyMap Version:

JourneryMap-1.16.5-5.7.1

#### Forge Version:

1.16.5 36.1.23

#### Describe the problem in repeatable steps:

1. Install the mod "Project: Vibrant Journeys"
2. Create a new world
3. Note that all of the ground decor blocks (the only blocks the mod adds) render on the minimap as specks all over the landscape, resulting in a map like this:
![2021-05-24_14 15 04](https://user-images.githubusercontent.com/75586106/119390968-c2dabd00-bc9b-11eb-9705-75372f9867fe.png)

All ground decor blocks do this, but are different colors. The ones you see in the example are the pebbles rendering on the map. 

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

No relevant errors, as this is more of a visual tweak.

Additional Screenshots:

The Sandstone pebbles and Sea Oats on a beach on the minimap.
![2021-05-24_14 18 28](https://user-images.githubusercontent.com/75586106/119391247-1fd67300-bc9c-11eb-8555-e07b8ef09705.png)

A fullscreen map view of the initial screenshot area, all of those small grey dots, and a few of the slightly darker green ones, are pebbles, twigs, and leaf piles.
![2021-05-24_14 16 01](https://user-images.githubusercontent.com/75586106/119391560-7c399280-bc9c-11eb-8ac9-479598268cd3.png)

Disabling all the blocks currently included by the mod from rendering on the map would remove this eyesore without having to remove Project: Vibrant Journeys.

**Comment by mysticdrew** [comment]
This is added in 5.7.2beta12. Should be on curseforge sometime today
