### ISSUE TITLE
[1.10.2/1.12.2] UI icons on browser map 404

### ISSUE THREAD

**Issue by dewiniaid** [TeamJM/journeymap#3]
#### JourneyMap Version:

`5.5.1 (MC 1.10.2) / 5.5.2 (MC 1.12.2)`

#### Forge Version:

`14.18.3.2511 / 14.23.0.25.28`

#### Describe the problem in repeatable steps:

1. Enable the webmap using the default port of 8080.
2. Visit http://localhost:8080/
3. Observe 404 errors on everything under `/theme/icon/` (e.g. http://localhost:8080/theme/icon/day.png) -- example: https://i.imgur.com/p2FJOVz.png

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

There is no journeymap folder under `%APPDATA%/.minecraft`

#### Other comments

Haven't tested with mobs/etc, but other images (i.e. the icons in the dropdown menu with links to websites and such) appear fine.

Optifine, Foamfix and Equanamity (resource pack) were installed, but the issue was reproduced with all three disabled.

Some armchair debugging suggests that it may simply be a case of missing files under `assets/journeymap/ui` in the .jar file, as there is no theme directory there at all.

**Comment by techbrew-mc** [comment]
Fixed in 5.6.0b1
