### ISSUE TITLE
[1.16.5] When the mouse is not pointing at waypoints, waypoints can be obscured by blocks

### ISSUE THREAD

**Issue by LTCatt** [TeamJM/journeymap#300]
#### JourneyMap Version:

1.16.5-5.7.1

#### Forge Version:

1.16.5-36.1.0

#### Describe the problem in repeatable steps:

1. Create a waypoint
2. Put a block between the waypoint and you

![image](https://user-images.githubusercontent.com/40348278/120136228-73007680-c204-11eb-83bd-12a3b1b1c372.png)

**Comment by mysticdrew** [comment]
are you using texture packs?

**Comment by LTCatt** [comment]
I didn't use texture packs to do a lot of texture or model modification.
My modpack's texture pack only changed textures for certain minerals, and a few language files.
Textures for blocks in my screenshot are all vanilla...

**Comment by mysticdrew** [comment]
Can you try 5.7.2 Beta 2 on curseforge and see if that resolves the issue?
What graphic settings are you using Fast, Fancy, Fabulous?

**Comment by LTCatt** [comment]
It seems doesn't work :(
I tried all the graphics qualities, or removed OptiFine, but nothing worked.
This is the modpack I used:
https://github.com/Hex-Dragon/ExploreOrigins/releases/download/a1.2.0/Client.zip

**Comment by mysticdrew** [comment]
First before we move forward, you need to remove journeymap from your repo. Journeymap and many of the other mods you have there specifically state in their license that rehosting is not permitted. 
Please create and use a curseforge pack, ATLauncher, or tekkit with solder.io for curse downloads.

**Comment by LTCatt** [comment]
Thanks for reminding me. I know the restriction. This modpack is still in the works and has not been released to the public. We'll switch to CurseForge format when it's finished and released to the public... It's a little more convenient to put the file directly while developing.

**Comment by mysticdrew** [comment]
is this an issue for you with only journeymap and no other mods?

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/120673021-665e7580-c4c5-11eb-8b87-3d5f4f7762bf.png)

Yes...

**Comment by mysticdrew** [comment]
hmm, I am unable to replicate that issue. I did find another issue though, a couple other issues in-fact.
Does it change if you get closer or back up further to the beacon?

**Comment by LTCatt** [comment]
Oh, I think I found the reason. 
I restored the Settings I had changed one by one, and found this bug will occur after turning off the "Stationary Beam" option.
![image](https://user-images.githubusercontent.com/40348278/120678792-11256280-c4cb-11eb-95c7-bd0abf5170e2.png)

**Comment by LTCatt** [comment]
And if you turn off "Auto-Hide Label", this dot will not be occluded, but the label text will be occluded.
![image](https://user-images.githubusercontent.com/40348278/120679625-f6072280-c4cb-11eb-9941-bf70d7f1bd24.png)

**Comment by mysticdrew** [comment]
Interesting, thanks. I will look into it and see if I can find a solution.

**Comment by mysticdrew** [comment]
I found the issue and fixed it. 

Will close when 5.7.2 is released or beta 3 is published

**Comment by mysticdrew** [comment]
Beta 3
https://www.curseforge.com/minecraft/mc-mods/journeymap/files/3336841
