### ISSUE TITLE
singleplayer to multiplayer world no players showing for host.

### ISSUE THREAD

**Issue by CashCow4** [TeamJM/journeymap#301]
[1.16.5] Journey map version: 1.16.5-5.7.1

Whenever I make a world in singleplayer and upload it to my server I can't see other people on my journey map, however other people can see everyone just fine. If there's an easy solution like deleting my player data that would be cool. Just thought this might want to be addressed.

**Comment by mysticdrew** [comment]
Please head to our discord so I can find out more about this issue and help fix it. 
https://discord.gg/eP8gE69

**Comment by mysticdrew** [comment]
this was resolved by cleaning the configs.
