### ISSUE TITLE
[1.16.5] When the mouse is pointing at a waypoint, waypoint's label can be obscured by blocks

### ISSUE THREAD

**Issue by LTCatt** [TeamJM/journeymap#302]
#### JourneyMap Version:

1.16.5-5.7.2 Beta 3

#### Forge Version:

1.16.5-36.1.0

In 1.16.5-5.7.2 Beta 3, this dot will not be occluded, but the label text still be occluded.
![image](https://user-images.githubusercontent.com/40348278/120679625-f6072280-c4cb-11eb-9941-bf70d7f1bd24.png)

_Originally posted by @LTCatt in https://github.com/TeamJM/journeymap/issues/300#issuecomment-854007777_

**Comment by mysticdrew** [comment]
can you come into our discord server please?
https://discord.gg/eP8gE69

**Comment by mysticdrew** [comment]
Fixed in beta 4 now on curse.
