### ISSUE TITLE
[1.16.5] The waypoint created by death is OFF by default and cannot be turned ON

### ISSUE THREAD

**Issue by LTCatt** [TeamJM/journeymap#303]
#### JourneyMap Version:

1.16.5-5.7.2 Beta 3

#### Forge Version:

1.16.5-36.1.0

#### Describe the problem in repeatable steps:

1. Suicide
2. See waypoints' list

![image](https://user-images.githubusercontent.com/40348278/120839913-23bb9c80-c59c-11eb-8070-a52c2b67e573.png)

This issue did not appear in 5.7.1, but appeared after I upgrade.
If you click the "ON" button, nothing happens.

**Comment by mysticdrew** [comment]
Fixed in beta 4 now on curse.
