### ISSUE TITLE
[1.16.5] Opening and closing the fullscreen map sometimes makes the PolygonOverlay created with the API disappear

### ISSUE THREAD

**Issue by alejandrocoria** [TeamJM/journeymap#305]
#### JourneyMap Version:

Recently detected in 1.16.5-5.7.2 betas, but I've been detecting it since 1.12.

#### Forge Version:

1.16.5-36.1.16

#### Describe the problem in repeatable steps:

1. Use the API to create a PolygonOverlay.
2. Open and close the fullscreen map.
3. The polygon disappears. Moving on the fullscreen map makes it come back, sometimes.

**Comment by mysticdrew** [comment]
Fixed in 5.7.2 beta 11, will be available on curseforge shortly.
