### ISSUE TITLE
[1.16.5] Realms Server Name Error

### ISSUE THREAD

**Issue by XiaoPangxie732** [TeamJM/journeymap#308]
#### JourneyMap Version:

`1.16.5-5.7.2beta9`

#### Forge Version:

`1.16.5-36.1.31`

#### Describe the problem in repeatable steps:

1. Join a multiplayer server
2. Then the game will log `[Render thread/ERROR] [WorldData] Unable to get Realms server name: net.minecraftforge.fml.common.ObfuscationReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: callbackScreen` all the time

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
[journeymap.zip](https://github.com/TeamJM/journeymap/files/6646402/journeymap.zip)

**Comment by mysticdrew** [comment]
Are you able to invite me to your realms server so i can fix this? 
If so please join our discord and ping me. https://discord.gg/eP8gE69

**Comment by XiaoPangxie732** [comment]
The error is logged all the time when I join a multiplayer server after a while, not Realms. And currently, you cannot join Realms in version 1.16.5.

**Comment by ZekerZhayard** [comment]
[`ObfuscationReflectionHelper.getPrivateValue`](https://github.com/MinecraftForge/MinecraftForge/blob/33499db93f3bf3b3523a6dd3c7ae66b5022b34ec/src/main/java/net/minecraftforge/fml/common/ObfuscationReflectionHelper.java#L75) requires srg name, so it should be `field_147307_j` instead of `callbackScreen` and this will automatically remap to mcp name in development environment

**Comment by mysticdrew** [comment]
> [`ObfuscationReflectionHelper.getPrivateValue`](https://github.com/MinecraftForge/MinecraftForge/blob/33499db93f3bf3b3523a6dd3c7ae66b5022b34ec/src/main/java/net/minecraftforge/fml/common/ObfuscationReflectionHelper.java#L75) requires srg name, so it should be `field_147307_j` instead of `callbackScreen` and this will automatically remap to mcp name in development environment

yes, it broke when I migrated to mojang maps, Fix is on curseforge now waiting for approvial.

**Comment by ZekerZhayard** [comment]
MinecraftForge itself also has the same issue when they migrated to mojmap. 
https://github.com/MinecraftForge/MinecraftForge/commit/e33f794298dff0ebafce89f401e66d9cf6b2bc1e

**Comment by mysticdrew** [comment]
It is approved now, grab beta 10 from curseforge. 
https://www.curseforge.com/minecraft/mc-mods/journeymap/files/3351640

**Comment by mysticdrew** [comment]
> MinecraftForge itself also has the same issue when they migrated to mojmap.
> [MinecraftForge/MinecraftForge@e33f794](https://github.com/MinecraftForge/MinecraftForge/commit/e33f794298dff0ebafce89f401e66d9cf6b2bc1e)

Srg2Source seems a little over aggressive maybe, I was really surprised that it migrated comments.
