### ISSUE TITLE
[1.16.5] [Feature Request] Option to make server ops invisible on map

### ISSUE THREAD

**Issue by StarHunter36016** [TeamJM/journeymap#309]
#### JourneyMap Version:

1.16.5-5.7.1

#### Forge Version:

1.16.5-36.1.4

#### Describe the problem in repeatable steps:

Add a feature where the server operators can make themselves invisible on the map to all other players on the server.

**Comment by mysticdrew** [comment]
I will add this but it will only work when **_"Expanded Radar"_** is enabled.

**Comment by mysticdrew** [comment]
Added in 5.7.2beta11 will be available on curseforge shortly.
