### ISSUE TITLE
[Suggestion/fix for 1.13+ versions] Bring back auto-focus when placing a waypoint

### ISSUE THREAD

**Issue by vizthex123** [TeamJM/journeymap#310]
#### JourneyMap Version:

1.16.5-5.7.1

#### Forge Version:

36.1.31

In the 1.12.2 and older versions of the mod, you could place a waypoint and immediately start typing to label it. But now, you have to select the box first and it's a tad annoying.

Could you bring back the auto-focusing?

**Comment by mysticdrew** [comment]
This is already done in a current 5.7.2 beta on curseforge.
