### ISSUE TITLE
[Feature Request] Force everybody to disable death marker (Admin panel)

### ISSUE THREAD

**Issue by Hadyark** [TeamJM/journeymap#312]
#### JourneyMap Version:

1.12.2-5.7.1

#### Forge Version:

14.23.5.2854

#### Describe the problem in repeatable steps:

1. I would like to prevent all the players from my server to see where they died with the Death Marker (Waypoint) like i can disable the radar in the Admin panel

**Comment by mysticdrew** [comment]
1.12.2 is no longer getting updates.

**Comment by mysticdrew** [comment]
This has been added in 1.16.5_5.7.2Beta16. 
If users have deathpoints when the server disables them, it will remove all deathpoints the user currently has.
