### ISSUE TITLE
[1.16.5] Waypoint Editor - Hovering a colour wheel closes the menu

### ISSUE THREAD

**Issue by tajemniktv** [TeamJM/journeymap#313]
---
  

#### JourneyMap Version:

`1.16.5-5.7.1`

#### Forge Version:

`1.16.5-36.1.0`

#### Describe the problem in repeatable steps:

1. Open JourneyMap
2. Enter Waypoint Editor
3. Hover the colour picker/wheel. 

#### Description

Whenever I try to open a waypoint editor and hover the colour wheel - It instantly closes. The wheel looks (a cake/3D) like this: 
https://imgur.com/af6E1t8

Might be a incompatibility with other mod - Here's the full mod list:
https://imgur.com/a/2gygGqS

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

These relevant are probably the ones that start with: _[Render thread/ERROR] [WaypointEditor]_
https://paste.ee/p/p3ZYw

#### Link to a reddit post:
https://www.reddit.com/r/CurseForge/comments/oc5xcm/journeymap_create_waypoint_screen_broken/

---

**Comment by mysticdrew** [comment]
This was an issue due to changes in minecraft 1.16.5 and tooltips, we create dynamic tooltip for the birthday easteregg (cake). This was missed in the port. 
Download the beta for 1.16.5_5.7.2beta18 for the fix.

**Comment by tajemniktv** [comment]
Oh, if that's so then happy birthday to anyone who has them today!

**Comment by mysticdrew** [comment]
Link to fixed version.
https://www.curseforge.com/minecraft/mc-mods/journeymap/files/3373817

It is techbrew's birthday, the creator of journeymap.
