### ISSUE TITLE
[1.16.5] Distance is overlapping when above 6 digits

### ISSUE THREAD

**Issue by mkg20001** [TeamJM/journeymap#314]
#### Describe the problem in repeatable steps:

1. /tp @s ~ ~ ~1000000
2. make waypoint
3. see this (screenshot below)

![image](https://user-images.githubusercontent.com/7735145/124357559-6ebce400-dc1c-11eb-8d23-fa7494b192bb.png)

**Comment by mysticdrew** [comment]
There is no such thing as JourneyMap Version: 1.6-SNAPSHOT

**Comment by mysticdrew** [comment]
I need to know which journeymap version please.

**Comment by mkg20001** [comment]
5.7.1

**Comment by mysticdrew** [comment]
This is fixed and will be in the next 5.7.2 beta release. 
I increased the gap between name and distance and if the distance number is very large, I am converting it to scientific notation.

**Comment by mysticdrew** [comment]
![image](https://user-images.githubusercontent.com/5459941/124362802-d7946400-dbfc-11eb-90b6-8013f97713cd.png)
