### ISSUE TITLE
The incompatibility of Ice and Fire

### ISSUE THREAD

**Issue by joe-vettek** [TeamJM/journeymap#316]
#### JourneyMap Version:

any

#### Forge Version:

`Example: any

#### Describe the problem in repeatable steps:

When I played Ice and Fire on 1.12 and 1.16, dragons were considered neutral creatures (will actively attack players), and the gray icons were difficult to determine what they were. Can I customize the monster icon?

**Comment by joe-vettek** [comment]
By the way, would you develop such a function, which is to draw the boundary of the biome?

**Comment by mysticdrew** [comment]
The dragons are gray icons because of they implemented their mobs. Not anything to do with us. 
These are more slated as discussions. Not issues. 
https://journeymap.info/Custom_Mob_Icon_Sets
Better suited on our discord server. 
https://discord.gg/eP8gE69

**Comment by joe-vettek** [comment]
OK，thank you.
