### ISSUE TITLE
[Feedback] Potion Icon Feature Could Use Some Customization

### ISSUE THREAD

**Issue by Darkosto** [TeamJM/journeymap#317]
Hello!

Thank you for the new update! On the newest version of JM, the feature to move the buff/potion icons when the minimap is on the top right is a great feature but I think it may be lacking some customization. Currently, I use the map on the top right for all of my projects and when the Potion icons are moved over, they end up on top of another mod's UI elements. Is there a possibility we could have a setting to move the potion icons too? That way, I could setup my projects and not have UI elements on top of each other. The only way I have been able to solve this is by moving the minimap down about 10 pixels so the potion icons move back to their default position. This isn't ideal since having multiple icons will then cover the minimap again. 

One more thing to note, when using the "custom" placement for the minimap it's very difficult to line it up with the icons: 
![image](https://user-images.githubusercontent.com/10309699/127058955-13e6a01e-4aa0-4fe8-984b-f921badbf63e.png)

Is it possible to have a way to move the minimap in smaller increments? Thank you very much and have a wonderful day!!
Darkosto

**Comment by mysticdrew** [comment]
I can look into more customization for the icons, sure. What are some possible ideas for locations? Most people requested them to just be to the left of the minimap. 
So you can use the arrow keys, or drag the minimap while holding control. Are the arrow keys moving it too much for you? 

Feel free to hit me up in discord or w/e if that will be easier to chat about it.

**Comment by Darkosto** [comment]
Hey Drew!

Thanks for the response! For me personally, I think the trouble with moving the minimap is related to a few things:

1. After updating JM, I knew the minimap could be moved but it took me a minute to figure out the controls. I had to go back to the changelog to find it. Do you think it's possible a tooltip could be added to help players out?
2. When dragging the minimap with the mouse it seemed a bit 'out of control' and hard to fine tune the location I wanted it. Being able to use the arrow keys was much easier in control of where I wanted it to go
3. When trying to line up while using the arrow keys, as you asked in your response, it moves the map too much. I think it would be a nice quality of life change to allow the movement in smaller increments

In terms of the location for the icons, could they be set to anchor on a side of the minimap? I would personally set it up so it they are anchored below the minimp rather than to the left. This may be asking a lot, but it might be helpful to set how the icons are lined up, e.g. vertical or horizontal. If anchoring is not an option, what about setting their placement like you do with the minimap: top-right, middle-right, bottom-left, etc?

What do you think?

**Comment by mysticdrew** [comment]
1. Yes! I need to find a good place to do that. I am almost tempted to remove the "custom" option and you can just drag the minimap from any of the presets. The tooltip for it could be on the location button. 
2. It sometimes acts weird while dragging, it stutters a bit now and then. Not sure why, and it only does it on my computer when the game is fullscreen. 
3. Yea I can make the increments smaller. If I recall, they are percentage based, each key moves it 1% of your screen. I could make it one pixel. 

yea, I think I make something work with where the effect icons are placed and make it more configurable. 
It is pretty easy to move the icons for me. 

Thanks for the feedback!

**Comment by mysticdrew** [comment]
Just an update for you, 1.17.1_5.7.3 is out of beta and I have put out an official release. So, I have started progress on the 5.7.4 for 1.16 and 1.17. Which will include changes for this issue. 

Sorry for the delay, this summer was extremely busy and I had very little free time for JM work.

**Comment by Darkosto** [comment]
I meant to respond too this but completely forgot :P

No worries on your timeframe, it's not a high priority fix. Let me know if I can help out! Thank you 🦖
