### ISSUE TITLE
[1.16.5] Incompatibility with Immersive Portals

### ISSUE THREAD

**Issue by FlexGamesYT** [TeamJM/journeymap#318]
JourneyMap Version:
5.7.3

Forge Version:
36.1.65

Minecraft Version:
1.16.5

Describe the problem in repeatable steps:

1. Use JourneyMap + [Immersive Portals](https://www.curseforge.com/minecraft/mc-mods/immersive-portals-for-forge)
2. Travel through a Immersive Portal supported Portal 
3. See the result on the map (in attachment)
(4. The glitched stuff also randomly (partly) disappears on the map or/and some darkened spots appear)
![2021-07-27_16 58 18](https://user-images.githubusercontent.com/79639219/127177452-f1362d41-841b-433b-8dde-85d63e9837dd.png)
![2021-07-27_16 44 03](https://user-images.githubusercontent.com/79639219/127175440-9e590627-ecd3-4a37-87d2-2edab96c940a.png)
| Cave Mapping / "Show Caves" is disabled
![2021-07-27_16 48 57](https://user-images.githubusercontent.com/79639219/127175788-6881bfa4-266b-4625-ac58-60d64f4690d8.png)
![2021-07-27_16 53 54](https://user-images.githubusercontent.com/79639219/127176698-b944b0fe-e3f6-4703-b7b7-cb0b687dc438.png)
(I got about 90 Mods loaded but travelling between worlds that support Immersive Portals causes this)
It also seems like this is not always appearing, just randomly

New Example with more detailed and only JM and ImmP:
1. Install JM and ImmP newest Version
2. Build for this example a Nether Portal and activate it
3. Go through it (and maybe look shortly in not a too long distance around)
4. Go back through the portal (if it's important through the side you came out)
5. See the result on the Map (my try in attachment)
(this time not such an extreme result but you can see what I mean I hope)
![2021-07-27_17 41 36](https://user-images.githubusercontent.com/79639219/127184679-8b2d65de-0fae-45ae-92c1-e9b4ac2fb087.png)

Relevant errors from `.minecraft/journeymap/journeymap.log`:
The new Log File:
[journeymap.log](https://github.com/TeamJM/journeymap/files/6886873/journeymap.log)

**Comment by mysticdrew** [comment]
I am unable to replicate this. 
I need a detailed walkthrough on how to reproduce this using only jourenymap and immersive portals please.

**Comment by FlexGamesYT** [comment]
Updated with an extra example as you said, more detailed and that stuff and also added the new log file

**Comment by mysticdrew** [comment]
Looking at what is happening, it does not seem to be on jourenymap side of things. Immersive Portals is doing something that is messing up how we read the chunks. I have not isolated it yet. 
Immersive portals seems kind of buggy in general.

**Comment by mysticdrew** [comment]
https://github.com/qouteall/ImmersivePortalsModForForge/blob/11f4665ac1a56a01d5049aedcccdb45bd9abc7e8/src/main/java/com/qouteall/immersive_portals/chunk_loading/MyClientChunkManager.java#L130

likely a bug here between line 130 and 160. 

We check the chunk light level and color it based on what that light level is. We do not control it, only show what the chunk tells us.  I did notice chunk light levels changing for the odd looking chunks. 
Feel free to reference this issue on their issue tracker.
