### ISSUE TITLE
[1.16.5-1.17.1]: Waypoint Teleport in the Nether is not calculating Destination correctly.

### ISSUE THREAD

**Issue by Immaculala** [TeamJM/journeymap#319]
#### Instructions for Submitting an Issue
1. Ask for help on Discord (https://discord.gg/eP8gE69) #support if you're unsure this is a new issue.
2. Please search for existing issues before submitting a new one.
3. Please add the correct MC<version> label to your issue. Example: "[1.12.2] Waypoints are upside down"
4. Completely fill out the template below. Failure to do so is likely to get the issue closed immediately.
5. Prove you read these instructions by deleting this section before submitting. ;)
---
  
#### Describe the problem in repeatable steps:

1. When I am in the Nether it does not teleport me to the waypoint
<img width="960" alt="2021-07-30_22 40 25" src="https://user-images.githubusercontent.com/26187212/127714764-39b0aaa1-9d9f-4e34-95d5-0b8ca46f080c.png">

2. I think (not sure though) this may be a conflict with Cyclic or Abnormals mods.
3.

**Comment by mysticdrew** [comment]
I need some more detail please. 

Where were you when you initiated the teleport. 
Which dimensions the waypoint has activated. 

Tell me exactly step by step how to recreate this issue.

**Comment by Immaculala** [comment]
I was a little way west when I tried to teleport back to the portal but it happened other times from all over the nether,
All dimensions are activated and all the other ones work just fine as usual.
[journeymap.log](https://github.com/TeamJM/journeymap/files/6911025/journeymap.log)

**Comment by mysticdrew** [comment]
Alright, I have confirmed this bug with JM. Thanks. 
Fix may be a bit out yet until I wrap up the 1.17.1 port.

**Comment by Immaculala** [comment]
> Alright, I have confirmed this bug with JM. Thanks.
> Fix may be a bit out yet until I wrap up the 1.17.1 port.

Firstly, thank you for the fast response - really appreciated :)
Secondly, I for one can live with a bit of a wait, these things happen :)
Thirdly, in the meantime, I'll revert to an earlier version i.e. 1.16.5-5.7.2 and see if that solves the issue for now.
Very many thanks :)

**Comment by mysticdrew** [comment]
Lets leave this open until I fix it so it does not get forgotten.

**Comment by Immaculala** [comment]
You're a star - many thanks :)

**Comment by Hagerdorn** [comment]
hi, will this issue be fixed for MC 1.16.5?

**Comment by Immaculala** [comment]
> hi, will this issue be fixed for MC 1.16.5?
I reverted to an older file i.e. journeymap-1.16.5-5.7.1 and that works okay.
N.B. journeymap-1.16.5-5.7.3 is the version with issues, and journeymap-1.16.5-5.7.2 crashed my game.
So, if you want something that works okay for now until mysticdrew can work on the fix, I suggest you download journeymap-1.16.5-5.7.1
Good luck :)

**Comment by mysticdrew** [comment]
> > hi, will this issue be fixed for MC 1.16.5?
> > I reverted to an older file i.e. journeymap-1.16.5-5.7.1 and that works okay.
> > N.B. journeymap-1.16.5-5.7.3 is the version with issues, and journeymap-1.16.5-5.7.2 crashed my game.
> > So, if you want something that works okay for now until mysticdrew can work on the fix, I suggest you download journeymap-1.16.5-5.7.1
> > Good luck :)

5.7.2 will crash your game with optifine installed. 5.7.3 fixes that issue, that is the only difference between the two versions. 

This fix will be included in the next release for 1.16.5 and 1.17.1. I have it fixed already in my local builds, but I have more things to address before I do a public release.

**Comment by Immaculala** [comment]
Ahhhh, I have Optifine so that'll be why 1.16.5-5.7.2 crashed my game.

**Comment by DarthStarGaming** [comment]
Hi I'd also like to comment on this same issue with waypoints from JourneyMap if I'm allowed. I'm on Seaopolis and I have the same issue. Basically every waypoint in the nether needs to divisible by 8. So if I wanted a waypoint at 400, 120, 300, I would have to set my waypoint at 50, 120, 37, and hope I don't fall through as the Nether is a Skyblock style. If I need to post screenshots please inform me and I will do so.
