### ISSUE TITLE
Problem using customized palettes

### ISSUE THREAD

**Issue by falazar** [TeamJM/journeymap#32]
#### JourneyMap Version:
journeymap-1.9-5.5.2

#### Forge Version:
1.9.2

#### Describe the problem in repeatable steps:
I cannot get the custom color palette to stay on for a single world... I have to edit and reset every time, and even after I die I believe, which is very cumbersome.  And if I forget one time it will wipe out that area of the map that I had created with custom colors. 

1. Currently I am searching for bedrock in the colorpalette.json, changing it to red, and hitting 
"Reset Color Palette" in the large map page.
2. This triggers a map update.
3. But upon dying or relogging it goes back to original, and I have to repeat this every time.

I tried a couple of other methods, but could not find anything that works.
Tried to walk a couple of friends thru this, they could not get it to work at all, but not sure what their issue is. 

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
none.

**Comment by mysticdrew** [comment]
Fixed in 5.5.4b4
