### ISSUE TITLE
1.17.1 eating up memory over time.

### ISSUE THREAD

**Issue by Dynis91** [TeamJM/journeymap#320]
#### JourneyMap Version:
.17.1-5.7.3rc1

#### Forge Version:
1.17.1-37.0.22

#### Describe the problem in repeatable steps:

1.  When running minecraft on our server the game gets more and more laggy over time, Checking the computers processes, OpenJDK Platform Binary starts at around 1-2gb of ram and goes during an hour up to 9gb of usage and then the game crashes.

2. Been in contact with Forge that checked the logs and said that it looks like a JM problem with OpenGL, so removed JM from my computer and now the game work flawless, We are 8people on a server playing and only me and another player is experiencing this. 

3. 
https://pastebin.com/JnHwLnG0
https://pastebin.com/GZ2hbpTB
https://pastebin.com/T09nxND0
https://discord.com/channels/313125603924639766/437001959950778368/873575533898780762 Discord with forge
 

Edit: tested new journeymap-1.17.1-5.7.3rc2   
and still same problem

**Comment by mysticdrew** [comment]
Fixed in 1.17.1rc3
