### ISSUE TITLE
Nether Waypoint Teleport Bug

### ISSUE THREAD

**Issue by Pixelplayz2215YT** [TeamJM/journeymap#322]
I made a waypoint for me to TP to in the Nether. it was at my nether Portal to go home. but when I TP back, it keeps teleproting me 1200+ block away from my waypoint.

#### Describe the problem in repeatable steps:

1. Go to nether
2. make waypoint (for me I did the Netherportal to go home)
3. TP their.

**Comment by mysticdrew** [comment]
Duplicate #319

**Comment by Pixelplayz2215YT** [comment]
Sorry, so it's a known issue and being worked on?
