### ISSUE TITLE
More Zoom Levels

### ISSUE THREAD

**Issue by PliskintheSaltyFork** [TeamJM/journeymap#328]
#### Forge Version: N/A

I would like to be able to have more zoom levels for JourneyMap so I can zoom in farther/further or closer.

#### Describe the feature you would like to add:

More zoom levels, similar to Mapwriter's and Xeno's.  Also, waypoint grouping and be able to switch between different groups of waypoints.  Also, more detailed maps.  Either way, I'd like to see more features added that are similar to the ones found in Mapwriter.

Max Zoom Out in Xeno's
![2021-09-28_11 22 28](https://user-images.githubusercontent.com/6131437/135117192-1d9337f2-05d5-483d-af2a-f31a478bdac5.png)
Mapwriter 2 World Map
http://www.9minecraft.net/wp-content/uploads/2017/01/Mapwriter-2-Mod-Screenshots-10-1024x576.jpg

**Comment by mysticdrew** [comment]
waypoint grouping is coming when I get time. Zoom levels are unlikely.
