### ISSUE TITLE
[1.16.5]: Icons missing log spam

### ISSUE THREAD

**Issue by PliskintheSaltyFork** [TeamJM/journeymap#329]
#### Describe the problem in repeatable steps:

1. Check to make sure you have console log open in the background when Launching Minecraft
      a. Launch Minecraft with Forge and JourneyMap installed correctly
2. Observe console log error for JourneyMap
      a. Look for the following error:
Couldn't locate icons for Default: E:\Games\Minecraft\Instances\Breath%20of%20the%20Wylde\mods\journeymap-1.16.5-5.7.3.jar\assets\journeymap\icon\entity
      b. Or this error if you having this other problem
Couldn't locate icons for flat: E:\Games\Minecraft\Instances\Breath%20of%20the%20Wylde\mods\journeymap-1.16.5-5.7.3.jar\assets\journeymap\theme\flat

Either way, it would seem that the mod is missing image files or forge is not looking in the right place for the image files
![JourneyMap Error](https://user-images.githubusercontent.com/6131437/135475780-d4584fd0-991e-431c-a287-64b32f1a76e9.png)

**Comment by mysticdrew** [comment]
While this looks really bad, it is not.
Those files are not missing, but sometimes there is a race condition that causes them not to be found on the first attempt. I have been meaning to fix it but it is extremely low priority. 

I will keep this ticket around so I do not forget to fix it when I get some JM dev time in.
