### ISSUE TITLE
Journey Map Vault Theme

### ISSUE THREAD

**Issue by AlexisLatias** [TeamJM/journeymap#33]
I'm on 1.7.10 for minecraft since it's the version that doesn't lag so much/at all.

I'm wondering if there's a way to get the Vault Theme download link alternative, the one on the JourneyMap website link to the download link http://minecraft.curseforge.com/projects/journeymap-32274/files/2303051 is not available. Is there a reason why?

**Comment by Timardo** [comment]
Here is your theme: https://minecraft.curseforge.com/projects/journeymap/files/2303051

And the reason why it is not available anymore is due to curse changes to paths to projects.

Should be closed when the page https://journeymap.info/UI_Themes will have the link fixed.

**Comment by mysticdrew** [comment]
Link has been updated on journeymap.info.
