### ISSUE TITLE
[Feature Request] Ability to toggle your own player icon on servers

### ISSUE THREAD

**Issue by Batimius** [TeamJM/journeymap#331]
Hello there. As most of us here agree, JourneyMap is an amazing mod and to the majority of us an essential when it comes to modded Minecraft. It allows for waypoints, a minimap, display of nearby mobs, and many more useful features that we use every day on our game. I am running a private server with a couple of friends of mine and we use JourneyMap along with some other mods.

Something that I love about using JourneyMap in a Forge server is the ability to see where your friend is. This feature comes in very handy whenever you wish to find your friend when mining together or just meet with them in general. The issue is though, if you want to make something secret from them (such as an underground base, or something concealed), it is very difficult to be in that secret place when they can see your username on their minimap. A feature that I would love to see is the ability to have toggleable self-blobs. What this means is that each player (or client if you wish) will have an option to be visible on the minimap only when they want to. This can be done via the full-screen GUI, or a keybind, or both. This way, you can enjoy the ability to find your friends but still have the option to work on your little secret base without them finding out immediately. If this feature could be implemented, then that would be wonderful.

This is a feature I would love to see in JourneyMap. This mod in itself is truly wonderful, and the addition of such a feature would make it even more brilliant in my opinion. Of course, this is up to the developers to decide upon based on how difficult it is to implement, if it is worth your time, and if you would like to implement one or both of these features. That is all. Thank you for your time and interest and I wish you a wonderful evening.

**Comment by mysticdrew** [comment]
Some thoughts on this. 
We already have an all or nothing for player radar via the server admin option screen. But again, that is all or nothing, all players are hidden or no players are hidden. Also has an option where only ops can see players. 

This feature as requested would require JourneyMap to be on the server.
With that in mind, I can see the use case for this. 
The server admin would have to enable this in the server options to allow users to hide themselves. 
When enabled, The user will be an option (will figure the where out later) for the user to enable their person to be hidden on the map. 
When a player is hidden, all OP users will still be able to see them for security's sake. 
The server option for enabling and disabling all player radar will supersede this option. As in, if the server has disabled all player radar, there will be no option for the user to hide or reveal themselves.

**Comment by mysticdrew** [comment]
This has been added in journeymap 5.8.0beta14 for minecraft 1.16.5-1.18.1 which is on curseforge now. 

To access this option, in the options screen click the multiplayer button on the  top if your server has it enabled.
