### ISSUE TITLE
[Feature Request] Ability to blacklist regions from rendering

### ISSUE THREAD

**Issue by Batimius** [TeamJM/journeymap#332]
Hello there. I am sure that a lot of us can agree that JourneyMap is a wonderful mod and an essential when it comes to playing modded Minecraft. From waypoints to icons for mobs to an interactive web map, JourneyMap has tons of features that we use regularly when playing on a Forge singleplayer world or a Forge multiplayer server.

The ability to render a map as you go by is an amazing feature as it lets you explore different places and make a landmark of those places. This feature comes in very handy when underground as it reveals different cave systems and structures. Although these features are amazing, they can have their downsides.

I am running a private Forge servers with a few of my friends and we utilize JourneyMap along with some other mods. Although JourneyMap rendering is very useful, it creates a very huge issue when it comes to my server. I am making a secret underground base in which I want to store valuables and structures that I do not want others in my server to know the location of. That being said, it is a bummer when you go mining nearby and you are able to see a huge hallway and room in the corner of your map as it reveals the entire base without the player ever being there. That being said, it would be very useful if there was some way to blacklist certain regions, either as a server administrator or as a normal user.

The way this would work is by creating a blacklist of region(s) that you want the map to ignore. If the minimap was to render any blocks within the region, then it will just skip those blocks and render them as if they were never there, kind of like how the majority of the minimap looks like while underground (assuming you are in a strip mine and away from major cave systems). When it comes to surface-level rendering (so blacklists on the surface), the area could either be completely ignored just like underground, or there could be some overlay on the blacklisted region, either by placing a pre-defined image, ground similar to surrounding ground, or blurring the region. Of course, I personally am interested only in underground region blacklist, but a surface region blacklist would also be cool. All of the blacklisted chunks (both underground and on the surface) could either stay unrendered for as long as the area is blacklisted, or pop on the map (and render as if a blacklist was never there) when the player enters the region (kind of like "unlocking" that part of the map). Of course, the second option could definitely take up some performance as you would have to calculate if the player is within the position and check if they have the area unlocked or not, which would also take up server space when having a lot of blacklisted areas.

I personally think that this feature would be very useful for JourneyMap. This can come very handy when playing in servers with friends and you want certain out-of-reach or secret areas in your world. This feature would certainly take some effort to implement (at least from my point of view), but I believe that it would come very handy for many users that utilize this mod in servers. That is all. Thank you for your time and interest and I wish you a wonderful evening.

**Comment by mysticdrew** [comment]
There is a server option to disable cave mapping per dimension or globally. 

This blacklisted area is not something I will likely have time or motivation to implement.
