### ISSUE TITLE
[1.16.5] [Feature Request] Option to change/disable the coordinate update delay

### ISSUE THREAD

**Issue by Pockey7** [TeamJM/journeymap#333]
#### JourneyMap Version:

1.16.5-5.7.3

#### Forge Version:

1.16.5-forge-36.2.4

#### Describe the problem in repeatable steps:

Not a problem just a request for an option to change or disable the coordinates update delay on the minimap overlay. Having them update instantly helps me a lot when I'm using an Elytra to fly somewhere specific and can travel many blocks very quickly. 

Thank you for your time.

**Comment by mysticdrew** [comment]
I sped all info slots up for the next release for 1.17.1 and 1.16.5
