### ISSUE TITLE
[Feature Request] Biome Overlay

### ISSUE THREAD

**Issue by LoneDestroyer** [TeamJM/journeymap#338]
JourneyMap Version: 1.17.1-5.7.3
Forge Version: forge-1.17.1-37.0.103

Request: Be able to have a colour / name overlay on top of biomes. An easier way of identifying biomes I have visited when viewing the world map.

**Comment by mysticdrew** [comment]
This will be in the next release, it is not an overlay but a new maptype. 
Not exactly what this ticket is requesting but it is something. 
![image](https://user-images.githubusercontent.com/5459941/144104919-d07da3e9-5b3c-42e5-9f2f-67d6d4ae2fe9.png)

**Comment by mysticdrew** [comment]
Closing this as a biome overlay will not be added to journeymap proper, it will be added to Journeymap-additions side mod.

**Comment by mysticdrew** [comment]
no, not by me. 
https://github.com/TeamJM/journeymap-legacy 
is open source, someone else can do it

**Comment by unicornbloods** [comment]
Biome overlay not in sources here, thought you added it?

**Comment by mysticdrew** [comment]
huh?
biome map type is in journeymap 5.8.5+ for minecraft versions 1.16.5 and newer. 
I will not be backporting it. 
someone can add it to legacy, if they wish and I will merge and publish it. but I will not be doing the backporting or coding of it.

**Comment by unicornbloods** [comment]
journeymap 5.8.5+ isn't open source though

**Comment by mysticdrew** [comment]
correct, so it would be all new code in legacy someone would have to develop from scratch.

**Comment by unicornbloods** [comment]
It would be easier if I had access to how it is done in 5.8.5+

**Comment by mysticdrew** [comment]
yes, I agree. But, that is not possible.

**Comment by unicornbloods** [comment]
Course it is. People must have access if it still gets updates

**Comment by mysticdrew** [comment]
It is not, because I do not have permission to open source it or give anyone access to the source. I am not the license holder.

Anyways, the colors for the biome map are the biome specific grass color I believe. Should be simple enough to implement. 

Also, even if you had access to 5.8.5, the mapping code not the same, it was rewritten in 1.12.2. It would provide very little help.

**Comment by unicornbloods** [comment]
I see, thank you! I was just hoping for a reference, but the grass thing does give some help.
