### ISSUE TITLE
[Feature Request] <All Versions> Scaling Up Mob Icons Makes Them Blurry

### ISSUE THREAD

**Issue by luffykazuma** [TeamJM/journeymap#340]
#### JourneyMap Version: 
1.16.5-5.7.3 (But should apply to all versions)

#### Forge Version:
1.16.5-36.2.8 (But again, should apply to all versions)

#### Describe the problem in repeatable steps:
Simply increase the default scale of mob icons, and you will notice that the icons are quite blurry (refer to screenshot below).

![image](https://user-images.githubusercontent.com/54678277/141009922-08b254bf-60b8-4802-bc2e-132883cfc39e.png)

As per thread: https://discord.com/channels/239040424214396929/325390896524951553/907745717215436880, a different scaling method/algorithm needs to be used to prevent the icon from getting blurred when scaling up.

**Comment by mysticdrew** [comment]
This as been added for the next release (5.7.4) for 1.16.5 and 1.17.1. Keep an eye on our discord or curseforge for the release
