### ISSUE TITLE
"[1.12.2] Incompatible bug between Optifine and JourneyMap, blur menu and text"

### ISSUE THREAD

**Issue by nhatanh0475** [TeamJM/journeymap#345]
#### JourneyMap Version:

`1.17.1-5.7.3`

#### Forge Version:

`Example: 1.171-37.0.104`

#### Describe the problem in repeatable steps:

1.Only load **Optifine**, Forge, **Journey Map** and that is it
2. Login Single Player
3. HD text turn into **blurry text**
4. Do some stuff, HD text return, then **immediately blur** again.
5. Check google, ton of website since google mislead a lot.
6. Found website about this exact problem on: https://githubmemory.com/repo/sp614x/optifine/issues/6281?page=2
7. Can't comment on there (even with account) , went back to here to discuss.
#### How to fix _(temporarily_)
1. **Disable ALL** beacon, turn off ALL of it.
2. **Wait** a couple minute.
3. HD text **return**, YAY
4. **Never** turn on Beacon ever again
5. **Only** using map with no beacon **Insert sad/disapointed emoji**
5. **Considering** other mods.
#### Relevant errors from `.minecraft/journeymap/journeymap.log`: 
[journeymap.log](https://github.com/TeamJM/journeymap/files/7620003/journeymap.log)
#### Note
This never happen before [MC 1.16.5] (At least for me)
Only happen to [MC 1.17.1] very recently.
 Delete entire .Minecraft, refresh it before getting 1.17.1
Minecraft main menu interface before login in game has a warning about Forge: Beta

**Comment by mysticdrew** [comment]
duplicate #334 
https://github.com/sp614x/optifine/issues/6281 
turn off waypoint labels to fix, has nothing to do with beacons. This is 100% an optifine issue.

**Comment by mysticdrew** [comment]
I created a pinned issue here
https://github.com/TeamJM/journeymap/issues/347 
Add any comments to that please.

**Comment by nhatanh0475** [comment]
Still by leaving an "open" issue, people would know about this and know this is a "known" bug that still exist.
By closing it, you declare it has been solve which isn't true.
Keeping my issue open will/may prevent other to report the same issue yet get brutally close by you.
I also add a temporary fix that can work no doubt cause now I know exactly what causing it. And if you closed then it also mean you don't want people to find a solution. Its took me hours just to find a "single" person post that actually have the same problem as I do.
And if you better keep the solvable solution to yourself from other than fine, I have no reason to stay with a Dev that doesn't allow me to help other.
I did read your rule in the instruction, isn't that enough?
I even search the keyword "blur" to check if anyone has post this issue yet I found no one. This mean If I never post that issue, no one will ever find the solution here, or at least this side of Github.
Just because you can't fix it doesn't mean you can just "sweep it under the carpet", you need to declare an incompatible and until it be fix, you can't do anything about it, that way it's both benefit for you to not get the same question over and over again and for the player when they find their answer and that they're not alone.
