### ISSUE TITLE
"[1.17.1] JourneyMap hide issue, preventing other to seek help from Github"

### ISSUE THREAD

**Issue by nhatanh0475** [TeamJM/journeymap#346]
#### JourneyMap Version:

`1.17.1`

#### Forge Version:

`1.17.1`

#### Describe the problem in repeatable steps:

1. Post issues and way to temporary solve it
2. JourneyMap try to hide the issue from other to found out
3. DELETE Journey Map, proceed using other mods, JourneyMap Dev have no respect for user try to help.
4. JourneyMap Dev have free time to close post yet no time to actually fix problem.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
[journeymap.log](https://github.com/TeamJM/journeymap/files/7620087/journeymap.log)

**Comment by mysticdrew** [comment]
Why are you creating this, I cannot fix the blurry text issue, that is on optifine to fix.

**Comment by nhatanh0475** [comment]
Still by leaving an "open" issue, people would know about this and know this is a "known" bug that still exist.
By closing it, you declare it has been solve which isn't true.
Keeping my issue open will/may prevent other to report the same issue yet get brutally close by you.
I also add a temporary fix that can work no doubt cause now I know exactly what causing it. And if you closed then it also mean you don't want people to find a solution. Its took me hours just to find a "single" person post that actually have the same problem as I do.
And if you better keep the solvable solution to yourself from other than fine, I have no reason to stay with a Dev that doesn't allow me to help other.
I did read your rule in the instruction, isn't that enough?
I even search the keyword "blur" to check if anyone has post this issue yet I found no one. This mean If I never post that issue, no one will ever find the solution here, or at least this side of Github.
Just because you can't fix it doesn't mean you can just "sweep it under the carpet", you need to declare an incompatible and until it be fix, you can't do anything about it, that way it's both benefit for you to not get the same question over and over again and for the player when they find their answer and that they're not alone.

**Comment by mysticdrew** [comment]
comment on your original issue, not this one.

**Comment by nhatanh0475** [comment]
> I provided and actual fix here #347 There was no intention of sweeping it under the carpet as you say. It is not a journeymap issue it is an optifine issue. The issue is open on their issue tracker. All reports should be handled there, which is why I linked to it in your original issue which you failed to read.

I'm not fail to read, I'm just too mad at you for shutting the door right at my face to have any respect left to listen to you.
I like the kid who want to help people yet being push aside at first sight.
