### ISSUE TITLE
[1.18.0] Unable to save waypoints with negative height

### ISSUE THREAD

**Issue by sEkHMeT90** [TeamJM/journeymap#351]
#### Instructions for Submitting an Issue
When you create a new waypoint with negative height, this value isn't kept saved. When you tray to edit the saved waypoint the Y's value disappears and an error was showed.

![imagen](https://user-images.githubusercontent.com/8137396/144463936-669c913c-397f-429a-9dbf-11fe0ad50df9.png)

  
#### JourneyMap Version:

5.8.0alpha2

#### Forge Version:

38.0.8

#### Describe the problem in repeatable steps:

1. Create a new waypoint in negative height
2. Open de map
3. Go to waypoints list
4. Edit the waypoint
5. Y value disappears

**Comment by mysticdrew** [comment]
You can manually put in negative values as a work around until I get this fixed.

**Comment by sEkHMeT90** [comment]
> You can manually put in negative values as a work around until I get this fixed.

I think is not possible. When I put the value manually and save it, also disappears.

**Comment by mysticdrew** [comment]
Interesting, I will get it fixed shortly. Thanks!

**Comment by mysticdrew** [comment]
Alpha 3 is published on curseforge with this fix, it will be available when they approved it.
