### ISSUE TITLE
Newest 1.16.5-5.8.0beta1.jar DOES NOT WORK with Forge 36.2.0 (Recommended Version)

### ISSUE THREAD

**Issue by FatherGuse** [TeamJM/journeymap#353]
Nice job guys .. your latest version/update requires the version of Forge NOT recommended on the Forge Download site with absolutely no warning or "heads-up" on your file page .. thanks for that (after updating your mod on all of my family's computers) .. nice waste of time when a simple "heads-up" or warning would have been perfect.

-- MOD journeymap --
Details:
	Mod File: journeymap-1.16.5-5.8.0beta1.jar
	Failure message: Mod journeymap requires forge 36.2.18 or above
		Currently, forge is 36.2.0
	Mod Version: 5.8.0beta1
	Mod Issue URL: https://github.com/TeamJM/journeymap/issues
	Exception message: MISSING EXCEPTION MESSAGE

**Comment by mysticdrew** [comment]
It is a beta version... 
Update your forge as newer forges provides new things in this beta version. If you do not want to use new features, go back to 5.7.3. 
There will not be a release version of 5.8.0 until there is a release version(RB) of forge

**Comment by mysticdrew** [comment]
Also, from the curseforge site. It clearly states the version of forge required.
![image](https://user-images.githubusercontent.com/5459941/144541380-632e2aa8-f893-4165-8804-dca102ce4170.png)
