### ISSUE TITLE
[Suggestion] Temporary Waypoints

### ISSUE THREAD

**Issue by 4rz0** [TeamJM/journeymap#354]
I suggest adding some kind of temporary waypoint that can be used for navigating and exploring.
It would work as follows: 
You create a waypoint the usual way and mark it as "temporary" (new WP option) or use the button/keybind (see below).
As you approach that waypoint it will automatically remove itself (new deletion radius setting).

Things worth consindering:
- separate keyboard shortcut and/or quick-access-button to allow for quickly setting a Temporary Waypoint from the fullscreen map
- separate settings regarding Temporary WP beacons
- make Temporary WP independent of Z-level to allow aiding in underground exploration
- some option to hide all but the closest Temporary WP if more are present
- (some way to display Temporary WPs one after another in a certain order)(?)

**Comment by mysticdrew** [comment]
First iteration of temporary waypoints is added and slated for 5.8.0 beta 13
In the waypoint options is an option to set the distance at which it is auto removed. 
To create a temp waypoint, right click on the minimap select waypoint, then select temp waypoint. 

`make Temporary WP independent of Z-level to allow aiding in underground exploration`
I suspect you mean Y level, but I do not understand what you want to happen here.

**Comment by mysticdrew** [comment]
Beta13 will be on curseforge shortly
