### ISSUE TITLE
[Feature Request]: Hide Fullscreen Buttons 

### ISSUE THREAD

**Issue by RazAssassin** [TeamJM/journeymap#355]
JourneyMap Version:

1.17.1-5.7.3

Forge Version:

1.17.1-37.0.103

Description:

I want a way to hide the button icons on the fullscreen map so I can take screenshots without having the hud icons in view.

**Comment by RazAssassin** [comment]
the save map function saves the map in a smaller resolution/pixel, and when you go to zoom in on that map it's all blurry.

**Comment by mysticdrew** [comment]
for 5.8.0beta13 this is added, default hotkey is H when in the fullscreen map.

**Comment by mysticdrew** [comment]
Beta13 will be on curseforge shortly
