### ISSUE TITLE
[1.18] The minecraft text is foggy on waypoints/full scale map 

### ISSUE THREAD

**Issue by ivanthenerd** [TeamJM/journeymap#356]
#### JourneyMap Version:

`1.18-5.8.0alpha4`

#### Forge Version:

`1.18 - 38.0.15`

#### Describe the problem in repeatable steps:

1. Go to a server with the mod
2.  Open either waypoints or full scale map
3. The minecraft text is foggy

#### Relevant errors from `.minecraft/journeymap/journeymap.log`: `none`
![foggy 3](https://user-images.githubusercontent.com/95715823/145096185-49d5b8fd-dec6-46bd-9303-59dfb304be02.png)
![foggy while using the mod](https://user-images.githubusercontent.com/95715823/145096194-8f2797be-71f9-4df7-b12f-0063db4a27a1.png)
![foggy 2](https://user-images.githubusercontent.com/95715823/145096199-600f44bf-27ee-4e91-bb1c-8160a3c55464.png)
![Foggy](https://user-images.githubusercontent.com/95715823/145096202-20c5520b-0d33-4b6c-93ef-2cc7adec8fa5.png)

**Comment by mysticdrew** [comment]
update journeymap
https://www.curseforge.com/minecraft/mc-mods/journeymap/files/3554119

**Comment by ivanthenerd** [comment]
btw this is how it looks when the for some reason fog effect don't apply

**Comment by mysticdrew** [comment]
I have no idea what you mean. 
It is an issue with optifine and jourenymap. It is resolved in Alpha 6 in the link I provided above.
