### ISSUE TITLE
[1.12.2] Bug

### ISSUE THREAD

**Issue by Kasia1403** [TeamJM/journeymap#359]
#### JourneyMap Version: 1.12.2-5.7.1

`Example: 1.12.1-5.5.0`

#### Forge Version: 1.12.2-1.12.2-14.23.5.2855 

`Example: 1.12.1-14.22.1.2478`

#### Describe the problem in repeatable steps:

1.Load world
2.Open map
3.Old world's map doesn't delete after loading new world even if new world has other seed and doesn't want to delete when I press delete map button.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

[journeymap.log](https://github.com/TeamJM/journeymap/files/7683511/journeymap.log)

Hope that I uploaded a correct journeymap.log file.

**Comment by mysticdrew** [comment]
Give your worlds Unique names, we save the data by the name you give it. 
If are all named "new world" we cannot differentiate between them.

**Comment by OpenSauce04** [comment]
Oh they are loaded by world name?
Wouldn't it be better to load it by world folder name so conflicts like this don't happen?

**Comment by mysticdrew** [comment]
> 

For singleplayer yes, but there are no world folder names for multiplayer.
