### ISSUE TITLE
[1.12.2/5.5.2] "Follow" not panning map to player

### ISSUE THREAD

**Issue by Fevix** [TeamJM/journeymap#36]
#### Instructions for Submitting an Issue
1. Ask for help on Discord (https://discord.gg/eP8gE69) #support if you're unsure this is a new issue. (Would have done this but I've been on the Discord for almost an hour and haven't been given the role to see/speak)
---
  
#### JourneyMap Version:

`1.12.2-5.5.2`

#### Forge Version:

`1.12.2-14.23.2.2611`

#### Describe the problem in repeatable steps:

1. Open map
2. Click "Follow" button

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
No errors in the log.

**Comment by mysticdrew** [comment]
duplicate #90

**Comment by Fevix** [comment]
How is this a duplicate of an issue that was posted nearly a year after?

**Comment by mysticdrew** [comment]
does it matter?

I saw that one first and started work on it. Then I saw this one. Same issue, they also have more details in the issue.
