### ISSUE TITLE
[1.18] Cave Maps Blacked Out at Negative Y Layers

### ISSUE THREAD

**Issue by DeadlySwede** [TeamJM/journeymap#360]
#### JourneyMap Version:

JourneyMap 1.18-5.8.0alpha8

#### Forge Version:

Forge 1.18-38.0.16

#### Other Mods:

Immersive Engineering 1.18-5.0.2-pre.352
Just Enough Items 1.18-9.0.0.40

#### Describe the problem in repeatable steps:

1. Dig and light tunnels at y=10, tunnels show up in cave maps.
2. Dig and light tunnels at y=-10, tunnels are blacked out in cave maps.

Happens in both single and multiplayer.

Was also happening with JourneyMap 1.18-5.8.0alpha4 and Forge 1.18-38.0.14. 

Can't use Forge 1.18-38.0.15 right now. Running multiplayer on Immersive Engineering 1.18 test server.

**Update** Tried just using JourneyMap 1.18-5.8.0alpha8 and Forge 1.18-38.0.15 in single player creative world. Same issue.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

No errors.

[journeymap.001.log](https://github.com/TeamJM/journeymap/files/7687166/journeymap.001.log)

#### Screen Shots

Lit Tunnels at Y=10
![2021-12-09_11 19 00](https://user-images.githubusercontent.com/2657769/145444778-5488455f-2e75-4ea0-a39b-2967ac76daf0.png)

Lit Tunnels at Y=-10
![2021-12-09_11 18 01](https://user-images.githubusercontent.com/2657769/145444818-58a5ea7a-64e4-4c67-b204-bd8991047614.png)

**Comment by mysticdrew** [comment]
Thanks, this is fixed and will be available when I publish alpha9.

**Comment by mysticdrew** [comment]
https://www.curseforge.com/minecraft/mc-mods/journeymap/files/3556454

**Comment by DeadlySwede** [comment]
Verified fixed. Thanks!
