### ISSUE TITLE
[1.17.1] Villagers never show on minimap or fullscreen map.

### ISSUE THREAD

**Issue by AHilyard** [TeamJM/journeymap#361]
#### JourneyMap Version:

Tested with
**1.17.1-5.7.3**
and
**1.17.1-5.8.0beta3**

#### Forge Version:

**1.17.1-37.1.1**

#### Describe the problem in repeatable steps:

1. Install Journey Map and no other mods.
2. Find a village.
3. Notice that no villagers show on the map, regardless of settings.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
No errors are logged.

#### Other details:
One potential failure point may be that journeymap.client.model.EntityHelper.isSpecialCreature seems to be rejecting any PathfinderMobs that are of categories other than MobCategory.MONSTER or MobCategory.CREATURE.  Villagers are in the category MobCategory.MISC.

**Comment by mysticdrew** [comment]
Ahh Ha! 
yea, Villagers were not pathfindermob in 1.16.5, but now in 1.17.1+ they are. Thanks!

**Comment by mysticdrew** [comment]
Fixed in beta4, should be on curseforge shortly.
