### ISSUE TITLE
[1.16.5]Failure to load game with journey map 5.8.0 beta 3 and Indicatia v4.1.8-forge (and dependencies)

### ISSUE THREAD

**Issue by PokeMaserJ** [TeamJM/journeymap#362]
#### JourneyMap Version:
journeymap-1.16.5-5.8.0beta3.jar
`Example: 1.12.1-5.5.0`

#### Forge Version:
36.2.19
`Example: 1.12.1-14.22.1.2478`

#### Describe the problem in repeatable steps:

1. Installed Journey Map 5.8.0 beta 3 and Indicatia v4.1.8-forge (needs SteveKunG's-Lib-mc1.16.5-v4.1.6-forge.jar and architectury-1.25.36-forge.jar
2. Game doesn't load, exits with no crash log
3.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
Oddly I don't have any logs under the journeymap folder, but  I do have the regular Minecraft Log 
https://gist.github.com/PokeMaserJ/68e89b156c38691a23a11d4ad56e2789

https://github.com/SteveKunG/Indicatia/issues/41

**Comment by mysticdrew** [comment]
fixed for beta 4, will close when i publish it

**Comment by mysticdrew** [comment]
Fixed in beta4, should be on curseforge shortly.
