### ISSUE TITLE
[1.18] minecolonies colonists issue.

### ISSUE THREAD

**Issue by drakosoldier298** [TeamJM/journeymap#365]
#### JourneyMap Version:

`Example: 1.12.1-5.5.0`

#### Forge Version:

`1.18 39.0.3`

issue description.
minecolonies colonists are in front of me yet appear to be 20 blocks away on the minimap.

#### Describe the problem in repeatable steps:

1.use minecolonies
2.watch the minimap and see colonists name sometimes appear in the wrong place

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
Full log from journeymap 
https://gist.github.com/drakosoldier298/572b6c3da8a36f363b4a8594869a14da

images ![image](https://user-images.githubusercontent.com/30358222/146413007-a449ff12-e50a-4e70-8520-6118d885af90.png)
![image](https://user-images.githubusercontent.com/30358222/146413039-08c813b3-9598-4bbf-8eeb-4d21fb3748ac.png)

**Comment by drakosoldier298** [comment]
i forgot these apparently forge 39.0.3 
journeymap 1.18-5.8.0alpha9
minecolonies 1.18.1- 1.0.278-RELEASE

**Comment by mysticdrew** [comment]
Ah ha! Ok so, the issue here is that when mob display is set to dots, the labels do not change position based on scale like they do for icons. 
I have this fixed for the next release, I will close it when it is published on curseforge.

**Comment by mysticdrew** [comment]
Fixed in beta4, should be on curseforge shortly.
