### ISSUE TITLE
1.16.5: Incompatible with Nicéphore on Macintosh and Multimc

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [TeamJM/journeymap#366]
#### JourneyMap Version:
journeymap 5.7.3, 5.8.0beta3

#### Forge Version:
forge 36.2.22
Multimc 0.6.14 develop 3020
Macintosh OS Yosemite

#### Mods in Question:
journeymap 5.7.3, 5.8.0beta3
nicéphore 1.16.x 1.5.0

#### Describe the problem in repeatable steps:

1. Create new minecraft client with forge, 1.16.5
2. add journeymap, nicephore
3. launch
4.  30 minutes pass, no movement past final completion

https://paste.ee/p/wRvFR

Hangs up at final completion as Journeymap is loading the theme palette, and as such does not function. By themselves, the mods work. 

I've spent about three hours trying to launch Smashing Mods Together 1.2.1 that features both mods and after a LOT of restarts, pulling and readding mods, I've narrowed the issue down to the interaction between these two mods. 

also reported on Nicephore:
https://github.com/LotuxPunk/Nicephore/issues/17#issue-1082921530

**Comment by LotuxPunk** [comment]
Hey ! This seems to be something wrong on my side, for the screenshot clipboard feature I need to set the java.awt.headless to false, and it appear to not works on macOS' Java implementation.

It'll be fixed soon.

**Comment by mysticdrew** [comment]
> 

Thanks for the update! Closing
