### ISSUE TITLE
When ever I use the wand tool to fill in the blank areas it causes my game to freezish.

### ISSUE THREAD

**Issue by PliskintheSaltyFork** [TeamJM/journeymap#368]
#### JourneyMap Version:

Version: 5.8.0beta4

#### Forge Version:

Version: 39.0.8

#### Describe the problem in repeatable steps:

1. After using the tool to reload or fill in blank areas that have been generated it freezes the mobs.
2. However, I'm still able to move around and load old chunks within the nearby area but I am unable to generate any new chunks

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

Sadly, I might have lost the logs for this.  If I happen to run into this again I'll post that log if there is anything useful in it.

**Comment by mysticdrew** [comment]
You might need to come into discord, this sounds like a mod interaction issue.

**Comment by mysticdrew** [comment]
I did some testing and I am unable to replicate this issue. At a minimum I am going to need logs when you experience this issue.

**Comment by mysticdrew** [comment]
This is stale, closing until logs are provided.
