### ISSUE TITLE
[Feature Request]: Add Option to disable strike-through of disabled Waypoints

### ISSUE THREAD

**Issue by ACH1980** [TeamJM/journeymap#369]
Hey, I'd like to have an feature to disable the strike-through of the disabled Waypoints in the options. I use them pretty much for almost everything and often only for teleportation and when displayed on the map I mostly choose a few of them, but it's hard to find specific waypoints with the strike-through. I mean it should still get colored in  grey when disabled so it's possible to see (if you not use grey for your waypoints itself obviously), just not strike-through in the list.

**Comment by mysticdrew** [comment]
![image](https://user-images.githubusercontent.com/5459941/152658124-8bb6d409-2c6f-4749-93ac-e275951e1fcd.png)
This will be in 5.8.0 beta13 when released

**Comment by mysticdrew** [comment]
Beta13 will be on curseforge shortly
