### ISSUE TITLE
[1.12] Mod compatibility programming question - Is there a way to mark Npcs as hostile?

### ISSUE THREAD

**Issue by P3pp3rF1y** [TeamJM/journeymap#37]
I was fixing Ancient Warfare 2 Npcs visibility on JourneyMap and have marked them with INpc interface. However there doesn't seem to be a way to have JourneyMap display different colors if these are hostile vs not. I am syncing attack target to client so that JourneyMap can mark these as hostile in its DTOs, but it only seems to care about this flag for non Npcs and will use default green color for all Npcs.

Is this a bug or am I missing something?

**Comment by mysticdrew** [comment]
IMob interface works for hostile creatures.

**Comment by P3pp3rF1y** [comment]
Well that's true but my Npcs are a little more complicated. Player can create/hire their own NPCs which are friendly to them. The ones that naturally spawn are hostile to the player if they are soldier like entities, but they can also be friendly if player has good standing with their faction. 

So I definitely cannot use simple interface to identify hostile vs friendly, there needs to be a bit more dynamic stuff going on in this case where a non hostile entity gets marked as hostile if it actually starts being hostile to the player.

**Comment by mysticdrew** [comment]
IMob.class is always considere hostile never passive. 
EntityVillager.class, INpc.class is considered hostile if its attack target is the player, can be passive or not passive. 
EntityAnimal.class, EntityGolem.class, EntityWaterMob.class is considered hostile if its attack target is the player, can be passive or not passive. 

An entity is not passive when entity.getAttackTarget() returns an EntityPlayer.class or IEntityOwnable.class. 

Another option is to use the API to display them on the map how you want them displayed. 

In the future maybe the API can have an interface for custom entities for other mods, so they can display them how they want.

**Comment by P3pp3rF1y** [comment]
This is exactly how I have it implemented (INpc with attackTarget being set) and both hostile and npc flags get set properly.
However because of this logic in EntityDTO the hostile check part is skipped and they always get marked with green color per what villagers are marked with whether they're hostile or not.
```
        } else if(this.profession == null && !this.npc) {
            if(hostile) {
                this.color = coreProperties.getColor(coreProperties.colorHostile);
            } else {
                this.color = coreProperties.getColor(coreProperties.colorPassive);
            }
        } else {
            this.color = coreProperties.getColor(coreProperties.colorVillager);
        }
```

**Comment by mysticdrew** [comment]
@P3pp3rF1y is this still an ongoing issue? If you want we can work on getting this addressed, come into our discord and we can work on getting a solution.

**Comment by mysticdrew** [comment]
@P3pp3rF1y for 1.14.4-1.15.2 I have a planned solution for this, if you would like to discuss it further please come into our discord so I can work with you to get it working on your end.

**Comment by mysticdrew** [comment]
Closing until @P3pp3rF1y responds
