### ISSUE TITLE
Requested Feature: Underground player visibility settings

### ISSUE THREAD

**Issue by TinyDeskEngineer06** [TeamJM/journeymap#370]
I'm running a private modded server with Journeymap, and I'd really like a setting for not showing players that are underground or indoors, whatever conditions that trigger the underground map view, because while I do have expanded radar set to only show for operators, it's still quite easy to find where players have bases they would like for nobody who is especially TNT-happy to find if you just wander around and happen to come close to it while the base owner is themselves there. It would also make _getting_ to bases undetected much easier by just swimming there, as that would also trigger this.

**Comment by mysticdrew** [comment]
Added for beta10 when released on curseforge.

**Comment by mysticdrew** [comment]
A bit of clarification on the implementation of this.
This will only work with expanded radar enabled. There is an option to everyone can see anyone underground, or ops can see anyone underground, or no one can see anyone underground. 

In the future, (hoping by release of 5.8.0) I am adding a multiplayer settings so users can save specific server values about themselves, one of the options will be "Hide me while underground" so only ops will be able to see them underground, unless this setting is set to none.
