### ISSUE TITLE
You can see Invisible people on the map

### ISSUE THREAD

**Issue by Ch1216** [TeamJM/journeymap#372]
#### JourneyMap Version:

`1.18.1-5.8.0beta5`

#### Forge Version:

`1.18.1-39.0.10`

#### Describe the problem in repeatable steps:

1.Be in a server
2.Have another player in said server
3.Have 1 of the player drink an invisibility potion
4.Notice how any other player can see the invisible player in the Map

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

None

**Comment by Ch1216** [comment]
Did I do something wrong?, it doesn't have any labels

**Comment by mysticdrew** [comment]
> 



> Did I do something wrong?, it doesn't have any labels

nope, just didn't get to it yet! 

this will be fixed in beta 10. Thanks for the report.
