### ISSUE TITLE
[1.16.5] Journeymap overwrites custom keybind.

### ISSUE THREAD

**Issue by HootlingMC** [TeamJM/journeymap#375]
#### JourneyMap Version:

journeymap-1.16.5-5.8.0beta8.jar

#### Forge Version:

36.2.20

#### Describe the problem in repeatable steps:

Updated Journeymap from beta7jar to beta8jar.   Doing so reverted my custom keybind for fullscreen map back to the default (J).   Changed it back to my custom keybind (M).  Each time client is restarted, keybind reverts back to J. 

If I roll back to beta7jar, the custom keybind sticks.

**Comment by mysticdrew** [comment]
That's no good, thanks for the report. Looking into it.

**Comment by mysticdrew** [comment]
Found the issue, it will be resolved in beta9

**Comment by Gbergz** [comment]
Coming from the issue linked above, using the mod DefaultOptions and shipping changed keybinds, "Create Waypoint" to P for example, reverts it to stock Keybindings. (B).

**Comment by mysticdrew** [comment]
Fixed in beta 9 on curseforge now

**Comment by mysticdrew** [comment]
> 

Your issues is not related to this issue. Create a new issue.

**Comment by mysticdrew** [comment]
> Coming from the issue linked above, using the mod DefaultOptions and shipping changed keybinds, "Create Waypoint" to P for example, reverts it to stock Keybindings. (B) When installing a new instance.

Your issues is not related to this issue. Create a new issue.
