### ISSUE TITLE
[Feature Request] Add a configurable limit to the amount of chunks JourneyMap tries to render out

### ISSUE THREAD

**Issue by DannyLeWasTaken** [TeamJM/journeymap#376]
# Describe the problem in repeatable steps:

1. Players in my server have different view distances due to PC specs
2. There is currently an unfair advantage towards higher end PC players because JourneyMap can map out further to higher view distances.

## Examples of this problem
- Players with high render distances can more easily travel as JourneyMap renders out places that wouldn't have been seen by the player either it being too far or hidden behind a block
- Mountains aren't really much of an issue to scout out as high-render distance players only need to just travel around a mountain to completely render it out in JourneyMap

3. A server sided implemented hard limit using server config is not suitable as it would sacrifice view distances

# My proposal
We add a new configuration option onto the server admin that allows us to set a hard limit on how far out Journey Map can render.

**Comment by mysticdrew** [comment]
added in 5.8.0 beta 10 when it is on curseforge. I will close this when it is published.
