### ISSUE TITLE
[1.18.1] Waystone Mod integration issue with API

### ISSUE THREAD

**Issue by Bmedina82** [TeamJM/journeymap#380]
#### JourneyMap Version:

`1.18.1-5.8.0beta9

#### Forge Version:

`1.18.1-forge-39.0.36

#### Describe the problem in repeatable steps:

1. Have Waystone mod downloaded
2. set displayWaystonesOnJourneyMap = true
3. Activate waystone, waypoint not added to JourneyMap

(Same issue as #396 but this time on 1.18.1, previous fix was due to API integration)
(Also submitted to Waystone's issue tracker as #521)

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

none

**Comment by mysticdrew** [comment]
This is not an issue with journeymap, not the same issue as 396. 
Blay has not implemented journeymap integration with waystones for 1.18.1 yet by the looks of it. 
Looks like https://www.curseforge.com/minecraft/mc-mods/journeymap-integration provides support for waystones and jm.
