### ISSUE TITLE
[1.18.1] Webmap Entities Freeze When Approaching Village

### ISSUE THREAD

**Issue by andrewauclair** [TeamJM/journeymap#381]
#### Describe the problem in repeatable steps:

1. Create new world
2. Enable webmap
2. Find village
3. TypeError will happen when entering or exiting the village area. 
Doesn't always happen. But is fairly consistent if I go near the village then far away (to unload the village) and back to the village over and over again to make it happen.
Seems to happen with tracking on and off.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

vue.esm.js?a026:1897 TypeError: Cannot read properties of undefined (reading 'key')
    at sameVnode (vue.esm.js?a026:5828:1)
    at updateChildren (vue.esm.js?a026:6230:1)
    at patchVnode (vue.esm.js?a026:6330:28)
    at VueComponent.patch [as __patch__] (vue.esm.js?a026:6493:1)
    at VueComponent.Vue._update (vue.esm.js?a026:3957:1)
    at VueComponent.updateComponent (vue.esm.js?a026:4075:1)
    at Watcher.get (vue.esm.js?a026:4488:1)
    at Watcher.run (vue.esm.js?a026:4563:1)
    at flushSchedulerQueue (vue.esm.js?a026:4319:1)
    at Array.eval (vue.esm.js?a026:1989:1)

**Comment by mysticdrew** [comment]
Thanks

**Comment by mysticdrew** [comment]
Full error
<html>
<body>
<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(32, 33, 36); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" title="webpack:///./node_modules/vue/dist/vue.esm.js?a026:1897" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">vue.esm.js?a026:1897</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;"><span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">TypeError: Cannot read properties of undefined (reading 'key')
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at sameVnode (<span class="devtools-link" role="link" tabindex="-1" title="webpack:///./node_modules/vue/dist/vue.esm.js?a026:5828" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">vue.esm.js?a026:5828</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at updateChildren (<span class="devtools-link" role="link" tabindex="-1" title="webpack:///./node_modules/vue/dist/vue.esm.js?a026:6230" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">vue.esm.js?a026:6230</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at patchVnode (<span class="devtools-link" role="link" tabindex="-1" title="webpack:///./node_modules/vue/dist/vue.esm.js?a026:6330" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">vue.esm.js?a026:6330</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at VueComponent.patch [as __patch__] (<span class="devtools-link" role="link" tabindex="-1" title="webpack:///./node_modules/vue/dist/vue.esm.js?a026:6493" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">vue.esm.js?a026:6493</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at VueComponent.Vue._update (<span class="devtools-link" role="link" tabindex="-1" title="webpack:///./node_modules/vue/dist/vue.esm.js?a026:3957" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">vue.esm.js?a026:3957</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at VueComponent.updateComponent (<span class="devtools-link" role="link" tabindex="-1" title="webpack:///./node_modules/vue/dist/vue.esm.js?a026:4075" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">vue.esm.js?a026:4075</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Watcher.get (<span class="devtools-link" role="link" tabindex="-1" title="webpack:///./node_modules/vue/dist/vue.esm.js?a026:4488" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">vue.esm.js?a026:4488</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Watcher.run (<span class="devtools-link" role="link" tabindex="-1" title="webpack:///./node_modules/vue/dist/vue.esm.js?a026:4563" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">vue.esm.js?a026:4563</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at flushSchedulerQueue (<span class="devtools-link" role="link" tabindex="-1" title="webpack:///./node_modules/vue/dist/vue.esm.js?a026:4319" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">vue.esm.js?a026:4319</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Array.eval (<span class="devtools-link" role="link" tabindex="-1" title="webpack:///./node_modules/vue/dist/vue.esm.js?a026:1989" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">vue.esm.js?a026:1989</span>)</span></span></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(32, 33, 36); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: consolas, lucida console, courier new, monospace; --source-code-font-size: 12px; --source-code-font-family: consolas, lucida console, courier new, monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size)  !important;">

  | logError | @ | vue.esm.js?a026:1897
-- | -- | -- | --
  | globalHandleError | @ | vue.esm.js?a026:1888
  | handleError | @ | vue.esm.js?a026:1848
  | eval | @ | vue.esm.js?a026:1991
  | flushCallbacks | @ | vue.esm.js?a026:1915
  | Promise.then (async) |   |  
  | timerFunc | @ | vue.esm.js?a026:1942
  | nextTick | @ | vue.esm.js?a026:1999
  | queueWatcher | @ | vue.esm.js?a026:4411
  | update | @ | vue.esm.js?a026:4553
  | notify | @ | vue.esm.js?a026:739
  | reactiveSetter | @ | vue.esm.js?a026:1064
  | setMapMode | @ | journeymap.js?575b:453
  | setDimension | @ | journeymap.js?575b:498
  | _callee$ | @ | journeymap.js?575b:149
  | tryCatch | @ | runtime.js?96cf:65
  | invoke | @ | runtime.js?96cf:303
  | prototype.<computed> | @ | runtime.js?96cf:117
  | journeymap_asyncGeneratorStep | @ | journeymap.js?575b:1
  | _next | @ | journeymap.js?575b:1
  | Promise.then (async) |   |  
  | journeymap_asyncGeneratorStep | @ | journeymap.js?575b:1
  | _next | @ | journeymap.js?575b:1
  | Promise.then (async) |   |  
  | journeymap_asyncGeneratorStep | @ | journeymap.js?575b:1
  | _next | @ | journeymap.js?575b:1
  | eval | @ | journeymap.js?575b:1
  | eval | @ | journeymap.js?575b:1
  | _checkForChanges | @ | journeymap.js?575b:208
  | eval | @ | methods.js?0b0a:38

</span></div>
</body>
</html>

**Comment by mysticdrew** [comment]
This is fixed for the next beta release.

**Comment by mysticdrew** [comment]
fixed in beta11, published to curseforge though not approved at the time of closing this issue
