### ISSUE TITLE
[1.18.1] Game crashes after update

### ISSUE THREAD

**Issue by SlavaOmega** [TeamJM/journeymap#385]
#### JourneyMap Version:

`1.18.1-5.8.0beta11`

#### Forge Version:

`1.18.1-39.0.59`

#### Describe the problem in repeatable steps:

When you try to send the mouse position from the full screen map to the chat, the game crashes.
#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
I didn't see any error here.

[journeymap.log](https://github.com/TeamJM/journeymap/files/7941250/journeymap.log)

Just in case, here is the crash file

[crash-2022-01-26_14.00.42-client.txt](https://github.com/TeamJM/journeymap/files/7941286/crash-2022-01-26_14.00.42-client.txt)

**Comment by mysticdrew** [comment]
This is an incompatibility with how we close the fullscreen map on keypress and JEI. I fixed this the other day for the next release. 
Thanks! Keep an eye out for beta12 in the coming days that will contain this fix.

**Comment by mysticdrew** [comment]
beta12 is now on curseforge
