### ISSUE TITLE
[1.18.1] Custom teleport command input field is limited to 32 characters

### ISSUE THREAD

**Issue by Bunny83** [TeamJM/journeymap#387]
#### JourneyMap Version:

1.18.1-5.8.0beta9

#### Forge Version:

1.18.1-39.0.44

#### Describe the problem in repeatable steps:

Since the tp command does not directly support teleporting into other dimensions, one might want to replace
the teleport command with 

`/execute in {dim} run tp {name} {x} {y} {z}`

This does actually work. However since the inputfield for the teleport command is limited to 32 characters, the
command does not fit into the field. We can manually place the command into the config file and restart MC. This
does work as a workaround but the input field should be fixed

**Comment by mysticdrew** [comment]
Interesting, thanks for reporting this. 
Looks like minecraft textboxes are hard coded at 32 characters but it can be changed.
This will be changed for the next beta release.

**Comment by Bunny83** [comment]
That's great :) Thanks for the quick response. The input field has other issues as well. No cursor movement, no auto-repeat (especially annoying when using backspace to delete the old command). I have the waypoint manager bound to the "M" key. When typing inside the input field and pressing M, the waypoint manager comes up instead. Though those are minor issues. As long as we can simply copy & paste a new command everything is fine ^^.

**Comment by mysticdrew** [comment]
Add all the little things, I'll get them fixed. 

You can add journeymap to your server and the get xdim teleport without the need for a custom command. But, I had no idea you could use the execute command to make it happen in vanilla.

**Comment by mysticdrew** [comment]
Please what do you mean by this?
> No cursor movement

**Comment by mysticdrew** [comment]
You may need to hold it a bit more. It works fine for me. 
> no auto-repeat (especially annoying when using backspace to delete the old command).

Fixed
> When typing inside the input field and pressing M, the waypoint manager comes up instead.

**Comment by mysticdrew** [comment]
Issues resolved for beta 12 when it is released.

**Comment by Bunny83** [comment]
> If you mean you cannot move the cursor in between characters and insert?

Yes, that's what I meant ^^

> You may need to hold it a bit more. It works fine for me.

Well, it does work for character keys, but at least backspace doesn't work ^^. So to clear the whole command field you have to repeatedly press backspace. Usually I clear inputfields by holding shift and pressing "Home" to select all the text and then delete / overwrite it. Though since cursor movement and therefore selection (through the keyboard) didn't work, this wasn't an option either.

I just did a few other tests (still in the old version) and funnily you can select text with the mouse and pressing "del" or "backspace" does delete that part. Though after any input the cursor jumps back to the end of the line. I guess this was probably the root of the problem. Even when placing the cursor (with the mouse) somewhere in the middle, typing a character would place it at the end of the line.

Anyways, great to hear that those issues are fixed. I will try the update when it comes out and when I have some time to play again ^^.

ps: Maybe this should be a new issue, but on the fullscreen map when you pan around fast, it would sometimes detect a double click and wants to create a new waypoint. The double click feature is great, though there should be a max movement threshold between the first and second click. Of course how easy it is to trigger this issue depends on your double click delay ^^

**Comment by mysticdrew** [comment]
beta12 is now on curseforge
