### ISSUE TITLE
Icon gets hidden correctly when outside the circle map, names don't

### ISSUE THREAD

**Issue by JohanniklasLp** [TeamJM/journeymap#388]
#### JourneyMap Version:

1.18.1-5.8.0beta6.

#### Forge Version:

1.18.1-39.0.99

#### Describe the problem in repeatable steps:

1. Be on a multiplayer world with another player (or, if you have names for those enabled, use named mobs with no AI or named Armor Stands)
2. use the round preset for the minimap
3. use one character to get the name of the other as far down and left as possible
4. You can get the name as far as this:
![grafik](https://user-images.githubusercontent.com/57828910/151667657-75b8d49f-9e47-44aa-982a-f469dad5913f.png)

It seems like the round preset uses a square mask for the names, since if you compare it to the square preset:
![grafik](https://user-images.githubusercontent.com/57828910/151668087-723c2b9e-7f41-4e5e-b679-af20a4becfa4.png)
The icon is barely still inside the map (the name label being outside the map here is not a bug according to mystic since the name labels are based on the icon, which is still visible in square preset).

**Comment by mysticdrew** [comment]
Fixed for the next release beta12

**Comment by mysticdrew** [comment]
beta12 is now on curseforge
