### ISSUE TITLE
[1.16.5-1.18.1]: Waypoint Manager Name Column Size

### ISSUE THREAD

**Issue by Nero8Eye** [TeamJM/journeymap#389]
#### JourneyMap Version:

1.18.1-5.8.0beta11

#### Forge Version:

1.18.1-39.0.64

#### Describe the problem in repeatable steps:

1. When the waypoint name is to long, the names overlap the buttons
2. The Column from the name should be dynamic
![unknown](https://user-images.githubusercontent.com/76174994/151828828-a96b8e66-736e-44a8-9274-311c65864890.png)

**Comment by mysticdrew** [comment]
Fixed for next release.

**Comment by Alexlion2308** [comment]
Hello, i searched for fix the collumn size and i found this issues so i reply. It seems to be the same issues ? 
![image](https://github.com/TeamJM/journeymap/assets/12431297/f09f66c5-e64d-42ca-9e34-2da9d4f96b71)
I'm using client side only 
![image](https://github.com/TeamJM/journeymap/assets/12431297/a50c9698-3a4e-4a36-a146-95619f4d423d)
Regards
