### ISSUE TITLE
[1.10.2][1.12.2] Radar icons issue(s?)

### ISSUE THREAD

**Issue by AnrDaemon** [TeamJM/journeymap#39]
#### JourneyMap Version:

5.5.2

#### Forge Version:

1.10.2 - 12.18.3.2511
1.12.2 - 14.23.3.2655

#### Describe the problem in repeatable steps:

1. Have a mod in your pack that spawn custom mobs. (Thaumcraft, GraveStone Extended, etc.)
2. Set minimap to show "Small Icons"
3. No custom mobs are displayed on minimap. At all. Did not fallback to small dots? Scaled to zero size?
4. When minimap is set to show Large Icons instead, the blank direction indicator of custom mobs strongly suggest scaling issue. Its size is about what the size of small icon should have been.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

None.

**Comment by AnrDaemon** [comment]
![dots-icons](https://user-images.githubusercontent.com/6532485/38779292-d007aed0-40ce-11e8-9b04-23560789af42.png)

**Comment by mysticdrew** [comment]
@AnrDaemon please verify if this is still an issue with 5.5.4.

**Comment by mysticdrew** [comment]
Closing, will reopen if still an issue when we get a response.

**Comment by AnrDaemon** [comment]
Sorry, was away from the game.
This is still an issue.
I.e. `Blitz` from `Thermal Expansion` and `Possessed Armor` from `Gravestone - Extended` aren't shown on minimap when it is set to "small icons".

**Comment by mysticdrew** [comment]
Fixed for 5.5.5 release.

**Comment by mysticdrew** [comment]
The small arrow icon was missing.

**Comment by AnrDaemon** [comment]
Seems fixed in 5.5b4, although the arrow icon is really small :)
Thank you!
