### ISSUE TITLE
[1.16.5 - 1.18.1] Overlay title rendering after full screen map is closed

### ISSUE THREAD

**Issue by frank89722** [TeamJM/journeymap#390]
#### JourneyMap Version:

`5.8.0beta12`

#### Forge Version:

1.16.5-36.2.22 & 1.18.1-39.0.59

#### Describe the problem in repeatable steps:

1. Place mouse cursor on an overlay that was created through API and has a custom title (`PolygonOverlay#setTitle`) in the full-screen map 
![image](https://user-images.githubusercontent.com/10683361/152304203-b279d4e8-61e3-4509-babb-8e8e1756b033.png)
2. Close full-screen map
3. Title still rendering after full-screen closed.
![image](https://user-images.githubusercontent.com/10683361/152303957-c45c5b97-9f54-40db-921f-e1fb71c47046.png)

**Comment by mysticdrew** [comment]
Is this new with beta12 or did it also happen in beta11?

**Comment by mysticdrew** [comment]
fixed for next release
