### ISSUE TITLE
[1.16.5] Overlay labels render at the wrong position in 5.8.0beta12

### ISSUE THREAD

**Issue by frank89722** [TeamJM/journeymap#392]
#### JourneyMap Version:

`5.8.0beta12` (didn't happen in beta11)

#### Forge Version:

`1.16.5-36.2.22` (this didn't happen in 1.18 but I'm not sure about 1.17)

#### Describe the problem in repeatable steps:

1. Add some overlay with a label (Overlay#setLabel)
2. Labels got rendered at the wrong position in minimap.

Works in fullscreen map:
![image](https://user-images.githubusercontent.com/10683361/152507652-f4d6b433-e618-493a-a546-1e0674445345.png)

But wrong label position in minimap: 
![image](https://user-images.githubusercontent.com/10683361/152508123-348bc592-93c4-486f-9ff0-e21463a43830.png)

**Comment by mysticdrew** [comment]
Fixed for next beta. 
This same code works correctly in 1.17 and 1.18..

**Comment by mysticdrew** [comment]
Beta13 will be on curseforge shortly
