### ISSUE TITLE
[1.16.5] Chat Waypoints will share all waypoints

### ISSUE THREAD

**Issue by Advtech92** [TeamJM/journeymap#394]
#### JourneyMap Version:

JourneyMap-1.16.5-5.8.0beta13

#### Forge Version:

1.16.5-36.2.21

#### Describe the problem in repeatable steps:

1. Add a new waypoint
2. Click chat to share it
3. All previous waypoints will chat along with the new one

**Comment by mysticdrew** [comment]
Found the issue, will be resolved on next release.. This only effects 1.16.5

**Comment by mysticdrew** [comment]
fix is in beta15 now on curseforge
