### ISSUE TITLE
[1.12.2] Switching key bindings cause client crash (I forgot to add log last time)

### ISSUE THREAD

**Issue by AlexFenix33** [TeamJM/journeymap#396]
JourneyMap Version:

1.12.1-5.7.1`
Forge Version:

1.12.2-14.23.5.2860`

Describe the problem in repeatable steps:

    1.Going to settings
    2.Changing key key bindings
    3.Clients crashes
    4.Can't re-enter MC
    5.Reinstaling everything
    6.Repeat

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
[journeymap.log](https://github.com/TeamJM/journeymap/files/8049278/journeymap.log)

**Comment by mysticdrew** [comment]
Next time, just edit and reopen your other issue... There is absolutely no reason to open a second issue. 

This looks like an issue with your installation.

**Comment by AlexFenix33** [comment]
Well, i downloaded your mod right from CurseForge. So i do not know what can be the issue

**Comment by AlexFenix33** [comment]
> Next time, just edit and reopen your other issue... There is absolutely no reason to open a second issue.
> 
> This looks like an issue with your installation.

Well, i downloaded your mod right from CurseForge. 
So i do not know what can be the issue.

**Comment by mysticdrew** [comment]
remove journeymap-api from your mods folder, it is not a mod
