### ISSUE TITLE
[1.16.5]Lags in a certain area, and extensive use of RAM

### ISSUE THREAD

**Issue by DoctorSigma** [TeamJM/journeymap#398]
#### JourneyMap Version:
1.16.5-5.8.0beta15

#### Forge Version:
1.16.5 - 36.2.21

#### Describe the problem in repeatable steps:
We play with a friend together with the MineColonies mod. Our base is located next to the created city of the same fashion. When I approach my city and when I go down to the caves below it, I have a lot of lag, and the RAM is absorbed very quickly, even if I allocate 14 GB, they will all fill up in about 10 seconds, then cleaned up to 8-9 GB and recruited again. Lays only in the area around the city. However, when I removed the mod MineColonies lags remained, I don't know why. When I press F3, the bottom left shows how long an action takes in your fashion, there on the base I often see values ​​above 4000 ms and sometimes 5000 (as shown in  screenshots).
I run minecraft with the following parameters: "- Xms3G -Xmx14G -XX: + UseConcMarkSweepGC".

1.Create a city from MineColonies mods (after removing this mod didn't work, I'm not sure that's one of the reasons, but it only lags in the city from this mod.)
2.Press F3 and watch how it lags and the memory gets clogged

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
journeymap.log - https://gist.github.com/f0db57d135c645610b12b4b9e50cd717.git
latest.log - https://gist.github.com/47d402b554f9080ee17195d8cd463e86.git
debug.log - https://gist.github.com/0ab9665fe0bf7b558187072bb1c9b2c7.git
I also created a profile using the spark mode, if necessary to identify the problem: https://spark.lucko.me/3awKgFQI3w

Screenshots:
![image](https://user-images.githubusercontent.com/93322905/154317487-f0fa337e-4538-440d-823b-c5e2b94d2935.png)
![image](https://user-images.githubusercontent.com/93322905/154317595-2e8d5e90-0c25-4340-ae9f-6c22a64e1dea.png)

**Comment by mysticdrew** [comment]
Couple things. 
The bottom numbers do not have anything to do with memory usage. Not really anything for you to worry about at this time. 
That spark report is not helpful at all since it is a server report. use `/sparkc` for client. 

If you remove journeymap is the memory usage fine?

**Comment by mysticdrew** [comment]
Also, only give minecraft 8gigs of memory and report back with a client spark report.

**Comment by DoctorSigma** [comment]
1)The latest version of Spark is the one I use for forge and version 1.16.5.
2)I didn't have enough 8 GB, so I increased it to 12. Also, when JourneyMap is installed, I need 6-7 GB for a comfortable game outside the lag zone, and in the lag zone I lacked 14, and at first I had 8, which was not enough. I increased by 1 each time, and reached 14 where I can at least move.
3)I did not say what I think these figures say about the use of memory. I think this is the CPU time that was used to display the card or read it.
4)I didn't know about / sparkc, so I used this command: https://spark.lucko.me/svycmiLPnO (Although a lot is written here about lycaniteMobs, I deleted it separately and together with Minecolonies, it is not very burdensome when there is no map. Maybe JourneyMap is in conflict with him)
5)Well, when JourneyMap was installed and when I was NOT in the lag zone, the memory ate 7-8 GB, in the lag zone up to 14 and above. And when I deleted the map, it was 3-4 GB. However, I like this mod, so I'm waiting for an answer ...
6)And another question: everyone says not to give more than 8 GB, but why, and what to do if it is not enough?

**Comment by mysticdrew** [comment]
Ok so one issue here I see is you have debug logging enabled. That can slow things down signficantly. I think Lycanite enables it somehow. 

So lets try a couple scenarios here.
First:
Press J, then press O, go to advanced and set log level to INFO. 
See how that performs.

Second: 
After you test turning off debug logging, if performance is still not great. Remove only LycaniteMobs, your cpu is spending a lot of time on those mobs, which I can almost guarantee that is contributing.

**Comment by mysticdrew** [comment]
Also, for both of those scenarios get me a sparkc report and the journeymap.log

**Comment by DoctorSigma** [comment]
1) Log level already installed on INFO. Therefore, nothing has changed in this step.
https://spark.lucko.me/1DpqCmmWGP
journeymap.log - https://gist.github.com/8004e1f782e48d045da1418b3384b6aa.git

2)It seems to have gotten a little better. But due to lag spikes I can't estimate how much better. I have a hang with a frequency of 1-2 seconds, sometimes longer, but the interval is not the same ....
https://spark.lucko.me/FzWqLKmRpt
journeymap.log - https://gist.github.com/79eb34e02928354b7820a402701180d4.git

**Comment by mysticdrew** [comment]
Next test. 
Press J, Press O, click on Advanced, Then uncheck "Chunk Cache" and see if that resolves it.

**Comment by DoctorSigma** [comment]
Ooooh, it helped, and now the memory is not 9 but 5 needs and does not lag. Just in case here is a sparkc log: https://spark.lucko.me/CQGpOYf4H2
journeymap.log - https://gist.github.com/3b6958e741d46047bd49a4ae68468031.git

**Comment by DoctorSigma** [comment]
Well, if you go out into the world, after coming out in this area, you need not 4 but 6 GB of RAM. A little weird
