### ISSUE TITLE
Compatability with the mod HuD Compass.

### ISSUE THREAD

**Issue by Romoslayer** [TeamJM/journeymap#399]
Not really a bug but if possible could you work with the author of the mod HuD Compass to create compatibility with Journey Maps waypoints and HuD Compass.

**Comment by mysticdrew** [comment]
> Not really a bug but if possible could you work with the author of the mod HuD Compass to create compatibility with Journey Maps waypoints and HuD Compass.

Never heard of it, provide a link and create an issue on their issue tracker with a link to this issue please.

**Comment by Romoslayer** [comment]
Curse Forge Mod Page
https://www.curseforge.com/minecraft/mc-mods/hud-compass
Issue Tracker
https://github.com/gigaherz/HudCompass/issues/10

**Comment by mysticdrew** [comment]
5.8.0beta17 I have added the requested features.
