### ISSUE TITLE
[1.12.2] Dimension scrollbar doen't work

### ISSUE THREAD

**Issue by wasweb** [TeamJM/journeymap#4]
#### JourneyMap Version:

1.12.2-5.5.2

#### Forge Version:

1.12.2-14.23.0.2531

#### Describe the problem:

When trying to create a new waypoint or editing an existing one, the list to select in which dimension it should show up doesn't scroll. At the bottom of 'Manage Waypoints' I can click through the avaliable dimensions and there are indeed more that don't appear in the aforementioned list.
Sidenote: The scrollbar's lenght seems to change according to the number of avaliable dimensions.

**Comment by techbrew-mc** [comment]
Fixed in 5.6.0b1

**Comment by Laike-Endaril** [comment]
I almost opened a new issue for this; nice that they have the auto-search when typing the issue topic.  Had looked through all open issues, but had not considered that it may be fixed in a not-yet-released version.
