### ISSUE TITLE
[1.18] Pressing certain keys causes GL errors

### ISSUE THREAD

**Issue by XFactHD** [TeamJM/journeymap#400]
Pressing special keys like media keys (play/pause, stop, prev, next, volume up, volume down) on the keyboard causes a GL error message to be logged:
```
[Render thread/ERROR]: ########## GL ERROR ##########
[Render thread/ERROR]: @ Render
[Render thread/ERROR]: 65539: Invalid key -1
[Render thread/ERROR]: ########## GL ERROR ##########
[Render thread/ERROR]: @ Render
[Render thread/ERROR]: 65539: Invalid key -1
```
Media keys (and most likely a few others as well) cause the `InputEvent.KeyInputEvent` to fire with `-1` as key code because they are "special" keys.
Your event handler for `InputEvent.KeyInputEvent` does not check if the key code is valid and passes the possibly invalid key code directly to `InputConstants.isKeyDown()` which in turn calls a GLFW method which then "throws" the aforementioned error in native code. Vanilla handles this edge case in `InputConstants.getKey()`.
The error is logged twice because the event fires for press and release.
Your event handler for `ScreenEvent.KeyboardKeyPressedEvent.Post` is most likely affected by this as well.

The fact that I am using Windows may have an impact here, I don't know how Linux handles the media keys.

#### JourneyMap Version:

1.18.1-5.8.0beta15

#### Forge Version:

1.18.1-39.0.66

#### Describe the problem in repeatable steps:

1. Press a media key on the keyboard
2. Observe log message

**Comment by mysticdrew** [comment]
Well, that is interesting, thanks! I will get it addressed

**Comment by mysticdrew** [comment]
Fixed for beta16

**Comment by mysticdrew** [comment]
beta16 will be available shortly on curseforge

**Comment by XFactHD** [comment]
Tested and works as expected now, thanks

**Comment by ItsTeraBytes** [comment]
The bug has reappeared with the same error message. Playing on 1.20.4 Fabric with only Fabric API and Journey map mods. Version 1.20.4-5.9.21
