### ISSUE TITLE
The Display Issue about Other Players' Name showed on MiniMap

### ISSUE THREAD

**Issue by NightSharp** [TeamJM/journeymap#401]
#### Instructions for Submitting an Issue
1. Ask for help on Discord (https://discord.gg/eP8gE69) #support if you're unsure this is a new issue.
2. Please search for existing issues before submitting a new one.
3. Please add the correct MC<version> label to your issue. Example: "[1.12.2] Waypoints are upside down"
4. Completely fill out the template below. Failure to do so is likely to get the issue closed immediately.
5. Prove you read these instructions by deleting this section before submitting. ;)
---
  
#### JourneyMap Version:

`1.18.1-5.8.0beta15`

#### Forge Version:

`1.18.1-39.0.79`

#### Describe the problem in repeatable steps:

Other players' name in minimap suddenly turn into partly missing like this
It displays as "█████者" instead of "帝国的制造者" which it should be displayed.
![2022-02-15_01 38 55](https://user-images.githubusercontent.com/9748063/154785109-26596e37-76e7-451e-a726-082991c4725b.png)

Of course, It behaves normally in fullscreen map

**Comment by mysticdrew** [comment]
I am unable to replicate this issue.

**Comment by NightSharp** [comment]
> I am unable to replicate this issue.

Actually, I'm not so sure about what caused this. because it appeares very casually. Maybe caused by Memory problems. Now I will close this issue temporarily. When I find out how to replicate this stably, I'll reopen this again. Thanks~
