### ISSUE TITLE
[1.18.1] Mana & Artifice double mana bar issue

### ISSUE THREAD

**Issue by PokeMaserJ** [TeamJM/journeymap#402]
#### JourneyMap Version:
journeymap-1.18.1-5.8.0beta15.jar

#### Forge Version:
39.0.78

#### Describe the problem in repeatable steps:

1. Have journeymap-1.18.1-5.8.0beta15.jar and Mana & Artifice1.7.0.5 installed (with dependencies) 
2. Obtain Codex Arcane from Mana & Artifice
3. Notice you have two mana bars. (should have one)

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

![2022-02-21_17 35 12](https://user-images.githubusercontent.com/11018346/155039539-5d92f92f-54c7-4906-b626-a117123f52e4.png)

https://github.com/Mithion/Mana-And-Artifice/issues/448

**Comment by mysticdrew** [comment]
Closing as unfixable on my end, I made a comment on the other issue.
