### ISSUE TITLE
[1.18.1] JourneyMap + Waystones error?

### ISSUE THREAD

**Issue by CDAGaming** [TeamJM/journeymap#403]
#### Waystones Version: 9.0.4

![image](https://user-images.githubusercontent.com/16328918/155470846-60cc9769-cbbf-4713-9972-44b9602c8ff4.png)

**Comment by CDAGaming** [comment]
Note: Journeymap Integration is also installed, but Waystone's integration on there was disabled in order to have JourneyMap's take over

**Comment by mysticdrew** [comment]
Did you create an issue on their issue tracker as well?

**Comment by mysticdrew** [comment]
So this was happening on logging in. 
Very strange issue, for some reason the caching was converting it json object instead of the object. I have resolved it for beta 16

**Comment by mysticdrew** [comment]
beta16 will be available shortly on curseforge
