### ISSUE TITLE
RGB color in waypoint sharing

### ISSUE THREAD

**Issue by ChromaPIE** [TeamJM/journeymap#405]
1.12.2 feature request

Allow players to attach RGB color in the waypoint sharing message so that others can sync the waypoint color. It would be optional so if the parameter is not present it would still suggest a random color.

**Comment by mysticdrew** [comment]
1.12.2 is no longer getting updates

**Comment by mysticdrew** [comment]
Sorry, this is not something I will implement with the current waypoint sharing chat.
