### ISSUE TITLE
[1.12.2] Incompatibility with Better Biome Blend mod

### ISSUE THREAD

**Issue by SomeNameUsername** [TeamJM/journeymap#408]
JourneyMap Version:

1.12.2 - 5.7.1
Forge Version:

1.12.2-14.23.5.2859

Describe the problem in repeatable steps:

1. Install Better Biome Blend mod and JourneyMap mod
2. Explore areas that have water
3. The minimap and fullscreen map show water as white instead of blue

![2022-03-11_01 58 10](https://user-images.githubusercontent.com/96031181/157782440-cb08c203-2365-421e-bac3-1d61245823d3.png)
![2022-03-11_01 58 14](https://user-images.githubusercontent.com/96031181/157782450-0196f882-3ee1-4adb-a79c-b6df0f145b4d.png)

**Comment by mysticdrew** [comment]
Looks like you may need to contact them as 1.12.2 journeymap versions are no longer updated
