### ISSUE TITLE
[1.18.2] getWaypoints(modId) and getWaypoint(modId, id) API issues

### ISSUE THREAD

**Issue by blay09** [TeamJM/journeymap#409]
#### JourneyMap Version:

`1.18.2-5.8.0beta17`

#### Forge Version:

`40.0.12`

#### Describe the problem in repeatable steps:

Kind of more of an infodump with the issues I came across trying to use the new API methods.

Waystones code: https://github.com/ModdingForBlockheads/Waystones/blob/feat/journeymap-compat/forge/src/main/java/net/blay09/mods/waystones/compat/JourneyMapAddon.java

Issues: 
- Changing the color of a waypoint and rejoining seemed to reset its ID. `Waystone I` was originally given a UUID when it was created by Waystones, but it changed to `Waystone-I_-13-68-27` after changing its color in the JourneyMap UI and rejoining the world
  - actually, the ID is only different in the result of `getAllWaypoints()`. When I reproduced this later and checked `getWaypoints(modid)`, it had the correct ID in there
- This probably won't affect me, but I got a bit confused by it: waypoints returned by `getAllWaypoints()` have a modid prefix added to their id (see screenshot above), whereas waypoints returned by `getWaypoints(modid)` do not have that prefix
- `getWaypoints(modId)` and `getWaypoint(modId, id)` return an empty list / null even when I'm using the exact modid and id (with or without prefix) seen in the result of `getAllWaypoints()`:
  - this seems to only occur (sometimes) for waypoints that were loaded from the save, if I add a waypoint using `api.show()` it will correctly show up in those methods until I restart (while the earlier ones still won't)
  - Is there something I can listen on to know when JourneyMap has finished loading? Wondering if timing may play a role since I couldn't always reliably reproduce things. I don't think that's the only issue though since I've had waypoints not be available in `getWaypoints(modid)` long after world load too

![image](https://user-images.githubusercontent.com/1933180/157989291-73934e7b-f6c1-4947-95ee-cde2524c1d67.png)
![image](https://user-images.githubusercontent.com/1933180/157990534-17776031-cade-4493-926f-d21472acd3d4.png)

**Comment by mysticdrew** [comment]
Alright, so I think everything here is addressed. 
I will DM you a test build on discord.

**Comment by blay09** [comment]
One more thing: it seems the color field in waypoints returned through the accessors is always `null` (though the color in the icon field is correct).

Other than that, I've got it working with no issues now I think.

**Comment by mysticdrew** [comment]
> One more thing: it seems the color field in waypoints returned through the accessors is always `null` (though the color in the icon field is correct).

yes, I noticed that and in fact I fixed it about 10 minutes ago :)

Perfect, thanks a lot blay!

**Comment by mysticdrew** [comment]
updates are in beta18 on curseforge when every they approve it.
