### ISSUE TITLE
[Feature Request] Show regions

### ISSUE THREAD

**Issue by ViciousVinnyD** [TeamJM/journeymap#41]
When auto-mapping I noticed journeymap shows and labels regions. It would be nice if there was an option to enable this permanently as it would make locating and pruning unused/corrupted server regions easier.

**Comment by Kibonik** [comment]
++

**Comment by mysticdrew** [comment]
@ViciousVinnyD where do you think a good spot for this data to be shown?

**Comment by ViciousVinnyD** [comment]
Idk, maybe next to the chunk grid button. It's not too important, I just want the feature to exist.

**Comment by mysticdrew** [comment]
I am not going to make this an overlay like the grid renderer yet. I will display region coords for now in the InfoSlot under the minimap and when you move the mouse on the full screen map. But it only goes so far, if the chunk is not loaded we have no idea what the region coords are.

**Comment by mysticdrew** [comment]
Region InfoSlot and Showing region where your mouse is on the full screen map will be in JM 5.5.5 release. 
I am going to leave this ticket open for now as we may add a region grid. Though it could be easily done via a plugin.

**Comment by mysticdrew** [comment]
OK well.. I feel like a dummy. I didn't realize it highlighted the regions as an overlay when you automap. When you said it shows, I thought you meant it outputs region coords as text. My bad, I did not implement that feature, nor have I ever used it. I always have automapped from the webmap.

**Comment by ViciousVinnyD** [comment]
Ah, yeah I was simply asking for a way to keep the automap region overlay thing active so I can locate regions.

**Comment by mysticdrew** [comment]
So, the region overlay is quite buggy.. I will continue to work on it when I have time. 
For now, there are two new grid options via the grid editor. Chunk and Region grid and Region grid. 

![](http://puu.sh/Da2MT/f5539e50bc.png)
![](http://puu.sh/Da2NA/c2bb7f9240.png)
