### ISSUE TITLE
[1.18.1] Waypoint OpenGL error 1282

### ISSUE THREAD

**Issue by leviathan13** [TeamJM/journeymap#411]
#### JourneyMap Version:

1.18.1-5.8.0

#### Forge Version:

forge-1.18.1-39.1.2
[journeymap.log](https://github.com/TeamJM/journeymap/files/8341577/journeymap.log)

#### Describe the problem in repeatable steps:

I deleted a waypoint and than recreate it near the same position. I was spammed with OpenGL errors 1282 and the waypoint wasn't created. I also have installed OptiFine, JourneyMap Integration and Waystones, though I do not know if they are involved, at least the errors seems to be logged by JourneyMap. Notably, this error happened while creating a normal waypoint in JM and I was able to create other waypoints before.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

[journeymap.log](https://github.com/TeamJM/journeymap/files/8341580/journeymap.log)

[latest.log](https://github.com/TeamJM/journeymap/files/8341610/latest.log)

**Comment by mysticdrew** [comment]
Are you able to consistently reproduce this when exiting the game and starting it back up?

**Comment by leviathan13** [comment]
I created a new world and spammed new waypoints, and while the waypoints themselves were created, I was constantly getting 1282 errors in the chat. I do not understand the triggering conditions, unfortunately. I'll attach the new logs.

[journeymap.log](https://github.com/TeamJM/journeymap/files/8341939/journeymap.log)

[latest.log](https://github.com/TeamJM/journeymap/files/8341942/latest.log)

**Comment by mysticdrew** [comment]
Can you try without optifine? This is likely an optifine issue as they break all kinds of rendering things internal to mc.

**Comment by leviathan13** [comment]
I tried creating new waypoints without OptiFine and I did not get the errors during my short test.

**Comment by mysticdrew** [comment]
I think this is related to optifine. 1.18.1 is EOL now since 1.18.2 has taken precedence. Feel free to create another issue if this happens in 1.18.2
