### ISSUE TITLE
[1.18.2 Fabric] Journeymap doesn't work with Optifabric

### ISSUE THREAD

**Issue by PolyLogic64** [TeamJM/journeymap#413]
#### JourneyMap Version:

`journeymap-1.18.2-5.8.1beta2-fabric`

#### Fabric Version:

`fabric-loader-0.13.3-1.18.2`

#### Describe the problem in repeatable steps:

1. Install optifabric (optifabric-1.13.0) along with its dependency fabric-api (fabric-api-0.48.0+1.18.2) and Optifine (OptiFine_1.18.2_HD_U_H6)
2. Install journeymap-1.18.2-5.8.1beta2-fabric
3. Launch Minecraft

The Minecraft Launcher just throws an Exit Code: 1.

**Comment by PolyLogic64** [comment]
No the last line in the logs is
`[15:46:50] [Render thread/INFO] [ColorManager] Updated color palette for 829 blockstates in 813ms: C:\Users\Tim\AppData\Roaming\.minecraft\journeymap\colorpalette.json`

**Comment by mysticdrew** [comment]
you should probably bring this issue up to the Optifabric team as well.

**Comment by PolyLogic64** [comment]
Alright

**Comment by PolyLogic64** [comment]
Done
