### ISSUE TITLE
[1.18.2 Fabric] Crashing when Journeymap is enabled.

### ISSUE THREAD

**Issue by Razatop** [TeamJM/journeymap#414]
#### JourneyMap Version:

journeymap-1.18.2-5.8.1beta2-fabric.jar

#### Fabric Version:

Fabric - 0.13.3 / fabric-api-0.48.0+1.18.2

#### Describe the problem in repeatable steps:

1. Enable Journey map
2. Get an Error spit out at you, at first it was Expandable storage, after disabling that it was bclib
3. Profit? I mean uh, repeat.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

Doesn't get updated because game doesn't boot.

#### Error log!!
[crash-2022-04-01_11.03.57-client.txt](https://github.com/TeamJM/journeymap/files/8399310/crash-2022-04-01_11.03.57-client.txt)

**Comment by mysticdrew** [comment]
the issue looks to be with konkrete what ever that is. 
konkrete.mixins.events.client.json:MixinGameRenderer

**Comment by Razatop** [comment]
Peculiar, as it was pointing to tonnes of other mods only when journeymap was enabled. I'll guess I'll throw this there too.

**Comment by Razatop** [comment]
>Anything can break anything.

Alright, well even with my being wrong. I'll drop it over there. Thanks for the insight.

**Comment by mysticdrew** [comment]
This fix will be in 5.8.1 beta 3 and you will need an updated konkrete
https://www.curseforge.com/minecraft/mc-mods/konkrete-fabric/files/3732395
