### ISSUE TITLE
[1.18.2] Opacity sliders are not working correctly.

### ISSUE THREAD

**Issue by codebam** [TeamJM/journeymap#415]
#### JourneyMap Version:

`journeymap-1.18.2-5.8.1beta2-fabric.jar`

#### Paper Version:

`0.13.3`

#### Describe the problem in repeatable steps:

1. Enable any of the opacity settings in JourneyMap
2. Look at the map

**Comment by mysticdrew** [comment]
It is that way in forge too. Thanks!

**Comment by mysticdrew** [comment]
Looks like the only one that is broken is the map opacity settings. 
I found the problem and it is fixed for the next beta release. (1.18.1 forge and 1.18.2 forge and fabric) not an issue in 1.16.5
