### ISSUE TITLE
Journeymap keybind for waypoint manager does not work

### ISSUE THREAD

**Issue by TronWoWGamer** [TeamJM/journeymap#416]
#### JourneyMap Version:

Journeymap 1.18.2-5.8.1beta2 (from All The Mods 7)

#### Forge Version:

Forge - 40.0.34

#### Describe the problem in repeatable steps:

1. Set keybind for waypoint manager with no conflicts to other mod keybinds (tried, k, u, +)
2. press keybind on keyboard
3. nothing happens, waypoint manager does not come up.  still can access from fullscreen map

**Comment by mysticdrew** [comment]
So there is a bug that is already fixed for the next beta release. 
The default keybind for the waypoint manager is ctrl+b, changing the keybind only replaces the key. So if you set it to k, you will need to press ctrl+k for it to work. Again, this is fixed and should have normal keys in beta3.
