### ISSUE TITLE
[1.18.2 fabric] crash with konkrete

### ISSUE THREAD

**Issue by IZeeXeS** [TeamJM/journeymap#417]
#### JourneyMap Version:

` journeymap-1.18.2-5.8.1beta2-fabric`

#### fabric version:

`Fabric Loader 0.13.3` + `fabric-api-0.48.0+1.18.2`

#### Describe the problem in repeatable steps:

1. install `Konkrete [Fabric] v1.3.3 MC 1.18-1.18.2` + `fabric-api-0.48.0+1.18.2` +` journeymap-1.18.2-5.8.1beta2-fabric`
2. launch game

#### Relevant errors from `.minecraft/journeymap/journeymap.log`: doesn't generate this folder so i add crash report 

>> ---- Minecraft Crash Report ----
>> // Oh - I know what I did wrong!
>> 
>> Time: 02.04.2022, 20:20
>> Description: Initializing game
>> 
>> java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'fabric-renderer-indigo'!
>> 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
>> 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
>> 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
>> 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
>> 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
>> 	at net.minecraft.class_310.<init>(class_310.java:452)
>> 	at net.minecraft.client.main.Main.main(Main.java:197)
>> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
>> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
>> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
>> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
>> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
>> Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_757 failed
>> 	at net.minecraft.class_4668.<clinit>(class_4668.java:125)
>> 	at net.fabricmc.fabric.api.renderer.v1.material.BlendMode.<clinit>(BlendMode.java:33)
>> 	at net.fabricmc.fabric.impl.client.indigo.renderer.RenderMaterialImpl.<clinit>(RenderMaterialImpl.java:34)
>> 	at net.fabricmc.fabric.impl.client.indigo.renderer.IndigoRenderer.materialFinder(IndigoRenderer.java:54)
>> 	at net.fabricmc.fabric.impl.client.indigo.renderer.IndigoRenderer.<clinit>(IndigoRenderer.java:37)
>> 	at net.fabricmc.fabric.impl.client.indigo.Indigo.onInitializeClient(Indigo.java:137)
>> 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
>> 	... 11 more
>> Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_757 failed
>> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
>> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
>> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
>> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
>> 	... 18 more
>> Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
>> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
>> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
>> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
>> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
>> 	... 21 more
>> Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector onRenderCurrentScreen(Lnet/minecraft/class_437;Lnet/minecraft/class_4587;IIF)V in konkrete.mixins.events.client.json:MixinGameRenderer from mod konkrete failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap konkrete.mixins.events.client-refmap.json
>> 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
>> 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385)
>> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
>> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
>> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
>> 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
>> 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
>> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
>> 	... 24 more

**Comment by mysticdrew** [comment]
duplicate #414 
in the future do not copy and paste logs into the issue. Use a pastebin site or attach the file to the issue(preferred)

**Comment by mysticdrew** [comment]
This fix will be in 5.8.1 beta 3 and you will need an updated konkrete
https://www.curseforge.com/minecraft/mc-mods/konkrete-fabric/files/3732395
