### ISSUE TITLE
[Suggestion - 1.18.1] Please add scaling for edge waypoint icons on the minimap

### ISSUE THREAD

**Issue by Zedrimar** [TeamJM/journeymap#424]
I have a 4k monitor so unfortunately, the current scale makes them look absolutely tiny. If that can be added sometime in the future, that would be great! 

Wonderful mod by the way. :)

Example of what I mean:
![image](https://user-images.githubusercontent.com/8153290/163904196-af54d0f8-966a-4de9-9555-07194533609c.png)

**Comment by mysticdrew** [comment]
I will add this for 1.18.2+ and it will be a single slider for all waypoint icons on the map, not just the ones on the edge.

**Comment by mysticdrew** [comment]
This will be in the next 1.18.2 release.
