### ISSUE TITLE
[1.18.2] Journeymap opens when doing keyboard combination

### ISSUE THREAD

**Issue by FuturePr0** [TeamJM/journeymap#427]
#### JourneyMap Version:

1.18.2 - 5.8.1

#### Fabric loader version:

0.13.3

#### Describe the problem in repeatable steps:

1. Do a keyboard combination in-game, e.g f3+ b to show hitboxes
2. It will show hitboxes, but at the same time it will open up the waypoint menu
3. This isn't limited to f3 + b, you can try any keyboard combination that has the same keybinds that Journeymap has and the problem is still there.

**Comment by mysticdrew** [comment]
So this is an issue in all loaders. 
This is resolved and will be included in the next release. 
As for #3 on your list, this cannot be worked around as it seems to be vanilla behavior. Hold down a key and press E while that key is held down.
