### ISSUE TITLE
[Suggestions] [1.18.2+] Option to link values of map-minimap icon scale values

### ISSUE THREAD

**Issue by Emojiime** [TeamJM/journeymap#428]
---
#### JourneyMap Version:
1.18.2-5.8.1-forge

#### Forge Version:
1.18.2-40.0.4

Mysticdrew has suggested this feature be officially requested.

It would be helpful to have an option in the Minimap settings to copy the scale values from the Fullscreen map, eliminating the need to manually edit them to match. As it is now, you would have to remember the exact values that were set on the other screen, or otherwise have to go back to see what they are - which is quite tedious.

**Comment by mysticdrew** [comment]
So thinking about the implementation for this a bit. 

I need to figure out how to do this dynamically since the minimap has many more options than the fullscreen map. I cannot just swap them in place. 

You think that the minimap should use the common settings from the fullscreen map?

**Comment by mysticdrew** [comment]
This is completed for the next major release. I will close when it is released.

**Comment by mysticdrew** [comment]
Cleaning up the issue tracker
Closing as this is completed for JourneyMap v6 when it is released.
