### ISSUE TITLE
Mod blocks /tutorial args

### ISSUE THREAD

**Issue by Nononitas** [TeamJM/journeymap#429]
JourneyMap Version:: 1.182-5.8.0
Forge: 40.0.40

Problem:
With your mod installed it's not possible to execute /tutorial args
Without the mod installed it works perfectly.
![grafik](https://user-images.githubusercontent.com/47149720/164794278-388eedee-b867-4234-bcbe-5a1241a1d47e.png)

Thanks in advance and I hope you can fix the problem :)

**Comment by mysticdrew** [comment]
logs?

**Comment by mysticdrew** [comment]
What mod adds the tutorial command? I have never heard of such a thing, nor is it in vanilla minecraft.

**Comment by mysticdrew** [comment]
> Thanks in advance and I hope you can fix the problem :)

Without more detail, I will not be able to fix it since I have no way to replicate it currently. Let me know as soon as you can how I can replicate this issue.

Provide logs, as required. 

I need the mod that adds this command, or if you are on a public server. Tell me which server. 
Closing as the template was not followed, will reopen when logs are provided.

**Comment by Nononitas** [comment]
This is a server command registered by a bukkit plugin.

```
[22Apr.2022 15:43:35.511] [Render thread/INFO] [journeymap/]: Mapping halted in C:\Users\Tjorven\AppData\Roaming.minecraft\journeymap\data\mp\Minecraft~Server\minecraft:tutorial
[22Apr.2022 15:43:35.512] [JM-task-78/WARN] [journeymap/]: TaskBatch thread interrupted: journeymap.client.task.multi.MapPlayerTask$MapPlayerTaskBatch@5533b175
```

**Comment by Nononitas** [comment]
The world name is also "tutorial" on the server

**Comment by mysticdrew** [comment]
This may be a better discussion in our discord server.

**Comment by Nononitas** [comment]
Yes you can keinsurvival.de

**Comment by Nononitas** [comment]
> This may be a better discussion in our discord server.

Ok I will go there. (didn't found any issue channel beforehand)
