### ISSUE TITLE
Implement mod blocking for Bukkit servers

### ISSUE THREAD

**Issue by DoNotSpamPls** [TeamJM/journeymap#43]
There are currently a lot of ways to block the mod on Forge, but pretty much none on Bukkit. I'd love if a way to contact the mod to block it is implemented (packet listener, plugin messaging, etc.)

**Comment by Weissmoon** [comment]
I believe [this](https://minecraft.curseforge.com/projects/journeymapfixer/files/2586654) is what you are seeking.

**Comment by DoNotSpamPls** [comment]
Why was this closed?

**Comment by mysticdrew** [comment]
Because it is planned, I am ironing things out on the forge side of things before I update the bukkit side of things. I am just cleaning up the github issue tracker.
