### ISSUE TITLE
[Suggestion] Keybinds for fullscreen map

### ISSUE THREAD

**Issue by Rozbiynk** [TeamJM/journeymap#430]
Hello, I would like to suggest do keybinds or presets for fullscreen map. How does it work? Let's say we have two modes for the map. In the first, everything is enabled, and in the second, the display of all entities is disabled. This would be convenient for servers where the display of entities or cave mode is prohibited, because there is an opportunity to do this for a minimap, but not for a fullscreen map.

**Comment by mysticdrew** [comment]
There are buttons to disable entity radar in the fullscreen map. If a server disables entity radar, they do not show up on the fullscreen map. If you don't want to have radar, disable it with the top buttons.
