### ISSUE TITLE
[1.18.2] Overlays stay fixed on screen instead of moving with the map when Follow is pressed

### ISSUE THREAD

**Issue by alejandrocoria** [TeamJM/journeymap#431]
#### JourneyMap Version:

`1.18.2-5.8.2`

#### Forge Version:

`1.18.2-40.1.0`

#### Describe the problem in repeatable steps:

1. Open Minecraft with the argument: `-Djourneymap.map_testing="for testing"`
2. Open a world
3. Open the fullscreen map
4. Press the _region display off_ button
5. Move the map with the mouse
6. Press the _Follow_ button

Overlays stay fixed on screen instead of moving with the map.

![image](https://user-images.githubusercontent.com/7003923/165169164-d5882c62-eb26-46f9-a353-5f2f35dde65e.png)
![image](https://user-images.githubusercontent.com/7003923/165169201-541cd261-cded-4437-b792-dd6d88393fcf.png)
![image](https://user-images.githubusercontent.com/7003923/165169219-bc5c6332-afec-4c71-90f1-8c8aeee2c366.png)

**Comment by mysticdrew** [comment]
Thank you very very much! 
Will be fixed with the next updated release.

**Comment by mysticdrew** [comment]
OOps, forgot to close this. This fix was in the 5.8.3 release.
