### ISSUE TITLE
[1.16.5] [Feature Request] Mob name display

### ISSUE THREAD

**Issue by ZHAY10086** [TeamJM/journeymap#432]
#### JourneyMap Version:

`journeymap-1.16.5-5.8.1`

#### Forge Version:

`1.16.5-36.2.33`

Could you please add a function to display mob name with a hotkey? It would be convenient for most people i think.

**Comment by mysticdrew** [comment]
So, this has been brought up before. I have been against it because of map clutter. 

![image](https://user-images.githubusercontent.com/5459941/165403962-8f595789-57b2-446c-83d9-66a6b99e1aad.png)

is an example.

**Comment by ZHAY10086** [comment]
It can be togglable, if someone dislike it, just turn it off. 
In most modpacks, there are tons of mob with no icon, this function is really useful in such situation.

**Comment by mysticdrew** [comment]
This is completed for the next Major release. 
New options for entities and a hotkey to enable disable on the fly. 
And you can hold Tab to show icons and names. 
Will close once this is released.

**Comment by ZHAY10086** [comment]
Thanks for your effort!

**Comment by mysticdrew** [comment]
Cleaning up the issue tracker
Closing as this is completed for JourneyMap v6 when it is released.
