### ISSUE TITLE
【1.18.2-5.8.2】forge minimap place crashing

### ISSUE THREAD

**Issue by liuzipeng** [TeamJM/journeymap#433]
JourneyMap Version:
1.18.2-5.8.2

Forge Version:
1.18.2-40.1.0

The location of editing the minimap is crashing stop 
here is error report 
[错误报告-2022-4-27_0.26.28.zip](https://github.com/TeamJM/journeymap/files/8565100/-2022-4-27_0.26.28.zip)

**Comment by mysticdrew** [comment]
Remove optifine and see if the crash still happens.

**Comment by mysticdrew** [comment]
are you able to replicate this on a restart of minecraft? If so, can you come to our discord so I can give you a test version please to verify it is fixed? I am unable to replicate this issue, my guess is that it is due to your locale.

**Comment by mysticdrew** [comment]
Closing as I am unable to replicate this issue and reporter has failed up provide more details as requested.
