### ISSUE TITLE
[1.16.5] Add a distance display to the fullscreen map

### ISSUE THREAD

**Issue by FADEOffical** [TeamJM/journeymap#434]
#### JourneyMap Version:

`1.16.5-5.8.3`

#### Forge Version:

`1.16.5-36.2.33`

As a user, I want to be able to have an easy way of measuring distances between two points on the full-screen map.
* One way to achieve such a thing would be something similar to Google Maps, where you have to Right-click, select "Measure Distance", and then press on another point to measure the distance. The second step can be repeated indefinitely, where the last point will be used as the reference to the new point. When multiple points are on the map, the distance displayed at every point should be the sum of all distances up to that point.

* Alternatively, a simpler but less preferred way would be to simply display the distance in the text-label above the bottom buttons.

A huge advantage of the first method would be the easiness of determining the perimeter of curved structures.

**Comment by mysticdrew** [comment]
As discussed in discord. 
I will add bullet #2 to journeymap, but bullet #1 should be added to [journeymap-additions](https://github.com/TeamJM/journeymap-additions) if you want to PR it so it gets released faster or wait until I have time to do it.

**Comment by mysticdrew** [comment]
Alright, so here is the plan with this feature request. 
I am going to close the issue here, but I have linked it in the [journeymap-additions](https://github.com/TeamJM/journeymap-additions) issue tracker. I will be adding it there post the next major journeymap release.
