### ISSUE TITLE
[Bug]: Canceling Automapping has weird results.

### ISSUE THREAD

**Issue by Jkosio23** [TeamJM/journeymap#435]
Just leaving this here for you to have it in the to-do list since I noticed you talking about it on the discord.

**Comment by mysticdrew** [comment]
Canceling automapping has weird results, The automapping is canceled but overlays will sometimes keep going or just stall and not get removed. Starting automapping again after stopping it will not always restart it, sometimes it will but overlays will not display. 

Current solution is to restart minecraft after automapping.

**Comment by mysticdrew** [comment]
Seems fixing #468 has resolved this? hmm

**Comment by mysticdrew** [comment]
Well that did not really fix it, but I did fix it I think. Will be in next release.
