### ISSUE TITLE
Full screen map closes

### ISSUE THREAD

**Issue by N0MAD91** [TeamJM/journeymap#437]
Modpack: Three Headed Beast Continuum 1.1.2

JourneyMap Version: 5.8.3
Forge Version: 1.16.5 v.36.2.35
I open the Fullscreen map.
When I hover the mouse over an unloaded section of the map, say to move the map or to click on one of the buttons, Journey map closes. I am unsure as to the exact number of times, but after a few tries, the game crashes. 

Steps:
1. Open Journey map
2. Move mouse over unloaded section of map
3. Journey map immediately closes
4. Repeat steps 1-3 enough times causes game to crash

I am not sure if it is Journey map itself or a mod interaction. Link below to crash report.

https://pastebin.com/8mXeB8ta

**Comment by mysticdrew** [comment]
Duplicate #436
