### ISSUE TITLE
 [Render thread/ERROR] [journeymap/]: Error during MiniMap.drawMap(): An unexpected critical error was encountered (SUPPRESSED)

### ISSUE THREAD

**Issue by OcrSu** [TeamJM/journeymap#438]
#### JourneyMap Version:

journeymap-1.16.5-5.8.5.jar

#### Forge Version:

1.16.5 36.2.35

#### Describe the problem in repeatable steps:
Use Java11 to start this modpack
[[1.16.5]Lost_CivilizationWilds-4.3.1.zip](https://github.com/TeamJM/journeymap/files/8747491/1.16.5.Lost_CivilizationWilds-4.3.1.zip)

1.Create a new world
2.Open FTB_Chunk
3.Claim some chunks
4.It Crash..

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
[journeymap.log](https://github.com/TeamJM/journeymap/files/8747485/journeymap.log)
[debug.log](https://github.com/TeamJM/journeymap/files/8747487/debug.log)

**Comment by mysticdrew** [comment]
You are going to need to supply logs that contain the actual crash.

**Comment by mysticdrew** [comment]
`
2.Open FTB_Chunk
3.Claim some chunks
`
sounds to be like this may be an issue with Journeymap-Integration but a full log will be needed.

**Comment by OcrSu** [comment]
There is no crash log , the game is just unresponsive.

**Comment by OcrSu** [comment]
I'll test the Journeymap-Integration mod tomorrow when I'm not busy, it's late at night here and I have to go to bed

**Comment by mysticdrew** [comment]
Thanks for the response, that is pretty interesting. I would suggest letting it hang for a bit and see if eventually it crashes.

**Comment by frank89722** [comment]
> I'll test the Journeymap-Integration mod tomorrow when I'm not busy, it's late at night here and I have to go to bed

Hello, could you also test your pack without rubidium installed?

**Comment by OcrSu** [comment]
I retested it and I found that there is no problem in caiming some chunks
It is unresponsive when pressing E or Esc.
I will remove rubidium for testing later.

**Comment by OcrSu** [comment]
> Thanks for the response, that is pretty interesting. I would suggest letting it hang for a bit and see if eventually it crashes.

After 5mins, he is still in unresponsive state.
No new information appears in the log either.

**Comment by OcrSu** [comment]
It has been found that MerchantMarkers mod is causing the problem
Update MerchantMarkers mod to 1.2.1 to fix it.
![image](https://user-images.githubusercontent.com/75876201/169747145-2d2ebd34-4d65-4541-89b2-4d99a499021b.png)
