### ISSUE TITLE
Adjusting font scale crashes the client

### ISSUE THREAD

**Issue by Porcy** [TeamJM/journeymap#439]
#### JourneyMap Version:
1.16.5-5.8.5

#### Forge Version:
1.16.5-36.2.34

#### Describe the problem in repeatable steps:
Go in options;
Try to modify the font scale of the first "info box" using the slider
Crash your client.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
I don't see any error in this log

MultiMC crash log here: https://paste.ee/p/fdeiR

**Comment by Porcy** [comment]
It definitely has to do with dragging the slider. Clicking in the bar to change the value works fine.

**Comment by mysticdrew** [comment]
are you able to consistently replicate this?

**Comment by mysticdrew** [comment]
Someone else experienced this issue but would not reply to the issue #433. 
The problem is the date time formatter is trying to format `17:36:-1` but the -1 fails. I am curious as to the why and how seconds is getting to be -1. 
If you are able to replicate this, please come into our discord. I need to find a solution that is not a band-aid. 

Thanks!

**Comment by Porcy** [comment]
Yup. If I drag the slider, client crashes. If I click in the slider box, it's fine. Crashed my client 3 times checking this.

**Comment by Porcy** [comment]
Just left the computer for the day. Maybe tomorrow I'll pop on Discord

**Comment by Porcy** [comment]
Wild guess: dragging the slider doesn't always output valid values while clicking the bar does. Maybe it outputs an unhandled value between numbers and the formatter defaults to -1.

**Comment by mysticdrew** [comment]
> Wild guess: dragging the slider doesn't always output valid values while clicking the bar does. Maybe it outputs an unhandled value between numbers and the formatter defaults to -1.

It has to do with the time setting, we calculate it based on world ticks. It should never be -1 so I am not sure how it is getting there. 

@Porcy are you able to come into discord to try a test build to see if it resolves your issue? I am unable to replicate it naturally, I'd like to verify it is fixed for you before I publish it. 

Thanks!

**Comment by Porcy** [comment]
On Discord right now. Under Kournin name.

**Comment by mysticdrew** [comment]
Publishing 5.8.5p2 now with the fix
