### ISSUE TITLE
[Feature Request] : Add light level to minimap info slots

### ISSUE THREAD

**Issue by bondenn** [TeamJM/journeymap#44]
I think it'd be a good addition to allow light level as a selection for the customizable info slots, this would essentially eliminate the need for the debug screen (which also covers the minimap when using the top two slots).

**Comment by mysticdrew** [comment]
Good idea!

**Comment by mysticdrew** [comment]
How does this look?
![](http://puu.sh/D9CwX/eec7e54d72.png)
