### ISSUE TITLE
[1.16.5] Mouse Movement Closes Fullscreen Map

### ISSUE THREAD

**Issue by HypnoPants** [TeamJM/journeymap#444]
#### JourneyMap Version:

1.16.5-5.8.3

#### Forge Version:

1.16.5-36.2.35

#### Describe the problem in repeatable steps:

1. Open Fullscreen Map
2. Move Mouse Around
3. Sometimes it closes when the mouse moves right, sometimes left, sometimes it takes a while of moving the mouse around, other times the slightest movement causes the fullscreen map to close.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

[07:13:24] [main/WARN] [StatTimer] Fullscreen.render is not running.
[07:14:11] [main/ERROR] [Fullscreen] Unexpected exception in jm.fullscreen.render(): java.lang.NullPointerException

[journeymap.log](https://github.com/TeamJM/journeymap/files/8786966/journeymap.log)

**Comment by mysticdrew** [comment]
update to the latest

**Comment by HypnoPants** [comment]
thank you :)
