### ISSUE TITLE
[1.18.2] Not allowed on the server

### ISSUE THREAD

**Issue by SadnessOfficial** [TeamJM/journeymap#446]
#### JourneyMap Version:
`1.18.2-5.8.4`
#### Fabric Version:
`0.50.0+1.18.2`

#### Describe the problem in repeatable steps:

1. Minecraft starts without problems.
2. But when entering a private server, it does not let you in after the item "Loading territory...".
3. After several restarts, I turned it on in the launcher settings, I saw that after the item "Loading territory...", an error was displayed in an endless loop.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
[journeymap.log](https://github.com/TeamJM/journeymap/files/8788064/journeymap.log)

**Comment by SadnessOfficial** [comment]
`java
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
`

**Comment by mysticdrew** [comment]
do not paste logs into issues. 
I will close this unless you delete the past and add the actual file

**Comment by SadnessOfficial** [comment]
i can't add file

**Comment by SadnessOfficial** [comment]
[journeymap.log](https://github.com/TeamJM/journeymap/files/8788061/journeymap.log)

**Comment by SadnessOfficial** [comment]
> do not paste logs into issues. I will close this unless you delete the paste and add the actual file

uploaded the file

**Comment by SadnessOfficial** [comment]
help pls?

**Comment by mysticdrew** [comment]
Github issues are not for instant help, Discord is faster help

**Comment by SadnessOfficial** [comment]
ok

**Comment by mysticdrew** [comment]
See if this is fixed in the 5.8.5 update. If not, you will need to come to our discord so we can assist further.
