### ISSUE TITLE
[suggestion] Categories for waypoints

### ISSUE THREAD

**Issue by Goten87** [TeamJM/journeymap#448]
#### Describe the problem in repeatable steps: None its not a bug

i wanted to ask if there is a way to make folder/categories for waypoints and then the option to enable/disable them with one click

so when i make a category Towns and i click the hide/show button all the towns waypoints i have in that category will be show or hidden on the mao

**Comment by Goten87** [comment]
good to hear keep up to good work

**Comment by RokeJulianLockhart** [comment]
> https://github.com/TeamJM/journeymap/issues/448#issue-1252885362

@Goten87, are you requesting a tagging system, or something more akin to directories, or a combination thereof?

**Comment by mysticdrew** [comment]
The beginning of this has been started in 6.0.0. You can reset enable the wip waypoint manager in a waypoint options

**Comment by mysticdrew** [comment]
1.21-6.0.0-beta.19

Phase 1 is complete, release is publishing
