### ISSUE TITLE
Lock Minimap preset to Biome/Topo mode

### ISSUE THREAD

**Issue by Gjum** [TeamJM/journeymap#449]
I want to be able to confgure one of the two Minimap presets to always show the Biome map and the other the Daytime map, so I can easily switch between the views while exploring.

Currently, a preset can't be locked to Biome/Topo display, only Day/Night/Cave can be configured.

Journeymap version: 5.8.4
MC/Forge/Fabric versions: all

**Comment by mysticdrew** [comment]
This is completed. 
See
https://github.com/TeamJM/journeymap/issues/91

**Comment by mysticdrew** [comment]
I will be closing this issue, please track https://github.com/TeamJM/journeymap/issues/91 to see when it is released.
