### ISSUE TITLE
[Feature Request]: A way to get the absolute/relative height of entities on radar

### ISSUE THREAD

**Issue by Mersid** [TeamJM/journeymap#45]
All mobs are placed orthographically on the entity map with no respect to its y value. Thus, a mob far beneath a player at y = 25 would appear on the map the same way a mob at y = 250 would. Players looking for rare mobs may have a bit of a difficult time manually determining the height after they locate the mob on the x and z planes.

**Comment by MauveCloud** [comment]
> All mobs are placed orthographically on the entity map with no respect to its y value.

That's not entirely true.  Under "Advanced Options", there is "Radar Range Vertical", which ranges from 8 to 256, with iirc a default of 16.

**Comment by Mersid** [comment]
It will hide mobs past a certain y level. I was hoping for something that can show its value, say next to the entity on the map.

**Comment by mysticdrew** [comment]
There is an up and down arrow to let you know where the mob is relative to you. Adding more is just cheaty.
