### ISSUE TITLE
[1.16.5] "Show Caves" in nether crashing the client

### ISSUE THREAD

**Issue by HazardEST** [TeamJM/journeymap#451]
JourneyMap Version:
1.16.5-5.8.5p2

Forge Version:
1.16.5-36.2.35

Describe the problem in repeatable steps:

1. Go to nether
2. Open your journeymap large map
3. Click on the "Show Caves" button
4. ???
5. Crash

Also, this happens on several older versions of journeymap too.

**Comment by mysticdrew** [comment]
Logs??

**Comment by mysticdrew** [comment]
fixed in p3 release, please update.
