### ISSUE TITLE
[Suggestion]: Option to display Minimap when other GUIs are open. 

### ISSUE THREAD

**Issue by Gjum** [TeamJM/journeymap#452]
I want to be able to configure the Minimap to stay on screen when the chat/inventory/other GUIs are open, so I can stay aware of my surroundings even in those situations.

While this could be configurable if contentious, IMO this could also just be the default.

Journeymap version: 5.8.4
MC/Forge/Fabric versions: all

**Comment by mysticdrew** [comment]
![java_R6rt045sOU](https://user-images.githubusercontent.com/5459941/212232123-a7879ce7-addf-4b33-b213-4b2bfee72db4.gif)

How's this? :)

**Comment by mysticdrew** [comment]
I'll likely add way to disable it for specific screens. Maybe a little X in the corner and then it saves the screen that it was in. So it so users can blacklist screens.

**Comment by Gjum** [comment]
Interesting choice to render on top of the (transparent) GUI background. Other map mods just render behind the GUI background, so the map doesn't obscure anything.

**Comment by mysticdrew** [comment]
Cleaning up the issue tracker
Closing as this is completed for JourneyMap v6 when it is released.
