### ISSUE TITLE
[1.19] Teleport option with waypoints sends the teleport command as a chat message

### ISSUE THREAD

**Issue by Captain-S0L0** [TeamJM/journeymap#454]
#### JourneyMap Version:

`journeymap-1.19-5.8.5-fabric.jar`

#### Fabric Version:

`0.14.6`

#### Describe the problem in repeatable steps:

1. Make a waypoint anywhere in the world
2. Either have operator or have cheats enabled
3. Click the teleport button in the waypoint menu

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
N/A.

[Screenshot 2022-06-07 234206](https://user-images.githubusercontent.com/70294758/172526929-1a95e2e3-8f3e-4950-88b3-7591eff5aaa8.png)

**Comment by mysticdrew** [comment]
Thanks, this is fixed for the next release.

**Comment by mysticdrew** [comment]
I will close this when it gets released

**Comment by mysticdrew** [comment]
oops, this was fixed in rc2, I forgot to close it
