### ISSUE TITLE
[Topo] tree trunks are shown on the topographic map

### ISSUE THREAD

**Issue by Pietropil15418** [TeamJM/journeymap#456]
JourneyMap Version: 5.8.5rc1

Fabric: 0.14.7

when using the topographic map, the trunks of trees show (see attached photo)

How to recreate this issue:

1. enter or create a new world 
2. search for trees and go to see the topographic map
3. you will find that the trunks of trees show on it

![Screenshot (9)](https://user-images.githubusercontent.com/107318636/173198194-951906c9-5824-4c2a-b50d-3bea67a2c138.png)

**Comment by mysticdrew** [comment]
Looks like this is also an issue in forge/fabric 1.18.2-1.19.

**Comment by mysticdrew** [comment]
This will be fixed in the next release. 
Sorry, I looks like I added the enhancement tag instead of the bug tag so it got missed in earlier versions.
