### ISSUE TITLE
[1.18.2, 1.19, Fabric] Compatibility with Immersive Portals 

### ISSUE THREAD

**Issue by qouteall** [TeamJM/journeymap#457]
Currently, when used with Immersive Portals, the map will mix content of different dimensions.

![](https://media.discordapp.net/attachments/662271867431682061/986248690542997504/Screenshot_20220614-143959_Discord.jpg?width=298&height=612)

Immersive Portals will switch the world when handling packets, rendering or ticking remote client dimensions. (The current version of ImmPtl switches both `Minecraft#level` and the client player's `level` field. But in the next version ImmPtl will not switch the client player's `level` field during ticking and packet handling)

JourneyMap can do:
1. When the client accepts chunk data packet or chunk update packet, if `Minecraft.getInstance().player.level != Minecraft.getInstance().level`, ignore the packet.
2. The client player can change dimension without reloading the client world (with loading screen). When the client player's `level` changes, JourneyMap should switch the map according to the player's dimension.
3. When the map content nearby the player is empty, directly read the blocks nearby to fill the map content. (Because when player is in overworld, the nether packets are being ignored, then when the player go to nether, it should re-fill the map content)

The ideal way would be that JourneyMap load different dimensions' maps at once and discriminate them. But it may require JoruneyMap to do some refactoring.

**Comment by mysticdrew** [comment]
> The ideal way would be that JourneyMap load different dimensions' maps at once and discriminate them. But it may require JoruneyMap to do some refactoring.

This specifically will not happen anytime soon. The other options I will look into and gauge feasibility as long as it does not break vanilla mechanics.

**Comment by mysticdrew** [comment]
I am working on this and have most of the issues addressed. But it seems there is a lighting issue with chunks, the lighting randomly changes it seems. Sections of chunks the lighting is randomly shifting, it's odd. 
![image](https://user-images.githubusercontent.com/5459941/207467480-51db29b0-4a36-47eb-bf4e-1ec56cb45c1d.png)
![image](https://user-images.githubusercontent.com/5459941/207467521-3d368aec-ad51-48e1-9cdf-91dd4b87e900.png)
![image](https://user-images.githubusercontent.com/5459941/207467586-9ea8d6ff-7a5d-43da-a46f-e729b29fc6ec.png)

**Comment by mysticdrew** [comment]
So the issues is with block lighting it seems. 
Many of those chunks are returning 0 when they should not be because the lightengine is constantly getting updated with chunks from the other world. 

`Minecraft.getInstance().player.level.getLightEngine().getLayerListener(LightLayer.BLOCK).getLightValue(blockPos));`

What do you suggest @qouteall ?

**Comment by mysticdrew** [comment]
Also, 
I am in the overworld and the player and the game world are both reporting as nether. I am not sure how I can work around this. 
![image](https://user-images.githubusercontent.com/5459941/207968753-94fa6c07-87f5-420b-87e7-7dfb2d1665a9.png)

**Comment by qouteall** [comment]
You can check whether `minecraft.player.level == minecraft.level`

**Comment by qouteall** [comment]
The player is not moved when ticking. However, when rendering the portal, the player moves to the dimension that gets rendered. I am planning to change this in the future.

**Comment by qouteall** [comment]
So currently you don't need to do more things for that.

**Comment by mysticdrew** [comment]
Ok so, I put in a bunch of checks, I am going to mark this as complete for now. We will address anymore issues when you get your updates out with the player's level being correctly set. 

I will close when I publish the release for 1.18.2 1.19.2 and 1.19.3

**Comment by qouteall** [comment]
I made the change in immptl 2.4.2. (In 2.4.2 it doesn't change player world when rendering portal)
