### ISSUE TITLE
[Feature Request] Optional Filled Map Restriction

### ISSUE THREAD

**Issue by naqaden** [TeamJM/journeymap#46]
Please consider adding a cartography option to limit JourneyMap to what players have explored with "filled" maps in-game.

My friends and I would enjoy JM's features if JM didn't replace in-game cartography for free. Even this proposed option would still feel cheat-y (effectively free access to all player maps ever?), but I think the initial investment to craft and guard maps till completion would help keep cartography rewarding.

**Comment by mysticdrew** [comment]
This can be done with a plugin and maybe the mod JourneymapStages. It's not really in the scope of mod.
