### ISSUE TITLE
[Feature Request] Entity Names are shown while holding a key

### ISSUE THREAD

**Issue by Laifsyn** [TeamJM/journeymap#463]
When holding a key(or through toggleable method), show entity names on the minimap, and or also show a representative icon of the entity (either through key press or check box)

**Comment by mysticdrew** [comment]
> and or also show a representative icon of the entity (either through key press or check box)
You can set the minimap to display icons already in the settings.

**Comment by Laifsyn** [comment]
That's why I mentioned toggleable method. I feel it more convenient to be able to just temporarily allow the icon show just to gather information, so I don't have it cluttered with symbols.

Also to be able to show their names or a representative icon because it doesn't support modded mobs

**Comment by mysticdrew** [comment]
closing due to duplication of issue #432 
Closing will not impact implantation, just doing some house cleaning of the issue tracker. I will be adding this for the next major release.
