### ISSUE TITLE
Waypoint Chat option

### ISSUE THREAD

**Issue by GrasshopperGit** [TeamJM/journeymap#465]
#### JourneyMap Version:

1.19-5.8.5

#### Forge Version:

1.19 - 41.0.38

#### Describe the problem in repeatable steps:

1.
![image](https://user-images.githubusercontent.com/67942455/174516838-ca573260-f3f0-4a7a-a000-ef0a15a19fbc.png)

2. You can't add the waypoint per click in chat

**Comment by mysticdrew** [comment]
Is this a bukkit/paper server or a forge server?

**Comment by GrasshopperGit** [comment]
> Is this a bukkit/paper server or a forge server?

its a paper server . but i had one bevor in version 1.18.2 and in that version it worked

**Comment by GrasshopperGit** [comment]
> Is this a bukkit/paper server or a forge server?

and i tried it already without plugins and with both doesn't work . i'm using the newest version of paper #31

**Comment by mysticdrew** [comment]
Oof.. 
So this is a paper issue, they are sending all chat as SystemMessages not ClientMessages. This will be resolved with the release version of 5.8.5. Hopefully today.
