### ISSUE TITLE
[1.19] Client cannot connect to server using JourneyMap 1.19-5.8.5rc2-forge and the MapFrontiers port to 1.19

### ISSUE THREAD

**Issue by alejandrocoria** [TeamJM/journeymap#466]
#### JourneyMap Version:

`1.19-5.8.5rc2-forge`

#### Forge Version:

`1.19-41.0.35`
 
#### MapFrontiers Version:

[The master branch has what I'm porting to 1.19.](https://github.com/alejandrocoria/MapFrontiers/tree/2e55165b7a5e05bc8b46d2ecb964ffc890ecd885)
 
---
When the client wants to connect to a server or LAN host, the connection is closed with a netty exception. Nothing happens on the server or host side, nothing is logged when that happens. On the client side, I see a couple of exceptions in the debug.log. On line 920 is the first one, right after JourneyMap's ClientPacketListenerMixin.
 
[debug.log](https://github.com/TeamJM/journeymap/files/8942834/debug.log)
 
The relevant lines are:
```
. . .
916  [20jun2022 13:51:28.788] [Netty Client IO #1/INFO] [net.minecraftforge.network.NetworkHooks/]: Connected to a modded server.
917  [20jun2022 13:51:28.806] [Netty Client IO #1/DEBUG] [mixin/]: Mixing client.ClientPacketListenerMixin from journeymap.mixins.json into net.minecraft.client.multiplayer.ClientPacketListener
918  [20jun2022 13:51:36.070] [Render thread/DEBUG] [net.minecraft.client.sounds.SoundEngine/SOUNDS]: Skipped playing sound minecraft:music/game/swamp/firebugs, volume was zero.
919  [20jun2022 13:51:37.036] [Netty Client IO #1/DEBUG] [net.minecraft.network.Connection/]: Failed to sent packet
920  io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(17205) + length(1) exceeds writerIndex(17205): UnpooledHeapByteBuf(ridx: 17205, widx: 17205, cap: 17205/17205)
921  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:480) ~[netty-codec-4.1.77.Final.jar%2336!/:4.1.77.Final]
. . .
```
_Line 918 is irrelevant, it's from another thread._

**Comment by mysticdrew** [comment]
Are you running both client and server in your IDE? 
Or in a production setup?

**Comment by alejandrocoria** [comment]
I run the server in the IDE and the official Minecraft client. For LAN I use one client in the IDE and the other the official one. The problem occurs with either one being the host.
 
I couldn't replicate it without MapFrontiers.

**Comment by mysticdrew** [comment]
So, I think this might be an issue with one of our packets. 
I would suggest wrapping all of your toBytes and fromBytes in a try/catch block to catch any errors. 
I am unable to replicate this from your master branch. 

I was able to connect in 
IDE Client to IDE Server, 
IDE Client to Vanilla Server, 
IDE Client1 Enabled Lan, IDE Client2 was able to Connect to IDE Client 1's lan game. 

I am having an issue where I cannot run forge for 1.19 outside of dev, tried vanilla launcher with forge and polyMC, I get some no classdeffound errors with only forge and no mods. So my test cases are a bit limited.

**Comment by alejandrocoria** [comment]
> I would suggest wrapping all of your toBytes and fromBytes in a try/catch block to catch any errors.

I tried that. No exception is thrown.

**Comment by mysticdrew** [comment]
Looking at your logs, something is messed up. I see a lot of errors coming from methods not found in journeymap. 
I did not get any errors and it worked perfectly in LAN and on a Server for me.

**Comment by alejandrocoria** [comment]
I noticed that the log I uploaded here has a lot of errors because I was using 1.18.2-5.9.0alpha5-forge, but in the official client I still had 1.19-5.8.5rc2-forge. I am sorry. The log I uploaded yesterday on discord is better.

**Comment by alejandrocoria** [comment]
[debug.log](https://github.com/TeamJM/journeymap/files/8944004/debug.log)
Here's a better one.

**Comment by mysticdrew** [comment]
This is not related to either of our mods. 
UserDev client connecting to a forge prod server, or forge prod client connecting to userdev server will cause this issue.
https://discord.com/channels/313125603924639766/540691915373412393/986532799974621264
Shrimp is working on a fix here
https://github.com/SizableShrimp/MinecraftForge/tree/1.19.x-gametest-connection-fixes
