### ISSUE TITLE
[1.18.2] `IClientAPI#show` does not work properly

### ISSUE THREAD

**Issue by frank89722** [TeamJM/journeymap#468]
#### JourneyMap Version:

`1.18.2-5.8.5+forge`

#### Forge Version:

1.18.2-40.1.0

#### Describe the problem in repeatable steps:

IClientAPI#show does not work properly when I pass in a Displayable object which has been used.
For example, I have a random Displayable object called `overlay` and then I have three lines of code: 
 ```
jmAPI.show(overlay); (this work)
jmAPI.remove(overlay); (still work)
jmAPI.show(overlay); (not work)
```

**Comment by mysticdrew** [comment]
This is fixed for the next release.
