### ISSUE TITLE
[1.19] map type icon fading overlay in wrong position on map type change

### ISSUE THREAD

**Issue by jason-green-io** [TeamJM/journeymap#470]
#### JourneyMap Version:

`1.19-5.8.5rc2 fabric`

#### Fabric API Version:

`0.55.3+1.19`

#### Describe the problem in repeatable steps:

1. The fading in map type overlay icon on the minimap upon map type change is in the wrong position on retina (pixel doubled) displays (MacOS only .. I think .. maybe)

2. Notice in the screenshot that the "sun" icon is nowhere near the minimap in the top-left-ish.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

<img width="1440" alt="2916E39B-D6AF-469B-8486-20C0B38E30FF" src="https://user-images.githubusercontent.com/2853489/175059106-b90f0713-2c71-4fd6-a1eb-1e2420082256.png">

**Comment by mysticdrew** [comment]
Retina displays have a few issues, so I am not surprised. 
Is dragging the full screen map odd on your computer too?

**Comment by mysticdrew** [comment]
this should be fixed now as of 5.9.18 I think
