### ISSUE TITLE
[1.18.2] When opening or closing the fullscreen map the DISPLAY_UPDATE event only fires for the minimap, never for the fullscreen map

### ISSUE THREAD

**Issue by alejandrocoria** [TeamJM/journeymap#471]
#### JourneyMap Version:

`1.18.2-5.8.5-fabric`

#### Fabric Version:

`0.50.0+1.18.2`

#### Describe the problem in repeatable steps:

1. Create a plugin
2. Subscribe to `ClientEvent.Type.DISPLAY UPDATE`
3. Respond to the event:
```
@Override
public void onEvent(ClientEvent event) {
    if (event.type == ClientEvent.Type.DISPLAY_UPDATE) {
        DisplayUpdateEvent de = (DisplayUpdateEvent)event;
        System.out.println("DISPLAY_UPDATE: de.uiState.ui:" + de.uiState.ui + "    de.uiState.active: " + de.uiState.active);
    }
 }
```

That code outputs the following when I open and close the map multiple times:
```
DISPLAY_UPDATE: de.uiState.ui:Minimap    de.uiState.active: false
DISPLAY_UPDATE: de.uiState.ui:Fullscreen    de.uiState.active: true
DISPLAY_UPDATE: de.uiState.ui:Minimap    de.uiState.active: true
DISPLAY_UPDATE: de.uiState.ui:Minimap    de.uiState.active: false
DISPLAY_UPDATE: de.uiState.ui:Minimap    de.uiState.active: true
DISPLAY_UPDATE: de.uiState.ui:Minimap    de.uiState.active: false
DISPLAY_UPDATE: de.uiState.ui:Minimap    de.uiState.active: true
DISPLAY_UPDATE: de.uiState.ui:Minimap    de.uiState.active: false
DISPLAY_UPDATE: de.uiState.ui:Minimap    de.uiState.active: true
```

Apparently the first time the map is opened it does send the event for the fullscreen map.

**Comment by mysticdrew** [comment]
is this for 1.19 or 1.18.2 or both?

**Comment by alejandrocoria** [comment]
1.18.2. I haven't tried upgrading to fabric 1.19 yet, should I try? I'd like to release both versions for now, at least until 1.19 becomes more popular.

**Comment by mysticdrew** [comment]
You put 1.18.2 in the title, but 1.19 in the jm version.

**Comment by alejandrocoria** [comment]
oh sorry i copied wrong.

**Comment by alejandrocoria** [comment]
The bug is also in 1.19.

**Comment by alejandrocoria** [comment]
I found the bug!

In JourneyMap-Forge:
- In `UIManager::closeCurrent` the method `JmUI::close` is called
- `JmUI` has an empty `close` method
- `Fullscreen` has a `close` method that inherits from `JmUI` and also implements from `IFullscreen`

In JourneyMap-Fabric:
- In `UIManager::closeCurrent` the method `JmUI::onClose` is called (not `close`)
- `JmUI` does not have an `onClose` or `close` method but inherits an `onClose` from `Screen`
- `Fullscreen` has a `close` method that implements from `IFullscreen` but not one that inherits from `JmUI`
- The bug occurs because `Fullscreen::close` is never called

**Comment by mysticdrew** [comment]
Ooooh! Yes because I had to change that for fabric mapping issues. 
I need to get multi-loader template working for JM, to avoid these issues.

**Comment by mysticdrew** [comment]
Fixed internally for next release.
