### ISSUE TITLE
[1.19-1.18.2] Mobs are not correctly rendered with JourneyMap and Iris.

### ISSUE THREAD

**Issue by Lolothepro** [TeamJM/journeymap#473]
https://user-images.githubusercontent.com/68275908/175811045-fe609f3e-af2a-40ba-8f33-ae054a50591d.mp4

journeymap-1.19-5.8.5rc2-fabric
[latest.log](https://github.com/TeamJM/journeymap/files/8987122/latest.log)
[journeymap.log](https://github.com/TeamJM/journeymap/files/8987123/journeymap.log)

**Comment by mysticdrew** [comment]
Delete the paste and attach the log file

**Comment by Lolothepro** [comment]
Is it good?

**Comment by mysticdrew** [comment]
This is fixed in 5.9.0 when released. 
5.8.5 release version for 1.19 will not contain this fix when it comes out of release candidate
