### ISSUE TITLE
[1.19] ice block doesn't show in map, bug or not ?

### ISSUE THREAD

**Issue by SummerXXXX** [TeamJM/journeymap#476]
#### JourneyMap Version:
Journeymap-1.19-5.8.5rc2-forge

#### Forge Version:
41.0.44

#### Describe the problem in repeatable steps:
ice block doesn't show in map, it show water block instead.

I'm not sure if this is how it works or it's a bug?

![2022-07-03_15 22 56](https://user-images.githubusercontent.com/10771754/177029608-20f6efd6-2341-4c9d-b2c5-5758d55815c1.png)

**Comment by mysticdrew** [comment]
Looks like you have Bathymetry enabled in cartography settings. Press J, press O, click cartography and disable bathymetry

**Comment by mysticdrew** [comment]
forge 1.19-41.0.34 and below you must use 5.8.5rc1
forge 1.19-41.0.35 through 1.19-41.0.63 you must use 5.8.5rc2
forge 1.19-41.0.64 through 1.19-41.0.93 you must use 5.8.5rc3
forge 1.19-41.0.94+ you must use 5.8.5rc4
