### ISSUE TITLE
[1.18.2] Strange patern in my map

### ISSUE THREAD

**Issue by YoYomec** [TeamJM/journeymap#477]
#### Forge Version: 1.18.2 - 40.1.54

I don't know the event that caused the problem, there was no error message. I think I disconnected and then reconnected to the server just before the problem.

![image](https://user-images.githubusercontent.com/98414804/177326972-c973bda0-f2b1-477d-9de5-f8d26ca7664f.png)
![image](https://user-images.githubusercontent.com/98414804/177327097-22d1471c-72d2-4cb6-ab81-93df184f9576.png)

**Comment by mysticdrew** [comment]
remove optifine

**Comment by YoYomec** [comment]
Ok, but can i know why ?

**Comment by YoYomec** [comment]
I think my optifine has a problem, I have errors in the chat : OpenGL exception: 1282 (invalid operation)

**Comment by mysticdrew** [comment]
> Ok, but can i know why ?
because optifine is causing the issues, I have no idea why. See the pinned issue

**Comment by YoYomec** [comment]
Ok, thank
