### ISSUE TITLE
Water does not show

### ISSUE THREAD

**Issue by s0ulkeeper** [TeamJM/journeymap#478]
JourneyMap Version: 
- journeymap-1.19-5.8.5rc1-forge

Forge Version:
- forge-1.19-41.0.63

Describe the problem in repeatable steps:
- Water doesn't show in the minimap/map, it only shows the sand and rock layers. How can i put the water layer visible?

![water does not show 1](https://user-images.githubusercontent.com/108934694/177988567-f90f98f8-b83d-47cf-9b48-194276123b6f.png)
![water does not show 2](https://user-images.githubusercontent.com/108934694/177988580-c59711ec-16b7-49eb-9314-e11b74035350.png)

**Comment by mysticdrew** [comment]
Update to rc2

**Comment by s0ulkeeper** [comment]
Whats that?

**Comment by mysticdrew** [comment]
The latest version of journeymap. Do not update forge

**Comment by s0ulkeeper** [comment]
Got it, thank u so much ^^
