### ISSUE TITLE
[Feature Request] Allow servers to provide map files that the client downloads

### ISSUE THREAD

**Issue by aaronhowser1** [TeamJM/journeymap#48]
It would be awesome if the admin could use the Auto-Map feature, then save it into somewhere in the server files, and then when a player joins for the first time it downloads and uses that map so the player can see a full map to find a place to base at.

**Comment by mysticdrew** [comment]
Due to file size and other limitations, this is likely to never be implemented.

**Comment by Dev4lexG** [comment]
and now? we have more tecnologies than 2018
