### ISSUE TITLE
Would you please add shadow for the Radar font for better visibility?

### ISSUE THREAD

**Issue by ardissaps** [TeamJM/journeymap#480]
- For information near the minimap like biome clock etch.

**Comment by mysticdrew** [comment]
I made it so that if the infoslot background is less than .05 alpha it will draw the font shadow. 

This will be in the next major release.

**Comment by mysticdrew** [comment]
Cleaning up the issue tracker
Closing as this is completed for JourneyMap v6 when it is released.
