### ISSUE TITLE
java.lang.ClassNotFoundException: net.minecraftforge.event.entity.EntityJoinWorldEvent

### ISSUE THREAD

**Issue by zkScorpionzk** [TeamJM/journeymap#481]
[crash-2022-07-12_13.01.35-fml.txt](https://github.com/TeamJM/journeymap/files/9092250/crash-2022-07-12_13.01.35-fml.txt)

I just downlaoded Forge 1.19 and JourneyMap 1.19. No other mods, and keep having this error. Any clue on what should I do?

**Comment by mrshomersimpson** [comment]
Also having this issue :) 

https://gyazo.com/decfbe3231741c9cd3f69619df9be68c

**Comment by blibenson** [comment]
> Also having this issue :)
> 
> https://gyazo.com/decfbe3231741c9cd3f69619df9be68c

I am having the exact same issue. Clean Java 17 install, clean Forge Install.

**Comment by xavvs** [comment]
Found a fix!
Just reinstall journeymap and it'll be good to go

**Comment by mysticdrew** [comment]
So make sure to look at the journeymap change log for the correct version of forge.
forge 1.19-41.0.34 and below you must use 5.8.5rc1
forge 1.19-41.0.35 through 1.19-41.0.63 you must use 5.8.5rc2
forge 1.19-41.0.64 through 1.19-41.0.93 you must use 5.8.5rc3
forge 1.19-41.0.94+ you must use 5.8.5rc4
