### ISSUE TITLE
[Feature Request] Freecam support

### ISSUE THREAD

**Issue by kosma** [TeamJM/journeymap#482]
When using JourneyMap 1.19-5.8.5rc2-fabric with Tweakeroo freecam, the player on the map doesn't move with the free camera. Making it move would be very useful, e.g. when marking specific spots. A sample solution would be to take the player position from the client camera, not from the player entity.

**Comment by mysticdrew** [comment]
This is completed for the next release, I will close and update this issue when it is published.

**Comment by mysticdrew** [comment]
Cleaning up the issue tracker
Closing as this is completed for JourneyMap v6 when it is released.
