### ISSUE TITLE
[Fabric 1.18.2 and 1.19] Resizing the Minecraft window with the map open changes the vertical scale of the GUI to half

### ISSUE THREAD

**Issue by alejandrocoria** [TeamJM/journeymap#483]
#### JourneyMap Version:

`5.8.5rc2`

#### Fabric Version:

`0.14.8 / api-0.57.0+1.19`

#### Describe the problem in repeatable steps:

1. Put Minecraft in windowed mode
2. Open fullscreen map
3. Open the right-click menu
4. Change the size of the Minecraft window (using the borders or maximizing/restoring)
5. GUI shrinks in half vertically

It doesn't happen if you don't have the menu open, but it does happen if there is a screen from another mod drawing on top of the map (ex: MapFrontiers)

#### Video:

https://user-images.githubusercontent.com/7003923/180618895-147f61e8-578e-41a9-9724-aa98e97bf7a1.mp4

**Comment by mysticdrew** [comment]
That looks neat! I bet the resize is got getting called correctly.

**Comment by mysticdrew** [comment]
Fixed for 5.9.0
