### ISSUE TITLE
[1.18.2] Error during MiniMap.drawMap : GUI misaligns on Launch 

### ISSUE THREAD

**Issue by Emojiime** [TeamJM/journeymap#485]
---
  
#### JourneyMap Version:
6.9.0beta1

#### Forge Version:
1.18.2-40.1.60

#### Describe the problem in repeatable steps:
Under Investigation - So far;

1. Load Minecraft
2. Spawn in an environment which is not above ground in the overworld (Underground, cave, etc) but has third-party mod entities

#### Relevant errors 
journeymap.log (trimmed) : https://gist.github.com/Emojiime/fa81322247c0896e0cdd44a8f3ad1cf9
journeymap.log (raw) : https://gist.github.com/Emojiime/c2434da4b14fbc1e63d5cf102f4a9cc7
client log : https://gist.github.com/Emojiime/2895754c2585cd5fe5759f45e8e69b3f

**Comment by mysticdrew** [comment]
This is fixed in 5.9.0beta2
