### ISSUE TITLE
[1.16.5] Map looks weird after editing world with external program (Worldpainter)

### ISSUE THREAD

**Issue by darthvader45** [TeamJM/journeymap#486]
#### JourneyMap Version: 5.8.5p5

`Example: 1.12.1-5.5.0`

#### Forge Version: 1.16.5-36.2.39

`Example: 1.12.1-14.22.1.2478`

#### Describe the problem in repeatable steps:

1. Open world in an external map-editing program, like Worldpainter.  Edit it to your heart's content.
2.  Close Worldpainter, merging any changes you like.  Open world in Minecraft.
3.  Notice the minimap render near the area you edited looks odd, with random lines and dashes spread throughout.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
![2022-08-03_17 52 52](https://user-images.githubusercontent.com/2816420/182729969-bbfc1bc5-3171-419e-a82b-df5132a512f5.png)

**Comment by mysticdrew** [comment]
You need to optimize you world from the singleplayer menu

**Comment by mysticdrew** [comment]
![java_BYN4vZzHcL](https://user-images.githubusercontent.com/5459941/182744408-2ddc101f-a54e-46cd-9a37-d4b16a7104da.gif)

Those world editing programs break the heightmap which JM needs. Try this

**Comment by darthvader45** [comment]
Thanks, that'll fix it for sure.  Is this only for new versions like 1.16.5, or all versions of Journeymap?

**Comment by mysticdrew** [comment]
All versions of Journeymap rely on chunk heightmaps. Many world editing programs break the heightmap and sometimes converting worlds from old versions of MC to new versions will not update the heightmaps correctly.
