### ISSUE TITLE
[Suggestion] Hotkey to toggle waypoint visibility

### ISSUE THREAD

**Issue by Nevrai** [TeamJM/journeymap#487]
The “toggle all waypoints” hotkey toggles all waypoints on or off, which is counter-intuitive if some of your waypoints are disabled. I find myself always having waypoints that are toggled off that I don’t want to delete, but this hotkey toggles them all on.

I think that it would be incredibly nifty to have a hotkey that toggles the visibility of all enabled waypoints, meaning that all your enabled waypoints are hidden and, when pressing the hotkey again, are unhidden, without toggling on the waypoints that were already disabled.

Using version 5.9.0beta1-forge for 1.18.2.

**Comment by mysticdrew** [comment]
I changed the logic of the disable waypoint key. It no only toggles rendering of the waypoints, it saves the value so it will remain on exiting and reentering the game.  It no longer flips the enabled flag in the waypoint json. 

This will be in the next major release, i will close this ticket when it is released.

**Comment by mysticdrew** [comment]
Cleaning up the issue tracker
Closing as this is completed for JourneyMap v6 when it is released.
