### ISSUE TITLE
critical error was encountered

### ISSUE THREAD

**Issue by godKrampus** [TeamJM/journeymap#488]
journeymap-1.19-5.8.5-forge

Forge Version: 1.19.2 43.0.0

MC<version> 1.19.2

I only have forge and I took out all my mods so I could find the one making this. I put only the map mod in my folder. It then gave me this... I have got forge 1.19.2 and I have looked throw all my mods, I only have 3. I keep getting this 

internal exception org.spongepowered.asm.mixin.transformer.throwables.mixintransformererror: an unexpected critical error was encountered 

I only have forge and that's it. I don't understand why it is doing this. Is there anything I can do to fix this? I have only ever use forge,
Thank you for your help.

**Comment by mysticdrew** [comment]
1.19 is not compatible with 1.19.1 or 1.19.2

**Comment by e-motiv** [comment]
For anyone bumping here, I use journeymap-1.19.1-5.9.0beta2-forge and it solved this error.
