### ISSUE TITLE
Issue Disabling Cave Mapping in Overworld [1.18.2]

### ISSUE THREAD

**Issue by digitaltrucker** [TeamJM/journeymap#490]
MC 1.18.2 Singleplayer
Fabric 0.14.9
Journeymap 1.18.2-5.9.obeta1
Fabric API 0.58.0+1.18.2

1.  Explicitly disable cave mapping in the overworld via Server Admin settings
2.  Travel from Nether to Overworld (note your coords while in the nether)
3.  The Overworld map will be centered on what your coords were in the Nether.
4.  Reverting to default settings (allowing cave mapping in Overworld) resolves the problem.

Latest log ->  https://pastebin.com/43zXGzc0
Journeymap log ->  https://pastebin.com/WS7euJxL

**Comment by mysticdrew** [comment]
This is super weird, thanks for details to replicate it!

**Comment by mysticdrew** [comment]
Sorry for the delay here. I am unable to replicate this.

**Comment by mysticdrew** [comment]
Are you able to get a video of this happening?

**Comment by mysticdrew** [comment]
Closing as I have been unable to reproduce this and no response from reporter. 
If this issue happens again, please reopen it.
