### ISSUE TITLE
[Feature Request] Add weather as an option to display in an info slot on the minimap

### ISSUE THREAD

**Issue by M1CR0H4CK3R** [TeamJM/journeymap#491]
I want to be able to tell if it's raining when underground, and in the MC 1.7.10 version handled by techbrew, it was possible to set an info slot to display the weather, but at some point that feature was removed. I would like it to be reimplemented at some point, and it should be relatively simple to query the game client for the weather and display the result in an info slot, coming from a person who has coded one Java JAR of his own.

**Comment by mysticdrew** [comment]
> and in the MC 1.7.10 version handled by techbrew
This was never part of journeymap, I looked through the old source code. 

> coming from a person who has coded one Java JAR of his own.
?? this is not needed and feels passive aggressive, but good for you? I am very confused by this statement.

While it may be easy to get the weather, it may not. I will have to look into it. As I said in discord, I will look into adding it.

**Comment by mysticdrew** [comment]
So, if you are using 1.16.5+ you can add this feature via the API with your own mod. You can add custom infoslots with the api. 
I am currently on a feature freeze meaning no new features until 5.9.0 is released. Then I will only be developing for 1.19.2+.

**Comment by M1CR0H4CK3R** [comment]
> So, if you are using 1.16.5+ you can add this feature via the API with your own mod. You can add custom infoslots with the api. I am currently on a feature freeze meaning no new features until 5.9.0 is released. Then I will only be developing for 1.19.2+. It will likely be a few months before I start adding new features.

I'm using a server, and have no control of the included mods, and besides, the server is using 1.12.2, not 1.16.5.

**Comment by mysticdrew** [comment]
This is added for the next major release

**Comment by mysticdrew** [comment]
Cleaning up the issue tracker
Closing as this is completed for JourneyMap v6 when it is released.
