### ISSUE TITLE
[1.18.2] Cave Layers Vertical Chunk Scale Does Not Match Overworld Height

### ISSUE THREAD

**Issue by Darkosto** [TeamJM/journeymap#492]
Hello!

Since 1.17, dimensions can go from Y=-2048 to Y=2048. In my current modpack, the Overworld is Y=-64 to Y=750. The Vertical Chunk scale cannot reach to the top of the overworld is unable to map anything about 255. Would you be willing to look at increasing this distance for worlds that are outside of the normal height ranges. To add to this, vanilla worlds are not 256 build height any longer. This was changed to Y=320

#### JourneyMap Version:
5.9.0beta1

#### Forge Version:
40.1.73

#### Describe the problem in repeatable steps:

1. See above
2. ???
3. Profit!

**Comment by mysticdrew** [comment]
This has been resolved and will be in the next update.

**Comment by mysticdrew** [comment]
fixed in beta3, available once approved on CF
