### ISSUE TITLE
Feature Support: Show Loaded Chunks

### ISSUE THREAD

**Issue by Boobies** [TeamJM/journeymap#493]
It would be very useful for technical players, who often use chunk loaders as part of their worlds, to be able to see which chunks are currently loaded on the full-screen map. This would obviously require server-side support.

There is one mod that I know of which supported this feature, however it is currently unmaintained: Just Map. However, it did not differentiate between the different types of chunk loading tickets. It would be nice if the overlays were rendered in different colors. The types of chunks players would specifically be interested in are:

1. Entity-processing chunks
2. Lazy chunks (redstone is processed but entities are not)
3. Border chunks (only block events are processed)

Thanks.

**Comment by gdude2002** [comment]
This feels entirely out of scope to me, and it's something that would be quite doable as a feature in a third party addon.

**Comment by mysticdrew** [comment]
This would be great for an addon as gdude stated. I will unlikely add this to journeymap.

**Comment by mysticdrew** [comment]
Let your chunk loader mod devs know, and they can add support. It is very easy to use our API to create overlays on the map

**Comment by Boobies** [comment]
> Let your chunk loader mod devs know, and they can add support. It is very easy to use our API to create overlays on the map

Which chunk loader mods? I wasn't talking about any mods, keeping chunks loaded in vanilla in the absence of players is possible with portals and it's useful to see which are loaded. At any rate, I understand if you don't want to add this, just clarifying because this was nothing to do with chunk loading mods.

**Comment by mysticdrew** [comment]
I'll consider it. I will reopen this ticket.

**Comment by mysticdrew** [comment]
![java_cv1JdmuTMt](https://github.com/user-attachments/assets/698cd31e-c242-48cc-a4a2-a5372a34c8a6)

So I am doing some testing with adding this, I may look at differentiating chunks, but right now I am just showing "All" loaded chunks in this test.

**Comment by mysticdrew** [comment]
New options in the multiplayer setting, these are only enabled for opped users. This will be available in 1.21-6.0.0.beta.21 when I release it.
![image](https://github.com/user-attachments/assets/fdf8a561-5598-4a14-a3a0-0a5b7fb05836)
![image](https://github.com/user-attachments/assets/dc265251-0bc9-4e8b-8fbc-4271e527fd2d)
