### ISSUE TITLE
[1.18.2] The minimap resets back to its default configuration on game reload

### ISSUE THREAD

**Issue by Vapaman** [TeamJM/journeymap#494]
#### JourneyMap Version:
1.18.2-5.9.0beta2

#### Forge Version:
1.18.2-40.1.73

#### Describe the problem in repeatable steps:

1. Configure minimap, for best results disable it entirely
2. Reload the game
3. The minimap is in its default configuration
4. It fixes itself when options menu is opened

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
Highlight added to the bit that seems relevant

Full log: https://pastebin.com/prHsvYed

**Comment by mysticdrew** [comment]
Couple things. 
Please do not paste raw logs like that anymore. It is a pain to read. 
Second, what do you mean by **Configure minimap**? 

Did you do something with a resource pack? Looks like part of the exception is coming from reloading resources.

**Comment by mysticdrew** [comment]
Unable to replicate.
User failed to respond.
Closing until more details are provided.
