### ISSUE TITLE
[1.19] Pressing Z to toggle all waypoints breaks the textures

### ISSUE THREAD

**Issue by Spuunj** [TeamJM/journeymap#495]
JourneyMap Version: 1.19 - 5.8.5
Forge Version: 1.19 - 41.0.105

#### Describe the problem in repeatable steps:

1. I load into a world and press the Z key to toggle the waypoints
2. Every time I press Z, whether enabling or disabling the waypoints, the map in the top corner goes funky
3. Some mob textures as well as UI textures (inside of chests for example) get screwed with. It's always random which ones, but for example wither skeletons looked like floating gold armor

**Comment by mysticdrew** [comment]
Remove optifine. Update to 1.19.1/2 and use 5.9.0 which fixes this issue
