### ISSUE TITLE
[1.19.2] Immediate Respawn gamerule not creating a death waypoint

### ISSUE THREAD

**Issue by TheMaskedGamer06** [TeamJM/journeymap#497]
#### JourneyMap Version:

journeymap-1.19.1-5.9.0beta2

#### Forge Version:

1.19.2 - 43.1.1

#### Describe the problem in repeatable steps:

1. Set the Immediate Respawn gamerule to true
2. Kill yourself
3. Look for a death waypoint

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

No relevant errors

**Comment by mysticdrew** [comment]
Will be fixed in the next release, I will close this issue when it is published

**Comment by mysticdrew** [comment]
This issue is resolved and in beta for for 1.18.2 and 1.19.3 for both fabric and forge. 
Download here:
https://www.curseforge.com/minecraft/mc-mods/journeymap/files
https://modrinth.com/mod/journeymap/versions
