### ISSUE TITLE
[1.19.2] [beta] [forge] JourneyMap does not update for client when connected to a forge server

### ISSUE THREAD

**Issue by FrederickEngelhardt** [TeamJM/journeymap#499]
Thank you so much for creating this wonderful mod for minecraft!
  
#### JourneyMap Version:

`[journeymap-1.19.1-5.9.0beta2-forge](https://www.curseforge.com/minecraft/mc-mods/journeymap/files/3927230)`

#### Forge Version:

`Example: 1.19.2-43.1.16`

#### Describe the problem in repeatable steps:

The player map does not sync with the server map. The player map may start writting, but when you disconnect it will refresh to the server map and the player map will refuse to write. Going to the nether (or perhaps another dimension) will allow the player map to start mapping again, it will then reset again if you log off.

Steps

1. Player joins, (fly around a bit to write to the world map)
2. Disconnect and reconnect.
3. Notice that there is no map data for the areas your discovered
4. Attempt to move around in this broken state will refuse to load the area around you.
5. Go to the nether (or perhaps the end or another dimension)
6. Fly around (and map the area)
7. Come back to the overworld, it should map again.
8. Leave the game
9. Return to the game
10. Notice that the map has reset back to whatever was loaded in the initial server area.

**This issue only occurs when using the 1.19.1-5.9.0beta2 version on a forge server with the same version for client.** 

Also a quick workaround is if you _use the 1.19.1-5.8.5 version on the forge server_ it will work _with the 1.19.1-5.9.0beta2 client_ IE disconnecting and reconnecting retains the player map.

Noting that the global config for everything is was set like this (I did not modify and default configs)
```
{
  "journeymapEnabled": "true",
  "useWorldId": "true",
  "viewOnlyServerProperties": "true",
  "allowMultiplayerSettings": "ALL",
  "worldPlayerRadar": "ALL",
  "worldPlayerRadarUpdateTime": "5",
  "seeUndergroundPlayers": "ALL",
  "hideOps": "false",
  "hideSpectators": "false",
  "allowDeathPoints": "true",
  "showInGameBeacons": "true",
  "allowWaypoints": "true",
  "teleportEnabled": "true",
  "renderRange": "0",
  "surfaceMapping": "ALL",
  "topoMapping": "ALL",
  "biomeMapping": "ALL",
  "caveMapping": "ALL",
  "radarEnabled": "ALL",
  "playerRadarEnabled": "true",
  "villagerRadarEnabled": "true",
  "animalRadarEnabled": "true",
  "mobRadarEnabled": "true",
  "configVersion": "5.9.0beta2"
}
```

**Comment by mysticdrew** [comment]
I need log files.. 
I also do not understand what you mean by server map? Journeymap does not have a server map. No mapping is done on the server. It is all done on the client.

**Comment by mysticdrew** [comment]
Unable to replicate.
User failed to respond.
Closing until more details are provided.

**Comment by superdusto** [comment]
A friend on my server is having this issue. How should I go about getting you his logs?
