### ISSUE TITLE
Issues tab on curse does not lead to this tracker

### ISSUE THREAD

**Issue by C0rn3j** [TeamJM/journeymap#50]
https://minecraft.curseforge.com/projects/journeymap

Issue tab leads to https://minecraft.curseforge.com/projects/github.com/TeamJM/journeymap/issues which does not even exist.

**Comment by Laike-Endaril** [comment]
I noticed this as well, had to google for the issue tracker to find it.

**Comment by mysticdrew** [comment]
I hope to have access to curse, when I have access I will fix this. I cannot fix it currently.

**Comment by mysticdrew** [comment]
Fixed!

**Comment by C0rn3j** [comment]
That took a while, but better later than never!

**Comment by mysticdrew** [comment]
well, I just got access to be able to do it.
