### ISSUE TITLE
[1.19.2] GUI Crash with Journeymap

### ISSUE THREAD

**Issue by ToastiMan** [TeamJM/journeymap#503]
#### JourneyMap Version:

`Example: 1.12.1-5.5.0`

#### Forge Version:

jei-1.19.2-forge-11.3.0.262.jar

#### Describe the problem in repeatable steps:

1. Load into a SP World
2. Fly around in Creative Mode for a bit
3. GUI Crashes.
4. look into latest.log and find it's this error: 

[13:24:00] [Render thread/WARN] [JMLogger] java.lang.Throwable: GL Error in method: disableBlend ERROR: 1281
[13:24:00] [Render thread/ERROR] [JMLogger] GL Error in method: enableTexture ERROR: 1281 (SUPPRESSED)

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

[latest.log](https://github.com/TeamJM/journeymap/files/9638586/latest.log)
[journeymap.log](https://github.com/TeamJM/journeymap/files/9638588/journeymap.log)

**Comment by mysticdrew** [comment]
What do you mean "Gui crashes"? Screenshot maybe? There is no crash in the logs

**Comment by mysticdrew** [comment]
Also provide your journeymap version

**Comment by ToastiMan** [comment]
> What do you mean "Gui crashes"? Screenshot maybe? There is no crash in the logs

my fault, copied the wrong filename:

journeymap-1.19.1-5.9.0beta2-forge

Screenshot is coming up shortly, i'm trying to figure out if it's just a problem on my end

**Comment by ToastiMan** [comment]
Can be closed, was a combination of the journeymap-beta not working with my version of the graphics drivers.

**Comment by mysticdrew** [comment]
> Can be closed, was a combination of the journeymap-beta not working with my version of the graphics drivers.
That is interesting, thanks for letting me know. 
If it happens again, try to get a screenshot.
