### ISSUE TITLE
Unknown custom packet identifier: journeymap:player_loc

### ISSUE THREAD

**Issue by Xetaxheb** [TeamJM/journeymap#504]
#### JourneyMap Version:

journeymap-1.18.2-5.8.5-forge.jar

#### Forge Version:

1.18.2-40.1.80

#### Describe the problem in repeatable steps:

1. Server has journeymap
2. Client does not have journeymaop
3. Client gets spammed with journeymap:player_loc packets

 [Render thread/WARN] [minecraft/ClientPacketListener]: Unknown custom packet identifier: journeymap:player_loc

**Comment by mysticdrew** [comment]
update to 5.9.0beta2
