### ISSUE TITLE
[1.16.5-5.8.5p5] Pixelmon 1.16.5-9.0.10 visual bug with Raid Dens.

### ISSUE THREAD

**Issue by KittyKatzyn** [TeamJM/journeymap#506]
#### JourneyMap Version:
JourneyMap-1.16.5-5.8.5p5.jar

#### Forge Version:
Forge 1.16.5-36.2.34

#### Describe the problem in repeatable steps:

In Pixelmon (as per Pokemon), Max Raid Dens are intended to display a red shaft of light into the sky to indicate the raid is available to be battled.  Currently, when you have the latest version of JM, this light turns white, making it difficult to see against snowy biomes.

1. Install the latest version of Pixelmon (current version is 1.16.5-9.0.10).
2. Install the latest version of JM (current version is 1.16.5-5.8.5p5).
3. Once the game loads up, start a new singleplayer creative world.
4. Upon loading into the world, you will be asked to choose a starter pokemon - please choose Litten because it's a very cute kitty.
5. "/give pixelmon:den_spawner" in chat.
6. Put the den spawner in your hand and right-click the ground to place a raid den.
7. Sometimes they can spawn as activated - if no light is visible, "/give pixelmon:wishing_piece" in chat and continue on to step 8.
8. Put the wishing piece in your hand and right-click on the den you spawned, to "summon" a pokemon to the den - the activation light should appear now, shooting upwards into the sky.

#### Screenshots:
A normal, unactivated den:
![image](https://user-images.githubusercontent.com/103725578/193174077-812982f7-aaf7-4210-a445-489853dd1cf6.png)

An activated den as intended by Pixelmon, without JM:
![image](https://user-images.githubusercontent.com/103725578/193174376-cf0005a2-ef26-4f83-9097-aeea49283868.png)

An activated den with JM:
![image](https://user-images.githubusercontent.com/103725578/193174194-633db524-245d-47f1-a90f-744cb535b5e7.png)

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
Nothing of note.

#### Side note from Pixelmon Devs:
"JourneyMap bug - unreset GL flag or something along those lines, likely to do with blend function"

**Comment by mysticdrew** [comment]
1.16.5 is no longer updated. Sorry, this won't get fixed.

**Comment by mysticdrew** [comment]
I lied, I found the issue and it was a simple fix. P6 will be released shortly.

**Comment by KittyKatzyn** [comment]
Thank you Drew, we really appreciate this :)  

![image](https://user-images.githubusercontent.com/103725578/193373307-d694debd-e49c-4b15-bbf8-234226a6584d.png)
