### ISSUE TITLE
[Bug]: Using a non slash prefix for custom waypoint tp command not working

### ISSUE THREAD

**Issue by Markrealhd** [TeamJM/journeymap#509]
Earlier it was possible to use commands with custom prefixes like . # + for example but now a / is automatically put in front of it which makes this impossible. I hope that the function to use your own prefixes will come back soon because it didn't harm anyone and was just practical.

**Comment by gdude2002** [comment]
I don't think this is related to JourneyMap - can you elaborate?

**Comment by mysticdrew** [comment]
We never had a custom prefix on the custom waypoint tp command.

**Comment by Markrealhd** [comment]
What? There was and still is a Custom Waypoint Teleport Command, it was changed a little bit in the last journeymap update like described in the Suggestion. It is used with the teleport button in the waypoint manager or is this not the journeymap that I think it is?

**Comment by mysticdrew** [comment]
> Earlier it was possible to use commands with custom prefixes like . # + 

Is wrong, this was never a feature for our custom waypoint teleport commands. Are there servers that actually use a non / prefix for commands?

**Comment by Markrealhd** [comment]
Yes there are some Plugins and also Client Side Mods that use . or + for example. 
I am able to use commands like +tp x y in Version 5.8 of Journeymap and they are executed without / in Chat but this is not working anymore in 5.9.
Or is it a bug that I am able to do that?
But even if it was a bug i think it should be a Feature in newer Versions.
I was able to perfectly use Baritone with Journeymap in Singleplayer by typing #goto x y as Teleport Command and by clicking teleport in the waypoint manager it startet Baritone.

**Comment by Markrealhd** [comment]
Yes there are some Plugins and also Client Side Mods that use . or + for example. 
I am able to use commands like +tp x y in Version 5.8 of Journeymap and they are executed without / in Chat but this is not working anymore in 5.9.
Or is it a bug that I am able to do that?
But even if it was a bug i think it should be a Feature in newer Versions.
I was able to perfectly use Baritone with Journeymap in Singleplayer by typing #goto x y as Teleport Command and by clicking teleport in the waypoint manager it startet Baritone.

**Comment by mysticdrew** [comment]
Seems like a bug then as this logic never changed. 
Are there errors in your logs when you try executing a command with a non / prefix?

**Comment by Markrealhd** [comment]
I am not at home right now so I cant test for Errors but i dont think that there are some. But in 5.9 it says in Chat that this Command doesnt exists and in 5.8 it just executes the Command.

**Comment by mysticdrew** [comment]
This is due to changes in minecraft 1.19.1/2
I do not have a way to test this on a server with special commands. 
When you get home, head to our discord make a post in #jm-support, be sure to read the READ FIRST post. I can get you a test version to verify if my changes work.

**Comment by Markrealhd** [comment]
Okay thank you, a test version would be nice too.

**Comment by mysticdrew** [comment]
are you planning on joining our discord to test this change?

**Comment by Markrealhd** [comment]
oh yes i saved this bug but forgot about it, thanks for remembering i will join and test it.

**Comment by Markrealhd** [comment]
#jm-support is archived, i posted it in #jmi.

**Comment by mysticdrew** [comment]
jm support is not archived create a new post in there
JMI is not the place to post, that was deleted. That is for the mod journeymap-integrations please read how our discord works.

**Comment by mysticdrew** [comment]
fixed in beta3, available once approved on CF
