### ISSUE TITLE
Strange points and display of objects on the map

### ISSUE THREAD

**Issue by SlavaUkrainy** [TeamJM/journeymap#510]
Hello! I had a problem: I used the WorldPainter program, where you can change the landscape in minecraft. In order for the changes to be saved, it is necessary to merge the chunks in which these changes occurred. After I combined these chunks, I had some points on the map. Updating the color palette, deleting the map, deleting chunks, changing the biome via WorldEdit did not help. The only thing I did was to connect my world with another world in the Amulet program. After that, some chunks began to display normally on the map, but some still contain points. What to do with it? Thanks in advance!

Journeymap version 1.17.1-5.8.0
ForgeOptifine version 1.17.1

![2022-10-02_14 15 57](https://user-images.githubusercontent.com/114859449/193451169-8a7b6222-d8ae-4a45-8040-7dd808a5965e.png)

**Comment by mysticdrew** [comment]
fix: https://github.com/TeamJM/journeymap/issues/486#issuecomment-1204660977

**Comment by SlavaUkrainy** [comment]
> fix: [#486 (comment)](https://github.com/TeamJM/journeymap/issues/486#issuecomment-1204660977)

Thank you!
