### ISSUE TITLE
[1.19.2] Fabric - StackOverflowError when using Fabric Yarn Mappings for plugin creation

### ISSUE THREAD

**Issue by Talon396** [TeamJM/journeymap#514]
#### JourneyMap Version:
1.19.1-5.9.0beta2-fabric

#### Fabric Version:
0.14.9

#### Describe the problem in repeatable steps:
1. Run "Minecraft Client" using IntelliJ IDEA
2. Mod crashes due to `java.lang.StackOverflowError`

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
```
[18:45:39] [Render thread/ERROR] [ThemeLoader] Error preloading theme textures: java.lang.StackOverflowError
	at journeymap.client.texture.DynamicTextureImpl.getImage(DynamicTextureImpl.java:146)
	at journeymap.client.texture.DynamicTextureImpl.getImage(DynamicTextureImpl.java:146)
	at journeymap.client.texture.DynamicTextureImpl.getImage(DynamicTextureImpl.java:146)
	at journeymap.client.texture.DynamicTextureImpl.getImage(DynamicTextureImpl.java:146)
... There's about 3000 more times this function is mentioned in the stack backtrace.
```

**Comment by Talon396** [comment]
Wait, I figured out the problem. Please disregard this issue.

**Comment by mysticdrew** [comment]
What was the issue?

**Comment by Talon396** [comment]
It was happening while using InteliJ IDEA to create a plugin for this mod. It works just fine with normal Minecraft without using any kind of development environment.

**Comment by Talon396** [comment]
Actually this might be a viable issue.

**Comment by mysticdrew** [comment]
Share your build.gradle

**Comment by Talon396** [comment]
Here you go: [build.gradle](https://github.com/TeamJM/journeymap/files/9843212/build.gradle.txt)

**Comment by mysticdrew** [comment]
Do you have a repo for your mod that you're working on?

**Comment by Talon396** [comment]
Yes, it can be found at: https://github.com/Talon396/EnhancedWeather

**Comment by mysticdrew** [comment]
Oh ok, so this is already fixed in my internal builds, come to our discord and I can give you a build. I fixed this last week, but I have not released it yet. 

The issue stems from the fact that I dev using mojangmaps and you're using yarn. 
MojangMaps getPixels() == Yarn getImage(). I use a getImage method in my class that calls super.getPixels().

My getImage method. 

MojangMaps
```
    public NativeImage getImage() {
        return super.getPixels();
    }
```
Yarn
```
    public NativeImage getImage() {
        return this.getImage();
    }
```

**Comment by Talon396** [comment]
Ah that makes sense. I went ahead and joined the discord server. Thanks for pointing that out.

**Comment by mysticdrew** [comment]
fixed in beta3, available once approved on CF
