### ISSUE TITLE
[1.18.2] Minimap overflow of MapFrontiers region's names

### ISSUE THREAD

**Issue by moninformateur** [TeamJM/journeymap#518]
#### JourneyMap Version:
JourneyMap: 1.18.2 - 5.8.5
MapFrontiers: 1.18.2 - 2.3.4
#### Forge Version:
40.1.73

#### Describe the problem in repeatable steps:

1. Load both JourneyMap and MapFrontiers
2. Create a new Frontier/Region
3. Walk out of range of said region, have the region's name overflow from JourneyMap's minimap.

#### Screenshot
![unknown](https://user-images.githubusercontent.com/79221061/198840379-b3cde8e1-0bd1-4709-b9e0-c187f8bc8b3b.png)

**Comment by mysticdrew** [comment]
This will be fixed in the next release. I will close it when the next release is published

**Comment by mysticdrew** [comment]
This issue is resolved and in beta for for 1.18.2 and 1.19.3 for both fabric and forge. 
Download here:
https://www.curseforge.com/minecraft/mc-mods/journeymap/files
https://modrinth.com/mod/journeymap/versions
