### ISSUE TITLE
[1.19.2] I keep having random crashes while using JourneyMap

### ISSUE THREAD

**Issue by stantios** [TeamJM/journeymap#522]
#### JourneyMap Version:

`5.9.0beta-2`

#### Quilt Version:

`Quilt Loader - 0.17.6`

#### Describe the problem in repeatable steps:

1. Download Quilt Loader - 0.17.6
2. Add JourneyMap and Quilted Fabric API / QSL
3. Load up Minecraft
4. Go into either a server or single player world
5. Click J to open World Map and click J again to exit (This happens with any keybind that is 'Show / Hide Fullscreen Map')
6. You've got a crash!

#### Relevant errors / logs

https://mclo.gs/pjrpBUn

**Comment by mysticdrew** [comment]
Please try with the newly released beta3 and updated qsl.

**Comment by mysticdrew** [comment]
Check discord, Triphora mentioned it may be a bug with QSL
