### ISSUE TITLE
*Suggestion* Ability to remove teleporting dimension to dimension but still keep teleporting to waypoints in dimension

### ISSUE THREAD

**Issue by Awilddraw4** [TeamJM/journeymap#525]
Might be weird but I give my players the ability to teleport to way-points but ive found with this you can make a way-point in a dimension you've never been to. I want to still let them teleport to way-points but not dimension to dimension.

**Comment by mysticdrew** [comment]
added for 6.0

**Comment by mysticdrew** [comment]
Cleaning up the issue tracker
Closing as this is completed for JourneyMap v6 when it is released.
