### ISSUE TITLE
Suggestion: Implementation of Open Parties and Claims

### ISSUE THREAD

**Issue by notIkibo** [TeamJM/journeymap#527]
I know this has a FTB support with chunks though for FTB, it's three mods you need (lib, chunks and teams) for the same functionality. And this one even has force chunks where I'm not so sure, if FTB chunks has that.
FTB is really clogging up the modlist and that would be refreshing to see different options at least?

**Comment by gdude2002** [comment]
JM has never had features like this, and I believe the developers consider it out of scope. This is already a very large project.

**Comment by notIkibo** [comment]
I already talked to the developers and didn't have a problem with a support. I'm not saying that Journeymap should have it implemented as in "in code", but "a support" for that. Just like a support for waystones or ftb chunks. So it's also not uncharacteristic to JM.

I generally think that the stated mod is more polished than ftb and is getting fairly regular updates. I have been able to test them both and it's just a nice-to-have as mods should be.

**Comment by mysticdrew** [comment]
Journeymap does support this through our API, FTBUtils has integration. FtbChunks has integration if the mod JMI(Journeymap Integration) is used along side both. 

If you wish to create a mod that does this, we can help direct and guide you with the integration points. Head to our discord and use the jm-projects channel. 

I will close this issue as we already provide support via our api.
