### ISSUE TITLE
[1.19.2] Players Name not showing on minimap

### ISSUE THREAD

**Issue by 147panda** [TeamJM/journeymap#528]
#### JourneyMap Version:
journeymap-1.19.2-5.9.0beta3-forge

#### Forge Version:
Forge - 43.1.1

#### Issue ####
Since the last update of JourneyMap i've done from my Curseforge own modpack,
All players name don't show on the minimap i've tried to uncheck - check the option to Show Entity Name but still nothing
i've read my logs and there are no errors.

**Comment by mysticdrew** [comment]
Are players showing up, just not their names?

**Comment by 147panda** [comment]
Yes i have players icons but not the name.

**Comment by mysticdrew** [comment]
Attach your journeymap.log and latest.log when you do too please.

**Comment by 147panda** [comment]
As said there are 3 screens
![Journeymap_minimap_1](https://user-images.githubusercontent.com/14365833/203821481-6b3b5a5d-7565-4d14-b013-41921357c6ba.jpg)
The icon of my friend showing on the minimap

![Journeymap_minimap_3](https://user-images.githubusercontent.com/14365833/203821993-9e5fa436-da9c-437a-97c8-030e978b64ee.jpg)
The icon + name on the fullscreen map

![Journeymap_minimap_2](https://user-images.githubusercontent.com/14365833/203821486-e9d4a7b0-da89-4e03-aab8-c09a075672f7.jpg)
My minimap settings

and for the last part the logs
[latest.log](https://github.com/TeamJM/journeymap/files/10085835/latest.log)
[journeymap.log](https://github.com/TeamJM/journeymap/files/10085839/journeymap.log)

**Comment by mysticdrew** [comment]
Try removing optifine and see if that resolves it.

**Comment by 147panda** [comment]
Same issue with optifine removed
![Journeymap_minimap_4](https://user-images.githubusercontent.com/14365833/204100184-a9dfc50c-8a73-4ba9-99e3-ec9e3282edf7.jpg)
![Journeymap_minimap_5](https://user-images.githubusercontent.com/14365833/204100191-f9143af1-b16a-46c1-916f-ee76b3b2338a.jpg)
[latest.log](https://github.com/TeamJM/journeymap/files/10096678/latest.log)
[journeymap.log](https://github.com/TeamJM/journeymap/files/10096679/journeymap.log)

**Comment by mysticdrew** [comment]
I think there may be an issue with another mod but not sure which one. 
You may need to try removing some mods to find the culprit. Start with clientside only mods.

**Comment by mysticdrew** [comment]
Oh, waypoint labels are also not showing up? 

Alright so to make this easier to figure out the mod, load up a singleplayer world and verify that waypoint labels also do not show up in singleplayer. 
If they do not show up in singleplayer first thing to do. 
- Exit minecraft, go to your minecraft install folder and find the journeymap folder. 
- Delete the config directory and only the  config directory. This will not cause you to lose any map data.
- Start minecraft and see if that fixed it. 

If that did not fix it. 
- Exit minecraft
- Disable all mods other than Journeymap. 
- Check your singleplayer world if Waypoint labels are showing up. 
- If they are, it is mod conflict. 
- If they do not display, it is a Journeymap problem. if that this point it is in fact a JM problem. It may be a good idea to come into our discord so we can figure this out and get it resolved. 

If the labels show up start adding mods back in until you find the one that causes the labels to not display and let me know which mod. 
Use the binary search for finding the culprit mod. 
```
The binary search is a way of finding a faulty thing among a lot of other things, without having to remove the things one-by-one.
This is useful for finding a broken mod among hundreds of mods, without having to spend time testing the mods one-by-one.
The procedure is simple:
  1. Remove half of the existing things, and put them aside.
  2. Run the program / game.
  3. Does the issue still exist?
    If YES: Repeat from step 1 with the current things.
    IF NO: Swap out the current things with the ones set aside, and repeat from step 1.
  4. Repeat this process until the problematic thing/s have been found.
  ```
  
  If you need any help with this, come to our discord server.

**Comment by 147panda** [comment]
Deleting the JourneyMap config folder had fix the issue.

Thanks Mysticdrew
