### ISSUE TITLE
can't find option to modify zoom level in minimap

### ISSUE THREAD

**Issue by joecabezas** [TeamJM/journeymap#531]
self explanatory, I cant find a way to modify the zoom level of the minimap, the only way I found is to modify the `journey.minimap.config`, file, and increase the `zoomLevel` config, is there a way to modify this value in the UI in game?
  
#### JourneyMap Version:
journeymap-1.19.2-5.9.0beta3-forge

#### Forge Version:
forge-1.19.2-43.1.58

**Comment by mysticdrew** [comment]
+ and - keys. 
It says that in the key overlay on the Fullscreen map

**Comment by joecabezas** [comment]
thanks, it was not clear that this will also affect the minimap, also, the keys for me are = and - keys:
![image](https://user-images.githubusercontent.com/110182/204804773-ec76cbc8-747e-4457-8d1b-e51792f7e76f.png)

reclosing this, thanks for your time
