### ISSUE TITLE
[Suggestion] Change the way the maps *discover* chunks

### ISSUE THREAD

**Issue by MIfoodie** [TeamJM/journeymap#535]
I don’t know if you could do this but if you could make a feature where you only discover chunks that you have seen? For example if there’s a huge mountain in front of you and you haven’t visited that area before the map doesn’t load chunks behind that mountain. This makes adventuring better because you can’t just walk around and look at the map to find structures.

**Comment by mysticdrew** [comment]
This is not really possible with current systems in MC, sounds cool though.
