### ISSUE TITLE
Webmap returns 404 with Quilt Loader 0.18.1-betas

### ISSUE THREAD

**Issue by kohanis** [TeamJM/journeymap#536]
#### JourneyMap Version:

Checked 1.19.2-5.9.0beta5-fabric and 1.18.2-5.9.0beta5-fabric

#### Describe the problem in repeatable steps:

Even in the game menu webmap shows "404 Not found" with any quilt loader 0.18.1-beta versions I tested and works just fine with 0.17.7

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

Nothing

**Comment by mysticdrew** [comment]
Provide your journeymap.log and your latest.log files.

**Comment by mysticdrew** [comment]
This seems to be a quilt-loader beta issue. You should also report it to them.
