### ISSUE TITLE
[suggestion] Ability to delete certian parts of a map ingame

### ISSUE THREAD

**Issue by DisPie** [TeamJM/journeymap#542]
![image](https://user-images.githubusercontent.com/62095484/208993774-c801231c-0f76-46b4-b170-715e9bb9979b.png)
select the area on the map to delete the part of the map.

-maybe also move certain parts of the map to other areas of the map so it isn't overlapping.

**Comment by mysticdrew** [comment]
Deleting chunks and/or regions is already planned. 
However moving map tiles is not some that is supported nor will it be.

**Comment by mysticdrew** [comment]
I've added deleting regions to the next major release. 
![java_YtsTy8k1Sg](https://user-images.githubusercontent.com/5459941/217963491-930fb1ed-8a41-435d-a297-f3eb2e21c7ea.gif)

I will close this issue when it is released.

**Comment by mysticdrew** [comment]
Cleaning up the issue tracker
Closing as this is completed for JourneyMap v6 when it is released.
