### ISSUE TITLE
[suggestion] Make it possible to keep the fullscreen buttons hidden

### ISSUE THREAD

**Issue by Cooliosity** [TeamJM/journeymap#543]
Please make it possible to keep the JourneyMap buttons hidden when reopening the fullscreen map.

**Comment by mysticdrew** [comment]
Only bottom buttons?

**Comment by Cooliosity** [comment]
All the buttons, so I don't have to press h everytime I open the map

**Comment by mysticdrew** [comment]
Alright, so in the next major release, the way it works now is you press H, the buttons disappear and stay gone until you either press H again while the fullscreen map is open, or you restart minecraft.

**Comment by Cooliosity** [comment]
very nice thank you

**Comment by Cooliosity** [comment]
Still not there

**Comment by mysticdrew** [comment]
Cleaning up the issue tracker
Closing as this is completed for JourneyMap v6 when it is released.
