### ISSUE TITLE
[Feature Request] Display Movement Speed

### ISSUE THREAD

**Issue by alison-gravley** [TeamJM/journeymap#544]
I do not know the feasibility of this, but it would be nice if one of the info options for the minimap could be movement speed. So it is easy to monitor mount speed and things like that.

**Comment by mysticdrew** [comment]
I will add this as a blocks/sec calculation. It will be in the next major release.

**Comment by mysticdrew** [comment]
![java_Aog3vDA9OW](https://user-images.githubusercontent.com/5459941/210156247-f693b54f-36b7-43cb-9c88-b954c10ddd8b.gif)

**Comment by mysticdrew** [comment]
Cleaning up the issue tracker
Closing as this is completed for JourneyMap v6 when it is released.
