### ISSUE TITLE
journeymap, vulkanmodб minecraft 1.19.3

### ISSUE THREAD

**Issue by Genudza** [TeamJM/journeymap#547]
#### JourneyMap Version:

` journeymap-1.19.3-5.9.0-fabric and betas`

#### quilt Version:

`: quilt-loader-0.18.1-beta.27-1.19.3`
quilt-loader-0.17.8-1.19.3

What's up with vulkanmod support now?(I'm playing on version 1.19.3 and quilt mod loader). Either I do something wrong, but with vulkanmod does not work journeymap

1. I tried to leave only two mods (vulkan mod and journeymap) did not work 
2. left all the other mods and journeymap, but moved vulkanmod in another folder and worked
3. left all the mods (including vulkanmod), except for journeymap and it worked
4. I tried to run it on java 17 and java 19 and the result is the same

The specifications of my laptop
Ryzen 7 5800hs
amd ryzen integrated graphics
nvidia rtx 3060 laptop
16 gb ram
[crash-2023-01-06_05.56.25-client.txt](https://github.com/TeamJM/journeymap/files/10357013/crash-2023-01-06_05.56.25-client.txt)

**Comment by mysticdrew** [comment]
@Genudza I contacted the vulkan mod dev. This seem more on their end than mine.

**Comment by Genudza** [comment]
> @Genudza I contacted the vulkan mod dev. This seem more on their end than mine.
> 
> [xCollateral/VulkanMod#174](https://github.com/xCollateral/VulkanMod/issues/174)

thank you

**Comment by Genudza** [comment]
> @Genudza I contacted the vulkan mod dev. This seem more on their end than mine.
> 
> [xCollateral/VulkanMod#174](https://github.com/xCollateral/VulkanMod/issues/174)

Which minimap is compatible?(xaero's minimap doesn't work)

**Comment by mysticdrew** [comment]
Probably none, 
VulkanMod changes a ton of things in the rendering code. 
Anyways, I have given the dev of VulkanMod the solution to fix that mixin, however, even with that fix there are many other problems. 

VulkanMod completely replaces the rendering engine in minecraft, it is great for vanilla and other things. But map mods generally make a bunch of raw opengl calls which breaks VulkanMod. 

You can track the VulkanMod issue that I opened.

**Comment by Genudza** [comment]
ok, thank you
