### ISSUE TITLE
Feature request: enable web map only

### ISSUE THREAD

**Issue by Klyser8** [TeamJM/journeymap#548]
**FEATURE REQUEST**

Feature: _config to disable any type of mapping provided by JourneyMap client and server side._

As I was making a modpack for me and a few friends, I was looking for some form of mapping mod that isn't completely overpowered and makes actual orientation skills useless.
When I found Journeymap, I was hoping to be able to have the browser map enabled server side while the players did not have access to any of map features themselves.

With this, players would be able to see a map of the whole Minecraft world to try to interpret themselves through the web browser version, requiring more skill and better understanding of their surroundings.

To make this work properly, it would be great if there was a way for the mod server side to have an option to fully configure its behavior on clients connecting to the world.

**Comment by mysticdrew** [comment]
The browser map does not run on the server, it is a client webmap, intended for use on another monitor or device in your network. Like a tablet or anther computer even. The webmap is just the fullscreen map in your web browser.

For pure server sided webmaps, bluemap and dynmap are the popular ones.
