### ISSUE TITLE
[1.18.2-Fabric] Unable to enter the game

### ISSUE THREAD

**Issue by denghahaxixi** [TeamJM/journeymap#549]
Since I don't know English, I used a translator, sorry if some words are misnomerous

I clicked the respawn button after dying in survival mode, but after the button responded, I did not respawn but stayed on the death page, I chose to exit, and when I entered the world again, I stayed in the interface of loading the terrain, I checked the background log and found a loop error, and the problem was 100% reproduced in my client

#### Describe the problem in repeatable steps:

1. Die
2. Quit game
3. Join game

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

https://gist.github.com/denghahaxixi/7d16af16efa3c97fa0ffd99251eb4c93
https://pastebin.com/8Buduihi

**Comment by mysticdrew** [comment]
If you install 5.9.0, does this issue go away?

**Comment by mysticdrew** [comment]
> Since I don't know English, I used a translator, sorry if some words are misnomerous

not a problem. 
If you wish to come into our discord, let me know when you have arrived. I can give you a test build that hopefully fixes it. 
This is a weird error that should never happen.

**Comment by mysticdrew** [comment]
I believe this to be fixed, though if you can come into discord to get a test build to verify. I can release it.

**Comment by denghahaxixi** [comment]
I have already tried to install version 5.9.0, but it doesn't work
Because of my region, it was very difficult to connect to Discord. So can you give me another way to connect. I'll also try my best to get into Discord

**Comment by denghahaxixi** [comment]
The reason is that the Prefab mod seems to conflict with this mod, and the problem with me removing this mod has been solved, but even if I delete Prefab I can't enter the old world

**Comment by mysticdrew** [comment]
I'll look into prefab mod

**Comment by mysticdrew** [comment]
This is on modrinth and curseforge now, please update and see if your issue is fixed

**Comment by denghahaxixi** [comment]
Thanks, the latest 1.18.2-5.9.2 version still conflicts with Prefab Mod, it crashes directly and generates an error report when I try to enter the world, it goes back to normal when I delete Prefab

**Comment by denghahaxixi** [comment]
JourneyMap .log everything works fine, crash also has no information about JourneyMap, this issue may not be caused by JourneyMap, sorry

**Comment by denghahaxixi** [comment]
The problem has been solved Thank you

**Comment by mysticdrew** [comment]
if you can provide your latest.log and crash.log from your crash, I can take a look and help identify the issue.

**Comment by denghahaxixi** [comment]
Thanks, but I can't reproduce this issue anymore

**Comment by mysticdrew** [comment]
Oh, that is great!
