### ISSUE TITLE
[1.18.2] Journeymap displays create mod tracks wrongly, and wrong colors for train casing, valves, and bells

### ISSUE THREAD

**Issue by Ch1216** [TeamJM/journeymap#550]
#### JourneyMap Version:

1.18.2 - 5.9.1

#### Forge Version:

1.18.2 - 40.2.0

#### Describe the problem in repeatable steps:

1. Place curve or elevation train tracks / train casing / valves / bells
2. See them displayed how one would think they are in a normal Minecraft map
3. See curve/elevation tracks are not displayed in journey map / See train casings, valves, bells, have wrong colors

#### Relevant info

![ultaimte journeymapthing](https://user-images.githubusercontent.com/68875386/211957652-1f98f732-fed4-43da-a4e6-1d3515d3a785.png)
Showcase of train tracks and train casing issue, with map as comparison

![ofekawsmioe](https://user-images.githubusercontent.com/68875386/212194567-ca4638e5-94ad-40b6-afe3-97e893094e66.png)
Showcase of valves, and bells. same location, with map as comparison, with build that fixes curve train tracks not appearing and train casing color

All color valves are orange, they should match their color
May or may not be important. Valve break particles are undyed

Train casing's id is create:railway_casing

Also happens with [Steam 'n Rails](https://www.curseforge.com/minecraft/mc-mods/create-steam-n-rails) tracks
(Which id's are railway:(woodtype)_track they also have blackstone tracks)

**Comment by mysticdrew** [comment]
seats and toolboxes look fine. They match the texture, I am not trying to replicate the in game map. It uses the material color, Journeymap uses the texture's average color. 
Valves are fixed.

**Comment by mysticdrew** [comment]
on curseforge and modrinth now
