### ISSUE TITLE
[Bug] 1.18.2 Forge Error with Marker Displays

### ISSUE THREAD

**Issue by LunafeyLazuli** [TeamJM/journeymap#551]
#### JourneyMap Version:

journeymap-1.18.2-5.9.1-forge.jar

#### Forge Version:

Forge 40.2.0

#### Describe the problem in repeatable steps:

1. Start the server
2. Run the server for a few minutes
3. Have you and a friend join and it works fine
4. Have a third friend join
5. Game locks up
6. Both players that were on before get timed out from the server with the log below v

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
https://pastebin.com/MPKDKAp2

[journeymap.log](https://github.com/TeamJM/journeymap/files/10400893/journeymap.log)

**Comment by mysticdrew** [comment]
I fixed this already for the next release. It will be in 5.9.2, I will close this ticket when I release it.

**Comment by LunafeyLazuli** [comment]
Sweet thank you!

**Comment by mysticdrew** [comment]
update is on curseforge and modrinth. 5.9.2
