### ISSUE TITLE
My journeymap will create multiply files for a same server

### ISSUE THREAD

**Issue by fank040118** [TeamJM/journeymap#552]
fabric 0.14.12, Minecraft 1.19.3
journeymap 5.9.0 beta 5

Sorry I'm using a Web translator so the gramma looks weird

Sometimes my journeymap will create a new file when I log in to a server that I played before(already have a file for that server), new file doesn't have anything such as routes, or map, it just looks like a world that I never played, when it creates a new file, the new file has the same name but different ID, If it has multiply files and I ignore them, every time I log in the server might switch to different files, I tried to delete those files I don't need, but it will create more after that, this problem never happened in the offline game

for example, if I played  the same server, and log in twice, there will be two files in the [.minecraft\journeymap\data\mp
   Servername_id_00000001
   Servername_id_00000002

I already delete those files to four-five times so there are only two files I left in the screenshot, is that some issue that happened in the server that caused the mod to think it is a different server so it create a new one?

![屏幕截图(35)](https://user-images.githubusercontent.com/69049138/212440272-fa6a23bd-6831-42de-b08a-e5e45a0112cf.png)

**Comment by mysticdrew** [comment]
This is supposed to happen if you enabled mulitworld support in the advanced options. It'll happen on servers that have hubs and such. That id is the identifier. Disable multiworld support to stop it from happening. But, you may get maps from the wrong worlds.
