### ISSUE TITLE
[Feature Request] Change the rendering of shadows

### ISSUE THREAD

**Issue by DaCrazyRaccoon** [TeamJM/journeymap#554]
Feature request: I like to make map arts in my worlds but on JM the way the shadow appears on the map ruins the look of the image I build. I would like a setting that change the way JM renders shadows. Possibly one that renders like minecraft does with maps and one that turns it completely off.

I.E. This is how minecraft renders my map art
![image](https://user-images.githubusercontent.com/79057902/213036294-ff8dc053-284c-4cb1-9fae-47e34781d158.png)

This is how JM renders my map art
![image](https://user-images.githubusercontent.com/79057902/213036407-d4b08f5f-149e-4e90-b8ad-113da98e4f4e.png)

**Comment by mysticdrew** [comment]
![image](https://github.com/TeamJM/journeymap/assets/5459941/3e5cb70e-bc2e-4a67-b8c3-be2f5cfb4ad7)
![image](https://github.com/TeamJM/journeymap/assets/5459941/f50b8c2c-84be-48a0-b0eb-7f7e461f20e5)

Completed for 6.0, will close this when released

**Comment by mysticdrew** [comment]
Cleaning up the issue tracker
Closing as this is completed for JourneyMap v6 when it is released.
