### ISSUE TITLE
[1.12.2] Host can't see players beyond render distance whenever the world is open to LAN

### ISSUE THREAD

**Issue by UnLegitCombos** [TeamJM/journeymap#558]
#### JourneyMap Version:

1.12.2-5.7.1

#### Forge Version:

1.12.2-14.23.5.2860

#### Describe the problem in repeatable steps:

1. Make a singleplayer world
2. Open to LAN
3. Join with another client
4. Host can only see players on both the minimap and bigmap only when they are in render distance, all other players can see everybody else normally

**Comment by mysticdrew** [comment]
1.12.2 is no longer supported. Any issues will remain issues. 
If this is an issue on modern versions for 1.18.2+ I can fix it.
