### ISSUE TITLE
[Suggestions] [1.19.3+] Add entity filters / enable AmbientCreatures viewability

### ISSUE THREAD

**Issue by Emojiime** [TeamJM/journeymap#559]
JourneyMap Version:
1.18.2-5.9.3

Forge Version:
1.18.2-40.1.86

Mysticdrew has suggested this feature be officially requested.

At the moment bats are not displayed on the map. They **are** considered AmbientCreatures but are also a potential source of map clutter for those who don't need them so I had an idea; Viewing Filters

Based on this I suggest implementation via:
1. Have a section in the settings to change which set of creatures you are viewing
2. Have a slider of presets available for which creatures are viewable on the map
3. Have options to view "Normal" "Animals only" "Ambient only" "All" (Or however best worded)

To achieve a QOL improvement for players who require more entity tracking than the current Standard state (as seen by mods that require killing X ambient creatures, et al).

**Comment by mysticdrew** [comment]
So, sadly this wont come to 1.18.2. I will include it in the next major release for 1.19.3+. 
I will add an existing checkbox to Minimap1 Minimap2 and Fullscreen. "Show Ambient Creatures" You can check it and it will show. 

There is an option already for how many entities to show on the map. It is under "Advanced" If it is too small, I can increase the size.

**Comment by Emojiime** [comment]
This would certainly help. Looking forward to it!

**Comment by mysticdrew** [comment]
![image](https://user-images.githubusercontent.com/5459941/218273249-7408ee97-5a0c-42d2-b01f-fa459da16c24.png)
![image](https://user-images.githubusercontent.com/5459941/218273587-c293802c-6064-4369-9a65-e9eef0b65d5a.png)
![image](https://user-images.githubusercontent.com/5459941/218273660-2686e0bb-b34a-41ba-a8bf-2842eaaa839c.png)

**Comment by mysticdrew** [comment]
default will be disabled.

**Comment by mysticdrew** [comment]
Servers disabling this will use the Animals Radar. I am not not creating a new server setting for these.

**Comment by mysticdrew** [comment]
Cleaning up the issue tracker
Closing as this is completed for JourneyMap v6 when it is released.
