### ISSUE TITLE
[1.19.2] Map Does Not Update With Immersive Portals

### ISSUE THREAD

**Issue by PolyframeX** [TeamJM/journeymap#560]
#### JourneyMap Version:

JourneyMap 5.9.3

#### Forge Version:

Fabric 0.14.12

#### Describe the problem in repeatable steps:

1. Load the world with Immersive Portals and Journeymap
2. Enter A Nether Portal
3. See The Map Not Update

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
https://pastebin.com/Zht3Wyyi

latest.log
https://pastebin.com/8rtB2QJt

**Comment by mysticdrew** [comment]
What version of immersive portals?

**Comment by PolyframeX** [comment]
I am using 2.3.1

**Comment by mysticdrew** [comment]
I did some extensive work to make sure JM would work with Immersive portals, 
I don't see 2.3.1 on curseforge. IP v2.4.2 was the version I verified compatibility with in December. They made some changes in that version to work with other mods better. 
Try updating to the latest version please.

**Comment by PolyframeX** [comment]
It seems immersive portals isn't updated to that version for 1.19.2 fabric.

**Comment by mysticdrew** [comment]
JM has the changes in 1.19.2 that are needed for IP's  2.4.2 changes. There is no way to get it to work correctly without the changes in IP 2.4.2. This Issue is better suited for their issue tracker.

**Comment by mysticdrew** [comment]
This issue is closed now. I am sorry I am unable to help. The problem is how IP sets dimension values. IP needs to move the changes from 2.4.2 to 1.19.2 version and JM will work correctly if they do that.
