### ISSUE TITLE
[1.18.2 - 5.9.3] Couldn't locate icons for flat (from discord)

### ISSUE THREAD

**Issue by xFirefalconx** [TeamJM/journeymap#561]
#### JourneyMap Version:

`1.18.2-5.9.3`

#### Forge Version:

`1.18.2-40.2.0`

#### Describe the problem in repeatable steps:

No idea what is happening visually. I just read the log, as described on [Discord](https://discord.com/channels/239040424214396929/1075090185806692492) before. 

my screen (grey chunks are fine it's a mod, ignore them)

![grafik](https://user-images.githubusercontent.com/106652912/218808869-aa271482-3e46-4d1f-a19c-6ee1ed24b32b.png)

1.
2.
3.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

`Couldn't locate icons for flat: F:\Games\Twitch\Minecraft\Instances\SWEM%20Custom%20Modpack_V2%20(2)\mods\journeymap-1.18.2-5.9.3-forge.jar\assets\journeymap\theme\flat`

Latest log
https://gist.github.com/xFirefalconx/2ddbe2b6acff223c0a0adc0ed57fa274
Journeymap log
https://gist.github.com/xFirefalconx/24c0861d1df39c616beb85bcaff6f811

Important info: Supplementaries is stating that *some* mods are loading too early and it won't attempt to fix this. Maybe it's related, not sure.

**Comment by mysticdrew** [comment]
this was un replicatable on my end, and it seemed to fix itself according to the user in discord.
