### ISSUE TITLE
[1.18.2] Colors of modded blocks display wrong, override not working (since 1.16.5)

### ISSUE THREAD

**Issue by xFirefalconx** [TeamJM/journeymap#562]
#### JourneyMap Version:

`1.18.2-5.9.3`

#### Forge Version:

`1.18.2-40.2.0`

This though already happened in 1.16.5 Minecraft and older Journeymap!

#### Describe the problem in repeatable steps:

There is a color mapping problem with at least two identified mods. 
New info! This also happens to the leaves of a palm tree from "Oh The Biomes You'll Go"

https://www.curseforge.com/minecraft/mc-mods/chinjufumod
https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go

Blocks from both of these mods get rendered in "ugly" colors. 
Precisely, the tree leaves are greyish-white instead of their respective colors. 
In Chinjufu mod, the "Fallen Leaves" block also doesn't display the correct color.

Using a journeymap override doesn't fix this, as we attempted in 1.16.5 without success. 

1. Install Chinjufu mod (any version <= [1.18.2]6.2.4.)  && || the Oh The Biomes You'll Go mod (any version <= 1.18.2-1.4.7)
2. Find a kaede biome or a beach biome that contains a tree from Oh The Biomes You'll Go
3. See if the colors can be overridden using the normal method. If not, you found my situation. See a few blocks. Downscaled, their pixel colors should be different. This issue even *might* spread to colored minecraft beds not displaying their bedsheet color. Just a thought, though.

![grafik](https://user-images.githubusercontent.com/106652912/218816521-e81443c9-42f8-45ce-8718-b9f710210be8.png)
![grafik](https://user-images.githubusercontent.com/106652912/218816636-9554e6b2-9839-4cf5-8bb8-c29a9e93c476.png)
![grafik](https://user-images.githubusercontent.com/106652912/218816730-226fc3ba-452c-4d87-9992-99dc7847d14b.png)

This is a screenshot from the 1.16.5 issue back then. The pixels around the circled area are what's supposed to happen, probably. I have no idea what's different. On 1.18.2 I couldn't find a map that wasn't broken like you can see above. 
![grafik](https://user-images.githubusercontent.com/106652912/218818121-05529c11-a2cb-48fd-ba0d-62c7c68ad1d5.png)

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
[journeymap.log](https://github.com/TeamJM/journeymap/files/10735420/journeymap.log)

Latest.Log
https://gist.github.com/xFirefalconx/16880a36aeda60f997899795283854e8

**Comment by mysticdrew** [comment]
![image](https://user-images.githubusercontent.com/5459941/218854246-86bc348b-1e15-4c1d-8188-0468ca6cd090.png)
palm trees are rendering fine with the latest 
TerraBlender Forge 1.18.2-1.1.0.102
Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4.7
with Journeymap 5.9.3 for 1.18.2

**Comment by mysticdrew** [comment]
I fixed the two types of leaves that I found were broken. I gave you a test build in discord. 
If you find more miss colored blocks, please provide the resourceid for them. Can be obtained by looking at a block and press f3.

**Comment by xFirefalconx** [comment]
byg:maple_leaves are shown brown instead of green. Unsure if this is intended.

Fruit trees mod also affected. They have a slight hue but I think it didn't get applied to green base layers. 
fruittrees:mandarin_leaves
fruittrees:lime_leaves
fruittrees:citron_leaves
fruittrees:pomelo_leaves
fruittrees:orange_leaves
fruittrees:lemon_leaves
fruittrees:grapefruit_leaves
fruittrees:apple_leaves

Potentially unwanted look on
chinjufumod:block_taru_koucha_f as the upside is green because of tea leaves, but shown brown. There might be more from this mod. I'll edit if I find any. 

biomesoplenty:flowering_oak_leaves is shown black-ish

naturaldecormod:straw_bedding is not shown at all, unsure whether this is fine or not. 



Something else I observed is that beds from a particular mod are 90% displayed with wrong block measurements. Can branch a new issue from here if you want. 
![grafik](https://user-images.githubusercontent.com/106652912/219447325-b97321a2-8509-4cc3-b775-c189b1c3bb4c.png)
The only ones with correct size but also wrong colors are:
fantasyfurniture:dunmer/bed_double
fantasyfurniture:dunmer/bed_single

The rest is sized wrong, the only one I think got a slight hue issue is 
fantasyfurniture:nordic/bed_single
fantasyfurniture:nordic/bed_double

perhaps also 
fantasyfurniture:royal/bed_double
fantasyfurniture:royal/bed_single

I will potentially also have to edit this when testing Star Worm Equestrian Mod (SWEM) V2. The mod is not released yet but will be added to the modpack once it is.

**Comment by mysticdrew** [comment]
The wrong sized blocks are how they do their models, they are really only one block but they look like two blocks. I cannot find a good way to resolve this. 
Most of these fixes will be in 5.9.4 when published. I did not get to every single one.
