### ISSUE TITLE
[Suggestion] Add a way to put font shadow on the info lines

### ISSUE THREAD

**Issue by Imzxhir** [TeamJM/journeymap#565]
Description: Basically the title. With Font Shadow, it makes the text look really nice without a background and makes it easy to read.

**Comment by mysticdrew** [comment]
This is already done for the next major release. 

`Info Slot text will draw font shadow if the background alpha is less than .05 to enhance visibility`

**Comment by mysticdrew** [comment]
Cleaning up the issue tracker
Closing as this is completed for JourneyMap v6 when it is released.
