### ISSUE TITLE
[Suggestion] Add a way to change the colour of player names

### ISSUE THREAD

**Issue by Imzxhir** [TeamJM/journeymap#566]
Description: Basically the title. I think it would be cool to add a way to chnage the colour of the player names and maybe entity names to a different colour instead of staying green. This could help with user accessibility and maybe using a different colour instead of green, could maybe help the user.

**Comment by mysticdrew** [comment]
yea, adding a color config for those would be a good idea. 

Size is already available, Player Display Scale, Mob Display Scale, and Font Scale

**Comment by mysticdrew** [comment]
> Which option impacts the player / entity names? I'm guessing the Font Scale

Yup!

**Comment by mysticdrew** [comment]
Cleaning up the issue tracker
Closing as this is completed for JourneyMap v6 when it is released. 
![image](https://github.com/TeamJM/journeymap/assets/5459941/30d19a51-446c-435b-84c3-664d0d4bb0a8)
