### ISSUE TITLE
[Suggestion] Order the info lines selector alphabetically

### ISSUE THREAD

**Issue by Imzxhir** [TeamJM/journeymap#567]
Description: Basically the title. By having it sorted alphabetically, it will help the user find what they are looking for by looking for the name and what the letter begins with. This will also help with organsing the info line selector so it's easy to find the right info line your looking for

Current info line selector: 
![image](https://user-images.githubusercontent.com/98621617/221281975-fc4cb2bb-0012-4f22-ae50-9a979b47d2f4.png)

**Comment by mysticdrew** [comment]
Cleaning up the issue tracker
Closing as this is completed for JourneyMap v6 when it is released.
