### ISSUE TITLE
[Suggestion] Add a way to add waypoints from Xaero's Share Waypoints feature

### ISSUE THREAD

**Issue by Imzxhir** [TeamJM/journeymap#568]
Description: Basically the title. This will help JourneyMap players add waypoints from people that are still using Xaero's Minimap, this could also help people not be left behind by letting people add waypoints that Xaero Minimap users share and edit them.

**Comment by mysticdrew** [comment]
How does xaeros share waypoints?

**Comment by mysticdrew** [comment]
yea, you can add screenshots to this issue.

**Comment by mysticdrew** [comment]
oh I don't know what all those values mean. but I can investigate it.

**Comment by U5B** [comment]
https://github.com/U5B/jsmacros/blob/eb9e5aafa2ac56fef6cd74c432b3b8ac07840d25/scripts/lib/xaero.ts#L86
This may be helpful.
`xaero-waypoint:${name}:${label}:${x}:${y}:${z}:${color}:${rotation}:${yaw}:Internal-dim%${world}-waypoints`
name: String - name of waypoint
label: String - first uppercase letter of waypoint name (from what I could find)
x, y, z: Integer - position in world
color: Integer - Values are 0-16, standard minecraft color code, with a-f replaced with 10-16
rotation: Boolean - probably if the waypoint should rotate or something, always was false
yaw: Integer - Also unsure what the yaw means, always was 0
world: String (minecraft$overworld) - This is the world name with the `:` replaced with an `$`

However, this was only tested on newer minecraft versions (1.16.5+) so world name format may be different.

**Comment by mysticdrew** [comment]
> Any prospect on when this feature will be made available?

This is in journeymap 6 for 1.21.1+ for quite a while already
