### ISSUE TITLE
[1.19.2] Very long dimension names impact the UX

### ISSUE THREAD

**Issue by son0fether** [TeamJM/journeymap#569]
The mod Nomadic Tents uses dimension names of the form "Dimension [UUID with 36 characters]".
https://www.curseforge.com/minecraft/mc-mods/nomadic-tents

Displaying these dimension names in the Journeymap UX on a smaller screen pushes the UX elements past the edge of the screen, see screenshots.  In particular, the UX of the screen to add a waypoint becomes extremely hard to use as most of its critical fields are off the left side of the screen.  They're still tab-accessible and functional.

![Screenshot (1530)](https://user-images.githubusercontent.com/40579173/221341111-a9a047e7-8128-44aa-86de-e745ef235d52.png)
![Screenshot (1529)](https://user-images.githubusercontent.com/40579173/221341113-b3905916-93ba-4f59-ad24-b155e3a2dc68.png)

This problem persists even after exiting the dimension.

#### JourneyMap Version:
1.19.2-5.9.3

#### Forge Version:
1.19.2, 43.2.0

#### Describe the problem in repeatable steps:

1. Load a game with any mod that has lengthy dimension names, such as the tents in Nomadic Tents, and travel to that dimension
2. Use a relatively moderate window size, screenshots are at 1768x992, with GUI size set to Auto
3. Attempt to add a waypoint, you can see that elements the waypoint adding screen and the waypoint list screens have been pushed off the edge of the screen
5. Repeat outside that dimension, you can see that the issue persists

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
No errors in log

I don't have a specific solution in mind.  The UX elements could shorten dimension names to "Some fixed max length..." or similar, with dots when there are extra characters.  They could auto-scroll (XCom2 style menus).  The dimensions could be assumed to be problematic and excluded from the list.  Whatever works.

This is obviously a bit of a corner case, but it does make using JourneyMap and that particular mod Nomadic Tents together rather tricky.  My personal vision, distance from the screen, and physical screen size don't allow increasing the resolution without making the game a challenge to see.

Thanks for all your hard work making a great mod.

**Comment by mysticdrew** [comment]
Might need to inquire also on why the dimension names need to have a UUID in the name.
I will likely truncate the name.

**Comment by son0fether** [comment]
The mod in question likely creates a separate dimension per tent. A UUID probably seemed reasonable, although I would have used a serially incrementing int.

Truncating would be just fine. Thank you for your attention on this.

**Comment by son0fether** [comment]
Also I'd like to politely request that a1.19.2 version is created with whatever change is made for this since so many mods aren't ready for 1.19.3 yet.

**Comment by mysticdrew** [comment]
> Also I'd like to politely request that a1.19.2 version is created with whatever change is made for this since so many mods aren't ready for 1.19.3 yet.

I cannot promise anything, we are in the middle of a big update to JM for 1.19.3+ I added the 5.9 tag to it, if I get time to add it to a bugfix release I will. Even though I do not consider this a bug.

**Comment by mysticdrew** [comment]
![image](https://user-images.githubusercontent.com/5459941/224565307-e0756ac1-ae79-466f-8480-0026c5516ae3.png)

**Comment by mysticdrew** [comment]
this will also be in 5.9.4 for 1.18.2-1.19.4 forge and fabric.

**Comment by son0fether** [comment]
I want to thank you for fixing this, and for updating the 1.19.2 version.  It's working great.

**Comment by mysticdrew** [comment]
You're welcome
