### ISSUE TITLE
[1.19.3] Minecraft crashes on startup when using Journeymap Fabric

### ISSUE THREAD

**Issue by doncullen** [TeamJM/journeymap#570]
JourneyMap Version:
journeymap-1.19.3-5.9.3-fabric

Fabric Version:
Fabric Loader 0.14.14

Loading JourneyMap with Fabric API with no other mods: no issues
Loading JM with Fabric API & Optifine (Fabric): Crashes

Optifabric Version:
optifabric-1.13.21
preview_OptiFine_1.19.3_HD_U_I2_pre5

Loading Minecraft with Optifabric and other usual mods minus JourneyMap; no crash.  It appears JourneyMap and Optifine are conflicting somehow. 

Logs: https://pastebin.com/PAR0y9LC

**Comment by mysticdrew** [comment]
Don't use optifine with fabric or at all. 
Use sodium and iris
