### ISSUE TITLE
[1.19.2] Strangeness in map rendering

### ISSUE THREAD

**Issue by AxeDark13** [TeamJM/journeymap#571]
#### JourneyMap Version:

`1.19.2-5.9.3-fabric`

#### Forge Version: (I have fabric)

Don't know, but Fabric API is `0.73.2-1.19.2`

#### Describe the problem in repeatable steps:

Problem in rendering map.
1. I'm moving around the map, chunks is drawn quickly (the rendering distance is 12). I move on foot - not running.
2. But map rendering a very slow - 5 chunks around my position and no more.
3. But map rendering on all 12 chunks when i just came in the world or have I been standing still long enough(about 15 seconds). 
My computer is quite powerful (Ryzen 5 2400g, RTX 3060 ti (without RTX shaders), 16 GB of RAM, 500 GB SSD) and this clearly should not be. And it wasn't when I was playing with Forge.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
[journeymap.log](https://github.com/TeamJM/journeymap/files/10833551/journeymap.log)

**Comment by mysticdrew** [comment]
your description is very confusing
Can you show video of what you are describing?

**Comment by AxeDark13** [comment]
Sorry, I found the reason - it was in a different mod. Everything is fine now. Thanks

**Comment by FiskenPoul** [comment]
> Sorry, I found the reason - it was in a different mod. Everything is fine now. Thanks

May i ask what mod?
After updating to 1.21.11 i have the same issue, journeymap is insanely slow to render
