### ISSUE TITLE
[Feature Request]: Add a config button in Mod Menu

### ISSUE THREAD

**Issue by Imzxhir** [TeamJM/journeymap#574]
### Describe the new feature.

I would like a button in mod menu where you can access a button that leads to the options screen without having to be in game or have a keybind that goes to it. This can help with accessing the options screen without having to be ingame to access it. Since the current situation on accessing the options screen, in my opinion is a bit confusing to new users of the mod.

**Comment by mysticdrew** [comment]
I will look into this, but I am not sure it is possible. We do not use the clothconfig api for our configs.

**Comment by mysticdrew** [comment]
Cleaning up the issue tracker
Closing as this is completed for JourneyMap v6 when it is released.
