### ISSUE TITLE
[Feature Request]: Add a way to always see the player head

### ISSUE THREAD

**Issue by Imzxhir** [TeamJM/journeymap#577]
### Describe the new feature.

Basically the title. When a player goes away from your player, the player head starts to fade away leaving the name on its own which in my opinion, is a bit weird. My proposal is to add an option to keep rendering the player head even when they go away from you, this is a more of a QoL feature as some people may like the fading out of player heads and some people may not.

**Comment by mysticdrew** [comment]
New check box for this feature in the Advanced Option section. 
"Player Icon Fade" 
"Enable/Disable Player Icons from fading based on vertical distance."

Currently the icon fades based on vertical distance. Unchecking this option, it will not fade based on vertical distance.

**Comment by mysticdrew** [comment]
Cleaning up the issue tracker
Closing as this is completed for JourneyMap v6 when it is released.
