### ISSUE TITLE
ExecutionException in getPlayer

### ISSUE THREAD

**Issue by Preminenc3** [TeamJM/journeymap#58]
#### Instructions for Submitting an Issue
1. Ask for help on Discord (https://discord.gg/eP8gE69) #support if you're unsure this is a new issue.
2. Please search for existing issues before submitting a new one.
3. Please add the correct MC<version> label to your issue. Example: "[1.12.2] Waypoints are upside down"
4. Completely fill out the template below. Failure to do so is likely to get the issue closed immediately.
5. Prove you read these instructions by deleting this section before submitting. ;)
---
  
#### JourneyMap Version:

1.12.2-5.5.2

#### Forge Version:

1.12.2-14.23.4.2709

#### Describe the problem in repeatable steps:
[This issue is constantly spammed in the MC log](https://pastebin.com/aHwyiC1n)

**Comment by mysticdrew** [comment]
This is not really an issue. It is an exception being thrown when JM tries to end mapping on an unloaded wrold because minecraft unloads it before JM gets a chance to stop mapping preunload. However, the mapping still stops. This is just unnecessary log spam, I will clean it up.
