### ISSUE TITLE
[Bug]: weird thing happens when opening fullscreen map

### ISSUE THREAD

**Issue by HiddenDeath** [TeamJM/journeymap#581]
### What happened?

I don't know how to explain, but you should see screenshots
![image](https://user-images.githubusercontent.com/48379201/228840397-1c22e776-9add-4b1b-be73-1a27328fff25.png)
![image](https://user-images.githubusercontent.com/48379201/228840653-ab642d38-e3ce-4ec8-9411-4ae0fa54f244.png)
![image](https://user-images.githubusercontent.com/48379201/228840761-6ea18438-eec4-4d72-96f0-0e18c8cd94f4.png)

### Minecraft Version

1.18.2

### Version

5.9.4 (Default)

### Relevant log output

[journeymap.log](https://github.com/TeamJM/journeymap/files/11111695/journeymap.log)
[latest.log](https://github.com/TeamJM/journeymap/files/11111699/latest.log)

**Comment by HiddenDeath** [comment]
didn't help

**Comment by HiddenDeath** [comment]
oh and also I had version 5.7 on 1.12.2, and there were no problems like this

**Comment by HiddenDeath** [comment]
yes

**Comment by mysticdrew** [comment]
> 



> yes

try the vanilla launcher

**Comment by HiddenDeath** [comment]
I don't have money :(

**Comment by mysticdrew** [comment]
When you purchase the game, I can help.
