### ISSUE TITLE
[Feature Request]: JourneyMap and Cobblemon map icons by ResourcePack

### ISSUE THREAD

**Issue by Maxitotito** [TeamJM/journeymap#582]
### Describe the new feature.

Let Journeymap use resourcepack map icons to show Pokémon by the mod Cobblemon for Fabric 1.19.2.

Here is a Resoruce Pack for Cobblemon 1.3.0 with almost all available Pokémon.
[JourneyMap+Cobblemon1.3.0_1.19.2.zip](https://github.com/TeamJM/journeymap/files/11125784/JourneyMap%2BCobblemon1.3.0_1.19.2.zip)

**Comment by mysticdrew** [comment]
Fixed for next minor release, will close when published

**Comment by mysticdrew** [comment]
Note: the above resource pack the images are not center. 
No changes for 6.0 as the resource pack will need a minor update to work by default. "entity_icon" will need to be renamed to "pokemon"
