### ISSUE TITLE
Journey Map Keys / Controls not Working

### ISSUE THREAD

**Issue by GoldenRetrieverX** [TeamJM/journeymap#585]
### What happened?

I'm sure this is probably something stupid easy? But, I'm currently playing ATM7 on 1.18.2 journeymap comes pre-installed on that modpack > I did add a few extra mods to this pack, but I don't think any of these should cause any conflicts with a mapping mod - if you need a list I can send one.

But none of the keys for any of the journey map commands works. Example I want to open the fullscreen map > I click J > nothing happens I verified key conflicts and made sure nothing else even uses J > still nothing. I then tried with like change mini-map type that didn't work either. I also tried the waypoint manager and creating a waypoint but none of the keybinds do anything.

I know the version of JourneyMap for ATM7 is outdated so I tried updating that as well and deleting the whole journeymap folder in the mod pack so it would re-create a default folder still nothing.

EDIT: I've used this modpack before and have never had this issue (even with adding extra mods). I've also tried removing the JMI because I thought maybe some integration function was messing with it?

### Mod Loader

Forge

### Minecraft Version

1.18.2

### Version

5.9.5

**Comment by mysticdrew** [comment]
Do the keybind settings show up in the vanilla controls screen?

**Comment by GoldenRetrieverX** [comment]
If you are asking do I see the JourneyMap keys when going into Options > Controls > Key Binds... then yes they do show up there and I can change them

Logs attachted.
[journeymap.log](https://github.com/TeamJM/journeymap/files/11237631/journeymap.log)

couldn't attach the latest log as it was 27MB > I seen some errors being thrown for Draconic Evolution in there though so not sure if that is the root cause...?

**Comment by mysticdrew** [comment]
take the contents of the latest.log and create a gist and provide a link
https://gist.github.com/
I bet that has some info in it that would be helpful.

**Comment by GoldenRetrieverX** [comment]
[options.txt](https://github.com/TeamJM/journeymap/files/11237689/options.txt)

[latest.log](https://github.com/TeamJM/journeymap/files/11237715/latest.log)

I re-launched game and got a new latest file and this one worked.

**Comment by mysticdrew** [comment]
Looks like you have a bunch of key input issues going on. 
CyclicClientPlugin has some errors regarding keys too. Draconic Evolution has some but it may be due to Optifine. 
I would suggest removing Optifine as I see Optifine on the key errors. 

Optifine does not work well in heavily modded instances. It breaks a lot of mods.

**Comment by mysticdrew** [comment]
Actually, Cyclic may be the cause. 
https://github.com/Lothrazar/Cyclic/issues/2209
Looks like you will need to update, you are on 5.2.0.2
5.2.0.4 fixes it according to that issue.

**Comment by GoldenRetrieverX** [comment]
Updated server and updated client > tested > all working.
Thanks.

**Comment by mysticdrew** [comment]
awesome, glad to help!
