### ISSUE TITLE
[Feature Request]: Option to Log Successful Teleports to Console

### ISSUE THREAD

**Issue by Wundrfull** [TeamJM/journeymap#586]
### Describe the new feature.

Hey, I'm requesting there be an option that enables logging for successful teleports. I spoke with Mysticdrew on the JourneyMap Discord and he mentioned that you all log teleport errors and denials, but not for successful teleports. 

I'm hoping that it says in the console, a player's name and that they teleported (maybe coords option too). It would be great to see which players are using teleports via waypoints or the simple right-click + teleport option.

**Comment by mysticdrew** [comment]
added for 6.0

**Comment by mysticdrew** [comment]
Cleaning up the issue tracker
Closing as this is completed for JourneyMap v6 when it is released.
