### ISSUE TITLE
[1.12.2] blue borders around map on the fullscreen map

### ISSUE THREAD

**Issue by ProxyPlayerHD** [TeamJM/journeymap#59]
JM: 1.12.2-5.5.2
FORGE: 14.23.4.2730

Video showing the problem: (warning 4k Resolution) [GIF](https://i.imgur.com/pcBDeU3.mp4)

for some reason the map only shows itself as a perfect square, and since the screen is not a perfect square it cuts off the sides of the map. zooming in doesn't change anything, the borders are still around it in a square, except zoomed in.

**Comment by ProxyPlayerHD** [comment]
it has been almost a month... any kind of status update would be nice.

is just noone there to work on anything?

**Comment by mysticdrew** [comment]
This is not really an issue.

**Comment by ProxyPlayerHD** [comment]
how is it not? it's a bug so it already counts as issue plus it's really annoying as i cannot really zoom into stuff without everything around it disapearing

**Comment by mysticdrew** [comment]
I have a fix in my 1.14.4 branch. If you come into discord I can give it to you to test. It is resolved for 1440 resolution, but I have not had anyone test it in 4k.

**Comment by 0xpr03** [comment]
I can provide a 4k test if you want, as I'm affected by this too on 1.12.2 (so it's at least fixed in recent versions)

![Uploading grafik.png…]()

**Comment by mysticdrew** [comment]
Use 5.7.1

**Comment by VincyChannel** [comment]
@ProxyPlayerHD 
**Fixed here:** https://www.curseforge.com/minecraft/mc-mods/journeymap-fixes
