### ISSUE TITLE
1.12.2 Journey Loop Error

### ISSUE THREAD

**Issue by NightingaleZK** [TeamJM/journeymap#591]
#### Describe the problem in repeatable steps:

1. Original error when establishing mods in a new world: https://imgur.com/a/iW5LCJr
2. I make the appropriate changes, and then I run a new world creation fresh to have the installation of mods processed.
3. Crash Report states: 
"Duplicate Mods:
	journeymap : /home/minecraft/multicraft/servers/server678556/./mods/journeymap-1.12.2-5.5.4.jar
	journeymap : /home/minecraft/multicraft/servers/server678556/./mods/journeymap-1.12.2-5.7.1.jar"
4. I delete journeymap1.12.2-5.7.1.jar from the console and ensure 1.12.2-5.5.4.jar is installed on the console and on Curseforge correctly as the sole file.
5. After every new world launch, same crash occurs with the 1.12.2-5.5.4.jar appearing in my console.

**Comment by mysticdrew** [comment]
Remove 5.7.1 from the mods folder. JMstage won't work with it. You need 5.5.4

**Comment by mysticdrew** [comment]
Oh, I wonder if curseforge is automatically doing it. This sounds like a curseforge issue
