### ISSUE TITLE
[Bug]: [1.19.4] [v5.9.6] Massive lag spikes while resolving unauthenticated, unclaimed players skins

### ISSUE THREAD

**Issue by Redo11** [TeamJM/journeymap#592]
### What happened?

When an offline, unauthenticated and unclaimed account (basically cracked) is present within render distance, Journey map causes a massive lag spike. 

PS.
While I do not condone piracy myself, playing "non-premium" is popular in certain countries like Russia and Poland. 
I myself own a legitimate Minecraft account. Also, the same problem may occur with fake NPC players on servers and while playing offline multiplayer. 

### Mod Loader

Fabric

### Minecraft Version

1.19.4+

### Version

other (please list)

### Relevant log output

[Minecraft log](https://pastebin.com/tyd3e8M8) — Log trimmed only to relevant error
[JourneyMap log](https://pastebin.com/ApQ0tBEL)

**Comment by mysticdrew** [comment]
piracy fixes are not something I will do. I do not care about reasons or how popular it is in specific countries. 

However, a fix for fake players is already done for the next major release. 6.0.

**Comment by mysticdrew** [comment]
5.9.7 is on curseforge and modrinth with the fix
