### ISSUE TITLE
Incorrect time

### ISSUE THREAD

**Issue by VsUK** [TeamJM/journeymap#593]
### What happened?

Not to be rude, but this bug was first raised over 5 yrs ago & it's still present in the mod. The map time over the minimap is wrong. There's a simple mod that shows the correct time in game so it's not like it's rocket science. I could fix it myself in like 2 minutes,  but it's not my mod. 

So please fix it.

### Mod Loader

Fabric

### Minecraft Version

1.19.2

### Version

5.9.5

**Comment by mysticdrew** [comment]
You provided no details.

**Comment by mysticdrew** [comment]
There are several time info slots. use the one that fits your needs. 

Vanilla Minecraft day starts at 6am. We have an option for that. 
There is an option that makes a new day start at 12am. You can use that one if you like too. 

It is not rocket science to look the multiple options we provide.
