### ISSUE TITLE
[Bug]: 1.19.2 Journeymaps fails to register dimension change with Immersive Portals

### ISSUE THREAD

**Issue by bluesteel53** [TeamJM/journeymap#594]
### What happened?

When using Immersive Portals and Journeymaps for Forge 1.19.2 (not using Optifine), Journeymaps does not seem to register player moves to other dimensions through Immersive Portals. When I create a nether portal and enter the nether, both the world map and minimap go gray and stay grayed out even after long periods in the nether, etc.  I have tried multiple times on new worlds.  When using commands to teleport to the nether, everything works as expected.  

### Mod Loader

Forge

### Minecraft Version

1.19.2

### Version

5.9.5

### Relevant log output

There’s no report because the game doesn’t crash or recognize an error.

**Comment by mysticdrew** [comment]
What version of Immersive portals are you using?

**Comment by mysticdrew** [comment]
Actually, looking at the forge version.
This is on immersive portals, not JM. I did a ton of work to ensure compatibility. 
See this: https://github.com/TeamJM/journeymap/issues/560

You need to make an issue on their issue tracker and reference the issue linked above. They need to migrate the changes from the compatible version of IP to the forge version.

**Comment by bluesteel53** [comment]
Thanks for the quick response.  Makes sense and will do.
