### ISSUE TITLE
[Bug]: Random colors/patterns/noise in unexplored map

### ISSUE THREAD

**Issue by andrewjbennett** [TeamJM/journeymap#595]
### What happened?

**What happened:** Some of the unexplored parts of the map are random colors/patterns, rather than being plain black.

One example: 
![2023-06-04_17 55 23](https://github.com/TeamJM/journeymap/assets/864138/12a6f38a-72d0-41c4-91f9-67fd710fa1cf)

I've uploaded multiple screenshots here: https://imgur.com/a/p03d1dn

One time instead of being random noise, the beacon UI showed up in the unexplored areas: 
![image](https://github.com/TeamJM/journeymap/assets/864138/4b3a9e98-5981-4aa4-9585-0d8f1fbe9ea8)

The random noise exists in the images stored on disk:

![journeymap/data/mp/LurgCraft/overworld/day/0,-10.png](https://github.com/TeamJM/journeymap/assets/864138/4ae0b621-d576-423f-9966-1799a9ad5cdb)

**What did I expect to happen**: unexplored parts of the map remain dark until explored, and don't show random colors/noise that isn't actually there

**Other information**: 

I play on a server, although the issue isn't affecting anybody else on the server. I'm on the ATM7 modpack, although I think I remember this happening on other modpacks too (but I can't currently confirm)

The random noise is persistent -- e.g. if I restart the game and look back at the same place on the map, the random noise is identical to before I restarted.

I don't think the map started like this (when I first logged into the server for the first time), I think it's only happened after some number of hours of playing. That said, the random noise showed up immediately when I visited a new dimension.

The fact that it contains random noise, and that one time it contained graphics from the game, makes me suspect there might be memory corruption going on.

Journeymap version: 5.9.0beta2 -- I can try updating, but given that the noise is persistent after restarting my client, I assume I would need to delete all of the current map files to tell whether the problem is gone. (which I'm willing to do if it will help test / narrow down the problem)

### Mod Loader

Forge

### Minecraft Version

1.18.2

### Version

other (please list)

### Relevant log output

* [journeymap.log](https://github.com/TeamJM/journeymap/files/11645151/journeymap.log)
* [latest.log](https://github.com/TeamJM/journeymap/files/11645173/latest.log)

**Comment by mysticdrew** [comment]
This was fixed, which is why you should not be on old beta versions of mods.
