### ISSUE TITLE
[Bug]: Death Waypoint deleted/not created

### ISSUE THREAD

**Issue by notIkibo** [TeamJM/journeymap#597]
### What happened?

With the config "Delete death waypoint at arrival" true, I died relatively near my initial death point. And my death didn't have a waypoint. I don't know what exactly made it happen. May it be that I clicked "Respawn" too fast (which seems unlikely) or that I died relatively near my initial death (which may be something to look into). There was nothing else noteworthy.
I think that it has to do with the config mentioned above since it really never happened before and I just recently found this configuration (which is really useful) and an "accidentally deleted waypoint" sounds likely to happen.

### Mod Loader

Fabric

### Minecraft Version

1.19.2

### Version

other (please list)

### Relevant log output

v5.9.7

**Comment by notIkibo** [comment]
[12:03:03] [Render thread/INFO] [DeathPointHandler] Ikibo died at class_2338{x=59, y=68, z=76}. Deathpoints enabled: true. Deathpoint created: true
[12:05:18] [Render thread/WARN] [JMLogger] Can't get entityTexture for betteranimalsplus:textures/entity_icon/tarantula_jungle_1.png
[12:05:45] [Render thread/INFO] [DeathPointHandler] Ikibo died at class_2338{x=48, y=70, z=81}. Deathpoints enabled: true. Deathpoint created: true

So my deathpoint was indeed created, but not visible and not found in the waypoint manager

**Comment by mysticdrew** [comment]
as per the bug request form, you need to supply the latest.log and journeymap.log
I need the files, do not copy and past them or give me partial logs. Drop the files into the issue.

**Comment by mysticdrew** [comment]
Try to reproduce the issue, then send the logs. journeymap.log will clear when you start minecraft.

**Comment by mysticdrew** [comment]
I will close this in 24 hours unless I get a response

**Comment by mysticdrew** [comment]
Stale- closing
