### ISSUE TITLE
[Bug]: Unable to check box 'Waypoint Teleporting' on multiplayer server JM version: 1.16.5-5.8.5

### ISSUE THREAD

**Issue by theprodigy19444** [TeamJM/journeymap#598]
### What happened?

Even /OP myself to try and get it to become available but the entire "Server Admin" section is greyed out for me, not sure how to un-grey it so I can allow teleportation to waypoints.

### Mod Loader

Forge

### Minecraft Version

1.16.5

### Version

5.8.5

**Comment by mysticdrew** [comment]
Rejoin your server after getting op-ed

**Comment by mysticdrew** [comment]
I will close this in 24 hours unless I get a response

**Comment by theprodigy19444** [comment]
Hi, yes sorry this worked perfectly. Thank you very much!
