### ISSUE TITLE
[Bug]: Waypoints

### ISSUE THREAD

**Issue by SydIsMe** [TeamJM/journeymap#599]
### What happened?

Playing 1.20 and my waypoint was not going past 320m no matter how far away I got. When I got closer it didn't budge until I got about 320-250m away from my waypoint. 

### Mod Loader

Forge

### Minecraft Version

1.19.4+

### Version

5.9.5

**Comment by SydIsMe** [comment]
https://youtu.be/q1QFKmQmxWc

**Comment by mysticdrew** [comment]
Ahh yea ok, I remember this bug. It will be fixed for the next release, it accidentally got reverted.

**Comment by SydIsMe** [comment]
thank you!

**Comment by mysticdrew** [comment]
you're welcome.
Your issue reminded me to update the template to add mc1.20 and jm5.9.7 :)
I will close when this fix is published. I may not release it until 1.20.1, let more bugs come up for 1.20. I suspect 1.20.1 will be out next week as they fixed some critical bugs this morning.

**Comment by mysticdrew** [comment]
5.9.8 is in the process of being published to both Curseforge and Modrinth with this fix. 
Will be on Modrinth first. 
https://www.curseforge.com/minecraft/mc-mods/journeymap/files
https://modrinth.com/mod/journeymap/versions
