### ISSUE TITLE
[1.11.2] No Teleport button on Waypoint Manager screen

### ISSUE THREAD

**Issue by neil-bowers** [TeamJM/journeymap#6]
#### JourneyMap Version:

`1.11.2-5.5.0`

#### Forge Version:

`1.11.2-13.20.1.2476`

#### Describe the problem in repeatable steps:

1. Set `teleportEnabled` to `true` in `C:\...\journeymap\server\5.5\journeymap.server.global.config`
2. Start Single Player Survival World.
3. Create waypoint.
4. Open Waypoint Manager (ctrl-B by default) - no Teleport button next to any waypoints.
5. `/jtp` command works correctly.
6. `journeymap.server.dim0.config` is not enabled.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

No errors in log file.

**Comment by neil-bowers** [comment]
I've updated to JourneyMap 1.11.2-5.5.2 and the issue is still present.

**Comment by techbrew-mc** [comment]
Fixed in 5.6.0b1
