### ISSUE TITLE
[1.12.2] Stacktrace when players join without journeymap

### ISSUE THREAD

**Issue by iamtpage** [TeamJM/journeymap#60]
#### JourneyMap Version:

`journeymap-1.12.2-5.5.2`

#### Forge Version:

`spongeforge-1.12.2-2705-7.1.0-BETA-3250`

#### Describe the problem in repeatable steps:

1. Enable options on server (disable radar, mapping ,etc)
2. Players join without journeymap installed
3. Stack trace on world load (even going to nether/end/etc)

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
https://gist.github.com/iamtpage/b5b618ef89d2fb9ea23d231a0a3e0ced

**Comment by Weissmoon** [comment]
> Current solutions:
> Don't put JM on your server.
> Use any forge below forge-1.12.2-14.23.4.2703.
> Use @Weissmoon's fix.

I fixed it with [this](https://minecraft.curseforge.com/projects/journeymapfixer/files/2586654).

**Comment by iamtpage** [comment]
@Weissmoon thanks
