### ISSUE TITLE
[Bug]: Can't edit name and location in New Waypoint UI

### ISSUE THREAD

**Issue by UCPRER** [TeamJM/journeymap#600]
### What happened?

Can't edit name and location in New Waypoint UI.
![2023-06-10_13 56 28](https://github.com/TeamJM/journeymap/assets/53432924/d5494992-e70c-4b8a-8756-4f8e6abddc8d)

jouneymap: 5.9.7
minecraft: 1.20
fabric: 0.14.21
fabric-api: 0.83.0+1.20

### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Version

5.9.7

**Comment by mysticdrew** [comment]
Interesting, thanks for the report. 
Looks like you can tab through the fields but not click on them. 
I will work on a fix later today

**Comment by mysticdrew** [comment]
5.9.8 is in the process of being published to both Curseforge and Modrinth with this fix. 
Will be on Modrinth first. 
https://www.curseforge.com/minecraft/mc-mods/journeymap/files
https://modrinth.com/mod/journeymap/versions
