### ISSUE TITLE
[Crash]: Creating a waypoint Overworld enabled crashes the game

### ISSUE THREAD

**Issue by awooso** [TeamJM/journeymap#602]
### What happened?

Creating a waypoint Overworld enabled crashes the game

### Mod Loader

Forge

### Minecraft Version

1.20

### Version

5.9.8

**Comment by awooso** [comment]
[crash-2023-06-11_14.47.49-client.txt](https://github.com/TeamJM/journeymap/files/11715609/crash-2023-06-11_14.47.49-client.txt)

**Comment by mysticdrew** [comment]
looks like it due to oculus
I do not see Journeymap anywhere in those crash logs. 
Journeymap is not ready for 1.20.1 yet, so go back to 1.20 for now and see if that works.

**Comment by awooso** [comment]
> looks like it due to oculus I do not see Journeymap anywhere in those crash logs. Journeymap is not ready for 1.20.1 yet, so go back to 1.20 for now and see if that works.

My apoligies i updated the field and refreshed the page and it set it back to 1.20.1

I am on 1.20

**Comment by mysticdrew** [comment]
Try removing oculus and see if that solves it. 
Might need to report to them too.

**Comment by awooso** [comment]
> Try removing oculus and see if that solves it. Might need to report to them too.

Removing oculus had no effect on the crash

**Comment by mysticdrew** [comment]
That crash log lists that you still have it installed

**Comment by awooso** [comment]
> That crash log lists that you still have it installed

Wonder if I need to delete the config folder as well not just the mod, good catch!

**Comment by mysticdrew** [comment]
the mod wont load if does not exist, the configs are not mods, the configs will not load if the mod is not in the mods folder. 
Maybe it is packaged up by rubidium, remove that too then

**Comment by awooso** [comment]
> the mod wont load if does not exist, the configs are not mods, the configs will not load if the mod is not in the mods folder. Maybe it is packaged up by rubidium, remove that too then

Oddly enough, deleting the config file fixed the issue, the mod and config being removed solved the problem for me!

**Comment by awooso** [comment]
Thanks for all your help and speed on this, I will open a piece with oculus letting them know the issue.

Thanks!

**Comment by mysticdrew** [comment]
thanks

**Comment by awooso** [comment]
https://github.com/Asek3/Oculus/issues/380
