### ISSUE TITLE
[Suggestion]: Press Waypoint manager key to close the screen

### ISSUE THREAD

**Issue by XEN0PHIL** [TeamJM/journeymap#603]
### What happened?

1. Press N to open your Waypoints menu;
2. Press N again to close it.
Expected: Waypoints menu closed.
Result: Waypoints menu is not closed.
Inconsistent with other menu buttons like M for open/close Full Map screen.

### Mod Loader

Fabric

### Minecraft Version

1.19.4

### Version

5.9.7

**Comment by mysticdrew** [comment]
Closing as this is completed for JourneyMap v6 when it is released.
