### ISSUE TITLE
[Bug]: The font goes weird when scaling any text up or down

### ISSUE THREAD

**Issue by Imzxhir** [TeamJM/journeymap#605]
### What happened?

I am not sure the best way to describe this so here I go. This bug happends when scaling the any font related scale, up or down. This causes the font or the pixels of the font to go really weird and be misaligned at certain scales. This issue is reported on 1.20.1 and a test build of JourneyMap but it does happen on 5.9.x builds of JourneyMap.

A related issue I could find of this is here: <https://github.com/Snownee/Jade/issues/208>

A screenshot of this is found on the LunarClient website when they had this issue, it got fixed though (search in the page for 'Pixel Alignment' and you will find it): <https://www.lunarclient.com/news/patch-notes-22/>

### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Version

6.0.0

### Relevant log output

Here is my log file for JourneyMap: [journeymap.log](https://github.com/TeamJM/journeymap/files/11739805/journeymap.log)

Here is my latest.log: https://mclo.gs/29IghBF

**Comment by mysticdrew** [comment]
can you get a screenshot of it happening in journeymap, so I know where and what text please?

**Comment by Imzxhir** [comment]
I'll send a screenshot tommorow since it is kinda getting late here, the text that is happening to is any font scales like waypoint font scale, compass font scale and font scale. Also, I am on GUI Scale 3 if that makes any difference.

**Comment by Imzxhir** [comment]
I am back with screenshots, so here you go:

Waypoint Label Scale: 1.58
![image](https://github.com/TeamJM/journeymap/assets/98621617/7485cb18-9469-49fa-a822-363704c88c38)

Waypoint Label Scale: 1.4
![image](https://github.com/TeamJM/journeymap/assets/98621617/6ebe50e5-4af9-46ee-9189-c685537e0fed)

Waypoint Label Scale: 1.27
![image](https://github.com/TeamJM/journeymap/assets/98621617/ebff00dd-88ca-455e-8de5-aab8add63f7a)

**Comment by mysticdrew** [comment]
https://bugs.mojang.com/browse/MC-263614

**Comment by mysticdrew** [comment]
Since this is a minecraft bug and I cannot do anything about it, I will close this for now. We can revisit if Mojang fixes it and issues persist.
