### ISSUE TITLE
game crash when i move around(this is on my other pc)

### ISSUE THREAD

**Issue by Janneftw2** [TeamJM/journeymap#606]
### What happened?

the mini map would not be on screen and would crash when i press t he key to open.

### Mod Loader

Forge

### Minecraft Version

1.7.10

### Version

other (please list)

### Relevant log output

Time: 6/13/23 10:25 PM
Description: Unexpected error

java.lang.ExceptionInInitializerError
	at journeymap.client.data.DataCache.instance(DataCache.java:121)
	at journeymap.client.forge.event.ChunkUpdateHandler.onChunkEvent(ChunkUpdateHandler.java:45)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_233_ChunkUpdateHandler_onChunkEvent_Unload.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.world.chunk.Chunk.func_76623_d(Chunk.java:941)
	at net.minecraft.client.multiplayer.ChunkProviderClient.func_73234_b(ChunkProviderClient.java:47)
	at net.minecraft.client.multiplayer.WorldClient.func_73025_a(WorldClient.java:176)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147263_a(Unknown Source)
	at net.minecraft.network.play.server.S21PacketChunkData.func_148833_a(S21PacketChunkData.java:141)
	at net.minecraft.network.play.server.S21PacketChunkData.func_148833_a(S21PacketChunkData.java:256)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(Unknown Source)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at journeymap.client.data.DataCache.getCacheBuilder(DataCache.java:138)
	at journeymap.client.data.DataCache.<init>(DataCache.java:60)
	at journeymap.client.data.DataCache.<init>(DataCache.java:31)
	at journeymap.client.data.DataCache$Holder.<clinit>(DataCache.java:576)
	... 23 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at journeymap.client.data.DataCache.instance(DataCache.java:121)
	at journeymap.client.forge.event.ChunkUpdateHandler.onChunkEvent(ChunkUpdateHandler.java:45)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_233_ChunkUpdateHandler_onChunkEvent_Unload.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.world.chunk.Chunk.func_76623_d(Chunk.java:941)
	at net.minecraft.client.multiplayer.ChunkProviderClient.func_73234_b(ChunkProviderClient.java:47)
	at net.minecraft.client.multiplayer.WorldClient.func_73025_a(WorldClient.java:176)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147263_a(Unknown Source)
	at net.minecraft.network.play.server.S21PacketChunkData.func_148833_a(S21PacketChunkData.java:141)
	at net.minecraft.network.play.server.S21PacketChunkData.func_148833_a(S21PacketChunkData.java:256)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(Unknown Source)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['D1san1_Water'/3223, l='MpServer', x=257.03, y=75.62, z=16.36]]
	Chunk stats: MultiplayerChunkCache: 535, 544
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-4,64,256), Chunk: (at 12,4,0 in -1,16; contains blocks -16,0,256 to -1,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 108089 game time, 127449 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 97 total; [EntityClientPlayerMP['D1san1_Water'/3223, l='MpServer', x=257.03, y=75.62, z=16.36], EntityChicken['Chicken'/3600, l='MpServer', x=225.56, y=64.00, z=-55.44], EntityChicken['Chicken'/3601, l='MpServer', x=232.47, y=67.00, z=12.38], EntityChicken['Chicken'/3602, l='MpServer', x=229.41, y=65.00, z=14.41], EntityChicken['Chicken'/3603, l='MpServer', x=236.59, y=73.00, z=13.59], EntityChicken['Chicken'/3604, l='MpServer', x=232.69, y=71.00, z=18.38], EntityPig['Pig'/3605, l='MpServer', x=224.63, y=72.00, z=36.69], Girlfriend['Girlfriend'/3606, l='MpServer', x=227.09, y=64.00, z=77.50], RedCow['Apple Cow'/3615, l='MpServer', x=249.47, y=63.00, z=-43.75], EntityChicken['Chicken'/3616, l='MpServer', x=243.56, y=70.00, z=-8.53], EntityChicken['Chicken'/3617, l='MpServer', x=247.41, y=70.00, z=-7.17], EntityPig['Pig'/3618, l='MpServer', x=254.45, y=69.00, z=52.45], EntityPig['Pig'/3619, l='MpServer', x=254.06, y=69.00, z=54.91], Girlfriend['Girlfriend'/3620, l='MpServer', x=250.50, y=70.00, z=72.95], Girlfriend['Girlfriend'/3621, l='MpServer', x=257.50, y=65.00, z=72.78], EntityWolpertinger['Wolpertinger'/3622, l='MpServer', x=250.50, y=65.00, z=72.50], EntityWaypointContainer['unknown'/42, l='MpServer', x=0.00, y=0.00, z=0.00], EntityButterfly['Butterfly'/3886, l='MpServer', x=288.09, y=80.24, z=1.11], RedCow['Apple Cow'/3634, l='MpServer', x=263.13, y=63.00, z=-42.97], EntityChicken['Chicken'/3635, l='MpServer', x=259.44, y=71.00, z=-9.53], EntityChicken['Chicken'/3636, l='MpServer', x=266.63, y=70.00, z=-15.22], RockBase['Rock'/3637, l='MpServer', x=264.50, y=71.00, z=40.50], RockBase['Rock'/3638, l='MpServer', x=268.50, y=71.00, z=37.50], RockBase['Rock'/3639, l='MpServer', x=267.50, y=71.00, z=45.50], RockBase['Rock'/3640, l='MpServer', x=267.50, y=71.00, z=38.50], RockBase['Rock'/3642, l='MpServer', x=258.50, y=71.00, z=38.50], RockBase['Rock'/3643, l='MpServer', x=270.50, y=71.00, z=38.50], RockBase['Rock'/3644, l='MpServer', x=258.50, y=70.00, z=45.50], RockBase['Rock'/3645, l='MpServer', x=266.50, y=71.00, z=44.50], EntityPig['Pig'/3646, l='MpServer', x=252.34, y=70.00, z=51.28], GoldCow['Golden Apple Cow'/3647, l='MpServer', x=271.94, y=70.00, z=58.03], EntityPig['Pig'/3648, l='MpServer', x=264.06, y=70.00, z=60.97], Girlfriend['Girlfriend'/3649, l='MpServer', x=260.50, y=64.00, z=73.50], EntityTrail['unknown'/66, l='MpServer', x=257.03, y=75.62, z=16.36], Girlfriend['Girlfriend'/3650, l='MpServer', x=259.50, y=64.00, z=77.50], EntityChicken['Chicken'/3657, l='MpServer', x=275.75, y=68.00, z=-34.53], EntityFeeder['Spotted Bottom Feeder'/3913, l='MpServer', x=213.75, y=26.00, z=71.44], EntityChicken['Chicken'/3658, l='MpServer', x=285.44, y=66.00, z=-47.78], EntityChicken['Chicken'/3659, l='MpServer', x=271.56, y=69.00, z=-19.53], EntityChicken['Chicken'/3660, l='MpServer', x=281.95, y=67.00, z=-31.72], EntityJackalopes['Jackalope'/3661, l='MpServer', x=279.84, y=72.66, z=-1.59], EntityJackalopes['Jackalope'/3662, l='MpServer', x=281.09, y=72.07, z=-2.25], EntityButterfly['Butterfly'/3918, l='MpServer', x=280.87, y=71.88, z=41.51], EntityWolpertinger['Wolpertinger'/3663, l='MpServer', x=286.66, y=69.00, z=-10.16], EntityWolpertinger['Wolpertinger'/3664, l='MpServer', x=279.06, y=68.00, z=-10.47], EntityButterfly['Butterfly'/3920, l='MpServer', x=276.50, y=72.31, z=32.55], EntityJackalopes['Jackalope'/3665, l='MpServer', x=277.53, y=71.31, z=-3.94], EntityButterfly['Butterfly'/3921, l='MpServer', x=270.59, y=77.78, z=45.95], EntityWolpertinger['Wolpertinger'/3666, l='MpServer', x=275.50, y=72.00, z=29.50], EntityWolpertinger['Wolpertinger'/3667, l='MpServer', x=275.53, y=72.00, z=30.44], EntityWolpertinger['Wolpertinger'/3668, l='MpServer', x=283.50, y=70.00, z=43.50], GoldCow['Golden Apple Cow'/3669, l='MpServer', x=284.00, y=64.00, z=65.88], EntityWolpertinger['Wolpertinger'/3676, l='MpServer', x=296.94, y=73.00, z=-6.91], EntityJackalopes['Jackalope'/3677, l='MpServer', x=288.38, y=77.04, z=-7.53], EntityPig['Pig'/3678, l='MpServer', x=302.44, y=72.00, z=6.38], EntityPig['Pig'/3679, l='MpServer', x=303.75, y=71.00, z=5.09], EntityJackalopes['Jackalope'/3680, l='MpServer', x=302.31, y=72.84, z=5.38], EntityWolpertinger['Wolpertinger'/3681, l='MpServer', x=288.50, y=75.00, z=6.50], EntityWolpertinger['Wolpertinger'/3682, l='MpServer', x=291.50, y=75.00, z=6.50], EntityWolpertinger['Wolpertinger'/3683, l='MpServer', x=292.50, y=75.00, z=6.50], EntityJackalopes['Jackalope'/3684, l='MpServer', x=297.50, y=76.56, z=15.50], EntityJackalopes['Jackalope'/3685, l='MpServer', x=297.41, y=71.71, z=-4.53], EntityChicken['Chicken'/3692, l='MpServer', x=315.56, y=68.00, z=-43.44], EntityWolpertinger['Wolpertinger'/3693, l='MpServer', x=319.50, y=71.00, z=-26.50], EntityWolpertinger['Wolpertinger'/3694, l='MpServer', x=310.28, y=70.00, z=-7.53], EntityWolpertinger['Wolpertinger'/3695, l='MpServer', x=306.50, y=67.00, z=-8.50], EntityPig['Pig'/3696, l='MpServer', x=304.59, y=69.00, z=4.53], EntityWolpertinger['Wolpertinger'/3697, l='MpServer', x=308.25, y=69.00, z=11.38], EntityWolpertinger['Wolpertinger'/4209, l='MpServer', x=213.50, y=67.00, z=73.50], EntityPig['Pig'/3698, l='MpServer', x=308.81, y=74.00, z=2.19], EntityChicken['Chicken'/3705, l='MpServer', x=329.44, y=75.00, z=-38.44], EntityWolpertinger['Wolpertinger'/3706, l='MpServer', x=327.50, y=73.00, z=-17.50], EntitySkeleton['Skeleton'/4218, l='MpServer', x=258.50, y=14.00, z=74.50], EntityChicken['Chicken'/3707, l='MpServer', x=323.56, y=70.00, z=60.56], EntityChicken['Chicken'/3708, l='MpServer', x=334.78, y=71.00, z=66.66], EntityChicken['Chicken'/3709, l='MpServer', x=325.31, y=69.00, z=68.53], EntityChicken['Chicken'/3710, l='MpServer', x=329.06, y=70.00, z=74.53], EntitySkeleton['Skeleton'/4224, l='MpServer', x=323.50, y=21.00, z=80.50], EntityZombie['Zombie'/4225, l='MpServer', x=321.50, y=21.00, z=81.50], EntityZombie['Zombie'/4231, l='MpServer', x=338.50, y=19.00, z=34.50], EntityWolpertinger['Wolpertinger'/3733, l='MpServer', x=337.63, y=76.00, z=-31.41], EntityWolpertinger['Wolpertinger'/3735, l='MpServer', x=336.72, y=76.00, z=-31.25], EntityButterfly['Butterfly'/4265, l='MpServer', x=289.78, y=72.76, z=40.50], EntityWolpertinger['Wolpertinger'/4267, l='MpServer', x=282.50, y=72.00, z=39.50], EntityWolpertinger['Wolpertinger'/4268, l='MpServer', x=278.50, y=72.00, z=34.50], EntityChicken['Chicken'/3535, l='MpServer', x=182.47, y=66.00, z=-10.31], EntityChicken['Chicken'/3537, l='MpServer', x=179.59, y=65.00, z=55.56], EntityChicken['Chicken'/3559, l='MpServer', x=208.44, y=71.00, z=-53.47], EntityChicken['Chicken'/3560, l='MpServer', x=193.59, y=68.00, z=-39.59], EntityChicken['Chicken'/3574, l='MpServer', x=221.72, y=63.00, z=12.38], EntityChicken['Chicken'/3575, l='MpServer', x=219.56, y=63.00, z=8.63], EntityChicken['Chicken'/3576, l='MpServer', x=212.78, y=64.00, z=15.94], EntityChicken['Chicken'/3577, l='MpServer', x=215.84, y=63.00, z=22.75], EntityPig['Pig'/3578, l='MpServer', x=218.41, y=64.00, z=28.94], EntityPig['Pig'/3579, l='MpServer', x=211.94, y=63.00, z=26.12], EntityPig['Pig'/3580, l='MpServer', x=220.34, y=69.00, z=53.47], Girlfriend['Girlfriend'/3581, l='MpServer', x=219.50, y=65.00, z=60.66]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:425)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 280952880 bytes (267 MB) / 704643072 bytes (672 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D8 50 mods loaded, 50 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	particlecustomiser{1.0} [Particle Customiser] (minecraft.jar) 
	UCHIJA	modJ_StarMinerCore{0.9.9} [StarMinerCore] (minecraft.jar) 
	UCHIJA	se{0.4.1} [Super Enchants] (minecraft.jar) 
	UCHIJA	TooManyItems{1.7.10} [TooManyItems] (minecraft.jar) 
	UCHIJA	debug{1.0} [debug] (denseores-1.6.2.jar) 
	UCHIJA	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.3.jar) 
	UCHIJA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJA	extrastairs{1.7.10-2.0} [extrastairs] ([1.7.10]ExtraStairs.jar) 
	UCHIJA	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCHIJA	koresample{1.7.10-1.3.2} [Kore Sample] (KoreSample-1.7.10-1.3.2.jar) 
	UCHIJA	dendrology{1.7.10-1.6.4} [Ancient Trees] (AncientTrees-1.7.10-1.6.4.jar) 
	UCHIJA	modJ_StarMiner{0.9.9} [Starminer Mod] (Anti-Gravity-Mod-1.7.10.jar) 
	UCHIJA	apples{1.4} [apples] (Apples-Mod-1.7.10.jar) 
	UCHIJA	armourersWorkshop{1.7.10-0.48.5} [Armourer's Workshop] (Armourers-Workshop-1.7.10-0.48.5.jar) 
	UCHIJA	B0bGrowsOre{1.9.2} [B0bGary's Growable Ores] (B0bGarys-Growable-Ores-Mod-1.7.10.jar) 
	UCHIJA	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x (1).jar) 
	UCHIJA	FLabsBF{4.3} [Better Furnaces] (Better-Furnaces-Mod-1.7.10.jar) 
	UCHIJA	CarpentersBlocks{3.3.8.1} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8.1 - MC 1.7.10.jar) 
	UCHIJA	cpsmod{2.0} [CPSMod] (CPSMod v2 1.7.10.jar) 
	UCHIJA	craftguide{1.7.1.0} [CraftGuide] (CraftGuide-1.7.1.0-forge.jar) 
	UCHIJA	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UCHIJA	DyeableBeacons{1.1.1} [Dyeable Beacons] (DyeableBeacons-1.1.1.jar) 
	UCHIJA	emeraldobsidianmod{1.3.1} [Emerald & Obsidian tools/armor mod] (emeraldobsidianmod-1.7.10-1.3.1.jar) 
	UCHIJA	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCHIJA	enchapples{1.0} [Enchanted Apples] (EnchApples-1.11.jar) 
	UCHIJA	extremefoodmod{0.5} [Extreme Food] (ExtremeFood[0.5+Beta-MC+1.7.10].jar) 
	UCHIJA	fakename{1.0} [Fake Name] (Fakename+MC1.7.10+v1.0.jar) 
	UCHIJA	fantastic{1.0.0} [Fantastic Fish] (Fantastic-Fish-Mod-1.7.10.jar) 
	UCHIJA	iChunUtil{4.2.3} [iChunUtil] (iChunUtil-4.2.3.jar) 
	UCHIJA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJA	journeymap{5.1.4p2} [JourneyMap] (journeymap-1.7.10-5.1.4p2-unlimited.jar) 
	UCHIJA	LagBGon{.1.2} [Lag'B'Gon] (LagBGon-0.1.2.jar) 
	UCHIJA	lucky{5.1.0} [Lucky Block] (Lucky-Block-Mod-1.7.10.jar) 
	UCHIJA	me{1.3.1.2} [More Enchantments] (More-Enchantments-Mod-1.7.10.jar) 
	UCHIJA	AencEx{0.0.1} [AencEx] (More-Enchantments-Mod-1.7.10.jar) 
	UCHIJA	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10) (1).jar) 
	UCHIJA	mam{1.7.10-1.0.2} [Myths & Monsters Mod] (Myths-and-Monsters-Mod-1.7.10.jar) 
	UCHIJA	NBTEdit{1.7.2.2} [In-game NBTEdit] (NBTEdit_1.7.10.jar) 
	UCHIJA	OreSpawn{1.7.10.20.3} [OreSpawn] (Ore-Spawn-Mod-1.7.10.zip) 
	UCHIJA	PortalGun{4.0.0-beta-6} [PortalGun] (PortalGun-4.0.0-beta-6-fix-1.jar) 
	UCHIJA	samsapples{1.7.10-1.1.3} [Power Apples] (Power-apples-mod-by-lothrazar-1.7.10.jar) 
	UCHIJA	rivalrebels{1.7.10Z1} [Rival Rebels] (rivalrebels-1.7.10Z1.jar) 
	UCHIJA	shinyfood{1.5} [ShinyFood] (ShinyFood-Mod-1.7.10.jar) 
	UCHIJA	Treecapitator{1.7.10} [Treecapitator] (Tree-Capitator-Mod-1.7.10.jar) 
	UCHIJA	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.7.10-6.1.1-dist.jar) 
	UCHIJA	voxelmap{1.7.10} [VoxelMap No Radar] (Zans-Minimap-No-Radar-Mod-1.7.10.jar) 
	UCHIJA	denseores{1.0} [Dense Ores] (denseores-1.6.2.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 535.98' Renderer: 'NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2'
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	Armourer's Workshop: 
		Render Type: MODEL_ATTACHMENT
		Texture Render: false
		Baking Queue: 0
		Request Queue: 0
		Texture Painting: true
		Multipass Skin Rendering: true
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 535.98, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_D8
	Render Distance Chunks: 12
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 535.98
	OpenGlRenderer: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8"

**Comment by mysticdrew** [comment]
pasting logs into issue is an insta close. 
Upload files directly.

**Comment by Janneftw2** [comment]
Oh thank you I didn't know that
