### ISSUE TITLE
[Bug]: {Water Blending fails to blend correctly}

### ISSUE THREAD

**Issue by AliCCfire** [TeamJM/journeymap#607]
### What happened?

When drawing a chunk that is at the render distance border, Journeymap messes up the blending, likely due to not having a blending ref, so it assumes white and blends a white line on the border chunk.

![image](https://github.com/TeamJM/journeymap/assets/97907169/cf8d8334-915e-4314-92a6-0c153f2769cb)

As can be seen above, the issue happens at chunk borders, with the option [cartography] Surface Max Distance set to 0, which means the issue lies at render borders, as is suggested on the thread below.

#289 
> This is added in 5.7.2 beta 12 for mc 1.16.5. Setting journeymap's render distance (cave or surface) to 0 will then default to using the minecraft's game render distance.

hypothesis which is also supported by the fact that the white marks disappeared once I set Surface Max Distance to 5 while having the game's render distance set to 10

![image](https://github.com/TeamJM/journeymap/assets/97907169/863666cc-7d20-40fc-af6b-b0224cface39)

funnily enough, however, the issue still happens when Surface Max Distance is anywhere close to Render Distance, Which might suggest that the issue can happen at any chunk border between a loaded and an unloaded chunk.

the highest i managed to set Surface Max Distance while at RenderDistance 10 was 7

### Mod Loader

Fabric

### Minecraft Version

1.19.2

### Version

5.9.7

### Relevant log output

No relevant log outputs are generated on this issue.

**Comment by mysticdrew** [comment]
This is in multiplayer I assume?

**Comment by AliCCfire** [comment]
you assumed quite right actually. part of the reason why i didn't test for anything beyond 10 chunk radius is because i was too lazy to change server configs on that

**Comment by mysticdrew** [comment]
Can you try in singleplayer please.

**Comment by AliCCfire** [comment]
Checked in singleplayer and the issue does not seem to happen at all.
Reviewed my server's config and realized render distance was set to 8, so my guess is that the issue happens when the mod tries blending something which it didn't get data of, since the bug only happened with Surface Max Distance >= server render distance

**Comment by mysticdrew** [comment]
Hmm, that was supposed to be fixed in 5.9.3. Are you able to come into our discord so we can do some testing?

**Comment by AliCCfire** [comment]
sure thing. i am reviewing the modpack to see if there's any risk of it being a compat issue

**Comment by AliCCfire** [comment]
Found the issue! It seems that the bug was reintroduced by adding [view distance fix](https://www.curseforge.com/minecraft/mc-mods/view-distance-fix) to the server.

[That mod](https://www.curseforge.com/minecraft/mc-mods/view-distance-fix) seems to objectively cause the issue. Once removed, no more errors occurred.

`viewdistancefix-1.19.2-1.0.0.jar` was the main culprit.
