### ISSUE TITLE
"Unable to delete map. See journeymap.log for details."

### ISSUE THREAD

**Issue by XvaleX10** [TeamJM/journeymap#608]
### What happened?

A bug happened!

I can't delete the map

### Mod Loader

Forge

### Minecraft Version

1.12.2

### Version

5.7.1

### Relevant log output

[journeymap.log](https://github.com/TeamJM/journeymap/files/11855954/journeymap.log)

**Comment by mysticdrew** [comment]
go to the directory "C:\Users\valed\curseforge\minecraft\Instances\Jurassic Test\journeymap\data\sp\New World\" and do it manually.
