### ISSUE TITLE
[Feature Request]: Add a way to always see the mob / entity head

### ISSUE THREAD

**Issue by Imzxhir** [TeamJM/journeymap#609]
### Describe the new feature.

Basically the title. When a mob or entity goes away from your player, the mob head starts to fade away leaving the name on its own which in my opinion, is a bit weird. My proposal is to add an option to keep rendering the mob head even when they go away from you, this is a more of a QoL feature as some people may like the fading out of mob heads and some people may not.

*This issue is also similiar to https://github.com/TeamJM/journeymap/issues/577*

**Comment by mysticdrew** [comment]
Okay, fixed the name fading issue. 
Added the always show Advanced Option. 
This is till effected by the vertical distance. But no more fading with option disabled. 
![image](https://github.com/user-attachments/assets/208dbb6a-1c5a-4595-9d04-6db2cf4323c9)
