### ISSUE TITLE
[1.12.2]In JM 5.5.2, Non-English name world use same map bug

### ISSUE THREAD

**Issue by Flithor** [TeamJM/journeymap#61]
#### JourneyMap Version:

1.12.2-5.5.2

#### Forge Version:

1.12.2-14.23.3.2678`

#### What's happened:

World with non-English name will using the same map
Speculation this problem caused by the loss non-English characters when coding conversion.

**Comment by mysticdrew** [comment]
Examples of names please. 

I do not really understand what you mean by non-english name uses same map. What is the same map? 

If both of your worlds are named the same, then it does not matter what language is used, it will use the same map. Give your worlds unique names! 

I will close this issue until you can add more detail, then I will reopen it if needed.

**Comment by Flithor** [comment]
well, this bug not exist in 5.5.4.

just like one world called“新的世界”, another world called“另一个世界”
they will use same map. enter those world, the map data will cover each other.

**Comment by mysticdrew** [comment]
So, it is no longer a bug then? marked as fixed. 

Thanks!

**Comment by Flithor** [comment]
Correction: Bug still exists, and this bug still exists in 5.5.4.
When I was testing, the world names were doped with a space character. So I mistakenly believe that the bug has disappeared.

**Comment by mysticdrew** [comment]
@Flithor can you do me a favor. In the directory where minecraft is located, can you navigate to minecraft/jouneymap/data/ In there will be up to 2 folders, sp for single player, mp for multiplayer. can you take a screen shot of the inside of the folders that exist in there please? I want to see howit is saving the folder names, so I can fix it. 

Thanks!

**Comment by Flithor** [comment]
![image](https://user-images.githubusercontent.com/23412916/55375293-32cade00-553e-11e9-8b4b-66bafd46b38d.png)
"~" is for the world with name is Chinese character

**Comment by mysticdrew** [comment]
Thanks, I will look into it!

**Comment by mysticdrew** [comment]
@Flithor can you come into discord when you get a chance please so I can have you test to make sure my fix works? https://discord.gg/UVUJMH

**Comment by mysticdrew** [comment]
marking as resolved, my internal tests show it is fixed.
