### ISSUE TITLE
[Crash]: Game crash running Journey mod.

### ISSUE THREAD

**Issue by GitHubUser0220Yu** [TeamJM/journeymap#610]
### What happened?

A crash happened! When I run my game with this mod version 1.20.1, I enter my world to where it crashes my game and closes out.

### Mod Loader

Forge

### Minecraft Version

1.20.1

### Version

6.0.0

### Relevant log output

The game crashed whilst an unexpected error
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.RenderType.m_110185_()" because "type" is null

**Comment by mysticdrew** [comment]
remove occulus

**Comment by mysticdrew** [comment]
This is fixed in `JourneyMap-1.20.1-5.9.10-forge` should be on curseforge once approved(couple hours from now) and modrinth very soon (couple minutes)

**Comment by GitHubUser0220Yu** [comment]
Ok thank you.

**Comment by Drumstix42** [comment]
> This is fixed in `JourneyMap-1.20.1-5.9.10-forge` should be on curseforge once approved(couple hours from now) and modrinth very soon (couple minutes)

I'm still running into this issue on **MC 1.20.2**. Mod is installed on the server side. The first client (_any client_) that joins, will work fine. The 2nd client, when joining, gets the same error/crash listed in this Issue.

**Comment by mysticdrew** [comment]
I need logs

**Comment by mysticdrew** [comment]
> > This is fixed in `JourneyMap-1.20.1-5.9.10-forge` should be on curseforge once approved(couple hours from now) and modrinth very soon (couple minutes)
> 
> I'm still running into this issue on **MC 1.20.2**. Mod is installed on the server side. The first client (_any client_) that joins, will work fine. The 2nd client, when joining, gets the same error/crash listed in this Issue.

@Drumstix42

Please create a new issue and provide following
- The `journeymap.log` from the crashing user.
- The `crash.log` from the crashing user. 
- The `latest.log` from the crashing user.

I need all three logs.
