### ISSUE TITLE
[Bug]: All players get kicked after sending a waypoint in chat and then typing a follow up message

### ISSUE THREAD

**Issue by greendayguy7** [TeamJM/journeymap#611]
### What happened?

When sharing a waypoint to chat and then saying something else in chat all players get kicked for a chat message validation error. I am running a custom modpack and have never seen this issue with journey map before.

### Mod Loader

Fabric

### Minecraft Version

1.19.2

### Version

5.9.7

**Comment by mysticdrew** [comment]
Is there anything in the logs, server or client. 
This issue was fixed in 5.9.6, curious it came back.

**Comment by mysticdrew** [comment]
I am unable to replicate this on my end. 
I will close this for now I guess. Please verify you are using 5.9.7 and not an earlier version.
