### ISSUE TITLE
[Bug]: Toggle all Waypoints don't work with mouse button

### ISSUE THREAD

**Issue by LeoBeliik** [TeamJM/journeymap#612]
### What happened?

Setting the keybind for `Toggle all Waypoints` to a mouse button (button 4 or button 5) don't toggle the waypoints, it only work with keyboard... keys..

![image](https://github.com/TeamJM/journeymap/assets/11804768/e2604752-8a78-49f8-979f-af97117bb6c0)

### Mod Loader

Forge

### Minecraft Version

1.19.2

### Version

5.9.7

**Comment by mysticdrew** [comment]
Fixed for 5.9.11
