### ISSUE TITLE
[Bug]: Journey Map doesn't like it when I swift-sneak

### ISSUE THREAD

**Issue by artealys** [TeamJM/journeymap#613]
### What happened?

Ever since I got the swift sneak enchantment, sneaking too quickly while breaking blocks causes the chunk I am in the go invisible (but I don't fall into the void) and Journey Map starts rapidly flickering between clear and white squares. It only stops when I stop sneaking and leave the chunk. It didn't crash but this keeps happening. The version is 5.9.9.

### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Version

other (please list)

**Comment by artealys** [comment]
Update: It's not going away now. If I happen to step in a white square on the map things go back to semi-normal (the map stops flickering but some chunks are still clear) but as soon as I step out, most chunks around me are transparent as well.

**Comment by mysticdrew** [comment]
How do you know this is journeymap?

You have provided no logs either, it is required per the bug template.

**Comment by artealys** [comment]
I don't have a journeymap.log file in that location so I could not provide it. I just updated to 5.9.10 and haven't had the issue again so I would say that journeymap WAS the problem.

**Comment by mysticdrew** [comment]
The change for 5.9.10 was for waypoint icons, a very small change. It is unlikely to fix the issue, I suspect that restarting minecraft is what fixed the issue.

**Comment by artealys** [comment]
Then I suppose the issue will come back...
