### ISSUE TITLE
[Feature Request]: Add a way to scale individual entity icons

### ISSUE THREAD

**Issue by Imzxhir** [TeamJM/journeymap#615]
### Describe the new feature.

Basically the title, I want a feature where you can scale individual entity icons for both the minimap and world map. This would be helpful for modded icons and if they are small, the mob / entity icon can be scaled and be made wither bigger or smaller depending on what the user picks.

I was thinking that the scale for individual entity icon would be the same or similar so the user would have a variety of scales to choose from.

**Comment by mysticdrew** [comment]
are you suggesting for each icon individually. Or scaling individually as in mobs vs villagers vs animals? 
Because if you want to scale a creeper vs a skeleton icon, that will make a huge mess for any UI.

**Comment by Imzxhir** [comment]
Yeah, I am suggesting each icon individually.

**Comment by mysticdrew** [comment]
This honestly would be a nightmare to implement. 
Designing a UI and having to save the data for each Icon does not sound fun. 

Were you testing mods that supplied their own entity icons via resource packs or JM 6 alpha? If there are Icon issues, we can look into forcing a specific size so they are all the same size when generated.

**Comment by Imzxhir** [comment]
I was testing JM 6 Alpha and I was testing the mod with Better MC [FABRIC] 1.20, I noticed that some modded entity icons were small and heard to see compared to other ones where they were bigger.

**Comment by mysticdrew** [comment]
I added a channel for jm6 feedback. Let's keep jm6 talk there.

**Comment by AnrDaemon** [comment]
You could always create resource pack with mob icons of a desired size. The icon sprite dimension is quite allowing.
