### ISSUE TITLE
[Bug]: when waypoints are turned on models of you and items you hold look weird

### ISSUE THREAD

**Issue by UnderMan4** [TeamJM/journeymap#616]
### What happened?

I am not sure how to better describe this but its like they are much larger and further from player so when you are next to wall they sink into it.
Here is a video of this bug: [journeymap bug.mp4](https://cdn.discordapp.com/attachments/1091065409270206604/1125401473379991662/journeymap_bug.mp4)

I got this bug only on version of journeymap 5.9.10

### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Version

other (please list)

### Relevant log output

[latest.log](https://cdn.discordapp.com/attachments/1091065409270206604/1125402619112849458/latest.log)
[journeymap.log](https://cdn.discordapp.com/attachments/1091065409270206604/1125402647722201198/journeymap.log)

**Comment by mysticdrew** [comment]
Known issue and fixed for the next release already. I will close this issue when I publish the fix.

**Comment by mysticdrew** [comment]
also, if you go back to 5.9.9 it will work perfectly. 5.9.10 was mostly a refactor of some waypoint rendering which I missed how held items go in the blocks.

**Comment by mysticdrew** [comment]
publishing the release ina  few minutes, it will be on modrinth first, then cf
