### ISSUE TITLE
[Feature Request]: A shortcut for the "follow" command on the fullscreen map

### ISSUE THREAD

**Issue by vegiii** [TeamJM/journeymap#621]
### Describe the new feature.

I think it would have been easier to find my player on the fullscreen map if you had a hotkey for the "follow" command. I have a large world and if i scroll wide and far on the map it would have been faster for me if i had a shortcut. I know there is a button on the map, but i would rather have a short.

Thanks for creating this awesome mod!

**Comment by mysticdrew** [comment]
The F key will be the default keybind when in the fullscreen map for enabling following. 

This is completed for Journeymap v6 release. It will not be back ported.

**Comment by mysticdrew** [comment]
Cleaning up the issue tracker
Closing as this is completed for JourneyMap v6 when it is released.
