### ISSUE TITLE
[Crash]: Mod crashes when I create a waypoint while having oculus installed.

### ISSUE THREAD

**Issue by NotPauliboiiii** [TeamJM/journeymap#622]
### What happened?

Game crashed after I created a waypoint. Deleted oculus and it worked. Sent a issue to oculus aswell.

Error code: -1

Journey Map Version: 5.9.9

### Mod Loader

Forge

### Minecraft Version

1.20.1

### Version

other (please list)

### Relevant log output

[journeymap.log](https://github.com/TeamJM/journeymap/files/12061450/journeymap.log)
[latest.log](https://github.com/TeamJM/journeymap/files/12061453/latest.log)
[crash-2023-07-15_15.05.51-client.txt](https://github.com/TeamJM/journeymap/files/12061454/crash-2023-07-15_15.05.51-client.txt)

**Comment by mysticdrew** [comment]
update journeymap to 5.9.11
