### ISSUE TITLE
[Crash]: Server crash happened!

### ISSUE THREAD

**Issue by yoku0206** [TeamJM/journeymap#624]
### What happened?

When i use EssentialAddons's reloadFakePlayers it give me this error

### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Version

other (please list)

### Relevant log output

[crash-2023-07-18_20.28.18-server.txt](https://github.com/TeamJM/journeymap/files/12080584/crash-2023-07-18_20.28.18-server.txt)

**Comment by mysticdrew** [comment]
Someone reported this in discord yesterday, it will be fixed for the next release. I will update this issue once I release it. Thanks!

**Comment by mysticdrew** [comment]
This is fixed in 1.20.1-5.9.12 
CI is building now and publishing to CF and MD
