### ISSUE TITLE
[Bug]: visual relocation of waypoints

### ISSUE THREAD

**Issue by SteelTigerV2** [TeamJM/journeymap#625]
### What happened?

A visual bug happened!
![2023-07-25_23 36 23](https://github.com/TeamJM/journeymap/assets/78177911/9f47b1e5-0188-4a7a-a661-4cafb116b03f)
as you can see the way points are placed behind me but render in front of me

### Mod Loader

Forge

### Minecraft Version

1.18.2

### Version

5.9.7

**Comment by SteelTigerV2** [comment]
it's really anoying

**Comment by mysticdrew** [comment]
Fix the title of the issue... 

This is likely a mod interaction issue. Try with just journeymap and no other mods.

**Comment by SteelTigerV2** [comment]
with just journey map no bug
is there any known incompatilbe mods ?

**Comment by mysticdrew** [comment]
> with just journey map no bug is there any known incompatilbe mods ?

Not that I am aware of. 
You will need to slowly add mods back in until they break to see which one is causing the issue. 

```
The binary search is a way of finding a faulty thing among a lot of other things, without having to remove the things one-by-one.
This is useful for finding a broken mod among hundreds of mods, without having to spend time testing the mods one-by-one.
The procedure is simple:
  1. Remove half of the existing things, and put them aside.
  2. Run the program / game.
  3. Does the issue still exist?
    If YES: Repeat from step 1 with the current things.
    IF NO: Swap out the current things with the ones set aside, and repeat from step 1.
  4. Repeat this process until the problematic thing/s have been found.
```

**Comment by mysticdrew** [comment]
Two weeks, no response. 
Closing as stale
