### ISSUE TITLE
[1.18.2]: direct connect to IP over LAN doesn't load waypoints from previous sessions

### ISSUE THREAD

**Issue by raphaelsiz** [TeamJM/journeymap#626]
### What happened?

My spouse and I have been playing "Auto-TerraFirmaCraft (TFC + Create) ATFC V1.8.2" (on FTB) on a world on my computer over LAN. Today I booted up my world and opened to LAN, and my spouse booted up their version of the modpack, but for some reason the button they usually click to join me wasn't there (this is probably an error in Minecraft or another mod, just context here), so I gave them my IP address and the port the chat said my world was hosted on. They were able to join through the "direct connection" as if I was hosting a server, and all of their personal data on Minecraft's side of things (inventory etc) was remembered just fine, but all of their waypoints are gone. I suspect that the information is still stored in one of our computers (and I'll gladly test this theory if someone tells me where to look), but it seems JourneyMap didn't properly load their data because they entered the world in a different way.

### Mod Loader

Forge

### Minecraft Version

1.18.2

### Version

5.9.7

**Comment by raphaelsiz** [comment]
Note I didn't include "Relevant log output" because it says it has to be the actual file, which is probably in a different location for me and also contains personal information

**Comment by mysticdrew** [comment]
> Note I didn't include "Relevant log output" because it says it has to be the actual file, which is probably in a different location for me and also contains personal information

It does not contain personal information. 

This issue is expected behavior. 
Journeymap saves data by the name you give your server in the multiplayer menu. When you use the direct connect, there is no name so it uses a default folder since it has no idea what data to pull.
