### ISSUE TITLE
[Bug]: Minimap messes up GUI

### ISSUE THREAD

**Issue by WimpieRatte** [TeamJM/journeymap#628]
### What happened?

JourneyMap Version: 5.9.12

When the minimap is enabled, it squashes the rest of the GUI into the top left corner.
Not sure if this is related to a different mod installed, but with the minimap disabled, the HUD returns back to normal.
![image](https://github.com/TeamJM/journeymap/assets/42098550/41e850e1-8e4a-476a-844a-08f804588344)

This doesn't crash the game, so please let me know which logs I can upload, since there is no error log?

Since this might also be caused by a different mod, here's the mod list:

>   [✔] (Fabric)GlowInkPlus-1.20-1.2.0
  [✔] ACE-2.0.5
  [✔] ad_astra-fabric-1.20.1-1.15.3
  [✔] AdditionalStructures-1.20.x-(v.4.2.0)
  [✔] advancednetherite-fabric-2.0.2-1.20.1
  [✔] AdvancementPlaques-1.20.1-fabric-1.4.11
  [✔] advancementscreenshot-1.20.1-4.2
  [✔] alloy-forgery-2.0.22+1.20
  [✔] AmbientSounds_FABRIC_v5.2.20_mc1.20.1
  [✔] amecs-1.3.9+mc.1.20-pre2
  [✔] antighost-1.20-fabric0.83.0-1.1.5
  [✔] appleskin-fabric-mc1.20-2.5.0
  [✔] appliedenergistics2-fabric-15.0.6-beta
  [✔] arachnids-1.20.1-0.0.28
  [✔] architectury-9.1.12-fabric
  [✔] areas-1.20.1-5.0
  [✔] argonauts-fabric-1.20.1-0.1.3
  [✔] armorpod-1.4-1.20-fabric
  [✔] ArmorStatues-v8.0.2-1.20.1-Fabric
  [✔] autohud-6.1+1.20-fabric
  [✔] automobility-0.4.2+1.20.1-fabric
  [✔] automodpack-mc1.20.1-fabric-3.4.3
  [✔] autotools-1.6-fabric-1.20.1
  [✔] azurelib-fabric-1.20.1-1.0.19
  [✔] backslot-1.2.13
  [✔] backslotaddon-1.1.0
  [✔] BagOfHolding-v8.0.0-1.20.1-Fabric
  [✔] balm-fabric-1.20-7.0.7
  [✔] BarteringStation-v8.0.0-1.20.1-Fabric
  [✔] beautify-1.0.0+fabric-1.20
  [✔] bendy-lib-fabric-4.0.0
  [✔] better_climbing-fabric-3
  [✔] BetterAdvancements-Fabric-1.20.1-0.3.2.161
  [✔] BetterAnimationsCollection-v8.0.0-1.20.1-Fabric
  [✔] bettercombat-fabric-1.7.2+1.20.1
  [✔] BetterF3-7.0.1-Fabric-1.20.1
  [✔] BetterFurnaces-1.20.1-1.0.1-fabric
  [✔] bettermounthud-1.2.2
  [✔] betterstats-2.10.3+1.20.1
  [✔] bettertrims-1.1.0
  [✔] better-trim-tooltips-1.0.1
  [✔] BlockRunner-v8.0.0-1.20.1-Fabric
  [✔] bobby-5.0.0
  [✔] botarium-fabric-1.20.1-2.2.0
  [✔] Bountiful-6.0.3+1.20.1-fabric
  [✔] brrp-fabric-1.0.1-1.20.1
  [✔] butterfingers-1.0
  [✔] cadmus-fabric-1.20.1-0.0.6
  [✔] CameraOverhaul-1.4.0-fabric-universal
  [✔] carryon-fabric-1.20.1-2.1.1.3
  [✔] chalk-2.2.0
  [✔] chalk-colorful-addon-2.1.1
  [✔] chat_heads-0.10.19-fabric-1.20
  [✔] cherishedworlds-fabric-6.1.1+1.20.1
  [✔] clickthrough-1.20-fabric0.83.0-0.4.1
  [✔] cloth-config-11.1.106-fabric
  [✔] Clumps-fabric-1.20.1-12.0.0.3
  [✔] collective-1.20.1-6.65
  [✔] combatroll-fabric-1.2.1+1.20.1
  [✔] comforts-fabric-6.3.3+1.20.1
  [✔] CompletionistsIndex-v8.0.0-1.20.1-Fabric
  [✔] continuebutton-1.1.1+1.20
  [✔] cookingforblockheads-fabric-1.20-16.0.0
  [✔] copyworld-1.0.1
  [✔] CraftingPad-fabric-1.20.1-1.0.12
  [✔] craftingtweaks-fabric-1.20-18.0.2
  [✔] crawl-0.12.0
  [✔] CreativeCore_FABRIC_v2.10.28_mc1.20.1
  [✔] creeperoverhaul-3.0.1-fabric
  [✔] crops_love_rain-1.4.0
  [✔] ctov-3.3.2
  [✔] ctov-farmers-delight-compat-2.0
  [✔] ctov-friends-and-foes-compat-2.0
  [✔] deathlog-0.3.2+1.20
  [✔] defaultoptions-fabric-1.20-18.0.1
  [✔] DistinguishedPotions-v8.0.1-1.20.1-Fabric
  [✔] doubledoors-1.20.1-5.0
  [✔] duckling-3.0.0-fabric
  [✔] dummmmmmy-1.20-1.7.9-fabric
  [✔] dungeons-and-taverns-v2.1.4
  [✔] DungeonsArise-1.20.1-2.1.56-fabric-beta
  [✔] dynamic-fps-2.4.0
  [✔] dynmus-v2.3.1+1.20-fabric
  [✔] EasyAnvils-v8.0.1-1.20.1-Fabric
  [✔] EasyShulkerBoxes-v8.0.0-1.20.1-Fabric
  [✔] eating-animation-1.9.4+1.20
  [✔] EffectDescriptions-v8.0.1-1.20.1-Fabric
  [✔] emi-1.0.15+1.20.1+fabric
  [✔] emotecraft-for-MC1.20.1-2.2.7-b.build.50-fabric
  [✔] EnderZoology-v8.0.1-1.20.1-Fabric
  [✔] energizedpower-1.20.1-1.8.0-beta-1-fabric
  [✔] enhancedblockentities-0.9+1.20
  [✔] entity_texture_features_fabric_1.20-4.4.4
  [✔] entityculling-fabric-1.6.2-mc1.20
  [✔] EquipmentCompare-1.20.1-fabric-1.3.7
  [✔] explosive-enhancement-1.2.0-1.20.x
  [✔] ExtendedDrawers-2.0.5+mc.1.20.1
  [✔] extra_details-0.1.1+1.20-1.20.1-beta
  [✔] fabric-api-0.86.1+1.20.1
  [✔] fabric-language-kotlin-1.10.8+kotlin.1.9.0
  [✔] FactoryAPI-1.20.1-1.0-fabric
  [✔] fallingleaves-1.15.2+1.20.1
  [✔] farmers-delight-fabric-mc1.20.1-1.4.1
  [✔] farmingforblockheads-fabric-1.20-14.0.1
  [✔] fefes_storage1.20.1
  [✔] ferritecore-6.0.0-fabric
  [✔] FishingRework-1.20.1-0.2.7
  [✔] foodeffecttooltips-1.1.1-1.20.0
  [✔] footprintparticle-0.3.1c-mc1.20
  [✔] ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric
  [✔] ForgeConfigScreens-v8.0.2-1.20.1-Fabric
  [✔] forgero-fabric-0.10.9.2+1.20.1
  [✔] forgottengraves-1.20.1-3.2.0
  [✔] friendsandfoes-fabric-mc1.20.1-1.9.3
  [✔] FrozenLib-1.3.4-Fabric+1.20.1
  [✔] fullturtlearmor-1.5-fabric-mc1.20.1
  [✔] fusion-1.0.5-fabric-mc1.20
  [✔] geckolib-fabric-1.20.1-4.2.1
  [✔] gottagofast-1.1.0
  [✔] grapplemod-1.20.1-v1.6
  [✔] gravelminer-fabric-1.20-16.0.2
  [✔] grindstonesharpertools-1.20.1-3.1
  [✔] grizzlybear-1.20-1.6.1
  [✔] hardcorerevival-fabric-1.20-12.0.0
  [✔] healthindicator-1.1.0+mc1.20
  [✔] held-item-info-1.5.0
  [✔] heracles-fabric-1.20.1-0.0.6
  [✔] hiddenrecipebook-1.20.1-4.0
  [✔] iammusicplayer-fabric-mc1.20-3.22.0-alpha.1
  [✔] Iceberg-1.20.1-fabric-1.1.13
  [✔] idwtialsimmoedm-0.2.0+1.20
  [✔] immersive_aircraft-0.5.1+1.20.1-fabric
  [✔] indium-1.0.21+mc1.20.1
  [✔] InGameAccountSwitcher-Fabric-1.20-8.0.2
  [✔] instant-structures-1.0.0
  [✔] interactic-0.2.0+1.20
  [✔] inventoryessentials-fabric-1.20-8.0.0
  [✔] InventoryProfilesNext-fabric-1.20-1.10.6
  [✔] inventorytotem-1.20.1-3.0
  [✔] Jade-1.20-fabric-11.3.0
  [✔] jingle-1.0.2-1.20.1
  [✔] journeymap-1.20.1-5.9.12-fabric
  [✔] Kambrik-6.1.1+1.20.1-fabric
  [✔] knavesneeds-fabric-1.1.5+1.20.1
  [✔] labellingcontainers-1.2.4-mc1.20.1
  [✔] langsplit-1.20.1-2.3-beta
  [✔] language-reload-1.5.8+1.20.1
  [✔] lanterns-belong-on-walls-1.6.1+1.20.1
  [✔] largefluidtank-fabric-20.4.2
  [✔] laserbridges-1.20.1-1-fabric
  [✔] LeavesBeGone-v8.0.0-1.20.1-Fabric
  [✔] level-up-1.1
  [✔] liberty-villagers-mod-1.0.14+fabric+1.20.1
  [✔] libIPN-fabric-1.20-3.0.2
  [✔] lithium-fabric-mc1.20.1-0.11.2
  [✔] lootbags-2.0.0-fabric
  [✔] lovely_snails-1.1.2+1.20.1
  [✔] LunaSlimes-1.6.1-1.20
  [✔] mchalo-1.20-1.1.19
  [✔] memoryleakfix-fabric-1.17+-1.1.1
  [✔] midnightlib-fabric-1.4.1.1
  [✔] minecraft-comes-alive-7.5.3+1.20.1-universal
  [✔] mineralchance-1.20.1-3.2
  [✔] mishanguc-1.2.4-1.20.1
  [✔] mobility-1.1.0
  [✔] MobLassos-v8.0.0-1.20.1-Fabric
  [✔] mod-loading-screen-1.0.2
  [✔] modmenu-7.2.1
  [✔] moonlight-1.20-2.7.2-fabric
  [✔] MoreBows-1.0.11+1.20.x
  [✔] moremobvariants-fabric+1.20-1.2.2
  [✔] moreswordsmod-0.0.2-1.20.1
  [✔] MouseTweaks-fabric-mc1.20-2.25
  [✔] mru-0.2.1+1.20
  [✔] myloot-4.0.3-1.20.1
  [✔] mythicmetals-0.18.2+1.20
  [✔] NetherChested-v8.0.1-1.20.1-Fabric
  [✔] no-shield-delay-1.0.0
  [✔] Notebook-3.1.0+1.20.1
  [✔] notenoughanimations-fabric-1.6.4-mc1.20
  [✔] nutritious-feast-1.7.1
  [✔] otyacraftengine-fabric-mc1.20-3.7.0-alpha.2
  [✔] owo-lib-0.11.1+1.20
  [✔] particle-rain-2.0.7
  [✔] Philips-Ruins1.20.1-1.6[Fabric]
  [✔] philter-1.3.1+1.20.1
  [✔] PickUpNotifier-v8.0.0-1.20.1-Fabric
  [✔] piercingpaxels-1.0.11
  [✔] Ping-Wheel-1.4.0-fabric-1.20.1
  [✔] platforms-fabric-1.20.1-1.0
  [✔] player-animation-lib-fabric-1.0.2-rc1+1.20
  [✔] plenty-of-armors-1.2.1+mc1.20.1
  [✔] PlentyPlates-v8.0.0-1.20.1-Fabric
  [✔] polymer-bundled-0.5.6+1.20.1
  [✔] polymorph-fabric-0.49.0+1.20.1
  [✔] portabletables-fabric-1.20.1-2.4
  [✔] postmortalparticles-1.0.0-1.20.x
  [✔] PresenceFootsteps-1.9.0
  [✔] primalstorage-1.3-1.20-fabric
  [✔] PuzzlesLib-v8.0.14-1.20.1-Fabric
  [✔] quartz-elevator-2.2.5+1.20
  [✔] quickpaths-1.20.1-3.0
  [✔] quickstack-1.0.1-beta1+1.20.1
  [✔] randomvillagenames-1.20.1-3.3
  [✔] rare-ice-0.6.0
  [✔] reacharound+1.20-1.1.2
  [✔] rechiseled-1.1.2-fabric-mc1.20
  [✔] reeses_sodium_options-1.6.3+mc1.20.1-build.92
  [✔] reinforced-barrels-2.4.1+1.20
  [✔] reinforced-chests-2.4.2+1.20
  [✔] reinforced-shulker-boxes-2.4.1+1.20
  [✔] replantingcrops-1.20.1-5.1
  [✔] resourcefulconfig-fabric-1.20-2.0.0
  [✔] resourcefullib-fabric-1.20.1-2.1.7
  [✔] Resourcify (1.20.x-fabric)-1.1.0
  [✔] rocks-1.7.1
  [✔] scaffoldingdropsnearby-1.20.1-3.0
  [✔] scalable-cats-force-fabric-2.1.0
  [✔] segmented-0.3.0-1.20.1
  [✔] server-hats-0.16
  [✔] serversleep-datapack
  [✔] sfcr-1.7.6-mc1.20
  [✔] Sheep-Squeak-fabric-1.20.1-1.2.0
  [✔] shetiphiancore-fabric-1.20.1-1.0
  [✔] simple-armor-hud-1.20.1-1.3.1
  [✔] SimpleCopperPipes-1.13.3
  [✘] simple-hud-enhanced+1.20-1.20.1-v3.1.0.jar (disabled)
  [✔] simpleshulkerpreview-2.4.0
  [✔] SimpleVeinminer-1.4.2
  [✔] simplyswords-fabric-1.50.0-1.20.1
  [✔] skeletalremains-1.4.1
  [✔] skiptransitions-1.3.3+mc1.20
  [✔] SlotCycler-v8.0.1-1.20.1-Fabric
  [✔] SmartBrainLib-fabric-1.20.1-1.11.1
  [✔] snuffles-1.0.0+1.20
  [✔] sodium-extra-0.4.23+mc1.20.1-build.106
  [✔] sodium-fabric-mc1.20-0.4.10+build.27
  [✔] soundphysics-fabric-1.20.1-1.1.1
  [✔] SpikySpikes-v8.0.0-1.20.1-Fabric
  [✔] spoornpacks-5.0-1.20.1
  [✔] starlight-1.1.2+fabric.dbc156f
  [✔] Statement-4.2.6+1.14.4-1.20.1
  [✔] stendhal-1.3.9-1.20
  [✔] Stoneworks-v8.0.0-1.20.1-Fabric
  [✔] super_apple-3.0.0-1.20.1
  [✔] supermartijn642configlib-1.1.7-fabric-mc1.20
  [✔] supermartijn642corelib-1.1.12b-fabric-mc1.20
  [✔] supplementaries-1.20-2.5.21-fabric
  [✔] Terralith_1.20.1_v2.4.3
  [✔] theprinter-1.4.2+1.20
  [✔] toms_storage_fabric-1.20-1.6.4
  [✔] tooltipfix-1.1.1-1.20
  [✔] trade-cycling-fabric-1.20.1-1.0.5
  [✔] trailblazer-0.5.0+1.20.1
  [✔] trashcans-1.0.18-fabric-mc1.20
  [✔] trashslot-fabric-1.20-15.0.0
  [✔] travelers-backpack-1.20.1-9.1.2
  [✔] treeharvester-1.20.1-8.2
  [✔] ukulib-0.7.0+1.20
  [✔] UniversalBoneMeal-v8.0.0-1.20.1-Fabric
  [✔] UsefulSlime-fabric-1.20-1.6.0
  [✔] villagerdeathmessages-1.20.1-3.1
  [✔] villager-hats-1.6.1+1.20
  [✔] villagernames-1.20.1-5.2
  [✔] visuality-0.7.0+1.20
  [✔] visualoverhaul-fabric-5.0.1
  [✔] voicechat-fabric-1.20.1-2.4.16
  [✔] waystones-fabric-1.20-14.0.1
  [✔] woof-4.0.2+1.20.1
  [✔] World Host-0.4.3+1.20.1-fabric
  [✔] wunderreich-6.0.4
  [✔] yet-another-config-lib-fabric-3.1.0+1.20
  [✔] Zoomify-2.11.0

### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Version

other (please list)

**Comment by mysticdrew** [comment]
It is likely due to another mod causing issues. I can fix it if you can figure out which mod it is. Likely a mod that interacts with the hud.

**Comment by WimpieRatte** [comment]
Ok - I'll disable and enable mods until I find the culprit and will give feedback.
Insanely fast reply, wow! :D

**Comment by WimpieRatte** [comment]
FINALLY found the mod that caused it.
It was a Language Splitter mod. I removed the mod. Since all other mods didn't cause this, I cannot expect you guys to try compensate for their bug. Closing :)

**Comment by mysticdrew** [comment]
> FINALLY found the mod that caused it.
It was a Language Splitter mod. I removed the mod. Since all other mods didn't cause this, I cannot expect you guys to try compensate for their bug. Closing :)

Thanks for the update
