### ISSUE TITLE
[Bug]: Depending on where I look, coordinate text and waypoint text is turning black

### ISSUE THREAD

**Issue by Erilsio** [TeamJM/journeymap#629]
### What happened?

Depending on where I look, coordinate text and waypoint text is turning black. Is there a way to fix that?
![2023-08-04_13 12 49](https://github.com/TeamJM/journeymap/assets/103942082/c3956be4-2351-41c7-b255-b4214854bdaa)
![2023-08-04_13 13 01](https://github.com/TeamJM/journeymap/assets/103942082/1b1f2ffb-6455-4365-ba7e-8806efb1c5ef)

### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Version

journeymap-1.20.1-5.9.12-fabric

### Relevant log output

[journeymap.log](https://github.com/TeamJM/journeymap/files/12260165/journeymap.log)
[latest.log](https://github.com/TeamJM/journeymap/files/12260167/latest.log)

**Comment by mysticdrew** [comment]
It is likely a mod conflict. 
Please edit the version in your issue, you do not have 6.0.0. 

I would suggest creating a new singleplayer world. Remove all mods other than journeymap and fabric api. (Including resource packs and shaders)
See if it is still an issue. 
If so, we know it is a journeymap issue and then we can do more investigation on it. 
If not, it is a mod interaction. You'll then need to start adding mods back in until you find the one that is causing the issue. Then I can see if I can fix it or let the other dev know.

**Comment by Erilsio** [comment]
> It is likely a mod conflict. Please edit the version in your issue, you do not have 6.0.0.
> 
> I would suggest creating a new singleplayer world. Remove all mods other than journeymap and fabric api. (Including resource packs and shaders) See if it is still an issue. If so, we know it is a journeymap issue and then we can do more investigation on it. If not, it is a mod interaction. You'll then need to start adding mods back in until you find the one that is causing the issue. Then I can see if I can fix it or let the other dev know.





Sorry. I put the wrong version in it. Yes, I was using the latest available version for me (5.9.12-fabric) 
Thank you for the reply. This case can be closed because I found out that the culprit are the settings of the Feather launcher itself. Maybe I should just stick to Modrinth or Curseforge ^^

**Comment by mysticdrew** [comment]
Yea, feather launcher has been known to cause many issues with mods
