### ISSUE TITLE
Journeymap errors server side and cannot send config file

### ISSUE THREAD

**Issue by EnvyingGolem47** [TeamJM/journeymap#63]
#### JourneyMap Version: 1.12.2-5.5.2 & 1.12.2-5.5.1
(The same error occurs on both versions)

#### Describe the problem in repeatable steps:

1. I change the journey map config to disable player radar
2. Start up server
3. Join and get an error from journey map when sending config

**Comment by mysticdrew** [comment]
duplicate.
