### ISSUE TITLE
[Bug/Suggestion]: Tamed horses are not highlighted on minimap/fullscreen map

### ISSUE THREAD

**Issue by Xandar-YT** [TeamJM/journeymap#630]
### What happened?

Tamed horses appear as normal mobs on both mini and fullscreen maps. There is a "show pets" option, but it doesn't work with horses, only with cats and dogs (and other types of pets (unrideable)).

This is a tie between a bug and a suggestion, but I put the bug label. Sorry if it's incorrect.

I would suggest to not make horses blue like other pets currently, but to make them yellow and add a separate setting for them.

Thanks.

### Mod Loader

Forge

### Minecraft Version

1.20.1

### Version

6.0.0

**Comment by Xandar-YT** [comment]
Bump

**Comment by Xandar-YT** [comment]
Bump

**Comment by mysticdrew** [comment]
This is fixed for horses not showing up as pets in the next bugfix release. 
Please create a new suggestion issue if you want to change horse icon color. 

I will close this issue when 5.9.13 is released.
