### ISSUE TITLE
[Bug]: Cannot disable mob radar on browser map

### ISSUE THREAD

**Issue by SigmaFlame** [TeamJM/journeymap#631]
### What happened?

Hello,

In the server admin panel, I disabled radar for both ops and players.
But mobs are still shown on the browser map at port 8080.
There is a manual way to disable them inside the web page, but players still can view them.
I tested this behavior in singleplayer, but modpack makers should be able to disable radar as well.

Thank you in advance.

### Mod Loader

Forge

### Minecraft Version

1.19.2

### Version

5.9.7 (Latest version for mc 1.19.2)

### Relevant log output

There is no log since there is no crash.

**Comment by mysticdrew** [comment]
Closing as stale, no response from reporter.
