### ISSUE TITLE
No cave mode when there is a single layer in a house

### ISSUE THREAD

**Issue by Joker112112** [TeamJM/journeymap#632]
---
  
#### JourneyMap Version:

`1.19.2-5.9.7

#### Forge Version:

`1.19.2-43.2.21`

#### Describe the problem in repeatable steps:

1. Enable Always cave mode
2. Go inside a house or man made structure
3. Look at the minimap
#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
No errors

**Comment by mysticdrew** [comment]
More Details: 
When there is only one layer of blocks it does not switch. 
With two layers of blocks it will switch. 
I will add a slider to select how many layers of blocks before switching, default: 1

**Comment by mysticdrew** [comment]
This is added already for  v6 release, I thought it sounded familiar. 
![image](https://github.com/TeamJM/journeymap/assets/5459941/92167f18-8b76-4685-a7db-001d2d9fcc3c)
Keep an eye on this issue, I will close it when v6 is released to the public

**Comment by mysticdrew** [comment]
Cleaning up the issue tracker
Closing as this is completed for JourneyMap v6 when it is released.
