### ISSUE TITLE
[Feature Request]: Color Presets

### ISSUE THREAD

**Issue by EnderGirl1500** [TeamJM/journeymap#635]
### Describe the new feature.

I like to sort all my waypoints by color, so I'd be great if we had a "Save Color" and a "Color Presets" button to save colors and give them names.

For example, I like to use the same color for all the villages I find. Instead of memorizing the color by number, I'd like to be able to save that color as "Village".

**Comment by mysticdrew** [comment]
This is what was added
![image](https://github.com/TeamJM/journeymap/assets/5459941/d07a93cd-8b8c-4a01-b563-f7335cdc675b)
On the left hand side is color history. 
The updated waypoint manager will allow setting default colors for groups, so create a waypoint any color, move it to a group and it will use the default color of that group.
