### ISSUE TITLE
[Feature Request]: compatibility with waystones

### ISSUE THREAD

**Issue by DarkNasuada** [TeamJM/journeymap#637]
### Describe the new feature.

When teleporting towards a waypoint that's generated by the waystones mod you end up inside the waystone. It would be nice if you would end up next to the waystone instead.

**Comment by mysticdrew** [comment]
This is an issue you need to discuss with the waystones developer.

**Comment by EnderGirl1500** [comment]
I don't really understand your comment (my English level isn't really high) but in case this helps, theres a JourneyMap add-on for the waystones mod + some others, maybe that could fix jur issue?

**Comment by mysticdrew** [comment]
Waystones and the addon use the journeymap api to add waypoints. I do not interact with those mods at all, they do the interaction with journeymap. 
Any features you want in waystones, you'll need to talk to developer of that mod. There is nothing I can do.

**Comment by EnderGirl1500** [comment]
I know I know, I was just telling the OP about the add-on just in case it helps with their issue, but if not ofc they'd have to contact the other mods' devs
