### ISSUE TITLE
[Bug]: {JourneyMap Incompatible with Core Shaders}

### ISSUE THREAD

**Issue by SimonMage** [TeamJM/journeymap#639]
### What happened?

Minecraft Version 1.20.1
Forge Version 44.1.47

The mod is incompatible with Core Shaders used for removing name boxes of holograms, name tags, player tags... etc... I attached the file used in resource pack for removing them. Also I attached a resource pack example made by with this bug. But when I use it, I noticed that all buttons of JourneyMap remove all text inside (attached screen)
![Screenshot_5](https://github.com/TeamJM/journeymap/assets/75200996/0bd2074f-d4c6-44ad-bb77-ba7408a0fe4b)
![Screenshot_2](https://github.com/TeamJM/journeymap/assets/75200996/79e63914-2836-412a-aada-6953cccb2f23)
![Screenshot_3](https://github.com/TeamJM/journeymap/assets/75200996/b131d02f-e983-4674-9f51-c62ec690224c)
![Screenshot_4](https://github.com/TeamJM/journeymap/assets/75200996/87022663-de37-416f-a575-a35fdc88a7ad)
[JourneyMapBugged.zip](https://github.com/TeamJM/journeymap/files/12486760/JourneyMapBugged.zip)
![Screenshot_1](https://github.com/TeamJM/journeymap/assets/75200996/17cd9aea-7934-45d1-9836-eed3e79ef03b)

### Mod Loader

Forge

### Minecraft Version

1.20.1

### Version

5.9.12

**Comment by mysticdrew** [comment]
This is fixed for JourneyMap 6.0.0 when it gets released. 
This fix is too extensive to make into 5.9.x

**Comment by mysticdrew** [comment]
Cleaning up the issue tracker
Closing as this is completed for JourneyMap v6 when it is released.
