### ISSUE TITLE
[1.7.10] Player wont shown anymore on unlimited, but worked before

### ISSUE THREAD

**Issue by Caeas** [TeamJM/journeymap#64]
#### Instructions for Submitting an Issue
1. Ask for help on Discord (https://discord.gg/eP8gE69) #support if you're unsure this is a new issue.
2. Please search for existing issues before submitting a new one.
3. Please add the correct MC<version> label to your issue. Example: "[1.12.2] Waypoints are upside down"
4. Completely fill out the template below. Failure to do so is likely to get the issue closed immediately.
5. Prove you read these instructions by deleting this section before submitting. ;)
---
  
#### Forge Version:

[Jenkins] 1.7.10-1.4.6.1355

#### Describe the problem in repeatable steps:

1. normaly after Login on our Server (its my one) we can see each other on the minimap
2. all player specific options for any journeymap type are enabled
3. no configs of journeymap have been changed but today other players and the own player wont show up on map anymore
4. We updated Galaxy Space and Galacticraft to latest for 1.7.10 today (that info might help?)
5. until today everything worked, but since today it wont.
6. we dont use a server side journeymap mod
7. I hope someone can help me to fix this issue thanks much

**Comment by mysticdrew** [comment]
JourneyMap for Minecraft 1.7.10 is no longer supported. Sorry!
