### ISSUE TITLE
[Feature Request]: Route plotting and route following between waypoints

### ISSUE THREAD

**Issue by nickstuaw** [TeamJM/journeymap#641]
### Describe the new feature.

Routing (or navigation like a car sat-nav between waypoints)

Hi, just wondering whether route plotting and following could be added to JourneyMap.
I imagine it might be implemented by
* creating routes where each route has:
  * its own sequence of waypoints
    * which are linked up on the map in the order of the sequence
      * hence showing lines between waypoints
        * which would be the quickest method of travel without obstacles
* for in-game waypoint markers: the player would select a route (acting like a search filter) and, with a setting enabled, would only be shown the next waypoint they are expected to reach along the selected route based on their progress.

**Comment by mysticdrew** [comment]
While it sounds cool, it's not really possible. 
What is an obstacle? How is it defined?
We would have to store a lot of extra data to even calculate this, which I'd rather not do. 
On a server, only what is in render range is available to the client. With JourneyMap primarily being a client mod, this would not work well. 

This is probably something that could be done with an addon and a server component for an addon if someone wanted to make it. Our API has all the tools to add waypoints and such to JourneyMap to do this. The addon would need to do the calculations.
