### ISSUE TITLE
[Bug]: Crash when quit game

### ISSUE THREAD

**Issue by 12345-mcpython** [TeamJM/journeymap#642]
### What happened?

Minecraft crash when quit game

### Mod Loader

Forge

### Minecraft Version

1.18.2

### Version

5.9.7

### Relevant log output

[crash-2023-09-10_14.01.15-server.txt](https://github.com/TeamJM/journeymap/files/12567614/crash-2023-09-10_14.01.15-server.txt)

[journeymap.log](https://github.com/TeamJM/journeymap/files/12567615/journeymap.log)

**Comment by 12345-mcpython** [comment]
it seems to hard to replicate it.

**Comment by mysticdrew** [comment]
Interesting, is that crash on the client when you're connect to a server. Or in singleplayer?

**Comment by 12345-mcpython** [comment]
> Interesting, is that crash on the client when you're connect to a server. Or in singleplayer?

singleplayer

**Comment by mysticdrew** [comment]
This won't get fixed for 1.18.2, but it is fixed for 1.20.1+
