### ISSUE TITLE
[Feature Request]: Store waypoints in the world instead of config

### ISSUE THREAD

**Issue by EntityinArray** [TeamJM/journeymap#643]
### Describe the new feature.

I reinstalled a modpack and joined a world I was playing on to see all my waypoints gone.
I then learned that JM is storing waypoints in the config.
Waypoints should be stored in the world data (`saves/world_name/journeymap/player_UUID/waypoints.json` for example), there is no need for them to exist in config.

Because JM waypoints are not stored in the world, updating or reinstalling your modpack introduces a risk where user unknowingly deletes their waypoints.

**Comment by mysticdrew** [comment]
This is unlikely to change for client waypoints.
They are not in config. 
They are in `./minecraft/journeymap/data/sp|mp/worldname/waypoints`. No launchers delete that directory.
