### ISSUE TITLE
[Bug]: FOV impact the readability of waypoints

### ISSUE THREAD

**Issue by TomBPro** [TeamJM/journeymap#644]
### What happened?

The readability of Waypoints is quite hard while looking around in Minecraft. It is dependant on the FOV settings you set.
No settings was found to resolve this problem while FOV is different than normal.

At FOV 80:
![2023-09-18_16 09 22](https://github.com/TeamJM/journeymap/assets/59920643/e3436991-af9e-4f6c-a279-4504f611979a)

At FOV 60:
![2023-09-18_16 09 29](https://github.com/TeamJM/journeymap/assets/59920643/5f6f80d2-3099-40f5-91c1-18e16ae3f449)

### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Version

5.9.12

### Relevant log output

[journeymap.log](https://github.com/TeamJM/journeymap/files/12648741/journeymap.log)
[latest.log](https://github.com/TeamJM/journeymap/files/12648756/latest.log)

**Comment by mysticdrew** [comment]
There is nothing I can do to fix this, as this is a minecraft font renderer bug/issue. 
My guess is you can workround it by disabling Unicode Font in the language settings. 
![image](https://github.com/TeamJM/journeymap/assets/5459941/fe8bc03f-153e-4315-8862-9e1e993de7df)


Here are the mojang bugs regarding fonts. 
https://bugs.mojang.com/browse/MC-263614
https://bugs.mojang.com/browse/MC-2488
