### ISSUE TITLE
[Feature Request]: Port to 1.17.1?

### ISSUE THREAD

**Issue by TheD0ct0r101** [TeamJM/journeymap#647]
### Describe the new feature.

I know this is probably asking a lot but me and a small community of people have put together a modpack for an open world map that specifically requires 1.17.1 due to it's datapack's nature. We would love to make use of journeymap as Xaeros is giving us problems at the moment. We also thoroughly enjoy the topography-view feature journeymap offers, which Xaeros does not.

**Comment by mysticdrew** [comment]
What? It exists already.

**Comment by TheD0ct0r101** [comment]
> What? It exists already. It's on curseforge

Sorry, I should have clarified. We're using fabric. 1.17.1 Journeymap does not exist for fabric.

**Comment by mysticdrew** [comment]
Sorry, no it cannot be ported.

**Comment by TheD0ct0r101** [comment]
no specific reason?

**Comment by mysticdrew** [comment]
Because it is a major overhaul of the codebase and I don't have time, especially for a version that is not really used. 
Update to 1.18 or higher to use JourneyMap with fabric.

**Comment by TheD0ct0r101** [comment]
Wish we could
