### ISSUE TITLE
24h time is inverted

### ISSUE THREAD

**Issue by nbros** [TeamJM/journeymap#648]
### What happened?

Currently as displayed on the minimap 13:00 is night and 23:00 is day.
I think the time should be shifted by 12 hours to match the day and night cycles.

### Mod Loader

Forge

### Minecraft Version

1.20.2

### Version

5.9.14

**Comment by mysticdrew** [comment]
No logs, no details, not even a screenshot? 
Help me out a bit more.

**Comment by mysticdrew** [comment]
https://teamjm.github.io/journeymap-docs/5.8.5/Client%20Docs/settings/minimap/#info-slots

**Game Time:** The current ingame time, as represented by Minecraft's daylight cycle
**Game Time Real:** The current ingame time, shifted to match a real clock

https://minecraft.fandom.com/wiki/Daylight_cycle

Minecraft day starts at sunrise 6am. Which displays at 00:00:01

**Game Time Real** infoslot adjusts this so midnight is a new day like real world time. 
**Game Time** new day starts at 6am when the sun rises.

**Comment by nbros** [comment]
For me, Game Time sunrise starts at 6PM (displayed as 18:00 maybe because of my Mac settings) instead of 6AM (06:00).
See the time on the minimap:
![image](https://github.com/TeamJM/journeymap/assets/141089/ce7a1372-6b10-47b7-81d8-44e9853da226)

**Comment by mysticdrew** [comment]
Multiplayer or singleplayer?

**Comment by mysticdrew** [comment]
Set your infoslot to GameTime Real
![image](https://github.com/TeamJM/journeymap/assets/5459941/78d17c86-be34-4867-845e-3832daeb53ec)

**Comment by nbros** [comment]
ok that was my misunderstanding, thank you for the explanation!

**Comment by mysticdrew** [comment]
Minecraft time being shifted by 6 hours confuses a lot of people. I have no idea why they did it that way.
