### ISSUE TITLE
[Bug] \ shortcut doesn't work on an AZERTY keyboard

### ISSUE THREAD

**Issue by nbros** [TeamJM/journeymap#649]
### What happened?

I'm on a Mac with a French AZERTY keyboard, and I can't use some shortcuts that don't have a direct corresponding key on my keyboard. For example, I can't switch between the two minimaps with "\\" because I have no "\\" key on my keyboard.
![image](https://github.com/TeamJM/journeymap/assets/141089/a4339a9b-2442-471e-93c2-c84561ba048a)

In order to enter a "\\", I usually need to hit Shift+Option+/ but this doesn't switch the minimap with journeymap.

(p.s. if you need logs, I don't have a .minecraft so please tell me where I can find them)

### Mod Loader

Forge

### Minecraft Version

1.20.2

### Version

5.9.14

**Comment by mysticdrew** [comment]
have you considered changing the keybind?

**Comment by mysticdrew** [comment]
![idea64_yGiwNt6Uiz](https://github.com/TeamJM/journeymap/assets/5459941/fe963b65-c827-4235-bb1b-e5b510ad091f)
