### ISSUE TITLE
Streams Compatibility

### ISSUE THREAD

**Issue by Gazzzaa** [TeamJM/journeymap#65]
This may have been suggested but I could not find any posts on it. When playing with the mod streams with journeymap, streams appear as if there was no water: you can only see the ground. It looks like journeymap is not detecting them.

**Comment by BrainStone** [comment]
Would you mind to provide what MC version you are referring to?

**Comment by gconlon2002** [comment]
1.12.2

**Comment by mysticdrew** [comment]
Better yet, tell that mod author to use vanilla water so journeymap knows what it is.

**Comment by gconlon2002** [comment]
This has been reported on streams also.  https://github.com/delvr/Streams/issues/57

**Comment by mysticdrew** [comment]
Fixed in 5.5.4b5
