### ISSUE TITLE
[Bug]: [1.20.1] Mouse cursor appearing on startup of the world, can't take control

### ISSUE THREAD

**Issue by Jaxel13** [TeamJM/journeymap#651]
### What happened?

Hello.
Every time I open a world, there is a buffer time before I can actually control the Minecraft window: the mouse cursor appear, I can't look around and ESC and other keys do not do anything.
After several seconds, the minimap appear in the corner and the JourneyMap message appears in chat, and I regain control of the window, so I'm assuming it must me something related to JourneyMap.
I also tried older versions, but the bug stays.

### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Version

5.9.14

### Relevant log output

[latest.log](https://github.com/TeamJM/journeymap/files/12841249/latest.log)
[journeymap.log](https://github.com/TeamJM/journeymap/files/12841250/journeymap.log)

**Comment by Jaxel13** [comment]
https://github.com/TeamJM/journeymap/assets/147336559/e166ab93-5ea4-449a-9203-1a388a2af0b0

Here's a recording of the video.
Also, toggling fullscreen/windowed mode doesn't change anything

**Comment by mysticdrew** [comment]
This is highly unlikely related to journeymap. You likely have another mod messing with the mouse, we do not do anything with the mouse. Looks like another mod has an invisible screen at start up while things are loading.

**Comment by mysticdrew** [comment]
disable journeymap and see if the issue persists.
