### ISSUE TITLE
[Feature Request]: Waypoint groupfolder 

### ISSUE THREAD

**Issue by DaBrainZ** [TeamJM/journeymap#652]
### Describe the new feature.

Hello,

with me playing more with GregTech and Elementalcraft i notice that i have hundreds of waypoints for Orechunks or auranotes and i came to think it would be really helpfull to have folders where you can toggle the visibility of all contained Waypoints or just group some together.

**Comment by mysticdrew** [comment]
duplicate #448 

development is already in progress
