### ISSUE TITLE
[Feature Request]: {FTB Teams integration}

### ISSUE THREAD

**Issue by BaptisteII** [TeamJM/journeymap#653]
### Describe the new feature.

This feature would be used to integrate ftb teams into the mod. In the admin options we could authorize a team "A" to see its members on the radar but not authorize another team "B" to see team "A". Only allied players will be able to see each other.

**Comment by mysticdrew** [comment]
Closing as complete via this mod
https://github.com/mysticdrew/journeymap-teams
