### ISSUE TITLE
[Feature Request]: Move status effects to the right to not overlap the minimap

### ISSUE THREAD

**Issue by WildFyr16** [TeamJM/journeymap#654]
### Describe the new feature.

The ability to have the status effects not overlap the minimap, maybe a setting to have them either display to the right or horizontal under the map. That way players can still see the map, and all status effects.

### Images

![image](https://github.com/TeamJM/journeymap/assets/61173497/d52681ea-b49f-4f2f-b840-9da70e1c7058)

**Comment by mysticdrew** [comment]
In the Minimap Options, there is a Position Button. Click that and move the effects how you want.

**Comment by mysticdrew** [comment]
https://teamjm.github.io/journeymap-docs/5.8.5/Client%20Docs/settings/minimap/

**Comment by mysticdrew** [comment]
![image](https://github.com/TeamJM/journeymap/assets/5459941/d44d339c-51a3-4d23-ae39-50dd313368c5)

**Comment by mysticdrew** [comment]
![java_FI8nGIaWv1](https://github.com/TeamJM/journeymap/assets/5459941/12d69bd7-8d63-4915-b1aa-b8a34fe9e8c0)
