### ISSUE TITLE
[Feature Request]: Keep waypoint icons always visible

### ISSUE THREAD

**Issue by Imzxhir** [TeamJM/journeymap#655]
### Describe the new feature.

Basically the title. I want a feature where the waypoint icon is always visible no matter if you are hovering over the waypoint or not. I know there is an existing feature where you can keep the waypoint label always visible, but maybe there could be a toggle to keep the waypoint icon always visible rather than the label.

**Comment by camilochzzb** [comment]
PLEASE, I need this, thanks. I have no idea why waypoint are always hidden and I don't know where I am going... It's so weird and I get angry, I have to open the world map and I don't want that.

**Comment by mysticdrew** [comment]
This is already how it works. Though I do plan to separate options. 
https://github.com/TeamJM/journeymap/issues/762
will be keybind and option
