### ISSUE TITLE
[Bug]: Mouse Location not displaying on fullscreen map on laptop screen

### ISSUE THREAD

**Issue by nbros** [TeamJM/journeymap#656]
### What happened?

When using my MacBook Pro's laptop screen, the fullscreen map doesn't display the Mouse Location. It only displays the Player Location. The Mouse Location only shows up on the fullscreen map when I plug in my laptop to my external monitor.

![image](https://github.com/TeamJM/journeymap/assets/141089/95fdea9f-62dd-4396-86f1-a7b420d128af)

![image](https://github.com/TeamJM/journeymap/assets/141089/1c7d1a18-9f87-4d6d-b22f-5c5207c08089)

### Mod Loader

Fabric

### Minecraft Version

1.20.2

### Version

5.9.14

**Comment by mysticdrew** [comment]
The fix is in 5.9.16, should be on CF/MR shortly
