### ISSUE TITLE
[1.20.2]: {The time above the map does not match the time on the server}

### ISSUE THREAD

**Issue by Kvakochka** [TeamJM/journeymap#658]
### What happened?

https://youtu.be/IRQlsKSTnoY
The time above the map does not match the time on the server

### Mod Loader

Forge

### Minecraft Version

1.20.2

### Version

5.9.12

**Comment by mysticdrew** [comment]
Read the "Info Slots" 
https://teamjm.github.io/journeymap-docs/5.8.5/Client%20Docs/settings/minimap/#info-slots
