### ISSUE TITLE
[Feature Request]: Vanilla Map Requirement

### ISSUE THREAD

**Issue by Sweek9** [TeamJM/journeymap#659]
### Describe the new feature.

The idea is that (when toggled on in settings) mapping is locked, and regions (seen as black squares with a lock icon on them) unlock (lock disappears) by consuming vanilla maps. Unlocking for access to JourneyMaps mapping agent the 8x8 blacked chunks of the Journey Map currently in when consuming an Empty Map, or all the chunks currently coverable by a used map when it's consumed. Potentially with the ability to also remove the vanilla map from the journey map to expand it with paper later, if that's a realistic possibility. Alternatively it could just consume empty maps automatically for unlocking each 8x8 chunk region, or an empty map + 4 paper to unlock each 128x128 chunk region, either way not worrying about consuming used maps or expanding maps later.

The main reason is that while I love this mod it feels a bit like cheating (which breaks immersion) since it's automatic and doesn't have a cost in the game, and it eliminates the utility of the vanilla mapping system. This feature would alleviate both of those apprehensions. Although I'd be okay with it if they were, things like coordinates, player and mob icons, and waypoints don't need to also be locked by this feature (mainly just the visible map part), because a character would remember waypoints in relative coordinates from one another just as we remember how to get around where we live irl, and they could see, hear, and smell where the mobs and players around them are; and the player could open the debug menu and write down the coordinates to simulate that anyway.

**Comment by mysticdrew** [comment]
This is unlikely to make it into JourneyMap. It could possibly be an addon if someone wanted to create such a thing. 
Sounds cool, but there are a lot of technical problems with implementing this. 

Might be something to look into again if we ever get server sided mapping.
