### ISSUE TITLE
[1.12.2-Modpack] When opening Journey map ingame, i do only see a blue screen

### ISSUE THREAD

**Issue by Mogesla** [TeamJM/journeymap#66]
#### JourneyMap Version: 1.12.2-5.5.2

#### Describe the problem in repeatable steps:
1. press J ingame

Edit1: It seems like it only occurs when changing video settings, i do try to find out wich option is guilty.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

[journeymap.log](https://github.com/TeamJM/journeymap/files/2300221/journeymap.log)

[modlist.zip](https://github.com/TeamJM/journeymap/files/2300225/modlist.zip)

**Comment by battlekruiser** [comment]
JourneyMap Version: 1.12.2-5.5.2
Forge Mod Loader version 14.23.5.2768
Buildcraft 7.99.18
I have encountered a similar problem, and narrowed it down to Buildcraft machines (tested with quarry and stirling engine) being in player's field of view. Removing blocks from the world (with engine it's enough to just look away) fixes the problem. 
However, I also experience glitches in render of items in hotbar and in hand: hand can be obscured by blocks in world and hotbar items are visible through other GUIs. 
[modlist.txt](https://github.com/TeamJM/journeymap/files/2523017/modlist.txt)

**Comment by mysticdrew** [comment]
There is another mod messing with the rendering. 
You will need to do trial an error to figure it out. This is not a journeymap issue from what I gather, the errors in the log you posted have nothing to do with your issue.

**Comment by vpArth** [comment]
Same issue. Map becomes working, when I disable OptiFine.

**Comment by mysticdrew** [comment]
disable fast render

**Comment by datek11** [comment]
it's buildcraft, 100%.
have the same exact issue, bluescreen only appears when my buildcraft eyesore of a distillery is rendered
