### ISSUE TITLE
[Bug]: Auto-Remove Death Waypoints under Waypoint Beacons in options menu

### ISSUE THREAD

**Issue by a-a-GiTHuB-a-a** [TeamJM/journeymap#662]
### What happened?

While configuring the mod to auto-remove death waypoints (as one does), I noticed the setting is filed under Waypoint _Beacons_ rather than Waypoints. This doesn't really make sense, since the setting does not specifically regard beacons but rather waypoints themselves.

### Mod Loader

Forge

### Minecraft Version

1.19.2

### Version

5.9.7

### Relevant log output

N/A

**Comment by mysticdrew** [comment]
This has been moved already in future versions.
