### ISSUE TITLE
[Feature Request]: Setting to move the X,Y location of the circle HUD

### ISSUE THREAD

**Issue by Draxxar67** [TeamJM/journeymap#663]
### Describe the new feature.

Please add a settings feature to move the screen X,Y location of the circle map HUD that's in the top right corner.
Reason this would be very useful is I play on a server (performium.net) that has an information display rectangle that is overwriting the journeymap circle HUD graphics and if I could edit settings to move that, say even to top middle, it would be very useful.

### Images

![image](https://github.com/TeamJM/journeymap/assets/144786866/e242c798-aa5f-4c6f-87e7-fd08a76cb17b)

**Comment by mysticdrew** [comment]
https://teamjm.github.io/journeymap-docs/latest/Client%20Docs/settings/minimap/

Click the position button
