### ISSUE TITLE
[Feature Request]: Customizable minimap zoom

### ISSUE THREAD

**Issue by seqre** [TeamJM/journeymap#664]
### Describe the new feature.

The minimap should have configurable zoom in the minimap. Currently, the minimap is so zoomed out it's so hard to use, especially underground. Xaero's Minimap has this option, which looks much better (see screenshots). I prefer JourneyMap as a minimap mop, but the lack of zoom makes it hard to use.

#### JourneyMap:
![JourneyMap](https://github.com/TeamJM/journeymap/assets/44679055/366bd1e3-9bb0-4039-8ccf-8af7c0647b84)

#### Xaero's Minimap with changed zoom level (much more legible):
![[Xaero's Minimap](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap)](https://github.com/TeamJM/journeymap/assets/44679055/aaab9d62-ef76-412b-9309-4ccfbe26efd8)

**Comment by mysticdrew** [comment]
use the + and - keys
