### ISSUE TITLE
Journey map waypoints bug

### ISSUE THREAD

**Issue by Typhewn** [TeamJM/journeymap#665]
### What happened?

Hey fam, i keep deleting waypoints and every time i leave and join back in my server they re-appear any solution to this? i've tried deleting the waypoints directly from the data on my server and locally and they still come back...

### Mod Loader

Forge

### Minecraft Version

1.20.2

### Version

5.9.18

**Comment by mysticdrew** [comment]
First, there is no waypoint data on the server. 
Secondly, if you deleted the waypoints, they are gone. They do not magically reappear. 
The likely case is that you have an addon that is creating waypoints. 

You have failed to upload any logs, so not much help can be provided without logs.

**Comment by Typhewn** [comment]
yea  it's this annoying waystones thanks fam
