### ISSUE TITLE
[Feature Request]: Add support/blacklist for Dark Mode Everywhere

### ISSUE THREAD

**Issue by Buuz135** [TeamJM/journeymap#666]
### Describe the new feature.

[Dark Mode Everywhere](https://www.curseforge.com/minecraft/mc-mods/dark-mode-everywhere) uses the minecraft shaders to make every gui dark mode but that can make stuff dark that it's not supposed to like the map.

As per the discord convo:

> hey mystic can you do a cool thing? can you black list journey map from dark mode everywhere its imc stuff
> https://github.com/mekanism/Mekanism/blob/1.20.x/src/main/java/mekanism/common/integration/MekanismHooks.java#L146C13-L146C13
> you can just send journeymap
> or whatever the package name is

**Comment by mysticdrew** [comment]
added in 5.10.0
