### ISSUE TITLE
[Bug]: Web map not working for other computers on the same network

### ISSUE THREAD

**Issue by SigmaFlame** [TeamJM/journeymap#668]
### What happened?

Hello,

I want to see the web map of my game from another computer on my local network, but the page does not load.
I know that there is no problem with the network, port sharing and so on, because I tested to run Wamp on the same port and it works.
But JourneyMap completely refuses to allow the other computer of my local network to see the map.

### Mod Loader

Forge

### Minecraft Version

1.20.1

### Version

5.9.18

### Relevant log output

No trace of any connection (same computer that does work or other computer that doesn't work) are found inside the logs.

**Comment by mysticdrew** [comment]
Maybe there is an issue with your host computer's firewall?

**Comment by SigmaFlame** [comment]
As I said : wamp works in the same port, so it is not a problem with my firewall. It is really journeymap that refuses to respond to the other computer.

**Comment by SigmaFlame** [comment]
It works now, I needed to restart my computer in order to make it working.

**Comment by mysticdrew** [comment]
great!
