### ISSUE TITLE
[Bug]: {[1.20.1] Checking the "Show Bathymetry" but does not render water.}

### ISSUE THREAD

**Issue by Sn0w0wl** [TeamJM/journeymap#669]
### What happened?

I checked the rendering option in water (Show Bathymetry),  but it still appears black as if it's filled with solid blocks.
(I've also adjusted the cave layers.)
![2024-01-19_23 37 50](https://github.com/TeamJM/journeymap/assets/57548015/59e390d0-679c-41ff-a602-5ef71e9b9e50)
![2024-01-19_23 38 51](https://github.com/TeamJM/journeymap/assets/57548015/4df857db-d6c2-42cd-8f65-aacb660e81ba)

but If the top is open, the rendering is good.
(water rendering I wanted (expected))
![2024-01-19_23 58 08](https://github.com/TeamJM/journeymap/assets/57548015/5056e4f8-f6f6-4fb3-9510-b6521c9ef240)

### Mod Loader

Forge

### Minecraft Version

1.20.1

### Version

5.9.18

**Comment by mysticdrew** [comment]
That feature only works with the surface renderer, aka Day/Night it does not work with caves. 
This is not a bug.

**Comment by mysticdrew** [comment]
I can possibly add it to the list of features to add.
