### ISSUE TITLE
[Bug]: [1.20.1] Not rendering top layer of world after changing world generation

### ISSUE THREAD

**Issue by Emedo80** [TeamJM/journeymap#670]
### What happened?

Hello,

I'm creating a modpack for me and my friends and in the last changes I made I added mods that change the world generation.
Doing so, Journey map is not rendering the top layer of the world for chunks that were already generated.
I've already tried removing previously generated map.

I have tried xaero's mini map, and it is doing the same exact thing, but there is an option called "ignore server heightmap" that fixes this issue

Here are some screenshots:

With Journey :
![image](https://github.com/TeamJM/journeymap/assets/45518634/8cb0be97-fa9c-48bd-874b-07fc1da41bfc)
As you can see on the right, it is rendered properly for newly generated terrain.

With Xaero's :
Before "ignore server heightmap"
![image](https://github.com/TeamJM/journeymap/assets/45518634/6d864ced-806e-42c2-98a4-47617a978ee3)
And after "ignore server heightmap"
![image](https://github.com/TeamJM/journeymap/assets/45518634/d20900d0-acd3-4da8-a261-381c212c66e7)

Hope you can help me !

Best regards,
Emedo

### Mod Loader

Forge

### Minecraft Version

1.20.1

### Version

5.9.18

### Relevant log output

Here are the logs :

[latest.log](https://github.com/TeamJM/journeymap/files/14025118/latest.log)
[journeymap.log](https://github.com/TeamJM/journeymap/files/14025123/journeymap.log)

**Comment by mysticdrew** [comment]
If you are running a server, start the server once with this command
`java -jar server.jar --forceUpgrade --eraseCache`

If you are playing with the client, click edit world, 
![java_nbOe1VpxMC](https://github.com/TeamJM/journeymap/assets/5459941/c4f6c5b7-eb15-4785-80da-aae0c1da5375)

**Comment by Emedo80** [comment]
Hello,

It is the right fix !

Thank you

**Comment by BasquiatThe1** [comment]
I have the same issue, but in singleplayer. Optimizing the world and erasing cache data doesn't seem to work.

**Comment by mysticdrew** [comment]
> If you are running a server, start the server once with this command `java -jar server.jar --forceUpgrade --eraseCache`
> 
> If you are playing with the client, do this ![java_nbOe1VpxMC](https://private-user-images.githubusercontent.com/5459941/298969863-c4f6c5b7-eb15-4785-80da-aae0c1da5375.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNDI0OTQsIm5iZiI6MTcyNzE0MjE5NCwicGF0aCI6Ii81NDU5OTQxLzI5ODk2OTg2My1jNGY2YzViNy1lYjE1LTQ3ODUtODBkYS1hYWUwYzFkYTUzNzUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjRUMDE0MzE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTQxMWE0Y2IwMjVlMjcwYjA2YWZjZDBiYWVhOWEzOWUzMmQyYzUwZWQxMTI4MmQ2NGRkZDNhYzU0ZjRlOWZjMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.-P6Mzu3IuOY_Pq3dQa-xFtb1FByEdn_8r85l-ryuqI0) [ ![java_nbOe1VpxMC](https://private-user-images.githubusercontent.com/5459941/298969863-c4f6c5b7-eb15-4785-80da-aae0c1da5375.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNDI0OTQsIm5iZiI6MTcyNzE0MjE5NCwicGF0aCI6Ii81NDU5OTQxLzI5ODk2OTg2My1jNGY2YzViNy1lYjE1LTQ3ODUtODBkYS1hYWUwYzFkYTUzNzUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjRUMDE0MzE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTQxMWE0Y2IwMjVlMjcwYjA2YWZjZDBiYWVhOWEzOWUzMmQyYzUwZWQxMTI4MmQ2NGRkZDNhYzU0ZjRlOWZjMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.-P6Mzu3IuOY_Pq3dQa-xFtb1FByEdn_8r85l-ryuqI0) ]

this tells you exactly how to fix it

**Comment by mysticdrew** [comment]
I've now locked this post, as the solution is posted. Which is why it is pinned.
