### ISSUE TITLE
[Feature Request]: Add time format for Game Time

### ISSUE THREAD

**Issue by mysticdrew** [TeamJM/journeymap#671]
### Describe the new feature.

Game Time Real has a format option, but Game Time does not. Should simply use the current Game Time Real Format, but change the name to `Info Slot Time Format`

Game Time Real needs a new name as it is confusing.

**Comment by Noobishpro4** [comment]
[WaypointData.zip](https://github.com/user-attachments/files/16117638/WaypointData.zip)

WaypointData.dat file from Noobishpro on discord

**Comment by mysticdrew** [comment]
Updated the info slot, changed game time real to "Game Time with Offset"
