### ISSUE TITLE
[Feature Request]: Replace "Auto-Hide Labels" button w/ a Slider.

### ISSUE THREAD

**Issue by Sand-Mage** [TeamJM/journeymap#672]
### Describe the new feature.

Auto-Hide Lables button made into a slider so you can look further away from the waypoint while still avoiding most that would appear within your fov. For a physical example look at the picture: A slider to increase or decrease the range of "X" the waypoint will come into focus. I guess its like 20 degrees or something currently when button is selected and like 180 when its not selected.

### Images

![Screenshot 2024-03-07 040156](https://github.com/TeamJM/journeymap/assets/125189500/421d3d55-7ed3-4f6c-a86e-b64f74970a80)

**Comment by mysticdrew** [comment]
This has been added  for both icons and labels.
