### ISSUE TITLE
[Bug]: [1.20.1] Auto remove death waypoint trigger if player is moving whilst dying

### ISSUE THREAD

**Issue by LeoBeliik** [TeamJM/journeymap#673]
### What happened?

Dying by something that makes the player move after death (like dying in the middle of a fall or by a knockback arrow) will get the death waypoint immediately removed

This does not happen if the auto remove death waypoint option is disabled

### Mod Loader

NeoForge

### Minecraft Version

1.20.1

### Version

5.9.18

### Relevant log output

[journeymap.log](https://mclo.gs/6DI6GGV)
[latest.log](https://mclo.gs/QQKFqWR)

**Comment by mysticdrew** [comment]
This is fixed in 5.9.22, I added a 3s delay to deathpoint creation.
