### ISSUE TITLE
[Crash]: On full screen map

### ISSUE THREAD

**Issue by Tresillo2017** [TeamJM/journeymap#674]
### What happened?

Every time I open the full screen map it crashes.

Minecraft version: 1.20.4
JM Version: 5.9.21

### Mod Loader

Fabric

### Minecraft Version

other (please list)

### Version

other (please list)

### Relevant log output

[journeymap.log](https://github.com/TeamJM/journeymap/files/14548397/journeymap.log)
[latest.log](https://github.com/TeamJM/journeymap/files/14548398/latest.log)
[crash-2024-03-10_02.50.20-client.txt](https://github.com/TeamJM/journeymap/files/14548400/crash-2024-03-10_02.50.20-client.txt)

**Comment by mysticdrew** [comment]
if you disable `visualoverhaul 5.1.0` does it still crash?

**Comment by Tresillo2017** [comment]
The thing is that it wasn't giving me problems before. It was after updating mods

Tomas Palma - https://tomasps.tk

**Comment by Tresillo2017** [comment]
> if you disable `visualoverhaul 5.1.0` does it still crash?

Yes, disabling that mod works. Why was it?

**Comment by Tresillo2017** [comment]
> if you disable `visualoverhaul 5.1.0` does it still crash?

Yes, disabling that mod works. But why was that mod causing a crash?

**Comment by mysticdrew** [comment]
No idea, we will investigate

**Comment by mysticdrew** [comment]
you can try using an older version of visualoverhaul, or the current version and journeymap 5.9.20
See which combo breaks it. Though unlikely journeymap update caused anything, but you never know.

**Comment by Tresillo2017** [comment]
> you can try using an older version of visualoverhaul, or the current version and journeymap 5.9.20 See which combo breaks it, so I know more specifically what to fix or report to that mod dev. Though unlikely journeymap update caused anything, none of the changes were UI related, but you never know.

You can see the changes I made to the modpack the problem was caused on version 1.9 so probably it was an update
https://modrinth.com/modpack/spainrp

**Comment by mysticdrew** [comment]
Looks like 1.9.1 of the modpack fixes your bug

**Comment by Tresillo2017** [comment]
Yes, but that's because I deleted visualoverhaul mod as you suggested and the pushed the update

**Comment by mysticdrew** [comment]
Oh it's your pack. 
It'll be a few hours before i can look into it. Does journeymap crash when only journeymap, visualoverhaul, and fabricapi installed?

**Comment by Tresillo2017** [comment]
> Oh it's your pack. It'll be a few hours before i can look into it. Does journeymap crash when only journeymap, visualoverhaul, and fabricapi installed?

No, it works perfectly

**Comment by mysticdrew** [comment]
Odd. 
We need to reduce the modset as small as we can while still crashing. It may be a combination of mods. 
Might be a good idea to test the mods you updated in 1.9 version of your pack. One of those mod updates is interacting with visualoverhaul which is then effecting some buttons in the journeymap fullscreen map.
