### ISSUE TITLE
[Bug]: JM Display Errors 1.7

### ISSUE THREAD

**Issue by brandyyn** [TeamJM/journeymap#675]
### What happened?

most biomes o plenty tall grass shows up as grey on the minimap if show plants is enabled
![image](https://github.com/TeamJM/journeymap/assets/11356565/42f99f5e-dd23-4540-b194-19364625bbd4)
![image](https://github.com/TeamJM/journeymap/assets/11356565/151188e9-3b84-4ca2-aacc-21d63154aa85)
![image](https://github.com/TeamJM/journeymap/assets/11356565/d67a4ca7-09b6-49b8-a02c-3d7fffea0e7e)

snow is also invisible on the minimap(but not always?) could be because i'm using journeymap, and it may only happen at certain altitudes since if i break the block below and place it 1 block lower it appears on the minimap but if i place the block above again and place the snow at the same altitude it was it doesnt show up again
![image](https://github.com/TeamJM/journeymap/assets/11356565/b5a15646-ebef-4f0b-94fb-f515f886695c)
![image](https://github.com/TeamJM/journeymap/assets/11356565/e69f827c-5982-4497-8367-1f7a9caa1ae0)
![image](https://github.com/TeamJM/journeymap/assets/11356565/3a9f6080-6ba8-406e-a061-935cd8029e85)
breaking the snow fixes it
![image](https://github.com/TeamJM/journeymap/assets/11356565/8baf4265-21d9-4b29-92a1-755ef8e0dbff)
![image](https://github.com/TeamJM/journeymap/assets/11356565/94ee18cb-dfdc-4299-8afd-43bf8d82a013)

using angelica a34
using journeymap 1.7.10 514p8 
BiomesOPlenty-1.7.10-2.1.0.1860-universal.jar
i am aware my bop is slightly out of date but its the last version to include some textures i like that were changed in later 1.7 versions.

### Mod Loader

Forge

### Minecraft Version

1.7.10

### Version

other (please list)

**Comment by mysticdrew** [comment]
moved to https://github.com/TeamJM/journeymap-legacy/issues/18
