### ISSUE TITLE
[Bug]: Crazy visual bug

### ISSUE THREAD

**Issue by JaxX27** [TeamJM/journeymap#676]
### What happened?

It is pretty visual.

Im in a completely naturalized part of the map as the normal world of minecraft is but the map shows everything's supper bugged, like its made of cobblestone, or maybe its just bugged and perma shows the vertical chunks of the underground but with the structures on it, it will be better if I show you (every configuration is the default and the layer is set correctly):

![Screenshot_95](https://github.com/TeamJM/journeymap/assets/77545629/b5ec7454-4e14-4f13-9ca7-d67b323fd652)
![Screenshot_94](https://github.com/TeamJM/journeymap/assets/77545629/5d631b10-0287-453d-bc77-c998d9652a2a)

Hope its a common issue and maybe u know how to fix it!

Its on a server I made, not singleplayer.

version: 5.9.12

### Mod Loader

Forge

### Minecraft Version

1.20.1

### Version

other (please list)

### Relevant log output

[journeymap.log](https://github.com/TeamJM/journeymap/files/14625458/journeymap.log)
[latest.log](https://github.com/TeamJM/journeymap/files/14625462/latest.log)

**Comment by mysticdrew** [comment]
Try this
https://github.com/TeamJM/journeymap/issues/670#issuecomment-1906151284

**Comment by JaxX27** [comment]
That fixed it!!!

Thank you so much! You can close this now!

**Comment by mysticdrew** [comment]
Great!
