### ISSUE TITLE
[Bug]: Minimap active moves HUD up by 1 pixel

### ISSUE THREAD

**Issue by Pinkietron** [TeamJM/journeymap#677]
### What happened?

While the minimap is active the HUD is moved up by one pixel most noticeable by the line at the bottom of the screen that does not match the brightness of the surroundings.

[journeymap.log](https://github.com/TeamJM/journeymap/files/14631163/journeymap.log)
[latest.log](https://github.com/TeamJM/journeymap/files/14631168/latest.log)
![2024-03-18_01 00 48](https://github.com/TeamJM/journeymap/assets/103327140/a2cd39da-e95c-498d-ae44-40ac94719dfb)

### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Version

5.9.18

**Comment by mysticdrew** [comment]
I am unable to replicate this. 
Can you replicate it with only JourneyMap and fabric-api with no other mods at all?

**Comment by Pinkietron** [comment]
I too cannot replicate it with just journeymap and fabric-api. Though, enabling and disabling the map moves the hud in the instance shown in the picture, I can try scouring my mods one by one until I notice it.

**Comment by mysticdrew** [comment]
> I too cannot replicate it with just journeymap and fabric-api. Though, enabling and disabling the map moves the hud in the instance shown in the picture, I can try scouring my mods one by one until I notice it.

Might be a good idea to start with any mods that add items to the HUD. 
Thanks.

**Comment by mysticdrew** [comment]
Any update on this? 
I cannot fix it without replicating it, so I would need to know what mod is causing the problem.

**Comment by Pinkietron** [comment]
It appears to be due to an interaction with a mod called "Raised" 

Modrinth: https://modrinth.com/mod/raised

**Comment by mysticdrew** [comment]
> It appears to be due to an interaction with a mod called "Raised"
> 
> Modrinth: https://modrinth.com/mod/raised

Thanks!
The fix for https://github.com/TeamJM/journeymap/issues/678 also fixes this issue. 
I will publish a release today.
