### ISSUE TITLE
[Bug]: Minimap heading "my heading" rotates complete HUB including command line and debug screen.

### ISSUE THREAD

**Issue by Robijnvogel** [TeamJM/journeymap#678]
### What happened?

See title.

When the minimap heading "my heading" is selected, not just the content of the (round) minimap rotates, but all UI elements rotate around the mid-point of the minimap as well, including the command line/chat window, the hotbar and the debug screen.
Possibly the inventory UI is rotated as well when opened I have not tested.

MC version 1.20.4 .
NeoForge version 20.4.200 .
Journeymap version 5.9.21 .

Note that I was connected to a vanilla server when I observed this.

### Mod Loader

NeoForge

### Minecraft Version

other (please list)

### Version

other (please list)

**Comment by Robijnvogel** [comment]
Journeymap is the only mod I installed.

**Comment by mysticdrew** [comment]
Great, thanks! 
Fix will be published with the next update. Hopefully later today, I have a few other bugs I am lookin into before I can do a new release.

**Comment by mysticdrew** [comment]
5.9.22 is released with this fix.

**Comment by Robijnvogel** [comment]
Thank you very much for fixing this. In the latest version this works like a charm! :D
