### ISSUE TITLE
[Feature Request]: Option to always show other players on the map and minimap

### ISSUE THREAD

**Issue by TalusS** [TeamJM/journeymap#679]
### Describe the new feature.

The option to make it so other player heads never leave the map or minimap, even when out of range. Instead, their heads will sit on the corner of the map in the general direction of the other players. It would also be nice for waypoints and death points to do the same in order to make navigation easier for the directionally challenged like myself.

**Comment by mysticdrew** [comment]
Note: JourneyMap waypoints should do this, but I think it is broken. This is also a reminder to add that feature back/fix it.

**Comment by BenVlodgi** [comment]
Personally, I'd like to see where they are even in unmapped territory

**Comment by mysticdrew** [comment]
> Personally, I'd like to see where they are even in unmapped territory

That's not what it is about.

**Comment by mysticdrew** [comment]
added for next beta.
