### ISSUE TITLE
[1.12.2] GUI Textures too small for 4K screen resolution (3840x2160)

### ISSUE THREAD

**Issue by CatRabbit499** [TeamJM/journeymap#68]
#### JourneyMap Version:

`1.12.2-5.5.2`

#### Forge Version:

`1.12.2-14.23.4.2758`

#### Describe the problem in repeatable steps:

The map GUI textures max size is too small when viewed on a 4k screen. I play MC at 3840x2160 and the icons for Journeymap are way too small and cannot be adjusted to be reasonably legible at a glance:
![2018-08-27_20 59 35](https://user-images.githubusercontent.com/15235082/44696017-c174fb00-aa43-11e8-8470-974aa42bb30c.png)

I have found a rather hacky workaround overriding default assets for the icons and arrows and such with custom resized images consisting of mainly manually-upscaled files ripped from the mod JAR:
![2018-08-27_20 51 57](https://user-images.githubusercontent.com/15235082/44696135-46601480-aa44-11e8-99b9-13a977be7939.png)

I would like to suggest that you add native support for asset files of this size (2x width&height of current 'Large Icons') so people with UHD displays can use your mod without needing to modify the files themselves.

I have resized all the appropriate files in the custom resourcepack im using in the second screenshot. If you want to use the textures I modified and/or upscaled in the official mod let me know and I can put up a download link somewhere. Not going to post one now because I don't have permission to redistribute what is essentially still your files.

Steps To Reproduce:
1. Run Minecraft w/ JourneyMap on a UHD screen
2. *Constant squinting at tiny icons*

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
Not applicable.

**Comment by jermcfad** [comment]
> #### JourneyMap Version:
> `1.12.2-5.5.2`
> 
> #### Forge Version:
> `1.12.2-14.23.4.2758`
> 
> #### Describe the problem in repeatable steps:
> The map GUI textures max size is too small when viewed on a 4k screen. I play MC at 3840x2160 and the icons for Journeymap are way too small and cannot be adjusted to be reasonably legible at a glance:
> ![2018-08-27_20 59 35](https://user-images.githubusercontent.com/15235082/44696017-c174fb00-aa43-11e8-8470-974aa42bb30c.png)
> 
> I have found a rather hacky workaround overriding default assets for the icons and arrows and such with custom resized images consisting of mainly manually-upscaled files ripped from the mod JAR:
> ![2018-08-27_20 51 57](https://user-images.githubusercontent.com/15235082/44696135-46601480-aa44-11e8-99b9-13a977be7939.png)
> 
> I would like to suggest that you add native support for asset files of this size (2x width&height of current 'Large Icons') so people with UHD displays can use your mod without needing to modify the files themselves.
> 
> I have resized all the appropriate files in the custom resourcepack im using in the second screenshot. If you want to use the textures I modified and/or upscaled in the official mod let me know and I can put up a download link somewhere. Not going to post one now because I don't have permission to redistribute what is essentially still your files.
> 
> Steps To Reproduce:
> 
> 1. Run Minecraft w/ JourneyMap on a UHD screen
> 2. _Constant squinting at tiny icons_
> 
> #### Relevant errors from `.minecraft/journeymap/journeymap.log`:
> Not applicable.

I would like the resource pack if possible.  Thank you!

**Comment by CatRabbit499** [comment]
@BrainStone Do I have permission to post a download link to the files I have resized from JourneyMap?

**Comment by BrainStone** [comment]
I don't own any rights on the resources. I only tag the issues.

**Comment by hapm** [comment]
I have the same problem.

**Comment by Jfamig** [comment]
> @BrainStone Do I have permission to post a download link to the files I have resized from JourneyMap?

Hi, could you send them to me??

**Comment by Einhornyordle** [comment]
Same issue here, any updates on this?

**Comment by mysticdrew** [comment]
This is fixed in 1.14.4 and 1.15.2 versions

**Comment by mysticdrew** [comment]
I added a lot more scaling options for mc 1.16.5 jm 5.7.2 Beta 2, on curseforge. Please check it out and if some things are still too small please create a new issue. 

Closing as resolved.
