### ISSUE TITLE
[Feature Request]: Sort waypoints by distance from position on map

### ISSUE THREAD

**Issue by ChayseSmith** [TeamJM/journeymap#682]
### Describe the new feature.

I was just thinking of a feature I would use frequently. I was wondering if there is a feature planned for 1.12.2 or later that would allow us to "find waypoints closest to point on map".

Reasoning:
I have "waystones" mod that creates points on the map that allow me to teleport to by spending some exp. Whenever I discover a waystone, it automatically creates a journeymap waypoint. I'm constantly teleporting all over the map searching for stuff, and I have to visually zoom out and guess which waypoint is closest to map, which can be tricky sometimes. If we could set a keybind that when you press it while pointing to a point on the fullscreen map, or even in the world pointing at a block in the distance, it would open the waypoints view and sort all waypoints by distance from that position (not just player position). Then we could teleport to the nearest waystone with ease even if there are several waypoints in the area near that location. It would also work if you have a network of portalgun portals (another mod I have) that would show you the closest waypoint.

**Comment by mysticdrew** [comment]
You can sort waypoints by distance in the waypoint manager.
