### ISSUE TITLE
[Bug]: JourneyMap stops generating the map image after update

### ISSUE THREAD

**Issue by NovaViper** [TeamJM/journeymap#683]
### What happened?

Oddly when I enter a world (especially new ones), the minimap stops loading and doesn't generate the image of the area in the [latest Fabric update (1.20.1-5.9.19)](https://modrinth.com/mod/journeymap/version/1.20.1-5.9.19-fabric), going back to 5.9.18 makes it work again. 

### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Version

other (please list)

### Relevant log output

[latest.log](https://github.com/TeamJM/journeymap/files/14748901/latest.log)
[journeymap.log](https://github.com/TeamJM/journeymap/files/14748904/journeymap.log)

**Comment by mysticdrew** [comment]
I found the issue, I will push the fix

**Comment by mysticdrew** [comment]
Should be on modrinth if a few minutes

**Comment by NovaViper** [comment]
> what about 5.9.18p1?

Oop I didn't see this initally. Yeah it worked on that version too!


> Should be on modrinth if a few minutes

Also thank you! I just updated the mod and it works now

**Comment by mysticdrew** [comment]
Perfect!
All 1.20.1/2/4 versions were effected. Though forge seemed to work fine, no idea how or why. 
Anyways, should be a pretty huge performance bump with this newest versions
