### ISSUE TITLE
[Bug]: Can't Toggle Grid in Purist Theme

### ISSUE THREAD

**Issue by Boobies** [TeamJM/journeymap#684]
### What happened?

The grid cannot be enabled or disabled while using the Purist theme. However, it can be toggled while using other themes and the last setting will remain valid while using Purist.

### Mod Loader

Fabric

### Minecraft Version

1.20.2

### Version

5.9.18

**Comment by mysticdrew** [comment]
That is very interesting, thanks, I'll look into it

**Comment by mysticdrew** [comment]
So, this happens with all theme, well not all. Any theme to Purist or Purist to any theme.
Since purest is a different size, the button click locations are not recalculated it seems. 
Closing and reopening the fullscreen map will resolve this as a workaround until I get it fixed.

**Comment by mysticdrew** [comment]
fixed for next release

**Comment by mysticdrew** [comment]
oops forgot to close this. This was fixed in the latest release
