### ISSUE TITLE
[Crash]: Crashes when I press J to open full map.

### ISSUE THREAD

**Issue by crow-editing** [TeamJM/journeymap#686]
### What happened?

As the title says, Crashes when I press J to open full map.

### Mod Loader

NeoForge

### Minecraft Version

1.20.1

### Version

5.9.18

### Relevant log output

Crash report: https://bytebin.lucko.me/bw8wOWmL9N

**Comment by mysticdrew** [comment]
This looks like some kind of mod interaction issue. Meaning some mod is either messing with JourneyMap or breaking minecraft's keyboard handler via a mixin. 
Not much I can do without knowing which mod is causing it.

**Comment by mysticdrew** [comment]
to find the offending mod
```
The binary search is a way of finding a faulty thing among a lot of other things, without having to remove the things one-by-one.
This is useful for finding a broken mod among hundreds of mods, without having to spend time testing the mods one-by-one.
The procedure is simple:
  1. Remove half of the existing things, and put them aside.
  2. Run the program / game.
  3. Does the issue still exist?
    If YES: Repeat from step 1 with the current things.
    IF NO: Swap out the current things with the ones set aside, and repeat from step 1.
  4. Repeat this process until the problematic thing/s have been found.
```
