### ISSUE TITLE
[Bug]: Hitbox for the minimap position is off-centered

### ISSUE THREAD

**Issue by Imzxhir** [TeamJM/journeymap#687]
### What happened?

I noticed that the hitbox for the minimap position is off-centered and is not in the right position.

Screenshot:
<img width="2160" alt="6683" src="https://github.com/TeamJM/journeymap/assets/98621617/1441f7bb-d9b5-4f6d-a171-15b0f0cb1d60">

### Mod Loader

Fabric

### Minecraft Version

other (please list)

### Version

other (please list)

### Relevant log output

JourneyMap Log: https://mclo.gs/z3gm0g9

Minecraft Version: 1.20.4
JourneyMap Version: 5.9.24

**Comment by mysticdrew** [comment]
I am unable to replicate this.

**Comment by Imzxhir** [comment]
Strange, could be a macOS issue.

**Comment by mysticdrew** [comment]
THis is addressed in v6
