### ISSUE TITLE
[Crash]: java.lang.NullPointerException: Cannot assign field "sortActionsNeeded" because "this.handler" is null

### ISSUE THREAD

**Issue by kendofriendo** [TeamJM/journeymap#688]
### What happened?

Crash on launch.

### Mod Loader

Forge

### Minecraft Version

1.20.1

### Version

5.9.18

### Relevant log output

Journeymap.log unavailable

[latest.log](https://zipline.08182838.xyz/code/rZ0siB.json)

[Crashdate log](https://mclo.gs/7JdFSwJ)

**Comment by mysticdrew** [comment]
You have a lot of errors going on. 

Does it crash with only journeymap installed?

**Comment by mysticdrew** [comment]
Your issue is related to this mod. 
https://www.curseforge.com/minecraft/mc-mods/key-binding-patch

**Comment by mysticdrew** [comment]
I reported the issue on their issue tracker. 
https://github.com/Giant-Salted-Fish/Key-Binding-Patch/issues/4

I will have a patch for journeymap in the next release.

**Comment by mysticdrew** [comment]
This is fixed in the latest Key bind Patch update. 
Next JM release will have some more protection for this.
