### ISSUE TITLE
[Feature Request]: Maximum Range for Animal/Mob Radar for all players on Server 

### ISSUE THREAD

**Issue by K3ks390** [TeamJM/journeymap#689]
### Describe the new feature.

Basically the so far client sided option seen in the screenshot for a server to have animal/mob radar activated for everyone but with limited range.
Maybe also maximum amount of animals etc 

Reasoning: To have a better way to set this for the users. Also more then just turn on and off for the radar

### Images

![Screenshot_189](https://github.com/TeamJM/journeymap/assets/166447775/5d2f0f79-129c-422c-a669-d209610e2067)

**Comment by mysticdrew** [comment]
Added for next beta
