### ISSUE TITLE
[Feature Request]: Ability to zoom out further on full screen map

### ISSUE THREAD

**Issue by Desoroxxx** [TeamJM/journeymap#690]
### Describe the new feature.

It often feels like I should be able to zoom out further on the full screen map, it doesn't really allow me to get a big overview of the world around me.

Could a setting be added to allow that?

**Comment by mysticdrew** [comment]
This is already completed for the next major release: JMv6

**Comment by mysticdrew** [comment]
oops didn't mean to close it

**Comment by Desoroxxx** [comment]
> This is already completed for the next major release: JMv6

Will it come to 1.19.2?

**Comment by mysticdrew** [comment]
nope, we are targeting 1.21 release.

**Comment by mysticdrew** [comment]
This is released now in 1.21
