### ISSUE TITLE
[Bug]: Minimap info slot setting not save if it's create from API

### ISSUE THREAD

**Issue by frank89722** [TeamJM/journeymap#692]
### What happened?

Minimap Info slot setting got reset to "Blank" after game restart if the info slot is created from JM API

### Mod Loader

Forge

### Minecraft Version

1.20.1 (not happen in 1.20.4)

### Version

5.9.20

**Comment by mysticdrew** [comment]
This works fine in 1.20.4 but not 1.20.1? Strange. I will look at this in a couple days when I get home. Should be pretty simple to fix.

**Comment by mysticdrew** [comment]
After discussion, this is an issue with JMI and timing. 
I will close this now. @frank89722 let me know if anything more is needed on my end.
