### ISSUE TITLE
[Bug]: Leftover Logs in F3 Menu

### ISSUE THREAD

**Issue by Oxeus** [TeamJM/journeymap#694]
### What happened?

Journeymap 5.9.25 for 1.20.5. I only tested it on the newest version of Minecraft and removing the mod stops the issue. It looks like some leftover logs was left is the f3 menu. I am fine with it for now, but it may bother other people. 

### Mod Loader

Fabric

### Minecraft Version

other (please list)

### Version

other (please list)

### Relevant log output

![logs](https://github.com/TeamJM/journeymap/assets/13008923/c888f62b-078b-46b0-a2b8-13e0906bc4b0)

**Comment by mysticdrew** [comment]
Please fix the title of this report

**Comment by mysticdrew** [comment]
Thanks, that makes it easier for others to skim the tracker and see that it has been already reported. 
I found the issue, will be fixed in the next release.

**Comment by mysticdrew** [comment]
This is released in 5.9.26
