### ISSUE TITLE
[Bug]: weird rendering graphic issues

### ISSUE THREAD

**Issue by Steven0one** [TeamJM/journeymap#695]
### What happened?

journeymap-1.20.5-5.9.27-fabric

When I add the mod to my mod folder the game starts fine but.. I start a world and then it gets weird rendering graphic issues
If I walk around it gets worse! The Beds, Chests, Water, Items in picture frames all turn invisible!

All up-to date:
Java 17
![2024-04-27_19 22 19](https://github.com/TeamJM/journeymap/assets/49656000/d7d08de2-f68d-4ce8-9d3a-3b4b2fc3702d)
![2024-04-27_19 33 43](https://github.com/TeamJM/journeymap/assets/49656000/5632add3-2191-440d-b4c1-f419b233b3d9)

Minecraft 1.20.5
fabric 0.97.6+1.20.5

### Mod Loader

Fabric

### Minecraft Version

other (please list)

### Version

other (please list)

**Comment by mysticdrew** [comment]
You've verified that this does not happen when journeymap is disabled?

**Comment by Steven0one** [comment]
All is fine without journeymap enabled it's only started when I updated to 1.20.5 & used your latest journeymap-1.20.5-5.9.27-fabric.jar If I don't use that its all good.

**Comment by mysticdrew** [comment]
if you revert to 5.9.26, does that resolve it? 

If you create a new world with only journeymap  5.9.27 and fabric-api, does the issue persist?

**Comment by Steven0one** [comment]
Just tested and 5.9.26 & 5.9.27 and the strange issues still happen in old and new worlds.

**Comment by mysticdrew** [comment]
Can you please provide both your Journeymap.log and latest.log please?

**Comment by Steven0one** [comment]
[journeymap.log](https://github.com/TeamJM/journeymap/files/15139518/journeymap.log)
[latest.log](https://github.com/TeamJM/journeymap/files/15139519/latest.log)

That's latest files

**Comment by mysticdrew** [comment]
Please create a new world with only journeymap and fabric API installed. meaning no modmenu, no fabric sky boxes, no autoclicker fabric. 
See if there is still an issue. 
If there is no issue, add the mods back one at a time until it breaks so we can see if it is a mod interaction issue.

**Comment by Steven0one** [comment]
Tried a new world with only journeymap and fabric and the same issue water goes invisible & blue graphic glitches show still.
![2024-04-27_20 02 48](https://github.com/TeamJM/journeymap/assets/49656000/9869b61b-e12a-4162-8331-6759f45c2390)

**Comment by mysticdrew** [comment]
I am unable to replicate this.

**Comment by mysticdrew** [comment]
You say you're using Java 17? Please verify. MC 1.20.5 requires java 21.

**Comment by Steven0one** [comment]
Sorry! its updated to 22 but I can try take it back to 21 and see if that changes anything?

**Comment by mysticdrew** [comment]
> Sorry! its updated to 22 but I can try take it back to 21 and see if that changes anything?

probably a good idea

**Comment by Steven0one** [comment]
Still the same tried it with journeymap & fabric only in a new and old world still the same glitches, removed 22 re-booted installed 21 re-booted and still no luck sadly.

**Comment by mysticdrew** [comment]
are you using vanilla launcher or a different launcher?

**Comment by Steven0one** [comment]
Just the normal vanilla launcher no fancy things. I even tried emptying the resources and data pack folders they only had the Coordinates & 1 sky pack but sadly removing them still didn't help :/

**Comment by Steven0one** [comment]
Drew! I found a way around the issue :) Options, Video Settings & change the Graphics to Fast or Fancy = No weird graphics :)
If it's set to Fabulous! that's when the graphic glitches start showing & things disappear.

**Comment by mysticdrew** [comment]
Awesome, thanks that gives me something to go on! Phew.. 
I can replicate it now. 
![image](https://github.com/TeamJM/journeymap/assets/5459941/5345a2f6-a7b3-4be6-8b06-078ee0109c13)

**Comment by Steven0one** [comment]
Massive thanks! to you! for the help! & being patient, so glad we found what was causing it. I don't go in-to the settings very often, decided to go in on the off-chance and voila! Now I hope you can find the offending code, best of luck to you :)

I need to some sleep its nearly midnight, thanks again for the awesome! help and of course the Journey Map MOD
I'd be lost without it, literally! It's so helpful! I don't know if you want to close this, I'll leave it up to you & check tomorrow.

**Comment by mysticdrew** [comment]
Fix is getting published now 1.20.5-5.9.28-fabric
