### ISSUE TITLE
Null Pointer Exception related? to color pallette

### ISSUE THREAD

**Issue by gwynhefar** [TeamJM/journeymap#696]
### What happened?

No crash, but I'm getting errors in my log
 

### Mod Loader

Forge

### Minecraft Version

1.12.2

### Version

5.7.1

### Relevant log output

[journeymap.log](https://github.com/TeamJM/journeymap/files/15172010/journeymap.log)
[latest.log](https://github.com/TeamJM/journeymap/files/15172051/latest.log)

**Comment by mysticdrew** [comment]
you mean this?
```
:32:33] [Client thread/WARN] [journeymap]: Couldn't copy color palette html: java.lang.NullPointerException
[17:32:33] [Client thread/ERROR] [journeymap]: Can't write colorpalette.html: java.lang.NullPointerException
```
Don't worry about it.

**Comment by gwynhefar** [comment]
Ok thanks!
