### ISSUE TITLE
Journeymap not working properly in nether

### ISSUE THREAD

**Issue by swegfyy** [TeamJM/journeymap#697]
### What happened?

When I use Journeymap (journeymap-1.20.1-5.9.21-fabric) in the nether, it doesn't work properly. All the parts where netherrack hits the bedrock roof, it shows as black bits in the map (see the attached file for reference). In my opinion this is a bug because I could not find a way to make the netherrack appear normally on the map. Please, this would be very important to me to get fixed / working.

![2024-05-01_15 58 50](https://github.com/TeamJM/journeymap/assets/168681640/d0b5af18-fb18-4b76-941a-451d9624e041)

### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Version

other (please list)

### Relevant log output

[journeymap.log](https://github.com/TeamJM/journeymap/files/15181166/journeymap.log)
[latest.log](https://github.com/TeamJM/journeymap/files/15181168/latest.log)

**Comment by mysticdrew** [comment]
Screenshot? (not a mobile phone picture)

**Comment by mysticdrew** [comment]
I see no issues, that is how mapping works. Blocks that are not visible are not rendered.
