### ISSUE TITLE
[Feature Request]: Allow players to customize the colors for biome overlay

### ISSUE THREAD

**Issue by xadip** [TeamJM/journeymap#698]
### Describe the new feature.

Request: I've always enjoyed exploring and discovering different biomes. However, I think it would be amazing if
players could customize the colors for each biome to make the map even more unique and personalized, allowing us to
create visual distinctions that enhance our experience and improve navigation.

Extra: allow player to select different colors on the fly, without the need to "refresh" de map to see it.

**Comment by mysticdrew** [comment]
There is no biome overlay.  The biome map are separate map tiles. I will not be adding an overlay at this time. 

I can add a config file similar to the topo color config for biomes. Maybe a UI for it in the future.

**Comment by xadip** [comment]
that would be a start. 
That way I can select flower forest, with a color different from every biome. cool.

**Comment by mysticdrew** [comment]
This will be available in the color palette screen with 6.0.0.beta.19 release

**Comment by Roemischer** [comment]
where are the colors for the biome map currently drawn from?

**Comment by mysticdrew** [comment]
1.21-6.0.0-beta.19 is publishing now. 
Color Palette screen change it from blocks to biome and edit away!

**Comment by mysticdrew** [comment]
> where are the colors for the biome map currently drawn from?

what do you mean "drawn from"? The colors are derived from the biome grass color

**Comment by Roemischer** [comment]
thanks, I was not sure where the color was coming from, and it is really hard to distinguish biomes. I wanted to change the colors, but again didn't know where
