### ISSUE TITLE
GL Error 65539: Invalid key -1 bug

### ISSUE THREAD

**Issue by EKK98** [TeamJM/journeymap#699]
#400 bug has reappeared with the same error message. I'm playing 1.20.4-5.9.25 Fabric: 0.15.11

_Originally posted by @ItsTeraBytes in https://github.com/TeamJM/journeymap/issues/400#issuecomment-1987041481_

**Comment by mysticdrew** [comment]
How do you know this is JourneyMap? I need Logs and more details on how to reproduce it.

**Comment by EKK98** [comment]
Hey
it happens when a key bind is set to "not bound" in JourneyMaps key binds, then when i press the old key "m" the error message starts spamming every time a presses a different key.
And when i resets the key to default the GL error message stops spamming in the mc log file.
only happens with JourneyMaps key binds.

[Render thread/ERROR]: ########## GL ERROR ##########
[Render thread/ERROR]: @ Render
[Render thread/ERROR]: 65539: Invalid key -1

[journeymap.log](https://github.com/TeamJM/journeymap/files/15206415/journeymap.log)
[latest.log](https://github.com/TeamJM/journeymap/files/15206416/latest.log)

**Comment by EKK98** [comment]
> How do you know this is JourneyMap? I need Logs and more details on how to reproduce it.

Hey
it happens when a key bind is set to "not bound" in JourneyMaps key binds, then when i press the old key "m" the error message starts spamming every time a presses a different key.
And when i resets the key to default the GL error message stops spamming in the mc log file.
only happens with JourneyMaps key binds.

[Render thread/ERROR]: ########## GL ERROR ##########
[Render thread/ERROR]: @ Render
[Render thread/ERROR]: 65539: Invalid key -1

[journeymap.log](https://github.com/TeamJM/journeymap/files/15206415/journeymap.log)
[latest.log](https://github.com/TeamJM/journeymap/files/15206416/latest.log)

**Comment by mysticdrew** [comment]
Does this happen with only Fabric-API and JourneyMap installed? No other mods.

**Comment by mysticdrew** [comment]
fixed in 5.9.30

**Comment by mysticdrew** [comment]
This is now fixed on latest release version for 1.20.1/4/6 versions of minecraft.
