### ISSUE TITLE
[Bug]: [1.20.6] Can't Hide JourneyMap HUD by Pressing F1

### ISSUE THREAD

**Issue by Shiroiame-Kusu** [TeamJM/journeymap#700]
### What happened?

On 1.20.4, all the HUD will be hidden after pressing F1.
But on 1.20.6, it is not working.
Like this:
![2024-05-04_10 30 41](https://github.com/TeamJM/journeymap/assets/42903464/96432afd-4483-4291-b398-80e82c37d7c6)
![image](https://github.com/TeamJM/journeymap/assets/42903464/5b4e8a2a-4ca0-4c0a-b021-7d24f755db2e)

### Mod Loader

Fabric

### Minecraft Version

other (please list)

### Version

other (please list)

### Relevant log output

[latest.log](https://github.com/TeamJM/journeymap/files/15206398/latest.log)
[journeymap.log](https://github.com/TeamJM/journeymap/files/15206399/journeymap.log)

**Comment by mysticdrew** [comment]
Interesting, do the waypoints hide at least? I don't think I changed anything with how the minimap is rendered, I forget though. I am on holiday so I wont get a chance to look at this until monday.

**Comment by Shiroiame-Kusu** [comment]
> Interesting, do the waypoints hide at least? I don't think I changed anything with how the minimap is rendered, I forget though. I am on holiday so I wont get a chance to look at this until monday.

Yes, those waypoints are hidden properly, only the map is still there.
![2024-05-04_10 52 51](https://github.com/TeamJM/journeymap/assets/42903464/d6e08833-8b32-4711-8128-9d52d14092ea)
![2024-05-04_10 52 54](https://github.com/TeamJM/journeymap/assets/42903464/aeda831a-7e40-4639-93e3-a44f8632d7ae)

**Comment by Shiroiame-Kusu** [comment]
And in order not to affect the test results, I only added fabric-api and JourneyMap to the test client (you can also know this from the log I submit above.)
![image](https://github.com/TeamJM/journeymap/assets/42903464/d110b5c9-a634-439f-bbfc-d221a69f2617)

**Comment by mysticdrew** [comment]
fixed in 5.9.30
