### ISSUE TITLE
[Feature Request]: Disable entity icons from certain mods

### ISSUE THREAD

**Issue by tony0099** [TeamJM/journeymap#702]
### Describe the new feature.

Ability to disable entity icons from specific mods. Currently my ice and fire entity icons just show as big flat shapes on the map and minimap. 

If I could disable their specific icons that would be helpful. 

### Images

![error icon](https://github.com/TeamJM/journeymap/assets/31675035/05d99ccb-3717-4f6d-b99b-12eb964e0198)

**Comment by mysticdrew** [comment]
Were those icons added by a resource pack?  You could just disable that resource pack or delete the image files from the pack. 
We don't ship icons for modded mobs other than Quark since they have a special use case with replacing vanilla mobs.

**Comment by mysticdrew** [comment]
> If I could disable their specific icons that would be helpful.

So, I likely wont be adding this feature as it would require a lot of UI work that can get really messy that I simply don't want to do. 
Your issue with icons is an issue with your resource packs, not journeymap, nor ice and fire. Remove the resource pack providing those image or delete the images from the resource pack to solve your problem. 

I am going to close this, if you wish to respond and discuss options or need help removing the icons, feel free to reply.
