### ISSUE TITLE
[Bug] [1.20.1] Auto-map failing to render chunks

### ISSUE THREAD

**Issue by JENOVAAbsolute** [TeamJM/journeymap#703]
### What happened?

After using Chunky to pre-generate a 6000x6000 block radius, I used JourneyMap's auto-map function, but it fails to render a lot of chunks. This happened several times in a row.

Screenshot:
![map](https://github.com/TeamJM/journeymap/assets/60951301/0c294850-4d25-4bbf-ad6c-00bdd5d2c33b)

### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Version

JourneyMap 5.9.21

### Relevant log output

[latest.log](https://github.com/TeamJM/journeymap/files/15281687/latest.log)
[journeymap.log](https://github.com/TeamJM/journeymap/files/15281690/journeymap.log)

**Comment by mysticdrew** [comment]
Looking at the jourenymap.log It looks like you let automap run for about 90 seconds and then turned it off. 
You need to let it run to completion.

**Comment by JENOVAAbsolute** [comment]
> Looking at the jourenymap.log It looks like you let automap run for about 80 seconds and then turned it off. You need to let it run to completion.

Here's two more examples of the issue.
![New Project](https://github.com/TeamJM/journeymap/assets/60951301/0adbcd82-336b-4cbe-bdd0-bfa2bc0ee001)
![New Project(1)](https://github.com/TeamJM/journeymap/assets/60951301/db82ba2c-6dbe-4334-91fe-616f2363d3d6)

Please correct me if I'm wrong. All the white squares are marked as "completed" according to JourneyMap. Those are obviously not complete, so I stopped auto-mapping, as letting it run will only result in twelve hours of my day being wasted.

New logs:
[latest.log](https://github.com/TeamJM/journeymap/files/15283650/latest.log)
[journeymap.log](https://github.com/TeamJM/journeymap/files/15283651/journeymap.log)

**Comment by mysticdrew** [comment]
Looks like Chunky is not finishing the chunks all the way. 
I would suggest disabling c2me has it is known to cause issues with automapping. 
You have a lot of mods, there is likely an issue with a mod interaction going on. 
I have tested chunky and JM a lot, 100k chunks without issues and it did not take 12+ hours to map.

**Comment by mysticdrew** [comment]
looking at the logs, something is causing it to exit early. 
Can you upload a few of your regions please?
They will be in `./minecraft/saves/worldname/region/`
```
[12:45:14] [Render thread/INFO] [ChatLog] JourneyMap: Auto-mapping surface (0.4%).
[12:45:16] [JM-task-3/INFO] [MapRegionTask] Potential chunks to map in RegionCoord [-1,0]: 1024 of 1024
[12:47:25] [JM-task-3/INFO] [MapRegionTask] Actual chunks mapped in RegionCoord [-1,0]: 790 
```

**Comment by JENOVAAbsolute** [comment]
> Looks like Chunky is not finishing the chunks all the way. I would suggest disabling c2me has it is known to cause issues with automapping. You have a lot of mods, there is likely an issue with a mod interaction going on. I have tested chunky and JM a lot, 100k chunks without issues and it did not take 12+ hours to map.

Yeah, this was my next step in testing. I started removing mods to find a cause, and as soon as I read your message, I removed C2ME. It did indeed solve all my problems. Auto-mapping also became 8-10x faster. No, that's not an exaggeration.

If you'd like, I can re-apply C2ME and provide the region files you asked for in case you want them for anything else. Otherwise, we can close this issue.

**Comment by mysticdrew** [comment]
Wow, that's a lot faster. Glad it was an easy solution. 
I'll set up a test with c2me and see if I can solve it, or reach to he them to come up witha solution. 

I don't need your regions anymore, thanks though.
