### ISSUE TITLE
[Feature Request]: Waypoint Search

### ISSUE THREAD

**Issue by Duxizon** [TeamJM/journeymap#704]
### Describe the new feature.

Please add the ability to search for a waypoint. When you have alot of waypoints it is hard to find it and a search bar where you can search for the name of the waypoint would make journeymap way easier to use.

**Comment by mysticdrew** [comment]
This is in fact planned as part of the waypoint rewrite. Here is a sneak peak. 

![java_bpZL1UNLuu](https://github.com/TeamJM/journeymap/assets/5459941/46f7fa27-5bd9-481e-ae60-9a33a20ed491)

**Comment by UltraBlackLinux** [comment]
can't wait. I have two hundred and fifty waypoints and it's a pain to find a specific one

**Comment by mysticdrew** [comment]
![java_s0mYidHPpB](https://github.com/user-attachments/assets/96901622-6cf6-4da2-9daf-977e5d28a80f)

Incoming on next release

**Comment by mysticdrew** [comment]
1.21-6.0.0-beta.19 is publishing with the new waypoint manager, will be live in mr/cf soon
