### ISSUE TITLE
[Feature request]: Improve map color palette

### ISSUE THREAD

**Issue by Iker21dev** [TeamJM/journeymap#705]
### Describe the new feature.

It's been a long time with the same color palette for the map of this mod, it's time for a facelift, I think they should add an option or directly change the color palette, to be more faithful to the terrain as it does Xaero map example.

### Images

![image](https://github.com/TeamJM/journeymap/assets/80030992/f0bf4259-6473-4309-b685-0b0a0f634c5a)
Current xaero color palette.
![image](https://github.com/TeamJM/journeymap/assets/80030992/e4ffff7a-ab3e-4734-81af-8a2d9112ec3e)
Current Journey ( wee need more zoom lol)

**Comment by mysticdrew** [comment]
I have no idea what you mean by color palette in regards to those images.

**Comment by mysticdrew** [comment]
If you're talking about the water biome colors and bathymetry for the sea. 
https://teamjm.github.io/journeymap-docs/latest/Client%20Docs/settings/cartography/

**Comment by mysticdrew** [comment]
And more Zoom is coming in JM 6
![image](https://github.com/TeamJM/journeymap/assets/5459941/13781c39-039c-4cc3-8e60-1552779d259e)

**Comment by mysticdrew** [comment]
I will close this now, if I am missing something per your suggestions, I think your concerns have been addressed. Please add more detail and reopen.
