### ISSUE TITLE
[Bug]: Fails to load Singleplayer world - Exception thrown

### ISSUE THREAD

**Issue by greyhawk94** [TeamJM/journeymap#706]
### What happened?

Loading a Singleplayer world with MC 1.20.6 - Forge 50.0.22 - JM 5.9.25 throws an exception:
`Internal Exception: java.lang.NoSuchMethodError: 'net.minecraftforge.network.NetworkDirection net.minecraftforge.event.network.CustomPayloadEvent$Context.getDirection()'`

More specifically, it fails with Forge version 50.0.9 and above

From the Forge changelog:
https://maven.minecraftforge.net/net/minecraftforge/forge/1.20.6-50.0.22/forge-1.20.6-50.0.22-changelog.txt

50.0.9 "Rework networking" --> incompatibility?

### Mod Loader

Forge

### Minecraft Version

other (please list)

### Version

other (please list)

### Relevant log output

* journeymap.log : https://paste.ee/p/PCT12
* latest log : https://paste.ee/p/aKfAI

**Comment by mysticdrew** [comment]
Update to journeymap 5.9.26, it wa fixes the breaking change in forge you're having

**Comment by mysticdrew** [comment]
https://www.curseforge.com/minecraft/mc-mods/journeymap/files/5338162
