### ISSUE TITLE
[Feature Request]: Allow for longer text on waypoint Y coordinate field.

### ISSUE THREAD

**Issue by N0aW** [TeamJM/journeymap#708]
### Describe the new feature.

Currently, the Y coordinate field only allows up to three numbers/symbols.

Now this is fine for the Overworld, Nether and the End, since their build limit goes from -64 to 320 at maximum.

But, modded dimensions can have longer heights. The build limit can go from -2031 to 2031, and places that are below Y -99 or above Y 999 cannot be written into waypoints.

Also I am talking about inputting the coordinates manually into a waypoint.

**Comment by mysticdrew** [comment]
added in with the waypoint rewrite 1.21-6.0.0-beta.19
