### ISSUE TITLE
map displaying map of previous world causing lag

### ISSUE THREAD

**Issue by username32121** [TeamJM/journeymap#710]
### What happened?

the map keeps displaying the map of the last world, i start a new world and it shows the map as if its already discovered despite being a new world using version 1.12.2

### Mod Loader

Forge

### Minecraft Version

1.12.2

### Version

other (please list)

**Comment by mysticdrew** [comment]
Causing lag? I doubt it. 
Give your worlds unique names. The data is saved based on the name you give it in the singleplayer or multiplayer menu. 
If name them the same, it does not know it is a different map.

**Comment by username32121** [comment]
> you can take a screenshot, here are instructions https://techcommunity.microsoft.com/t5/windows-11/how-to-take-screenshot-on-windows-10/m-p/3760249
> 
> you never provided logs as required in the issue template.

first off i don't know how to get the logs, secondly its not required otherwise i couldn't have posted this at all, so no logs are NOT required

**Comment by mysticdrew** [comment]
![image](https://github.com/TeamJM/journeymap/assets/5459941/101ae89d-b50a-4f75-95bc-e2253276a1c6)
well provide them

**Comment by EyesISeeU** [comment]
Provide the stuff so you can get help bruh, stop acting like a child.

**Comment by mysticdrew** [comment]
I am going to lock this as people see your ranting in the multiple issues in our discord as you can see in the post above. 

If you create a new issue I will report to github as spam which will ban your account and possibly IP. 
If you wish to get more help regarding this issue, you can come to our discord, I will no longer provide you help on github.

Again, let me reiterate here. 
Map data is saved by the name you put in the Singleplayer menu for 1.12.2. 

This has been changed for singleplayer in future versions to use the name minecraft uses for the world save. 
So renaming or using the same names for worlds does not cause issues, though it still effects multiplayer. 

You can see your singleplayer map data in `(mc install directory)/journeymap/data/sp`

If you created a world, deleted it and created a new one with the same name, it will load your old data. JourneyMap does not interact with the singleplayer or multiplayer screens to know if you deleted/created/renamed your worlds/saves.
That can be deleted by the trashcan button in the fullscreen map. 

If you create a world with the same name as an existing world, it will load the data that your existing world already created. It does not matter if the seed is different, only the name is what is used for saving data. 

Regarding "lag" you experienced. Without you providing any actual data backing up this claim, based on how we create and write map data it does not cause any lag. The map is just pixels on an image. If there a chunk is about to be mapped and an image does not exist, a new transparent image is generated and we write the pixel data to each pixel. If the image already exists, we do not read the pixel data, we just overwrite it. So both cases use an existing image and write the rgb values to the pixel. The mapping engine actually has no idea if it is a transparent image or an image with colored pixels already, it just replaces the pixel rgb values.
