### ISSUE TITLE
[Bug]: entity/mob names not showing on both minimap and fullscreen map

### ISSUE THREAD

**Issue by 345022817** [TeamJM/journeymap#711]
### What happened?

mob name not showing, I already enabled the "show entity names" in settings.
Modpack is ATM9 latest version.
![image](https://github.com/TeamJM/journeymap/assets/47494915/31345c2a-dfbd-4d1c-8abd-42a26f12a6c5)
![image](https://github.com/TeamJM/journeymap/assets/47494915/815ea25d-8a6f-4cb6-ad9f-19c891de677b)

### Mod Loader

Forge

### Minecraft Version

1.20.1

### Version

5.9.18

**Comment by mysticdrew** [comment]
Show entity names is only for custom nametags provided by bukkit servers in the current state. This is the intended feature. 

However, journeymap v6 will properly show entity names with a lot more specific options.
