### ISSUE TITLE
[Bug]: Purist theme info slots have incorrect color

### ISSUE THREAD

**Issue by B1BU** [TeamJM/journeymap#719]
### What happened?

A typo is causing the info slots to look incorrect while using the purist theme. I believe the color is supposed to be `#555555` but it's incorrectly typed as `#55555` which the game reads as `#055555` making it cyan instead of gray

### Mod Loader

Forge

### Minecraft Version

1.20.1

### Version

5.9.18

**Comment by mysticdrew** [comment]
screen shot so I know exactly what you are talking about please?

**Comment by mysticdrew** [comment]
![image](https://github.com/TeamJM/journeymap/assets/5459941/27cb166c-164b-4693-b320-2aa844ac70e8)
I see what you're talking about here

**Comment by mysticdrew** [comment]
So this is fixed in 1.21 already, but I am working on a final bugfix release for the 1.20's. Hopefully this weekend.

**Comment by mysticdrew** [comment]
fixed in 5.10.0
