### ISSUE TITLE
[Feature Request]: hide snow layers config

### ISSUE THREAD

**Issue by loudwhitenoise** [TeamJM/journeymap#726]
### Describe the new feature.

A config option to ignore snow layers. (alternatively: an advanced config option to blacklist certain blocks from being mapped entirely would be cool, server owners could hide valuables with it. thats a bit off topic though)

When there is snow everywhere and it turns the whole map white it is not very useful for me to navigate with. I would like to be able to hide snow layers and display the block beneath them.

**Comment by mysticdrew** [comment]
` option to blacklist certain blocks from being mapped` no, this will turn JM into an x-ray mod. 

Disable snow rendering may be something I would consider.

**Comment by mysticdrew** [comment]
added but not sure how I like it, it has some weird side effects. I may remove it if people complain about it.

**Comment by MrMarvel** [comment]
Use case: same view for seasonal change of top blocks (like seasons with irregular snow layer)

**Comment by TheFriedEgg618** [comment]
is this available for 1.12.2?
