### ISSUE TITLE
[1.20.1]: Mid-game crash suspected to be related to JourneyMap

### ISSUE THREAD

**Issue by MingkLing** [TeamJM/journeymap#727]
### What happened?

Getting mid-game crashes. I'm not sure this is caused by Journey map but it seems to be the only mod that pops up in the error log, there are also several instances when the crash happens when I open the large map but not every time. 
I'm using the latest version of Journey map

### Mod Loader

Forge

### Minecraft Version

1.20.1

### Version

6.0.0

### Relevant log output

[hs_err_pid1588.log](https://github.com/user-attachments/files/15880363/hs_err_pid1588.log)
[journeymap.log](https://github.com/user-attachments/files/15880367/journeymap.log)
[latest.log](https://github.com/user-attachments/files/15880369/latest.log)

**Comment by mysticdrew** [comment]
You didn't provide your whole latest.log. 
I feel this is likely a mod interaction issue. Something is destroying allocated images prematurely. from the looks of it.

**Comment by mysticdrew** [comment]
Not much I can really do about this, your best bet is to remove all mods other than journeymap and see if the problem persists. 
I would start a new world just to not messing up an existing one. 
If the problem persists, it is a JM problem and we can try to figure out what is going on. 
If it does not happen, start adding mods back until it breaks again. Then let me know and we can start looking into fixing it. 

I will close this in 24ish hours if I get no response.

**Comment by mysticdrew** [comment]
stale
