### ISSUE TITLE
[Feature Request]: icons and waypoints options. 

### ISSUE THREAD

**Issue by cauamachado51** [TeamJM/journeymap#728]
### Describe the new feature.

Xaero's map makes the mob mod icons a good size, the same png placed for JourneyMap is tiny and the red dot appears. I wanted at least some option to enlarge the individual icon, completely remove the dot and have 100% opacity. Also note that it is difficult to see the vanilla fish icon on the JourneyMap, and the Waypoint is ugly. see in full screen.

https://github.com/TeamJM/journeymap/assets/132782265/634917d1-a333-4568-849d-ee5d83ed1ab9

take a closer look. see in full screen.
![Sem título](https://github.com/TeamJM/journeymap/assets/132782265/33b8672d-5628-41e9-8cf3-1015026365fe)

I wanted a waypoint option similar to Xaero's on the map and another in the world. NOTE: in the video it showed the waypopint on the map, but it did not show that when hovering the mouse over it it shows the name. see in full screen.
![Minecraft Forge_ 1 20 1 - Um jogador 18_06_2024 19_56_08](https://github.com/TeamJM/journeymap/assets/132782265/1f733aef-1fc1-4b68-9dea-6e7151ab7783)
![Minecraft Forge_ 1 20 1 - Um jogador 18_06_2024 19_56_27](https://github.com/TeamJM/journeymap/assets/132782265/6dcc46cb-5e28-4f4f-af73-72f73d102ce1)

**Comment by mysticdrew** [comment]
Fish icons have been completely redone.. well all icons have been completely redone in journeymap 6.0.0 for mc 1.21. 

But you also have the option to increase the size you know, in the options. Just about everything on the map has a scale option to make it larger or smaller. 

https://teamjm.github.io/journeymap-docs/latest/Client%20Docs/settings/overview/

So, the only feature that you want that we do not have it sounds like now is hide waypoint labels but only show them when you mouse over them on the fullscreen map?

**Comment by EyesISeeU** [comment]
@cauamachado51 Why not use Xaeros instead of JourneyMap if JourneyMap is so bad?
