### ISSUE TITLE
[Bug]: Waypoint Coords Changed After Updating Journeymap

### ISSUE THREAD

**Issue by Squtzy** [TeamJM/journeymap#729]
### What happened?

After updating to Journeymap 1.21-6.0.0-Beta.4 for Fabric all my waypoints in the nether now have the incorrect coordinates set. ONLY the waypoints in the nether have changed and are showing the incorrect coordinates that I have been able to tell so far. 
All my overworld waypoints seem to still be working as they should.

### Mod Loader

Fabric

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

https://mclo.gs/85fkKrV - Journeymap.log

https://mclo.gs/5zfzohE - Latest.log

**Comment by mysticdrew** [comment]
was this an upgrade from an earlier beta to beta.4 or from an older version of mc/jm right to beta.4?

**Comment by mysticdrew** [comment]
Can you come into our discord please or upload your WaypointyData.dat file here please?
`C:\Users\********\AppData\Roaming\PrismLauncher\instances\Vanilla\.minecraft\journeymap\data\sp\The World Of Stan\waypoints\WaypointData.dat`

**Comment by mysticdrew** [comment]
Oh, I found the issue. I am working on a fix.

**Comment by mysticdrew** [comment]
Fixed with 1.21-6.0.0-beta.5
Should be on curseforge and modrinth in 15ish minutes.

**Comment by Squtzy** [comment]
> Fixed with 1.21-6.0.0-beta.5 Should be on curseforge and modrinth in 15ish minutes.

Oh dang you worked fast haha. Sorry for the late reply I wasn't at my PC until now. Thanks for the quick work <3
