### ISSUE TITLE
[1.12.2] Different Colors on same map when switching Texturepack

### ISSUE THREAD

**Issue by deerangle2** [TeamJM/journeymap#73]
#### JourneyMap Version:

`1.12.2-5.5.2`

#### Forge Version:

`1.12.2-14.23.4.2705`

#### Describe the problem in repeatable steps:

1. Load some area into the map with some texture pack.
2. Switch texture pack to a different one and restart Minecraft.
3. Load some area with the new texture pack.
4. Block-Colors are no longer consistent across the entire map.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

`No error log because the error is in the design.`

**Comment by BrainStone** [comment]
That's essentially intended. The colors for the map are derived from the texturepack, meaning that if you change it, the palette will change too.

There's also not much that could be done. Any other solution would be a huge waste of resources.
