### ISSUE TITLE
[Bug]: Teleport to wrong location when I teleport from overworld to nether

### ISSUE THREAD

**Issue by Axxel2046** [TeamJM/journeymap#731]
### What happened?

When I want to teleport from any random location to a location in nether, it always send me to the wrong place.
For example, when I want to go to a location x:11, y:47 Z:12, it send me to the location x:2, y:42, z:2

### Mod Loader

Fabric

### Minecraft Version

1.21.x

### Version

6.0.0

**Comment by mysticdrew** [comment]
What beta an version?

**Comment by Axxel2046** [comment]
6.0.0. Beta 7
I tried Beta 2 before but found that the location setting of my waypoint in Nether kept changing.

**Comment by mysticdrew** [comment]
So, your waypoint is at - `x:11, y:47 Z:12`, 
But it teleports you to -` x:2, y:42, z:2`?

**Comment by Axxel2046** [comment]
Yes

**Comment by jaqque** [comment]
I was able top recreate this bug with beta 7:
`Nether Portal -76 -31 68`

From overworld, teleporting to that waypoint I ended up at:
`Teleported from portal -10 -3 60`

It's possible the y coordinate did not change; I was teleported in air and fell to y=60

**Comment by mysticdrew** [comment]
Sounds good, I will get this addressed for the next beta. Thanks

**Comment by mysticdrew** [comment]
Just pushed 1.21-6.0.0-beta.8 will be available to download in 15-20min, maybe sooner.

**Comment by jaqque** [comment]
Confirmed teleport from overworld to nether waypoint works as expected.
Tested the regression from nether to overworld, and that works as expected also.

**Comment by mysticdrew** [comment]
Nice, thanks! 
This version of JM for some reason on curseforge is back to manual review so, probably not available for a bit, will need to download on modrinth.
