### ISSUE TITLE
[Feature Request]: Allow sharing the user's map with (an)other player(s).

### ISSUE THREAD

**Issue by RokeJulianLockhart** [TeamJM/journeymap#734]
### Describe the new feature.

I play on a private open-to-LAN world with my brother, and we want to share our maps with one-another. We see no way to share a map between the users on a world. However, we would also want to were we playing on a server not hosted by ourselves, but potentially not with others, so if implemented, an adequately granular permission system would be advantageous.

**Comment by mysticdrew** [comment]
map sync duplicate of
https://github.com/TeamJM/journeymap/issues/419

**Comment by RokeJulianLockhart** [comment]
> https://github.com/TeamJM/journeymap/issues/734#issuecomment-2184158852

@mysticdrew, thanks. However, that issue contains multiple suggestions. Is there no merit to separation?

**Comment by mysticdrew** [comment]
You can share manually for now, the data is stored in ./minecraft/journeymap/data/mp or sp/WORLDNAME

**Comment by mysticdrew** [comment]
`However, we would also want to were we playing on a server not hosted by ourselves, but potentially not with others, so if implemented, an adequately granular permission system would be advantageous.`
Would require journeymap on the server still, but yes, that is planned.
