### ISSUE TITLE
[Crash]: {replace with description}

### ISSUE THREAD

**Issue by Alex115647** [TeamJM/journeymap#735]
### What happened?

A crash happened! I cannot create a waypoint without it crashing. This was on a server, and i was running Journey client side only. 

### Mod Loader

Fabric

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

[journeymap.log](https://github.com/user-attachments/files/15949039/journeymap.log)

[crash-2024-06-23_21.15.41-client.txt](https://github.com/user-attachments/files/15949044/crash-2024-06-23_21.15.41-client.txt)

**Comment by mysticdrew** [comment]
![Screenshot_20240623-215351_Chrome](https://github.com/TeamJM/journeymap/assets/5459941/3f762abb-c243-4fa1-a908-942c99ea5965)


Is not valid
