### ISSUE TITLE
Possible memory leak.

### ISSUE THREAD

**Issue by Arya1234343** [TeamJM/journeymap#736]
### What happened?

when using this mod, my FPS after about 10 minutes drops below 30 (normal 140+) and according to task manager minecraft is using 25GB of RAM. (normal ~12)

### Mod Loader

Fabric

### Minecraft Version

1.21.x

### Version

6.0.0

**Comment by mysticdrew** [comment]
What version

**Comment by mysticdrew** [comment]
Thanks for the report. This is fixed in beta.10 which is getting published right now. Should be on Modrinth and Curseforge within the next 20 minutes.

**Comment by Arya1234343** [comment]
Thank you!
