### ISSUE TITLE
[Bug]: FullScreen Map Player Icon Not Showing, Close View of Map Not Showing, and Spam in logs

### ISSUE THREAD

**Issue by Oxeus** [TeamJM/journeymap#737]
### What happened?

When viewing the fullscreen map you can see the loaded map from afar but when you zoom in it goes blank. The player icon is also not shown on the map. 

There is no crash data or error except for this one:
[14:59:12] [Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. No active program.'

I tested that it was the fullscreen map by opening and closing the map. As soon as I opened it again the error spam started again. I do have Iris and Sodium but the issue still persists when they are gone.

### Mod Loader

Fabric

### Minecraft Version

1.21.x

### Version

other (please list)

### Relevant log output

Mod Version: 1.21-6.0.0-beta.10+fabric

[14:59:12] [Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. No active program.'

This gets spammed about 100 times every couple seconds.

**Comment by mysticdrew** [comment]
provide the lastest.log and journeymap.log please

**Comment by Oxeus** [comment]
[journeymap.log](https://github.com/user-attachments/files/15979890/journeymap.log)
Thats the log for journeymap

**Comment by Oxeus** [comment]
I may have to cut the one for latest its balloons to over 30mb

**Comment by Oxeus** [comment]
[latest.edited.log](https://github.com/user-attachments/files/15979917/latest.edited.log)

**Comment by Oxeus** [comment]
I did some further testing and I think it mainly occurs if you enter the resourcepack menu, if you hit done whether selecting the resourcepack or not, the game refreshes the visuals of the game. 

I tested the fullscreen map before opening the resourcepack menu and it works fine after leaving though the problem occurs, this is even if you stay with the default textures.

**Comment by mysticdrew** [comment]
Thanks for the details! Likely something to do with our shaders and reloading them.

**Comment by mysticdrew** [comment]
Ha, so good news. Yesterday before you made this issue, I changed some or our shader logic and looks like it is fixed with those changes. 
The fix for this will be in beta.11 hopefully today I can release it.

**Comment by mysticdrew** [comment]
beta.11 is publishing right now with the fix.
