### ISSUE TITLE
[Bug]: Waypoints are not displayed.

### ISSUE THREAD

**Issue by YOMA8338** [TeamJM/journeymap#738]
### What happened?

I registered a waypoint, but it does not appear.
It does not seem that they are not registered.

### Mod Loader

Fabric

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

(In the process of being executed)
[latest.log](https://github.com/user-attachments/files/15994589/latest.log)

**Comment by mysticdrew** [comment]
Please provide your journeymap.log

**Comment by mysticdrew** [comment]
Also try right clicking on the map, select waypoints, then "Show All" do they appear?

**Comment by YOMA8338** [comment]
Not displayed

**Comment by YOMA8338** [comment]
I'll paste the one I'm starting up.
[journeymap.log](https://github.com/user-attachments/files/15996554/journeymap.log)

**Comment by mysticdrew** [comment]
` renderWaypoints=false`

delete the file
../minecraft/journeymap/config/6.0/journeymap.waypoint.confg

then restart minecraft.
