### ISSUE TITLE
[Crash]: When i lunch my survival game my game turn around 13fps

### ISSUE THREAD

**Issue by Pouletox** [TeamJM/journeymap#739]
### What happened?

A crash happened! I install your mod and after this my game lag (i have shaders and ressource pack) 

pls help

### Mod Loader

Forge

### Minecraft Version

1.20.1

### Version

6.0.0

**Comment by mysticdrew** [comment]
Provide logs

**Comment by mysticdrew** [comment]
- no logs provided. This issue will be closed in ~24 hours unless logs and more details are provided. 

./minecraft/journeymap/journeymap.log
./minecraft/logs/latest.log
./minecraft/crash-reports/crash.log

All three logs need to be provided. Thanks.
