### ISSUE TITLE
[Bug]: Waypoints don't show correctly while playing (Neoforge)

### ISSUE THREAD

**Issue by ThatElektrika** [TeamJM/journeymap#740]
### What happened?

It's hard to explain, this video should help.

https://github.com/TeamJM/journeymap/assets/74426302/cfcf3b15-4373-4d6a-81dd-64ece648eee6

### Mod Loader

NeoForge

### Minecraft Version

1.21.x

### Version

6.0.0

**Comment by mysticdrew** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/7976
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/7975
