### ISSUE TITLE
[Crash]: crashes at the moment the game starts

### ISSUE THREAD

**Issue by Lava-Erlow** [TeamJM/journeymap#741]
### What happened?

The game crashes at the moment of launch

### Mod Loader

Fabric

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

[journeymap.log](https://github.com/user-attachments/files/16030166/journeymap.log)
[latest.log](https://github.com/user-attachments/files/16030169/latest.log)
[crash-2024-06-28_16.14.14-client.txt](https://github.com/user-attachments/files/16030172/crash-2024-06-28_16.14.14-client.txt)

**Comment by mysticdrew** [comment]
It looks like journeymap is failing to generate the configs. 
Do you have a `journeymap/config/6.0/` folder? And are there files in that folder if you do? It generated the log in the journeymap folder. I wonder why the configs did not generate or became unreadable.

**Comment by Lava-Erlow** [comment]
i have journeymap/config/6.0/ folder, and i have files in that folder, the game crashes with beta-12, but does not crash with beta-10

**Comment by mysticdrew** [comment]
That is so strange, I did not touch the configs. 
Can you delete the config folder (it wont break your map) and see if that resolves it please?

**Comment by Lava-Erlow** [comment]
ok

**Comment by mysticdrew** [comment]
did the files generate? 
Can you provide the new logs after deleting the config files please? 
All three logs again.

**Comment by Lava-Erlow** [comment]
generate only journeymap.minimap.config
[journeymap.log](https://github.com/user-attachments/files/16031511/journeymap.log)
[latest.log](https://github.com/user-attachments/files/16031590/latest.log)
[crash-2024-06-28_17.08.51-client.txt](https://github.com/user-attachments/files/16031720/crash-2024-06-28_17.08.51-client.txt)

**Comment by mysticdrew** [comment]
are you able to come into our discord?

**Comment by Lava-Erlow** [comment]
Yep

**Comment by Lava-Erlow** [comment]
I came to your discord

**Comment by mysticdrew** [comment]
Fixed in beta.13

**Comment by HireSLH** [comment]
> Fixed in beta.13

Broken in beta 14
