### ISSUE TITLE
[Bug]: Journeymap is conflicting with Modnomicon

### ISSUE THREAD

**Issue by Kevin-Marsh** [TeamJM/journeymap#743]
### What happened?

Loading up Occultism and modnomicon with Journeymap breaks modnomicon rendering. This was determined to be due to modifications that journeymap is making to the posestack. Is there a conflict here which would need to be resolved by you or by Modnomicon?
https://github.com/klikli-dev/modonomicon/issues/230

### Mod Loader

NeoForge

### Minecraft Version

1.21.x

### Version

6.0.0

**Comment by unspunreality** [comment]
Just want to jump in and confirm this aswell. I use a data pack called Mine treasures and was trying to find out why Id use my entire graphical rendering, and what was happening was everything would then begin rendering in the mini map... for some reason. Figured I would just piggy back here cause there was no crash and it 'seems' like the same issue.

**Comment by mysticdrew** [comment]
> Just want to jump in and confirm this aswell. I use a data pack called Mine treasures and was trying to find out why Id use my entire graphical rendering, and what was happening was everything would then begin rendering in the mini map... for some reason. Figured I would just piggy back here cause there was no crash and it 'seems' like the same issue.

I commented on the issue linked on the technical problem. 
This will be fixed in the next beta.

**Comment by mysticdrew** [comment]
This is fixed for beta.14, we still have a few more issues to resolve before it gets released.

**Comment by mysticdrew** [comment]
1.21-6.0.0-beta.14 is publishing, should be available shortly
