### ISSUE TITLE
[Bug 1.21]: Always a small lag spike when entering a new / existing world or going through to another dimension.

### ISSUE THREAD

**Issue by Gbergz** [TeamJM/journeymap#744]
### What happened?

Everytime you enter a new / existing world, or going to another dimension like The Nether there's a small lag spike that occurs. Depending on PC specs the spike probably lasts longer.

The lag spike exists even with just NeoForge installed + Journeymap although smaller definitely noticable.
Going to a modpack though the lagspike is more noticable and can last 1-2s depending on pc specs.

Logs latest.log and journeymap.log pasted at the bottom.

Here's a spark client report from a modpack:
https://spark.lucko.me/Cje67yvoXv

Here's a spark report with just NeoForge and Journey Map:
https://spark.lucko.me/nve7n2fTdB

### Mod Loader

NeoForge

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

Latest.log: https://gist.githubusercontent.com/Gbergz/e98e1b8fc4568d5c2f8a4d65434f6958/raw/74cf1c0f5ea435894293333de3c6774cf659767c/gistfile1.txt

journeymap.log:
https://gist.githubusercontent.com/Gbergz/bb53ee689f9d30a1f65239d75f18ffc2/raw/5e15a2c77af83172533bb356dea93ce302b76e68/gistfile1.txt

**Comment by mysticdrew** [comment]
I don't see anything in the spark that would indicate an issue with journeymap. 

Have you tested with complete vanilla, and another test with only neoforge and no mods?

Keep in mind, when loading a world like joining a new world or dimension, minecraft has to load all the chunks in render range into memory. It takes a bit of time to do that.

**Comment by mysticdrew** [comment]
I do see some colorpalette methods that are probably a bit heavier than they should be

**Comment by Gbergz** [comment]
> I don't see anything in the spark that would indicate an issue with journeymap.
Have you tested with complete vanilla, and another test with only neoforge and no mods?
Keep in mind, when loading a world like joining a new world or dimension, minecraft has to load all the chunks in render range into memory. It takes a bit of time to do that.

Yes, tested just vanilla, and just neoforge no JMap, no lag spike anymore.

Removing the mod from modpack resolves the lag spike too.

**Comment by mysticdrew** [comment]
I see this. Probably the issue. Loading the colorpalette colors. 
![image](https://github.com/TeamJM/journeymap/assets/5459941/29c8b10d-2c8a-460d-ae14-00d7d741a3fa)
Probably the issue

**Comment by Gbergz** [comment]
Looks like it, yeah. Probably it

**Comment by mysticdrew** [comment]
I don't really notice it on my PC, can you come into our discord and we can get some test versions for you?

**Comment by Gbergz** [comment]
Sure I am already a member on there

**Comment by mysticdrew** [comment]
Make a support thread please, I'll be out when I get home, or meme will.

**Comment by Gbergz** [comment]
Gotcha, I opened one.

**Comment by mysticdrew** [comment]
This is fixed for beta.14, we still have a few more issues to resolve before it gets released.

**Comment by Gbergz** [comment]
Awesome, thanks. No worries!

**Comment by mysticdrew** [comment]
1.21-6.0.0-beta.14 is publishing, should be available shortly
