### ISSUE TITLE
[BUG]: issues when hiding buttons on fullscreen map.

### ISSUE THREAD

**Issue by Iker21dev** [TeamJM/journeymap#745]
### Describe the new feature.

Players like me sometimes just want a map as clean as possible, hiding the hud of buttons and info from the Fullscreen Map would be a very nice toggleable option via F1 to only appreciate the map of the explored world.

### Images

![f1](https://github.com/TeamJM/journeymap/assets/80030992/6369e1c4-1384-4dc8-8a63-490797c5f010)

**Comment by mysticdrew** [comment]
That already exists, check the key binds and set it to f1. It defaults to h in some versions, unbound in decent recent betas

**Comment by Iker21dev** [comment]
true, thank you very much, but I noticed that the mod icon is still in the corner (something minimal) but the bad thing is that I can't move on the map when I activate that option :'(

**Comment by mysticdrew** [comment]
Oh that's a bug, I'll reopen this toI know to address it.

**Comment by mysticdrew** [comment]
Hmm, I can drag the map just fine with the mouse when the buttons are hidden. So, not sure why you cannot.

I hid the logo though. This will be in 1.21-6.0.0-beta.14
