### ISSUE TITLE
[Feature Request]: separate the gui scale from the game and the mod

### ISSUE THREAD

**Issue by Iker21dev** [TeamJM/journeymap#746]
### Describe the new feature.

when I have the game's gui scale is large x4, the Fullscreen scacle gui is very large and covers a lot of the map and that is why I think it is better to separate the mod and game gui scale, especially from the Fullscreen map.

### Images

![image](https://github.com/TeamJM/journeymap/assets/80030992/f659b5b8-9805-4f8f-804f-d0f58d19ce9f)

**Comment by mysticdrew** [comment]
No can do

**Comment by mysticdrew** [comment]
Sorry, I was on my phone last night. Let me give a more detailed response to this now. 

While yes, I agree the buttons are very large and our UI seems very compact on GUI scale 4. This is how minecraft works. While gui scale 4 looks large for you, someone with a super large 4k monitor may need scale 4 to make the buttons large enough to be visible. 

Personally, I use gui scale 2 for my 1080p 25 inch monitors. 

Decoupling from gui scale would be a lot of work as so much is dependent on it, all the math for calculating where your mouse position is on the map would need to be adjusted. 

I will consider adding a custom journeymap specific scaling, as a lot of our UI looks terrible and is hard to use when on 4. This will only happen when I rewrite our options screen. I need to find a user friendly way to do it.
