### ISSUE TITLE
[Bug]: 1.21-6.0.0-beta.13 I just updated from 1.21-6.0.0-beta.12 but I can't see any sign of the mod in game.

### ISSUE THREAD

**Issue by Alexander-R-Z** [TeamJM/journeymap#747]
### What happened?

I just updated from version 1.21-6.0.0-beta.12 to 1.21-6.0.0-beta.13, but I can't find any trace of the mod in the game, even though it worked before. The game loads without any problems, but there's no indication of the mod being in the mods folder as far as I can tell.

### Mod Loader

Forge

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

[journeymap.log](https://github.com/user-attachments/files/16097404/journeymap.log)

[latest.log](https://github.com/user-attachments/files/16097406/latest.log)

**Comment by Alexander-R-Z** [comment]
I just looked at the logs and, as far as I can tell, there really is no sign of the mod being loaded. The mod is in the mod folder, and when I switch back to version 1.21-6.0.0-beta.12, everything works again.

**Comment by mysticdrew** [comment]
did you download the correct version 13 for your modloader?

**Comment by mysticdrew** [comment]
Looks like you're using fabric. You need `journeymap-fabric-1.21-6.0.0-beta.13.jar` fabric is in the name

**Comment by Alexander-R-Z** [comment]
Sorry, I did. I just didn't write out the full file name.

**Comment by Alexander-R-Z** [comment]
Well, it looks like I made a mistake. After re-downloading and trying again, the mod worked. Sorry for wasting your time.

**Comment by Alexander-R-Z** [comment]
How do I close this embarrassment?

**Comment by mysticdrew** [comment]
It happens ;)
