### ISSUE TITLE
[1.21]: Waypoints disappear

### ISSUE THREAD

**Issue by djnifos** [TeamJM/journeymap#749]
### What happened?

When changing dimensions waypoints disappear from the list.  They are repopulated from waystones on server start.  Happened on beta 13, and still happens on beta 14
Here's a video demonstration:
https://youtu.be/dRxcfZYVMYM

### Mod Loader

NeoForge

### Minecraft Version

1.21.x

### Version

6.0.0

**Comment by mysticdrew** [comment]
We need logs from the client. 
Journeymap.log and latest.log

**Comment by djnifos** [comment]
Latest - https://mclo.gs/tbsNa6q
JM - https://mclo.gs/C7IaGfl

**Comment by mysticdrew** [comment]
There are no errors or anything in your logs that would signify an issue. 
Is this only happening for you or for others on your server?

**Comment by djnifos** [comment]
It's just a personal server.  It's running on my pc.

**Comment by mysticdrew** [comment]
Okay, so I see that Waystones is not re-creating waypoints when switching dimensions. But the JourneyMap waypoints are staying. 
This is a waystones bug it seems. 
Am I correct that the waypoints that are disappearing are only waystones waypoints?

**Comment by mysticdrew** [comment]
If you activate a new waystone all the waypoints reappear. This issue needs to be reported to Blay09

**Comment by djnifos** [comment]
I lost the ones I had set manually within Journeymap at some point as well, but that may have been part of one of the updates. If I make one manually now and change dimensions it does not delete.

**Comment by mysticdrew** [comment]
They use our API here to create waypoints. 

https://github.com/TwelveIterationMods/Waystones/blob/687dded58b73e5f0eeb48ffdfc5c554d62185b8a/common/src/main/java/net/blay09/mods/waystones/compat/JourneyMapIntegration.java#L162

It is not a permanent waypoint by this false passed it. So it gets flushed from memory when you switch dimensions. 
non persistent waypoints are not saved to disk so they don't get reloaded when mapping starts in a new dimension.

**Comment by djnifos** [comment]
I passed it along, thank you for your help!
