### ISSUE TITLE
[Bug]: Waypoint beacons render in front of Distant Horizons LODs

### ISSUE THREAD

**Issue by johalun** [TeamJM/journeymap#751]
### What happened?

Just what the title says. The waypoint beacons render in front of Distant Horizons terrain, outside of vanilla render distance, but they render behind / obscured by terrain within vanilla render distance.

Journeymap 5.10

### Mod Loader

Forge

### Minecraft Version

1.20.1

### Version

other (please list)

**Comment by mysticdrew** [comment]
Not even a screen shot? Okay... 

Well anyways, journeymap is only being developed for 1.21+ so this won't be addressed or looked into. Journeymap 6.0.0 for 1.21+ is in active development. If it is an issue with that version it can get fixed.

**Comment by johalun** [comment]
Wow the manners... The bug report instructions didn't mention screenshots were required so no need to be rude to players who take the time out of their day to report bugs in order to help you improve the mod.

**Comment by mysticdrew** [comment]
Let's be honest here, you reported a visual bug but did not even show it. The bug report template shouldn't have to say show a screen shot of visual issues to show the dev what is going on. 
It doesn't really matter thought I guess, since I am no longer supporting mc 1.20.x anymore.
