### ISSUE TITLE
[1.21] [Bug]: Severe lag for some

### ISSUE THREAD

**Issue by NielsPilgaard** [TeamJM/journeymap#752]
### What happened?

One of our players was experiencing severe lag, ran a spark profile, and it pointed towards Journeymap being the culprit. 
Removing Journeymap alleviates the lag.

Original issue: https://github.com/EnigmaticaModpacks/Enigmatica10/issues/20

### Mod Loader

NeoForge

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

Spark profile: https://spark.lucko.me/4kEqk7gmBH

Latest.log: https://gist.github.com/NielsPilgaard/171c52dd933f07e6ef91cb1f0ad90560

Journeymap log: https://gist.github.com/NielsPilgaard/11c3f9226a11ba07af0c30d814bb75ac

Log appears to come from this code: https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/util/platform/windows/WmiQueryHandler.java#L140

**Comment by mysticdrew** [comment]
Looks like there is a lot of lag by `fpsreducer` lol 
![image](https://github.com/TeamJM/journeymap/assets/5459941/afaae029-de47-4144-ac6f-5f2c6c66c0ae)

**Comment by mysticdrew** [comment]
> Log appears to come from this code: https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/util/platform/windows/WmiQueryHandler.java#L140

I don't understand what this is in regards to? 

Also you should be on beta.14 as we did make some fairly significant performance improvements.

**Comment by NielsPilgaard** [comment]
> > Log appears to come from this code: https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/util/platform/windows/WmiQueryHandler.java#L140
> 
> I don't understand what this is in regards to?
> 
> Also you should be on beta.14 as we did make some fairly significant performance improvements.

I was guessing you used that library, thought a link to the source would save you some time.

Right, we have updated to beta.14. I'll ask the player to do the same.

**Comment by mysticdrew** [comment]
Nope, no idea what that's from, either mc or nf

**Comment by mysticdrew** [comment]
Looks like the lag is from log spam trying to register textures. Likely a mod interaction or somthing. But fpsreducer is taking the most rendering time, should try removing that.

**Comment by NielsPilgaard** [comment]
FPSReducer just decreases frames when the window is unfocused or paused, it shouldn't do anything during active play.

**Comment by mysticdrew** [comment]
> FPSReducer just decreases frames when the window is unfocused or paused, it shouldn't do anything during active play.

aah okay, it just has the most rendering time in the spark profile.

**Comment by NielsPilgaard** [comment]
That is a bit concerning, I'll keep my eye on it, thanks 😊

I've asked the player to update, we can hope that'll fix the texture registration issue.

**Comment by mysticdrew** [comment]
if not, let me know we can see if we can find a solution.

**Comment by NielsPilgaard** [comment]
Same issue I'm afraid, here are a bunch of new logs:
https://github.com/EnigmaticaModpacks/Enigmatica10/issues/20#issuecomment-2211847839

**Comment by mysticdrew** [comment]
1.21-6.0.0-beta.15
Is publishing with the fix.
However, we have to write some custom logic for the creeper reloaded mod to generate those icons, they do some funny stuff.

**Comment by NielsPilgaard** [comment]
Sounds good, thank you!
