### ISSUE TITLE
[Bug]: Blue blot where self should be

### ISSUE THREAD

**Issue by CookieStacks** [TeamJM/journeymap#753]
### What happened?

In the DawnCraft modpack, in the minimap and the fullscreen map, my own icon as a dot is just this large blue blot that restricts the direction indicator, making it harder for me to realize which direction I'm looking at and is also blocking a small portion of the minimap
![resim_2024-07-06_083826897](https://github.com/TeamJM/journeymap/assets/174854197/c64c3fcb-4a87-4e93-acb3-509c924a5b79)

### Mod Loader

Forge

### Minecraft Version

1.18.2

### Version

6.0.0

**Comment by mysticdrew** [comment]
Dawncraft does this intentionally.

**Comment by CookieStacks** [comment]
> Dawncraft does this intentionally.

Do you know why?

**Comment by CookieStacks** [comment]
Nevermind it seems I found the reason and changed it, it has something to do with the Dawncraft Resources resourcepack changing the icon, thanks for the info, cheers

**Comment by mysticdrew** [comment]
You world need to ask them, but probably to hide the players direction.

**Comment by eee19387338** [comment]
> Nevermind it seems I found the reason and changed it, it has something to do with the Dawncraft Resources resourcepack changing the icon, thanks for the info, cheers

what resource pack was it? cause i want to change it too

**Comment by CookieStacks** [comment]
Well sorry that I forgot, since it's been like 9 months since I fixed it. But I did kind of skim through the winrar files until I found a PNG icon or something called "mapicon" or along those lines. The file was the exact blue circle. The moment I deleted that image it just disappeared.
