### ISSUE TITLE
[Crash]: When launching the game

### ISSUE THREAD

**Issue by WingFrosty** [TeamJM/journeymap#755]
### What happened?

Updated to "journeymap-fabric-1.21-6.0.0-beta.14.jar" and after launching the game it crashes.

Everything works with "journeymap-fabric-1.21-6.0.0-beta.13.jar".

### Mod Loader

Fabric

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

[crash-2024-07-07_00.44.18-client.txt](https://github.com/user-attachments/files/16117627/crash-2024-07-07_00.44.18-client.txt)

**Comment by mysticdrew** [comment]
This is due to remove reloading screen. I have this fixed for the next release

**Comment by mysticdrew** [comment]
1.21-6.0.0-beta.15 with the fix is publishing, should be available in the next 30 minutes
