### ISSUE TITLE
[Feature Request]: icons options

### ISSUE THREAD

**Issue by cauamachado51** [TeamJM/journeymap#756]
### Describe the new feature.

Minecraft 1.20.1, JourneyMap 5.9.23, ATM9 0.2.61.
### Describe the new feature.

https://github.com/TeamJM/journeymap/assets/132782265/634917d1-a333-4568-849d-ee5d83ed1ab9

As you can see above, Xaero's Map has much better icons than JourneyMap, I wanted to request some very simple options, for JM 1.20.1, because of ATM9, (in my mind it seems easy) to improve JM:

1. Turn off dynamic opacity by height, the icons will always have 100% opacity.

on the left a zombie is easy to see, on the right a difficult one.

![Captura de Tela (9)](https://github.com/TeamJM/journeymap/assets/132782265/0f118409-1aaa-4b4d-89a4-e214acbe3268)

2. turn off dots if there is an icon.

on the left the dot, on the right the dot disturbing the icon.

![dot e dot atrapalhando](https://github.com/TeamJM/journeymap/assets/132782265/b83879d3-7257-419c-8a9d-76ef7bf02f49)

3. (I confess that this seems a little complicated) icon size varies via png resolution, for example, in the video and in the previous image it shows a warped forest enderman which in JM is small because it has a plume on its head that takes up part From the fixed size that all icons are submitted, by having the size according to the png resolution, I could increase the png resolution and resize the layer to be a good size in the game.

**Comment by mysticdrew** [comment]
First, 1.20.1 development has ended. I am only developing for 1.21 and beyond now. 

>1. Turn off dynamic opacity by height, the icons will always have 100% opacity.

I can add a setting for this and plan to in 1.21 versions.

>2. Turn off dots if there is an icon.

You can do this in the settings. In 1.21-6.0.0 icons are the default now.

>3. (I confess that this seems a little complicated) icon size varies via png resolution, for example, in the video and in the previous image it shows a warped forest enderman which in JM is small because it has a plume on its head that takes up part From the fixed size that all icons are submitted, by having the size according to the png resolution, I could increase the png resolution and resize the layer to be a good size in the game.

You can change the size your self in the options.
![java_o0aoluqoCY](https://github.com/TeamJM/journeymap/assets/5459941/968d0afb-a2d6-4c46-ad0c-85e2a64765c6)

If you want better icons, use a resource pack. 
https://teamjm.github.io/journeymap-docs/latest/Tools%20and%20Customisation/custom-mob-icons/

Seems most of your issues are addressed already. The only outstanding one is the vertical fading which is on the list of options to add in v6.

**Comment by cauamachado51** [comment]
Thanks for the quick response.

> You can do this in the settings. In 1.21-6.0.0 icons are the default now.
 
> You can change the size your self in the options. ![java_o0aoluqoCY](https://private-user-images.githubusercontent.com/5459941/346360351-968d0afb-a2d6-4c46-ad0c-85e2a64765c6.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzOTMzOTIsIm5iZiI6MTcyMDM5MzA5MiwicGF0aCI6Ii81NDU5OTQxLzM0NjM2MDM1MS05NjhkMGFmYi1hMmQ2LTRjNDYtYWQwYy04NWUyYTY0NzY1YzYuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDdUMjI1ODEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2MwNGEwMmQ4ZTg4ZmNjODA5MjMwNDM3YmFkNjRlYzBjMDkzZTMxN2I5MTE5MWYzODQ0YmEwMmU5ZTQzOWIxOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CSqPl37FSsY818UWTajZBtEF75e4c5qDQIGoG-8vtD0)

I mean that small resource pack icons for mods with new mobs must have some way of making them bigger without making others bigger, because several represent mobs with horns/feathers on their heads or are flat, making their icon small. But forget it, I'll make my package however I can, if necessary I'll cut off some of the horns/feathers.

**Comment by mysticdrew** [comment]
Yea, they probably provided larger images. 

In 1.21-6.0.0 we generate icons from the models and they look really nice.
