### ISSUE TITLE
[Bug]: Cherry Blossom Leaves render as green

### ISSUE THREAD

**Issue by BenVlodgi** [TeamJM/journeymap#757]
### What happened?

`cherry_leaves` render as green.
Using default Color Palette, which indicates that these should be pink.

![image](https://github.com/TeamJM/journeymap/assets/1462374/70583089-9f58-4bae-8c26-421264f73329)

### Mod Loader

Fabric

### Minecraft Version

1.21.x

### Version

6.0.0

**Comment by mysticdrew** [comment]
This was fixed for an early beta, update

**Comment by BenVlodgi** [comment]
Yes, My mistake, I was on beta 8.
