### ISSUE TITLE
[Bug]: Waypoints can not be removed via API after rejoining world

### ISSUE THREAD

**Issue by BlayTheNinth** [TeamJM/journeymap#758]
### What happened?

`removeWaypoint` seems to have no effect when calling it after leaving and rejoining the world. 

Both `getWaypoint` and `getWaypoints` still show the same instance existing and the waypoint also remains ingame.

![image](https://github.com/TeamJM/journeymap/assets/1933180/06d77b2d-6aa7-4911-8ab1-8df23eb82b8e)

### Mod Loader

Fabric

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

nothing odd in the log as far as I can tell - the three waypoints it loaded are two unrelated ones and then the one I'm trying to remove

[journeymap.log](https://github.com/user-attachments/files/16124828/journeymap.log)
[latest.log](https://github.com/user-attachments/files/16124852/latest.log)

**Comment by mysticdrew** [comment]
Did you switch these to persistent waypoints?

**Comment by BlayTheNinth** [comment]
Yes. https://github.com/TwelveIterationMods/Waystones/commit/83fa978b38e2e838136e2a415bd51881899d0aa1#diff-4c061dc10ebb2cdf1e3e7ca41daf1ed1edbeb68fd7483834a4b4ccfd5327ddb5R194 

The issue happens both when rejoining directly or when restarting Minecraft.

**Comment by mysticdrew** [comment]
forgot to close this, this has been fixed
