### ISSUE TITLE
[Bug]: Sometimes when holding TAB to see mob icons it renders the HUD totally invisible except hotbar.

### ISSUE THREAD

**Issue by Gbergz** [TeamJM/journeymap#759]
### What happened?

When holding TAB to see mob icons it sometimes renders the HUD totally invisible except for the hotbar.

This makes the chat among other elements also invisible until it randomly pops back.

Journey map log has errors in it, and is posted below. Latest.log looks normal.

Error:
`[Render thread/ERROR] [JMLogger] java.lang.NullPointerException: Cannot invoke "com.mojang.blaze3d.platform.NativeImage.getWidth()" because the return value of "net.minecraft.client.renderer.texture.DynamicTexture.getPixels()" is null`

Image:
![ss](https://github.com/TeamJM/journeymap/assets/26634554/15cf7014-0328-4590-ad8e-a893e6eff9f1)

Video 1: (these shows it best)
https://streamable.com/t6c7vn

Video 2:
https://streamable.com/8vj93t

### Mod Loader

NeoForge

### Minecraft Version

1.21.x

### Version

6.0.0-beta.15

### Relevant log output

[journeymap.log](https://github.com/user-attachments/files/16133516/journeymap.log)
[latest.log](https://github.com/user-attachments/files/16133525/latest.log)

### Edit
Edit: I'm aware I am on Beta10, but now I also tested latest version beta15, same issue persists there.

**Comment by mysticdrew** [comment]
This was fixed in beta.16, icon issues for these are still not generating correctly, but the main issue is resolved

**Comment by Gbergz** [comment]
Awesome, thanks again!
