### ISSUE TITLE
[1.12.2] Auto-map is taking longer and longer to complete

### ISSUE THREAD

**Issue by ghost** [TeamJM/journeymap#76]
#### JourneyMap Version: 

1.12.2-5.5.2

#### Forge Version:

1.12.2-14.23.5.2768

#### Describe the problem in repeatable steps:

1. Open JourneyMap.
2. Do auto-mappings.
3. After each auto-mapping, it's going to take longer to complete the next one.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

None

![pleh](https://user-images.githubusercontent.com/44909912/48317204-c3c40b80-e5d5-11e8-8c83-10b585925626.PNG)

**Comment by BrainStone** [comment]
Just to clearify you mean that the delay between the update messages takes longer and longer each time?

If you have more RAM available could you try to increase the RAM and see if it happens then as well?
