### ISSUE TITLE
[Feature Request]: Add a name variable in the custom TP for servers with /home plugins

### ISSUE THREAD

**Issue by devonkel4** [TeamJM/journeymap#761]
### Describe the new feature.

Several servers let you create multiple homes, it would be neat to add a name variable to the custom teleport command area that puts the name of the selected waypoint into the command.

An example of calling this would be /home {waypoint} turning into /home beach

**Comment by mysticdrew** [comment]
added for next beta release

**Comment by devonkel4** [comment]
I see the keyword is saved as {name} but doesn't this conflict with {name} for player name?

**Comment by devonkel4** [comment]
Upon testing, player name will supersede this addition

**Comment by mysticdrew** [comment]
you're correct.
Next update it will be {wpname}
