### ISSUE TITLE
[Feature Request]: Sub-palettes for grass block by biome type

### ISSUE THREAD

**Issue by TsengFayt** [TeamJM/journeymap#763]
### Describe the new feature.

`Suggestion` | `Feature Request` | `Palette` 
## Overview
> Currently, the color for grass blocks is set by default and changing the grass block color in palettes changes all grass blocks to match the selected color, regardless of biome.

## Suggestion
> Allow for sub-palettes per biome to be selected. This way you can change the hue/color of each biomes base grass color individually.

**Comment by mysticdrew** [comment]
This has been added to the color palette screen, switch blocks to biomes. 
In 1.21-6.0.0-beta.19
