### ISSUE TITLE
[Feature Request]: Filter/Cull Minimap Waypoints by Distance to Player

### ISSUE THREAD

**Issue by PieceMaker085** [TeamJM/journeymap#765]
### Describe the new feature.

I would find it useful to be able to filter/cull waypoints from the minimap based on a specific distance to the player.
This could help in two ways:

- To improve performance.
- To make it easier to only see relevant waypoints in your minimap.

When there are thousand or more Waypoints on your map things start to become a bit crowded. I tend to mark things of interest as I explore. On a top tier hardware you really don't notice any performance issue related to Journeymap, even with up to a thousand waypoints. But when I played the same server with the same config on my old computer I noticed a significant drop in framerate that wasn't related to shaders or anything else I toggled. I then realized that the sole issue was all the waypoints in the minimap.

With waypoints enabled I get around 20fps, while disabled I get around 60fps.

That's when I thought I usually only need to see the waypoints that are closest to me within a reasonable distance, and not so much the waypoints that are completely on the other side of the world. Being able to filter/cull waypoints based on the distance to the player could perhaps provide performance boost as well as remove clutter from the edge of your minimap.

### Images

![javaw_SDkcoXYg1B](https://github.com/user-attachments/assets/d47dff72-01c7-4404-92a6-db0e2e78d10e)

**Comment by mysticdrew** [comment]
![image](https://github.com/user-attachments/assets/be54f4b5-e043-4594-b2e5-96e711a14f87)
Can confirm, it does effect minimap and in game rendering of waypoints. (however they do all show on the fullscreen map still)

Closing as complete
