### ISSUE TITLE
[Bug]: Incorrect minimap box 

### ISSUE THREAD

**Issue by TQCnoARosto** [TeamJM/journeymap#766]
### What happened?

While in standard resolution (800x600 or so) map box pushes active effects correctly to the right.
![image](https://github.com/user-attachments/assets/a57ea18b-18e1-4c4f-9eca-0ac63e54495d)

Once the window enlarged or fullscreen, the map get bigger but the active effects are not moved correctly.
![image](https://github.com/user-attachments/assets/a040677a-b051-4ffb-a780-806d311269c5)

### Mod Loader

Fabric

### Minecraft Version

1.21.x

### Version

6.0.0

**Comment by mysticdrew** [comment]
This is a known issue, you'll need to go to the minimap position settings and manually move the effects for now.

**Comment by mysticdrew** [comment]
Fixed for next beta
