### ISSUE TITLE
[Bug]: [1.21] the map does not switch to cave mode in the overworld

### ISSUE THREAD

**Issue by OPkokakola** [TeamJM/journeymap#767]
### What happened?

the map does not switch to cave mode in the overworld and if you change the map type, then when switching to auto the same map type remains (all settings are default, except for font size)

and one more thing, the glow from luminous blocks on the map (in the overworld and nether) is not displayed, with the exception of lava and, apparently, fire

![2024-07-23_13 02 56](https://github.com/user-attachments/assets/fd40e7ed-dfc0-4c12-a437-05c89f8f28f9)

### Mod Loader

Fabric

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

[journeymap.log](https://github.com/user-attachments/files/16346449/journeymap.log)
[latest.log](https://github.com/user-attachments/files/16346450/latest.log)

**Comment by mysticdrew** [comment]
That's is cave mode, but high surface cave mode.

You can make it but show the surface in the cartography setting, uncheck always show surface. 

What luminous blocks

**Comment by OPkokakola** [comment]
either I don’t see it, or there is no “always show surface” function in cartography, perhaps “always map surface”, but it is disabled

luminous like torch, lanterns, shroomlight

**Comment by mysticdrew** [comment]
Oh, sorry it is show surface above caves. 
![image](https://github.com/user-attachments/assets/7f840a4d-2413-4bf7-8d6b-508c7d3cb577)
on
![image](https://github.com/user-attachments/assets/b8b75398-9554-470c-a90e-e5a374e9fe53)
off
![image](https://github.com/user-attachments/assets/3c825d11-47c7-44d5-bd87-2dd02ff2a89e)

torch lights show up
![image](https://github.com/user-attachments/assets/6c847e69-44cd-4b77-8693-b4d0c89eeeb8)

Shroom light
![image](https://github.com/user-attachments/assets/a54f0b7a-04f0-4cf1-a2f5-c84babf403dd)
lantern
![image](https://github.com/user-attachments/assets/be2865ad-4484-4df2-b637-94681aa83617)

**Comment by mysticdrew** [comment]
I think this can be closed now.

**Comment by OPkokakola** [comment]
I turned off “show surface above caves”, but it still didn’t help, besides, you can see that the image on the map is different, in my case the map thinks that I’m on the surface

![2024-07-23_16 01 35](https://github.com/user-attachments/assets/1725c62e-8c6e-4150-b0d4-1b5194b35934)

and this is what my luminous blocks look like, they just don’t emit light


![2024-07-23_15 57 10](https://github.com/user-attachments/assets/d6b4a194-9965-44c6-86c5-3ea87fa2a9a4)
![2024-07-23_16 00 41](https://github.com/user-attachments/assets/4d379578-c3fe-4a66-8df1-02267bf23156)

**Comment by mysticdrew** [comment]
> I turned off “show surface above caves”, but it still didn’t help, besides, you can see that the image on the map is different, in my case the map thinks that I’m on the surface

That looks like night map, how far under the surface are you? There is a block threshold before it flips to cave mod. It is adjustable in cartography settings. Or manually switch it with the `[` key.

**Comment by mysticdrew** [comment]
![image](https://github.com/user-attachments/assets/6cc850c7-5e37-488c-a219-07d287e4c8c3)

**Comment by mysticdrew** [comment]
is it maybe an issue with your texture pack and lighting?

**Comment by mysticdrew** [comment]
![image](https://github.com/user-attachments/assets/7bc41473-ffa1-4b8e-b91e-b1d7787b35af)

**Comment by OPkokakola** [comment]
I looked at all my mods and it turned out that the problem was with "Methane", although everything worked fine on 1.20.1
anyway, thanks for your help

**Comment by mysticdrew** [comment]
Interesting, I'll look into that mod. Thanks
