### ISSUE TITLE
[Bug]: Deleting waypoints does not delete the beam

### ISSUE THREAD

**Issue by SirTwsted** [TeamJM/journeymap#768]
### What happened?

[Issue]:
On death or creating then deleting a waypoint marker, For some odd reason, does not visually delete the beam.
A beam remains even when there are no waypoints on the location any longer.

[Expect]: 
the waypoint and beams along with any remains of the waypoint to be complete gone and not visible.

[Explanation]:
Many times when a mob kills me and I respawn, When I delete the death waypoint marker, 
I can still see the waypoint and marker beam even though it's been deleted.
I now have 20 death markers beams all over the world.   When I reboot, the waypoint beams still remains even when deleted.

### Mod Loader

NeoForge

### Minecraft Version

1.21.x

### Version

6.0.0

**Comment by mysticdrew** [comment]
These are probably FTBChunks deathpoints.

**Comment by SirTwsted** [comment]
This is a death waypoint that when deleted doesn't go away.

![2024-07-24_12 18 01](https://github.com/user-attachments/assets/41bca7f1-b896-4c08-827c-78e99fa0311a)

And there is no death point in the list of waypoint manager.  🤷‍♀️
I will investigate the FTB Chunks to see if that's the cause as you mentioned  😉👍

**Comment by mysticdrew** [comment]
That is not a journeymap waypoint. Likely FTBChunks or another mod adding.
