### ISSUE TITLE
[Feature Request] Dropddown menu for dimension selector on waypoints list

### ISSUE THREAD

**Issue by PurpleHel** [TeamJM/journeymap#77]
When looking at the waypoint manager, to change dimensions you have to click the dimension button again and again. For those of us on modpacks with lots of dimensions (Galacticraft with more planets and more planets extras, for example), this can be a *long* list. It would be a lot easier if instead of clicking until the list shows the chosen dimension, clicking brought up a dropdown list of all dimensions, and one could then just choose the desired dimension.

**Comment by zhukant** [comment]
I second this feature 100%. It takes me a very long time to find the right dimension in my Project Ozone 3 server and since they are always changing in quantity I often over-click and have to cycle through them all over again. Thank you!

**Comment by mysticdrew** [comment]
Currently you can right click to go forward through the list, left click to go backwards through the list. 
It will stay like this for the time being until we redo the waypoint manager screen. Drop downs are not simple.

**Comment by mysticdrew** [comment]
While this is an older ticket, I currently need some testers for this feature. For 1.16.5(it will not be back ported) drop a message in the #discussions channel in our discord. Do not ping about it. 
https://twitter.com/mysticdrew_/status/1409577963234934788/

**Comment by mysticdrew** [comment]
Meh, it is on curseforge now. 
5.7.2 beta15
