### ISSUE TITLE
[Crash]: when trying to make a waypoint [1.21]

### ISSUE THREAD

**Issue by AaronSzaboo** [TeamJM/journeymap#771]
### What happened?

I've had a crash when trying to make a waypoint, in the All the Mods 10 modpack.  This was within a minute of generating the world, I've been trying to make a waypoint for my spawn location. Issue persisted when I relaunched the game and tried to make the same waypoint. The journeymap version is "journeymap-1.21-6.0.0-beta.19+neoforge".

### Mod Loader

NeoForge

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

[journeymap.log](https://github.com/user-attachments/files/16569403/journeymap.log)
[latest.log](https://github.com/user-attachments/files/16569404/latest.log)
[crash-2024-08-10_13.36.11-client.txt](https://github.com/user-attachments/files/16570275/crash-2024-08-10_13.36.11-client.txt)

**Comment by N0aW** [comment]
This also happened on Fabric 1.21 when I didn't have a waypoint group selected.

After the crash, I tried the same but put "Default" as the waypoint group, and it didn't crash in this case?

**Comment by mysticdrew** [comment]
Publishing beta.20 right now with the fix.
