### ISSUE TITLE
[Bug]: Memory Leak of Server

### ISSUE THREAD

**Issue by pietro-lopes** [TeamJM/journeymap#774]
### What happened?

There is a leak of Server on Journeymap instance

Join a game, leave to main menu and server is leaked.

### Mod Loader

NeoForge

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

![image](https://github.com/user-attachments/assets/64592db1-57b9-44b1-abe2-151fab0bb194)

**Comment by mysticdrew** [comment]
What is that image suppose to represent? I need a lot more details

**Comment by pietro-lopes** [comment]
This image is a heap dump when I'm at the main menu, after I joined a game and exited.
It is from Eclipse Memory Analyzer.

When we logout/exit to Main Menu some instances needs to be cleared in case you saved like Players, Levels, Server.

Here is Neoforge clearing server instance when server is closed/shutdown:
<https://github.com/neoforged/NeoForge/blob/fb8915b8c3bf3220b30d35089b89dcd6a1651f30/src/main/java/net/neoforged/neoforge/server/ServerLifecycleHooks.java#L128>

You should listen to `ServerStoppedEvent` and when it fires you clean your Journeymap instance

**Comment by mysticdrew** [comment]
There are no memory leaks, it is just maintaining the server properties which do not change per server instance. Everything else on the server is event driven and state is not maintained. JourneyMap on the server is very minimal.

**Comment by mysticdrew** [comment]
It is cleaned up now for next beta release.
