### ISSUE TITLE
[Bug]: Player dont disappear on map after changing server

### ISSUE THREAD

**Issue by Rozbiynk** [TeamJM/journeymap#775]
### What happened?

If journeymap installed on server and "Expanded radar" is enabled, player dont disappear from mini and world map
before changing server
![2024-08-23_15 21 35](https://github.com/user-attachments/assets/94b026c4-307d-4efb-a8a4-7426e7070232)
after
![изображение](https://github.com/user-attachments/assets/c0e61e94-7ce7-4233-b26b-c105cca57ffa)
also same applies when YOU change dimension, you see player position on other server

### Mod Loader

Fabric

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

latest.log https://mclo.gs/R8S3tgJ
journeymap.log https://mclo.gs/WovDY0V

**Comment by mysticdrew** [comment]
Did that player go through the portal to another dimension or log off the server?

If they went through the portal, what mod adds those portals and how do I set them up?

**Comment by Rozbiynk** [comment]
same applies when you change server with command /server, this mod just make that player dont have acce for it directly

**Comment by mysticdrew** [comment]
there is no vanilla /server command. What mod adds it?

**Comment by Rozbiynk** [comment]
its command from proxy, we use Velocity for that

**Comment by Rozbiynk** [comment]
ill write steps here
1. Install velocity
2. setup two fabric servers into 1 network (using fabric proxy lite)
3. install journeymap on that servers
4. You and 1 other player join same server
5. type /server world2 (or name of your second world)
6. see that other player dont disappear from map

**Comment by mysticdrew** [comment]
This should be fixed with the next beta release.

**Comment by Rozbiynk** [comment]
tysm
