### ISSUE TITLE
[Feature Request]: move info slots

### ISSUE THREAD

**Issue by IMrCreepyI** [TeamJM/journeymap#776]
### Describe the new feature.

the ability to move the info slots to be under the minimap, above the minimap, custom or default
the feature could for example be placed in the same menu where you change the position of the minimap

**Comment by mysticdrew** [comment]
TA-DA!
next beta release will have it.
![image](https://github.com/user-attachments/assets/98204265-fe14-4fe0-a325-41f4d801488d)

**Comment by mysticdrew** [comment]
Eh, these are going to be moved the normal minimap options, I don't like them in the position options.
