### ISSUE TITLE
[Bug]: Journeymap key-binds cancel out held movement keys

### ISSUE THREAD

**Issue by FoilGear** [TeamJM/journeymap#777]
### What happened?

(Minecraft 1.21, Fabric 0.16.2, Journeymap 6.0.0-beta.20
Tested with only the fabric API, fabric language kotlin, and journeymap itself)
Walking (WASD) without releasing the keys you are holding, and then interacting with the minimap by zooming in, zooming out, changing the minimap display type, toggling the minimap or waypoint visibility, will cancel the held-state of the movement key-binds the player is holding at that moment.
Previous versions did not do this. (checked 1.20.4 for comparison, likely works on .5 and .6)
Not a game breaker but significant annoyance.

### Mod Loader

Fabric

### Minecraft Version

1.21.x

### Version

6.0.0

**Comment by mysticdrew** [comment]
I think I know the issue, a recent change I did to try to fix another issue, but that is already reverted for the next build. 
I will test my current indev build later and update you.

**Comment by mysticdrew** [comment]
Ahh yup, this is no longer an issue as was fixed indev already. Beta.21 will have the fix when it is released
