### ISSUE TITLE
[Crash]: Journeymap crash with Flashback replays

### ISSUE THREAD

**Issue by Iautner** [TeamJM/journeymap#778]
### What happened?

The game crashes when a replay recording is opened when journeymap-fabric-1.21-6.0.0-beta.20 is installed!
When Journeymap is removed, it works fine. It reaches the loading screen, increases to 100%, and then crashes with the attached error.
I'm not sure if it can fixed by @Moulberry

### Mod Loader

Fabric

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

[journeymap.log](https://github.com/user-attachments/files/16756962/journeymap.log)
[latest.log](https://github.com/user-attachments/files/16756965/latest.log)
[crash-2024-08-26_22.24.14-server.txt](https://github.com/user-attachments/files/16756967/crash-2024-08-26_22.24.14-server.txt)

**Comment by mysticdrew** [comment]
If band-aid fixed this on my end. Though, I think Flashblack needs to fire the proper events when loading servers that fabric fires or there will be a lot of other mod incompatibilities for them in the future.

**Comment by VenomousSteam81** [comment]
Was this ever fixed? I'm encountering a crash now https://mclo.gs/TrHqn4a

**Comment by mysticdrew** [comment]
Create a new issue
