### ISSUE TITLE
[1.12.2]  Constant lag spikes while running Journeymap

### ISSUE THREAD

**Issue by darthvader45** [TeamJM/journeymap#78]
#### JourneyMap Version: 1.12.2-5.5.2

`Example: 1.12.1-5.5.0`

#### Forge Version:14.23.5.2772

`Example: 1.12.1-14.22.1.2478`

#### Describe the problem in repeatable steps:

1.  Load up Minecraft.
2.  Start a world.
3.  Press Alt-F3 to see the framerate chart.

**Comment by mysticdrew** [comment]
Closing, not enough information.
