### ISSUE TITLE
[Crash][1.21.1][Fabric]: Crash upon opening waypoint manager

### ISSUE THREAD

**Issue by DisdainofDeimos** [TeamJM/journeymap#780]
### What happened?

After setting up waypoint groups and color schemes (using forced color override feature for grouping), the game now crashes upon opening the waypoint manager screen. This is replicate-able from both the waypoint manager hotkey, and the waypoint manager button in the fullscreen map. Crash report with mod list [link](https://pastebin.com/Vi7QxGXn)

Seems to be a problem with the getColor being = null, I am unsure as to the reason for this.

### Mod Loader

Fabric

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

[crash-2024-08-30_14.46.22-client.txt](https://github.com/user-attachments/files/16822349/crash-2024-08-30_14.46.22-client.txt)
[journeymap.log](https://github.com/user-attachments/files/16822350/journeymap.log)
[latest.log](https://github.com/user-attachments/files/16822351/latest.log)

**Comment by mysticdrew** [comment]
aaah okay, likely because you didn't set a color when you saved a force override. I will get this fixed, thanks for the report. 
While testing this, looks like there is an issue with changing colors of a group too for some reason, it worked at one point. I guess I broke it somehow.

**Comment by mysticdrew** [comment]
if you want to pass me your waypointdata.dat file in here I can fix it quick for you so you can use your waypoint manager while I work on releasing a fix. 
it is located in `C:\Users\matta\AppData\Roaming\ModrinthApp\profiles\2024 - Alibrealm (3)\journeymap\data\mp\Squeak\waypoints\WaypointData.dat`
Just drop it in a response here.

**Comment by DisdainofDeimos** [comment]
Yeah I did some further testing just now, and the waypoint manager still works just fine in a fresh singleplayer world without any waypoints or groups, so your explanation seems to fit! Thanks for the quick response, here's that WaypointData file (it won't let me upload a .dat so I changed the file extension to .txt temporarily, I can also put a drive link if changing the file extension messes something up!)
[WaypointData.dat.txt](https://github.com/user-attachments/files/16822454/WaypointData.dat.txt)

Thanks again <3

**Comment by mysticdrew** [comment]
[WaypointData.dat.txt](https://github.com/user-attachments/files/16822489/WaypointData.dat.txt)
See if this works for you.

**Comment by DisdainofDeimos** [comment]
![image](https://github.com/user-attachments/assets/caa4ad73-62cf-4da7-898f-c459b71ecd41)
Were back in business!
Thanks so much for your time and for the personal fix <33
Love your work, thanks for everything you give the community!

**Comment by mysticdrew** [comment]
> ![image](https://private-user-images.githubusercontent.com/38119524/363355194-caa4ad73-62cf-4da7-898f-c459b71ecd41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwNTg4MDEsIm5iZiI6MTcyNTA1ODUwMSwicGF0aCI6Ii8zODExOTUyNC8zNjMzNTUxOTQtY2FhNGFkNzMtNjJjZi00ZGE3LTg5OGYtYzQ1OWI3MWVjZDQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDIyNTUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhNWRhODllOWRkZTlhYWQ1Y2Y2OTJhYTZjNzMyMjM1MmIyNzc5MzU3YmYyMzljZDU0MmMzMWIzNjA2MDcyZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FMkh8xGOcuuUWE9dqdqDE8c-5Dk60fWNlpl-PASgFbo) Were back in business! Thanks so much for your time and for the personal fix <33 Love your work, thanks for everything you give the community!

Awesome thanks! I will get this bug fix out tomorrow hopefully. 
Other than this issue, what are your thoughts on the new waypoint manager? 
Like it, love it, hate it? Improvements I can make?

**Comment by DisdainofDeimos** [comment]
I love it! It's great being able to have groupings although I would like to see a quick and easy button to instantly hide/show whole groups of waypoints at a time, and maybe expanding on the icon choices for both individual waypoints and groups? All-in-all you've made (IMO) the best Minecraft mapping mod for both casual and veteran/technical players, great stuff!

**Comment by mysticdrew** [comment]
> I love it! It's great being able to have groupings although I would like to see a quick and easy button to instantly hide/show whole groups of waypoints at a time, and maybe expanding on the icon choices for both individual waypoints and groups? All-in-all you've made (IMO) the best Minecraft mapping mod for both casual and veteran/technical players, great stuff!

Icons are coming for groups. 
So more icons can be added easily via resource packs. I only provided the default ones for now
Details on adding new icons via resource packs. (not documented yet)
https://github.com/TeamJM/journeymap-docs/issues/90

The group panel is getting a bit squished already, we are a bit limited on space, I cannot make it larger really because unlike you and I, many people still do not adjust their GUI scale. So I have to make it all fit in scale 4, which sucks. but I will see what I can do.

**Comment by mysticdrew** [comment]
![image](https://github.com/user-attachments/assets/b078e535-d4cf-4b95-bdb5-e74b23695bb2)
I was able to make it work :)

**Comment by DisdainofDeimos** [comment]
Awesome! That will be a really convenient feature to have especially on large / long playtime servers/worlds with lots of waypoints! Great stuff friend :)
