### ISSUE TITLE
[Feature Request]: Server setting for capping cave render distance separately from surface difference

### ISSUE THREAD

**Issue by von-get** [TeamJM/journeymap#782]
### Server setting for capping cave render distance separately from surface difference

In the client options, you can separate the maximum render distance for surface and caves, however there is only one option on the server that caps both.  I would like the option to cap cave render distance separately from surface distance.

I know it can be turned off, but I would like to be able to turn it on, and just lower the range.

**Comment by mysticdrew** [comment]
Good idea! 
Added for next beta release
