### ISSUE TITLE
[Bug]: Issue playing on realm server

### ISSUE THREAD

**Issue by drm31415** [TeamJM/journeymap#784]
### What happened?

Journeymap seems to randomly create new folders in .minecraft\journeymap\data\mp for the same server with slightly different names, some with spaces, some with ~ replacing the spaces, because of the new folders it loses waypoints.  

I tried to change it to use the IP but it seems like the IP changes, I tried to change it to support multi world but that didn't seem to matter.

With testing it seems like if i select the realm in the launcher it creates a file with ~ instead of a space(s), if I open the game and then select the realm in the game it uses space(s)

### Mod Loader

Fabric

### Minecraft Version

1.21.x

### Version

6.0.0

**Comment by mysticdrew** [comment]
Hmm, it should always replace spaces with ~. Can you share a screenshot of your mp folder please?

**Comment by mysticdrew** [comment]
I do not have a realms server to test with, so this might take a bit of back and forth to get this resolved. Might be faster if you can join our discord too.

**Comment by drm31415** [comment]
![image](https://github.com/user-attachments/assets/001e9c03-e732-4ce4-845d-ba518875e3f4)

**Comment by drm31415** [comment]
I ended up copying the folder, clearing out the original and so far with multiworld and ip turned off and only only joining the realm ingame and not via the launcher it has used "SamWich Gang" thru multiple restarts, I'm assuming that the launcher passes the realm as a commandline param and that is somehow altering the "name" that the mod sees for the server

**Comment by drm31415** [comment]
i can join discord if u want to send an invite link

**Comment by mysticdrew** [comment]
https://discord.gg/eP8gE69

**Comment by mysticdrew** [comment]
I think I may have found a solution/fix, but I cannot test it.

**Comment by mysticdrew** [comment]
this is fixed maybe for beta.23
please download and verify. Reopen if not fixed and we need to figure it out.

**Comment by drm31415** [comment]
I cleared the mp folder connected both ways and it use the same folder each time, looks fixed
