### ISSUE TITLE
game crashed | loading server.

### ISSUE THREAD

**Issue by SmartStreamLabs** [TeamJM/journeymap#785]
### What happened?

The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: 'int journeymap.client.ui.minimap.DisplayVars.getInfoLabelAreaHeight(net.minecraft.client.gui.Font, journeymap.client.ui.theme.Theme$LabelSpec, journeymap.client.ui.theme.ThemeLabelSource$InfoSlot[])'

### Mod Loader

NeoForge

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

https://gist.github.com/SmartStreamLabs/e78f47aec09d75c5a39edda27b16578e

**Comment by mysticdrew** [comment]
They were depending on a specific method in journeymap for integration, the recent beta for journeymap changed that method and thus breaking integration causing a crash. 
I created a detailed report for them on fixing it. 
https://github.com/IanMods/SeasonHUD/issues/111

**Comment by mysticdrew** [comment]
This is fixed with latest seasonhud
