### ISSUE TITLE
[Bug]: Crash after remove death waypoint

### ISSUE THREAD

**Issue by Rumaruka** [TeamJM/journeymap#786]
### What happened?

Crash in Client Side

### Mod Loader

NeoForge

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

[crash-2024-09-06_14.47.01-client.txt](https://github.com/user-attachments/files/16906072/crash-2024-09-06_14.47.01-client.txt)
[journeymap.log](https://github.com/user-attachments/files/16906078/journeymap.log)
[latest.log](https://github.com/user-attachments/files/16906082/latest.log)

**Comment by mysticdrew** [comment]
Thanks, I see what the issue is. 
Will be fixed for the next release. Are you playing Lan by chance?

**Comment by Rumaruka** [comment]
If you mean enable "Open for Lan" 
 yes, it's enabled

**Comment by mysticdrew** [comment]
Ahh okay, thanks. That is helpful, fix will hopefully be out today.

**Comment by mysticdrew** [comment]
journeymap 1.21-6.0.0-beta.24
