### ISSUE TITLE
[Bug]: Crash using Beta 23 on ATM10

### ISSUE THREAD

**Issue by djnifos** [TeamJM/journeymap#787]
### What happened?

Fails to boot, <html><body>

  | java.lang.NullPointerException: Cannot invoke "com.mojang.blaze3d.platform.NativeImage.getWidth()" because "this.pixels" is null
-- | --

</body>
</html>
Deleting the journeymap folder on the client sometimes helps, downgrading the mod to Beta 22 always helps.   I believe one of our users tried to tie this to the SeasonHUD mod, but we don't use that.  If it is another mod in question causing it, I'll be happy to cross post. 

### Mod Loader

NeoForge

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

https://mclo.gs/2kvVAe6
https://mclo.gs/NNPn9Nv

**Comment by mysticdrew** [comment]
I'm not seeing in the logs anything related to journeymap in the crash. 
SeasonHUD did have an issue, they fixed it here
https://github.com/IanMods/SeasonHUD/issues/111

**Comment by djnifos** [comment]
I have a hunch based on the git history, that it's related to the accessibility setting that removes background blur.  Many of us have toggled that in ATM10 due to an unrelated bug.   Is that helpful?

**Comment by mysticdrew** [comment]
Not really, nor do I see how that is an issue with Journeymap. I dont touch anything with background blur. 

So the game crashes with JM active, but runs fine without it?
There is likely a mod interaction issue here that we need to figure what mod combined with JM causes the crash. So I can figure out what is going on.

**Comment by mysticdrew** [comment]
journeymap 1.21-6.0.0-beta.24
