### ISSUE TITLE
[Bug]: Minimap flashing "1", main map forces centering on character location, journeymap not saving new map data.

### ISSUE THREAD

**Issue by cedarpools** [TeamJM/journeymap#788]
### What happened?

A bug happened!  The minimap is flashing "1" and the main map automatically recenters to where I'm located.  The follow button is grayed out.  This happened when I was moving the main map around, I may have clicked something (it sounded like I clicked something, but I don't know what) and now it's glitching. 

I opened a new world and journey map isn't loading new map.  Minimap and main map is all grayed out.  Minimap still flashing "1".   Tried to upload videos but the file sizes were too big so I uploaded them to imgur: https://imgur.com/a/1xHyqow

Probably unrelated, but I am also unable to edit waypoints.  I click edit, rename the waypoint, click save, and the new name was not saved.

### Mod Loader

Forge

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

[journeymap.log](https://github.com/user-attachments/files/16920177/journeymap.log)
[latest.log](https://github.com/user-attachments/files/16920178/latest.log)

**Comment by cedarpools** [comment]
This may also be helpful. 

<img width="584" alt="Screenshot 2024-09-07 at 5 08 21 PM" src="https://github.com/user-attachments/assets/d1d6f9f8-b967-4c33-b236-e78785668a19">

**Comment by mysticdrew** [comment]
invalid 
![image](https://github.com/user-attachments/assets/58124e9d-461b-461f-8f76-af0ea25aabbb)

**Comment by cedarpools** [comment]
I don't understand, why is it invalid?

**Comment by cedarpools** [comment]
Never mind, sorry, I will fix this.

**Comment by mysticdrew** [comment]
> This may also be helpful.
> 
> <img alt="Screenshot 2024-09-07 at 5 08 21 PM" width="584" src="https://private-user-images.githubusercontent.com/180797721/365406385-d1d6f9f8-b967-4c33-b236-e78785668a19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NTQ3NjAsIm5iZiI6MTcyNTc1NDQ2MCwicGF0aCI6Ii8xODA3OTc3MjEvMzY1NDA2Mzg1LWQxZDZmOWY4LWI5NjctNGMzMy1iMjM2LWU3ODc4NTY2OGExOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQwMDE0MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hM2JiZGE0MDZlMTc4M2FhOGJiOGNhY2Q0YWNiNWRhYTYxMWI1NDU4NDBkMzFkMTU5Y2ZhMTkyNjlhMDlhYWQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ko4gZnfpAl2jXPi2F7CtoFuNyp1MRpi6ObTMYJ9q9Bs">

update to the beta.24, which is the latest and see if the issue persists. 

If it does, get me a fresh journeymap.log, your current log does not even have you ingame. it resets when you start minecraft.

**Comment by cedarpools** [comment]
Am I at risk of losing my map data?  Should I backup before updating?

**Comment by mysticdrew** [comment]
> Am I at risk of losing my map data? Should I backup before updating?

no

**Comment by cedarpools** [comment]
Updated both forge and journey map to current versions.  Still experiencing the same issues. 

<img width="604" alt="Screenshot 2024-09-07 at 5 42 34 PM" src="https://github.com/user-attachments/assets/e1cfe754-cafe-480c-becc-919f6a8d67ea">
<img width="579" alt="Screenshot 2024-09-07 at 5 42 21 PM" src="https://github.com/user-attachments/assets/ae711a46-6c9e-4750-a675-e4a832401fc0">

**Comment by mysticdrew** [comment]
Log ?

**Comment by cedarpools** [comment]
[journeymap.log](https://github.com/user-attachments/files/16920257/journeymap.log)
[latest.log](https://github.com/user-attachments/files/16920258/latest.log)

**Comment by mysticdrew** [comment]
Oof okay, so for some reason you are in a state reset loop. Not sure why. 

Let's try this, in your journeymap folder is a config folder, delete only that folder. Then restart.

**Comment by cedarpools** [comment]
I deleted it while minecraft was still open and a new config folder was instantly created.  Closed out and reopened minecraft, still experiencing same issues.
[latest.log](https://github.com/user-attachments/files/16920273/latest.log)
[journeymap.log](https://github.com/user-attachments/files/16920275/journeymap.log)

**Comment by mysticdrew** [comment]
Oh okay exit minecraft then delete the configs. Then start it back up, looks like it saved it exactly as it was. 
Your mapping is disabled, the bottom right button on the fullscreen map. You could probably click that button too and it wills top doing the reset loop. 

That is somehow causing a reset loop I think, I will see if I can replicate it locally.

**Comment by mysticdrew** [comment]
![image](https://github.com/user-attachments/assets/cc2b7cc8-b9b0-4b31-8fe5-97a35fb9b7c1)
Yup, I can replicate it. Okay I will fix this.

**Comment by cedarpools** [comment]
Wonderful, all fixed on my end too!  Thank you for your help!  Also, the issue I was experiencing with not being able to edit way points I mentioned in the beginning appears to be fixed as well.

**Comment by mysticdrew** [comment]
> Wonderful, all fixed on my end too! Thank you for your help! Also, the issue I was experiencing with not being able to edit way points I mentioned in the beginning appears to be fixed as well.

Yea, that waypoint editing bug was fixed in beta.23. 
I have the bug with the state reset loop fixed now, thanks for reporting this. 
This will be fixed in beta.25 release.

**Comment by cedarpools** [comment]
Of course and thanks!

**Comment by mysticdrew** [comment]
Fix is released in beta 25
