### ISSUE TITLE
[Bug]: Animals continue to be displayed after disabling "Show Animals"

### ISSUE THREAD

**Issue by cedarpools** [TeamJM/journeymap#789]
### What happened?

Animals are shown by default in the minimap.  When I disable "Show Animals" they continue to be shown in the minimap.  This feature worked for beta.22 but doesn't appear to be functional in beta.24

### Mod Loader

Forge

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

[latest.log](https://github.com/user-attachments/files/16923374/latest.log)
[journeymap.log](https://github.com/user-attachments/files/16923365/journeymap.log)

**Comment by mysticdrew** [comment]
Interesting, i will look into it.

**Comment by mysticdrew** [comment]
![java_PU6vxk6yQL](https://github.com/user-attachments/assets/5d15ca5c-de28-48bf-a274-9780c3b237c9)
I am unable to replicate this. 
Are you sure you disabled them for the active preset you are using?

**Comment by mysticdrew** [comment]
I tested singleplayer and multiplayer. 

My suggestion is to delete your journeymap configs. 

Exit minecraft, delete the `./minecraft/journeymap/config` folder, then start minecraft up again. 

Maybe your configs are not getting updated due to corruption or something? I am not sure, so let's delete them and let journeymap create fresh default configs to see what happens.

**Comment by mysticdrew** [comment]
If that doesn't work, please come into our discord, might be easier for us to diagnose and fix the issue.  https://discord.gg/eP8gE69

**Comment by cedarpools** [comment]
I deleted the config folder and there was no change.  I changed the settings in the minimap options and that did work.  What I was doing before was toggling Show Animals on and off in the main map viewer. 

<img width="1352" alt="Screenshot 2024-09-10 at 2 07 39 PM" src="https://github.com/user-attachments/assets/7107eaff-5e7f-49a0-b9c6-50bf7c310487">

**Comment by mysticdrew** [comment]
Yea, so that button only effects the fullscreen map, not the minimaps.

**Comment by mysticdrew** [comment]
I will close this as it is not an issue. 
I do plan to add an option to link them eventually so that those buttons also work for the minimap.
