### ISSUE TITLE
[1.12.2] JourneyMap crash upon loading title screen.

### ISSUE THREAD

**Issue by flyingjose72** [TeamJM/journeymap#79]
#### JourneyMap Version:

JourneyMap 1.12.2-5.5.3

#### Forge Version:

Forge 14.23.5.2768

#### Describe the problem in repeatable steps:

1. Put latest journeymap in /.minecraft/mods/
2. Launch latest Minecraft Launcher, recommended Forge profile.
3. Title Screen crashes after about a second.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

[journeymap.log](https://github.com/TeamJM/journeymap/files/2646772/journeymap.log)

Here's the log, hopefully providing the whole log would be a better help.

**Comment by mysticdrew** [comment]
Update your java to the latest version. This is a java issue, not a journeymap issue. Forge requires specific java version.
