### ISSUE TITLE
[Feature Request]: Move, edit, or remove UI buttons from the full map

### ISSUE THREAD

**Issue by Bebrich** [TeamJM/journeymap#791]
### Describe the new feature.

It would be quite useful if one could modify the buttons to customize, or minimize the ui on the map. Maybe even move them between containers and edit the hierarchy, as if one is editing the html? That might be overkill though.

As big of a request this is, I myself would be quite content even if one can merely hide the visibility of these buttons, be it something one does with themes, or a simple config option.

### Images

![image](https://github.com/user-attachments/assets/765088ce-5bd6-4f09-9055-3b2f111b5683)
![image](https://github.com/user-attachments/assets/2ca678be-76bd-4916-a8b1-14e901f4e310)

**Comment by mysticdrew** [comment]
I am not going to add an html like system, that is a lot of work for very small use-case. 

I will likely start with a single Fullscreen option "Minimalize" or "Minimal UI" a long the lines. 
It will hide most of the buttons. 

Top will show `Day, Biome, Topo, and Cave` 
Bottom will be `Waypoints and Options`
Left will be `Follow`

**Comment by mysticdrew** [comment]
this is fixed in beta.26 which is released now on CF and MR I forgot to update this issue when I released it.
