### ISSUE TITLE
[Crash]: [1.21.1] NeoForge IllegalStateException: Accept exceeded fixed size of 1

### ISSUE THREAD

**Issue by Cyranos** [TeamJM/journeymap#793]
### What happened?

I was playing normally then died and upon respawn, I crashed shortly after

### Mod Loader

NeoForge

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

[Crash Log](https://mclo.gs/L0meQF0)
[Latest Log](https://mclo.gs/0jna51R)
[journeymap.log](https://github.com/user-attachments/files/17036234/journeymap.log)

**Comment by mysticdrew** [comment]
Interesting, thanks, did it work fine after you started it back up again?

**Comment by Cyranos** [comment]
Yea, I could load back in, and I had this crash one time before, but I haven't had it in a bit now.

**Comment by mysticdrew** [comment]
Okay, thanks. I will look into it.

**Comment by mysticdrew** [comment]
Should be fixed in beta.26. 

reopen if it happens again
