### ISSUE TITLE
[Bug]: Waypoint Beams continue to show, even when deleting the waypoint.

### ISSUE THREAD

**Issue by SirTwsted** [TeamJM/journeymap#794]
### What happened?

A bug happened! 

I don't know how else to explain it, but when I delete a waypoint, including death waypoints,
For some odd reason, "A BEAM" of that waypoint continues to show even though I deleted the waypoint.  🤷‍♀️

![2024-09-18_09 45 36](https://github.com/user-attachments/assets/dd69e70a-c13a-43bd-87dc-d7f069ed1245)

and 

![2024-09-18_11 18 33](https://github.com/user-attachments/assets/0adffda1-55d0-43d2-8ce3-cd9f3fae8a9c)

and 

![2024-09-18_15 11 09](https://github.com/user-attachments/assets/7e878a08-c684-4f55-a71c-547d39b0fe53)

I am using Minecraft v1.21.1 with NEOForge v21.1.54 and Journey Map v6.0.0-beta25
It's starting to ruin my world.  😳

### Mod Loader

NeoForge

### Minecraft Version

1.21.x

### Version

6.0.0

**Comment by mysticdrew** [comment]
that is not a journeymap waypoint.

**Comment by SirTwsted** [comment]
The ONLY map mod I have installed is Journey Map.
So I don't know what else is doing it.

**Comment by mysticdrew** [comment]
I have no idea, those are not journeymap waypoints beacons. 
Are they locations where you died?

**Comment by SirTwsted** [comment]
yes they are.  😳

**Comment by mysticdrew** [comment]
So some other mod you have must be creating them, it does not have to be a map mod, a gravestone mod possibly? They look like FTB Chunks beacons to me.

**Comment by SirTwsted** [comment]
Here is the response from FTB Team:

https://github.com/FTBTeam/FTB-Mods-Issues/issues/1350
