### ISSUE TITLE
[Bug]: Unexpected error crash

### ISSUE THREAD

**Issue by SirTwsted** [TeamJM/journeymap#795]
### What happened?

A bug happened!

huge game crash happened while I was mining.

![journey map crash](https://github.com/user-attachments/assets/4c586fa0-dcb3-43a9-a1f5-7eae63f3d562)

This is the crash report log:
https://pastebin.com/jz3MxK4S

### Mod Loader

NeoForge

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

[journeymap.log](https://github.com/user-attachments/files/17060139/journeymap.log)

**Comment by mysticdrew** [comment]
duplicate https://github.com/TeamJM/journeymap/issues/792
this will be fixed in the next release. 
Does this happen every time you start the game?

**Comment by SirTwsted** [comment]
I'll give an explanation.  I was playing a brand-new map that I started at 10pm,  got tired at 1:00 am stopped playing.
Enjoying my paid work 2 weeks vacation, I decided to play again the next morning. Played for like an hour went down to go mining after exploring immediate area,  When I got to a certain distance, BOOM crash happened.

And now every time I start the game, I get immediate crash with this.
That's what happened so far.  😳

**Comment by mysticdrew** [comment]
oh okay... come into our discord and i will give you a build with the fix

**Comment by SirTwsted** [comment]
ok,  thank you  🥰

**Comment by SirTwsted** [comment]
I am in there, don't know what room to go to.  🤔

**Comment by mysticdrew** [comment]
user ghosted, closing
