### ISSUE TITLE
[Bug]: Crashes when connecting to the server

### ISSUE THREAD

**Issue by ocformula** [TeamJM/journeymap#798]
### What happened?

A bug happened!

### Mod Loader

Fabric

### Minecraft Version

1.21.x

### Version

6.0.0

**Comment by mysticdrew** [comment]
Upload the log files, do not copy and paste please. 

Please provide crash log, your journeymap.log and latest.log.

**Comment by ocformula** [comment]
[crash-2024-09-20_21.08.12-client.txt](https://github.com/user-attachments/files/17075354/crash-2024-09-20_21.08.12-client.txt)
an error is caused on 'pufferfish 1.20.4' with velocity and viaversion

**Comment by mysticdrew** [comment]
journeymap on a 1.21 client will not work on a 1.20.4 server.

**Comment by mysticdrew** [comment]
You are using a 1.21.1 client, but jourenymap from the looks of it in your crash long a journeymap for an older version of minecraft. 
JourneyMap 5.10.0 will not work on 1.21.1. You need journeymap 6 for 1.21. 
![image](https://github.com/user-attachments/assets/0dc151de-98ff-42f1-aa89-e665cb4511a5)
