### ISSUE TITLE
[Mod Compatibility] Hardcore Revival

### ISSUE THREAD

**Issue by Jomik** [TeamJM/journeymap#8]
#### JourneyMap Version:

`journeymap-1.12.2-5.5.2`

#### Forge Version:

`1.12.2-forge1.12.2-14.23.0.2545`

#### Describe the problem in repeatable steps:
When you "finally" die from not being rescued, JourneyMap doesn't create any death waypoint.

1. Install JourneyMap and HardcoreRevival
2. Die
3. Give up
4. Observe that no waypoint has been created.

#### HardcoreRevival issue:
https://github.com/blay09/HardcoreRevival/issues/6

**Comment by blay09** [comment]
Fixed in Hardcore Revival 1.1.7
