### ISSUE TITLE
[Feature Request]: Lazily cache block colors instead of retrieving all models at once

### ISSUE THREAD

**Issue by embeddedt** [TeamJM/journeymap#800]
### Describe the new feature.

The latest version of JourneyMap for NeoForge on MC 1.21.1 appears to eagerly scan all block models to find blocks' sprites and pick a color for them when the client finishes loading.

My mod, [ModernFix](https://legacy.curseforge.com/minecraft/mc-mods/modernfix), provides an optional feature that will dynamically load/unload block models when they are needed. In many modpacks this can greatly reduce startup time and memory usage (1GB or more). However, since JourneyMap explicitly requests every model to be loaded at game startup, it defeats the purpose of this optimization. It would be great if your block color cache could be built lazily when a block is first rendered, as most blocks are unlikely to be rendered immediately when a player first joins a world. This would probably improve startup times without ModernFix as well as it likely takes a bit of time to build the cache for all blocks anyway.

I've attached a profiler screenshot showing the problematic stacktrace & time it took to load models.

### Images

![image](https://github.com/user-attachments/assets/1a8c2765-26e8-4c7a-bb31-fd9abb9edc93)

**Comment by mysticdrew** [comment]
So, the issue with this. We allow players to modify block colors. If we do not get all the blocks and their colors initially, players will not be able to modify the colors of the blocks until they are first loaded. Will think on this a bit.

**Comment by mysticdrew** [comment]
Thinking about it, maybe do lazy and provide a way in the palette screen for a user to collect all block colors on demand.

**Comment by wagyourtail** [comment]
you could also just make opening the palette screen force the loading/collection of all of them.

**Comment by mysticdrew** [comment]
This has been added for the next release. Will be out in a little bit. Please check it out and let me know if it works for you.
 beta.26 few more bugs to fix and I will release it, probably an hour from now

**Comment by mysticdrew** [comment]
@embeddedt did this work for you?

**Comment by embeddedt** [comment]
Seems to work fine. Thanks.
