### ISSUE TITLE
[1.20.1] Memory Leak

### ISSUE THREAD

**Issue by RicardoLera** [TeamJM/journeymap#801]
### What happened?

JourneyMap version: **5.10.2**

I'm playing a modpack, but I have reason to believe this is an issue with JourneyMap, please read the issue to the end before closing.

This issue seems related to #228 and #231 but those have been fixed in an earlier version.

The modpack I'm using is BM: Revelations II, which includes JourneyMap and [JourneyMap Integration](https://github.com/frank89722/JourneyMapIntegration). While playing, I experienced random crashes with no warning and I noticed I was running out of RAM. I also noticed my RAM would increase every time I opened JourneyMap or managed waypoints in it, and it would never drop. After turning off both mods, the problem subsided.

I ran another test, this time enabling **only JourneyMap and not Integration** (all other mods enabled) just in case the problem was in that mod. Below are the results.

Here are my specs for context:
Ubuntu 22.04 (Linux)
Maximum of **9.6** effective RAM
Min and max memory allocation for Java: 4096 MiB
PermGen: 128 MiB
Other arguments: `-XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M`
(memory leak persisted without extra arguments)

```
Time    Java RAM  System RAM  Event
11:09   0.0       2.1         Before running
11:11   5.1       7.3         Launch (offline), now on Title Screen
11:13   6.8       8.6         Load world, wait for fps to stabilize
11:16   6.9       8.7         Open JourneyMap, do nothing else
11:18   6.9       9.0         Walk around the map
11:20   7.3       9.5         Open JourneyMap, move the cursor, make a waypoint
11:21   0.0       2.1         Save and quit before I run out of ram
```

For comparison, here's a previous test done without either of the mods (all other mods enabled):
```
Time    Java  Event
12:34   5.1   Title Screen
12:37   6.5   Load world, stabilize
12:37   6.6   Go into nether, stabilize
12:52   6.7   Back from nether after exploring
13:44   6.9   Back home after exploring world a lot
16:06   6.8   Long time later
```

### Mod Loader

Forge

### Minecraft Version

1.20.1

### Version

other (please list)

### Relevant log output

Here are the logs for the most recent test (the first table). Crash log not included because I didn't let it crash
[journeymap.log](https://github.com/user-attachments/files/17132591/journeymap.log)
[latest.log](https://github.com/user-attachments/files/17132605/latest.log)

## Edit 1

(Thank you so much for the swift response, @mysticdrew!)

> How many waypoints do you have?

Currently 6, all in the overworld, not too far from each other

As instructed, I ran another test with Waypoints disabled. Railways doesn't seem to be included in this modpack. I left JourneyMap Integration disabled as well. This time I let it crash to see if the logs would show anything useful.

```
Time    Java RAM  System RAM  Event
12:14   0.0       2.4         Before running
12:16   5.1       6.8         Launch (offline), now on Title Screen
12:18   6.6       8.6         Load world, wait for fps to stabilize
12:19   6.6       8.7         Open JourneyMap, do nothing else
12:20   6.7       8.8         Walk around the map
12:21   7.1       9.4         Open JourneyMap, move the cursor
12:25   7.0       9.4         Wait a bit to see if ram drops
12:26   6.9       9.2         Remove a waypoint (5 total now)
12:27   6.9       9.2         Remove another one (4 total)
12:28   ?         ?           Attempt to cause crash by moving cursor around JourneyMap and zooming in and out (succeeded)
```

Here are the logs:
JourneyMap -> [journeymap.log](https://github.com/user-attachments/files/17134255/journeymap.log)
Minecraft -> [latest.log](https://github.com/user-attachments/files/17134264/latest.log)

I can't find any crash logs. Maybe they weren't made?

## Edit 2

I ran a couple more tests. To reduce ram usage, I turned off Chunk Data Caching, High Display Quality, and Always Map Surface. I also changed the min/max ram allocation for java to 2048 and removed the extra arguments again. @mysticdrew pointed out I was indeed using Railways (Create: Steam 'n Rails) so I disabled that too.

I ran multiple tests between each change, but I'll summarize: It seems Waystones is the cause of the leak.

The last test (Edit 1) showed how the ram managed to decrease a bit on its own, which never happened with Waystones on. Moving the map around and zooming in/out caused a memory peak which lead to the crash, so I remedied that with the changes I mentioned. Now, if I scroll far past the undiscovered map, there's still a small ram peak (~0.5 GiB) but it is gradually de-allocated after the map's position is reset. Disabling Railways didn't seem to change much.

This modpack is fairly small, and my game still runs well with these settings, so I think for now disabling Waystones fixes the issue. I might inform the developers about it, if it's not already a known issue.

Thank you for the help! I'll be closing this issue.

**Comment by mysticdrew** [comment]
How many waypoints do you have?

**Comment by mysticdrew** [comment]
also please run your test again with these two mods disabled. 
Found @Ljourneymap/client/api/ClientPlugin;: com.railwayteam.railways.compat.journeymap.RailwayMapPlugin
Found @Ljourneymap/client/api/ClientPlugin;: net.blay09.mods.waystones.compat.JourneyMapIntegration

Waystones and railways, they both hook into journeymap.

**Comment by mysticdrew** [comment]
`
[25Sep2024 12:15:30.005] [Worker-ResourceReload-2/INFO] [journeymap/]: Found @Ljourneymap/client/api/ClientPlugin;: com.railwayteam.railways.compat.journeymap.RailwayMapPlugin`

log shows this exists. 
looks like it is coming from create. 

So, next step are you able to replicate this in a brand new instance with only journeymap, no other mods?

**Comment by mysticdrew** [comment]
Why did you close this?

**Comment by mysticdrew** [comment]
Oh, I see the edit. Great, glad you figured out the cause
