### ISSUE TITLE
[Crash]: JourneyMap crashes the game if Moonrise is enabled

### ISSUE THREAD

**Issue by MVukanichh** [TeamJM/journeymap#802]
### What happened?

Game simply crashes when either loading an existing world or creating a new one after a few seconds, sometimes loading a chunk or two and other times not even one.
I thought that it had to do something with Terralith/Tectonic, because Antique Atlas shows nothing in the map while using those two world generation mods (Does not crash the game, the map is simply empty except for the player icon and waypoints/deathpoints), but even after disabling them it crashes, now not even loading the world, with the exact same error message in the console.
Deleting the config file from .../.minecraft/config did nothing and it crashed again.

### Mod Loader

Quilt

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

[journeymap.log](https://github.com/user-attachments/files/17175824/journeymap.log)

[latest.log](https://github.com/user-attachments/files/17175826/latest.log)

[crash-2024-09-28_20.18.26-server.txt](https://github.com/user-attachments/files/17175831/crash-2024-09-28_20.18.26-server.txt)

**Comment by mysticdrew** [comment]
Definitely a mod interaction issue, likely related to  Terralith/Tectonic. If you disabled those mods, does it fix the problem. Might need to recreate the issue in a brand new world to not break your current world, then remove those mods to see if it fixes it.

**Comment by mysticdrew** [comment]
If we can isolate which mods are causing the problem, I should be able to fix it.

**Comment by MVukanichh** [comment]
Disabling Terralith/Tectonic does nothing. Obviously I can't test it on the same world I play on, because it has been generated using those two mods, but same thing happens on a brand new world even with those two mods disabled.
I just remembered that I have a mod that ports some Paper patches, including a chunk system rewrite, it being [Moonrise](https://modrinth.com/mod/moonrise-opt), and after disabling it, the new world loads and no crashes happen.

**Comment by mysticdrew** [comment]
Great, thanks! That will give me something to look into. Might also want to report it to them too, just incase.

**Comment by MVukanichh** [comment]
> ...Since it is also breaking antique atlas

Moonrise is not breaking it actually. Terralith developer opened an issue on the Antique Atlas' github issues page, because somehow Antique Atlas is not recognizing fallbacks from Terralith.
Moonrise is only breaking Jurneymap, since Antique Atlas is working properly with it and without Terralith/Tectonic, and Xaero's is working with all three no problem.
I will report it to the Moonrise dev and will mention this issue so they can access the logs and comment on it.

**Comment by mysticdrew** [comment]
great, sounds good! Thanks for quickly finding the mod that is causing the issue.

**Comment by jpenilla** [comment]
This should be fixable by using an accessor for `getChunks` instead of the backing `visibleChunkMap` field, since Moonrise redirects this method to the new chunk system.
```java
  protected Iterable<ChunkHolder> getChunks() {
    return Iterables.unmodifiableIterable(this.visibleChunkMap.values());
  }
```

**Comment by mysticdrew** [comment]
> This should be fixable by using an accessor for `getChunks` instead of the backing `visibleChunkMap` field, since Moonrise redirects this method to the new chunk system.
> 
> ```java
>   protected Iterable<ChunkHolder> getChunks() {
>     return Iterables.unmodifiableIterable(this.visibleChunkMap.values());
>   }
> ```

ah, thanks! That fixed it, release will be out shortly
