### ISSUE TITLE
[Crash]: Jouneymap crashes after installing iris, sodium, indium. Exit code 255

### ISSUE THREAD

**Issue by cedarpools** [TeamJM/journeymap#803]
### What happened?

I was using journey map (beta 25 I think) with forge and it worked well.  I thought it would be fun to play with shaders so I removed forge journeymap from the mods folder and added iris, sodium, indium, distant horizons, and journeymap for distant horizons.  Got tons of errors, tried many different things and nothing worked reliably.  I removed all the mods from the mods folder, put back in journeymap for forge (beta 27) and rebooted forge. Now forge is crashing and getting errors.  This time, I got error 225 and it says: 

The game crashed whilst initializing game
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

<img width="690" alt="Screenshot 2024-10-04 at 9 40 35 PM" src="https://github.com/user-attachments/assets/625c8145-ee95-43ed-8c4e-786874a141fb">

[crash-2024-10-04_21.45.32-client copy.txt](https://github.com/user-attachments/files/17265183/crash-2024-10-04_21.45.32-client.copy.txt)

I think I also installed universal mods of iris and maybe a few others.  I didn't know what I was doing but it looks like the mods broke minecraft.  I don't mind doing a hard reset to minecraft and reinstalling everything, but I don't know how to do that. I would like to back up my journeymap data though... 

Is journey map compatible with shaders in fabric?  

### Mod Loader

Forge

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

[journeymap.log](https://github.com/user-attachments/files/17265190/journeymap.log)
[latest.log](https://github.com/user-attachments/files/17265192/latest.log)

**Comment by mysticdrew** [comment]
This is kind of confusing. You say forge and your mod list is fabric mods? Your logs show forge.

**Comment by mysticdrew** [comment]
Oh, you are using minecraft 1.20.6 and journeymap for 1.21/.1

1.21 mods will not work with 1.20.6
