### ISSUE TITLE
[Bug]: Mob/animal names not showing on map

### ISSUE THREAD

**Issue by IdkWhatNameThingyToPut** [TeamJM/journeymap#804]
### What happened?

I'm trying to figure out how to display the names of mobs, animals, etc on both the minimap and world map but I can't get any names showing. I see in "options" there is an option called "Show Entity Names" and it's ticked but nothing happens I don't actually understand what this does because it seems nothing is happening with it enabled, when I hover over it some text appears "Show names of pets, NPCs, etc. on the map" but I don't see any names anywhere. I just want to add on to this that if showing mob names and animal names isn't a feature on this specific version then could you please update it and make that a thing because 1.12.2 is still a really good minecraft version to mod with some of the most popular mods/modpacks even right now being played on it like RLCraft and stuff so I don't understand why that minecraft version would be neglected. Anyway sorry I don't mean to be toxic or anything just trying to get to the bottom of things and really hoping this can get fixed or sorted out soon.

### Mod Loader

Forge

### Minecraft Version

1.12.2

### Version

5.7.1

**Comment by mysticdrew** [comment]
Ahh sorry forgot to comment on this. 

So... that entity names toggle is miss-named. It should be custom entities that have custom name tags set by the server. Generally this is only done by rpg servers. 

However, in 1.21+ we have names and selections for all kinds of entity types to show their names. This will not be back ported to 1.12.2. Sorry.
