### ISSUE TITLE
[Bug]: Not showing the cave biome

### ISSUE THREAD

**Issue by Ashleighlovesyou** [TeamJM/journeymap#805]
### What happened?

spoke to someone on Discord about not being able to see the cave biome I'm at but it tells me the block I'm on and the biome above ground eg. plains and birch forest. 
![dede](https://github.com/user-attachments/assets/ebf99d3b-e4fe-4eaa-8e65-8b48e5b4f80e)

### Mod Loader

Forge

### Minecraft Version

1.20.1

### Version

other (please list)

### Relevant log output

[journeymap.log](https://github.com/user-attachments/files/17352705/journeymap.log)
[latest.log](https://github.com/user-attachments/files/17352706/latest.log)

**Comment by mysticdrew** [comment]
What does the info slot say under the minimap for your biome?

**Comment by mysticdrew** [comment]
![image](https://github.com/user-attachments/assets/76df2303-f96a-4d2f-ac0a-80db1e2ca035)
![image](https://github.com/user-attachments/assets/33b8cb2a-1c13-4f31-88da-7e23a171581f)

I do notice when mousing around the map on the black areas it is kind of inconsistent, sometimes it displays the cave biome, other times the surface biome.

**Comment by mysticdrew** [comment]
I made some improvements in this for jm v6.
