### ISSUE TITLE
[Bug]: Journeymap is sending too many ServerPlayerLocationPacket

### ISSUE THREAD

**Issue by someaddons** [TeamJM/journeymap#806]
### What happened?

![image](https://github.com/user-attachments/assets/f20b54cd-0569-448a-8d70-b540c3d249c6)
20 player server, that data is recorded for 5 minutes. 775k packets in five minutes and using ~180kb/s for it seems too high for what it actually should use. I'd suggest to only send one packet per second

### Mod Loader

Forge

### Minecraft Version

1.20.1

### Version

5.10.0

**Comment by mysticdrew** [comment]
This is configurable
https://teamjm.github.io/journeymap-docs/latest/Server%20Docs/settings/global-properties/

**Comment by mysticdrew** [comment]
![image](https://github.com/user-attachments/assets/947b395f-950a-496a-9ad2-cef9c34155ce)

**Comment by someaddons** [comment]
That might be broken then, 5 minutes = 5 * 60 * 20  = 6000 ticks. We are using the default tickrate setting of 5, so 6000/5 = 1200 Updates. At 20 players I guess one update sends a packet to every player, so it should be in the ballpark of ~1200*20 = 24000
sent packets. 
But it does send like 770000 packets instead.

E.g. compared to the vanilla chunk packets, which seems much more reasonable:
![image](https://github.com/user-attachments/assets/56365c56-4e08-4bd9-8b58-d3e8cf1ec53d)
@mysticdrew

**Comment by mysticdrew** [comment]
Forge is likely splitting the packets into multiple parts. 
Due to the amount of players it will increase the packet size so forge will split up a single packet into multiple packets to stay within the packet size bounds. 

Set update time to 20 tickets, that should reduce it a lot so it sends update once every second like you suggested.  I made this configurable so servers can update based on their needs.

**Comment by mysticdrew** [comment]
What are you using to monitor packets?

**Comment by someaddons** [comment]
my own mod Connectivity does have network stat commands

**Comment by someaddons** [comment]
Forge only splits large packets, to account for the max packet sizes btw, small packets like this(0.07kb) wont get split

**Comment by mysticdrew** [comment]
I can look into optimizing it in future versions. 1.20.1 will likely not get any more updates as my primary focus is on journeymap v6 for 1.21+

**Comment by someaddons** [comment]
kk, thats fine :) Just making sure it gets looked at, as the amount of packets seems buggy

**Comment by mysticdrew** [comment]
> kk, thats fine :) Just making sure it gets looked at, as the amount of packets seems buggy

It's not buggy, it is unoptimized. We do not batch the packets up very much. Many times it is one or two player locations to each player. So it ends up being too many.
