### ISSUE TITLE
[1.12.2] Cartography: Ignore Glass Ceilings set to false

### ISSUE THREAD

**Issue by Acters** [TeamJM/journeymap#81]
#### JourneyMap Version:

1.12.2-5.5.3

#### Forge Version:

1.12.2-14.23.5.2768

#### Describe the problem in repeatable steps:

1. load up a world and set Cartography: Ignore Glass Ceilings to false
2. dig underground
3. make a glass ceiling that has visible sky from underground
4. walk under glass ceiling to notice minimap switching from cave mode to day/night

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:
None.

This issue affects me greatly in my StoneBlock FTB Pack world where I dug up to the sky lava and used glass to stop the flow for solar panels. Just having a minimap that displays orange is unhelpful. I thought this option would fix it but I don't see any difference in the JourneyMap.

**Comment by mysticdrew** [comment]
@Acters what kind of glass, normal vanilla glass or glass from a mod?

**Comment by Acters** [comment]
I had only vanilla glass back then. I used other mod's glass in the stone block modpack recently, too.

**Comment by mysticdrew** [comment]
I have no idea who or what the stone block modpack is or what mods it contains. I need to know what mod and what glass caused the issue. I will check the vanilla glass in 5.5.4 and see if I can replicate this bug. 

Also, there are mods that makes vanilla glass look better by turning the glass from a block to a tileentity. That could cause the issue to happen.

**Comment by mysticdrew** [comment]
Wait.. you said you set ignore glass ceilings to false. Is that correct? If you set it to false, it does not ignore the glass and things you are underground. Which means it is working as intended. The box needs to be checked for it to not switch to cave mod. 

![](http://puu.sh/D8NxL/76394396c8.png)

**Comment by Acters** [comment]
"Ignore Glass Ceilings 	
Being under a glass roof will not switch to cave mapping 	
Default: true"
This is the setting. I wish for it to not ignore glass ceilings and keep cave mapping. Of course this does not mean it will stay on cave mode but hoped it would.
I used a fresh install of forge and only journymap. I used vanilla glass as the ceiling underground.

**Comment by mysticdrew** [comment]
I see that, I just tested and went under a glass tile in a cave and it switch off cave mapping. i will see this is fixed, thanks!

**Comment by mysticdrew** [comment]
Just verified, this is working as intended in 1.16.5
