### ISSUE TITLE
[Bug]: Extremely High Memory Usage

### ISSUE THREAD

**Issue by Squydy** [TeamJM/journeymap#813]
### What happened?

Opening the full screen map with a large world uses large amounts of memory, in the order of gigabytes. On a 40k x 40k world with a full map it can easily use >10gb. When closing and reopening the map memory never gets cleared and it can start using >50gb and will eventually crash the game.

### Mod Loader

Fabric

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

[journeymap.log](https://github.com/user-attachments/files/17482792/journeymap.log)
[hs_err_pid19216.log](https://github.com/user-attachments/files/17482815/hs_err_pid19216.log)

**Comment by mysticdrew** [comment]
You have a lot of corrupt images and for some reason the system keeps trying to load them over and over I think.

**Comment by Squydy** [comment]
> You have a lot of corrupt images and for some reason the system keeps trying to load them over and over I think.

From a previous crash from testing, yes. Without the corrupt images this still happens tho.

**Comment by mysticdrew** [comment]
This should be much better with the next beta release. No eta yet, still have a few bugs to work out. 
If you want, pop into discord and I can give you a test version.

**Comment by mysticdrew** [comment]
fixed in beta.29, it will be available in CF/MR shortly. 

Please update if you still have issues with it. I noticed a significant drop in memory used. 
Minecraft in general was using 3gb with a 20k x 20k map zoomed out to show the whole map.
