### ISSUE TITLE
[Bug]: White-ish overlay on map

### ISSUE THREAD

**Issue by HellBr3ad** [TeamJM/journeymap#815]
### What happened?

![image](https://github.com/user-attachments/assets/eb684d0c-d0db-4d42-b716-58f011778109)
There's a bug with rendering block color/lighting and it causes the map to be covered in that weird white overlay on most blocks. The blocks in-game look completely normal, this is just an old growth taiga biome and it has vanilla blocks on the surface.

Technically it's not only a JourneyMap problem, Xaero's was the same (they just straight up refuse to take in my issue for some reason). I imagine it is caused by some kind of compatibility issue, but I have no idea what that could be.

This is my modlist:
[modpack.txt](https://github.com/user-attachments/files/17530198/modpack.txt)

### Mod Loader

Forge

### Minecraft Version

1.20.1

### Version

5.10.0

### Relevant log output

[2024-10-26-1.log.gz](https://github.com/user-attachments/files/17530210/2024-10-26-1.log.gz)
[journeymap.log](https://github.com/user-attachments/files/17530211/journeymap.log)

**Comment by mysticdrew** [comment]
You will need to figure out what mod is causing that.

**Comment by HellBr3ad** [comment]
Damn, I was hoping you've encountered that before... I'll try to find something then and will post an update.

**Comment by mysticdrew** [comment]
Yea never seen that. 
So some things that "may" be causing it. 
A mod is changing the biome tinting? Which is applied to grass and leaves, so that is why the color is off. 
So maybe try removing mods that do things to biomes as a start? 

There is always the binary search method. 

I would create a new world if you want to preserve your existing world for testing. 

```
The binary search is a way of finding a faulty thing among a lot of other things, without having to remove the things one-by-one.
This is useful for finding a broken mod among hundreds of mods, without having to spend time testing the mods one-by-one.
The procedure is simple:
  1. Remove half of the existing things, and put them aside.
  2. Run the program / game.
  3. Does the issue still exist?
    If YES: Repeat from step 1 with the current things.
    IF NO: Swap out the current things with the ones set aside, and repeat from step 1.
  4. Repeat this process until the problematic thing/s have been found.
```

**Comment by HellBr3ad** [comment]
I found it! It is something caused by Destroy and its library Petrolpark. It's worth mentioning that it didn't happen before I updated it to 0.10.0 version. I will report the bug to their github as well.

**Comment by mysticdrew** [comment]
Closing since it is not a journeymap issue, seems this problem effects all map mods and both the mods that increase render distance like distance horizons.
