### ISSUE TITLE
[Crash]: Crash on client startup after update to beta28

### ISSUE THREAD

**Issue by X-Machiavelli** [TeamJM/journeymap#817]
### What happened?

If Journeymap is disabled or rolled back to a previous version, it will work again. I will attach the crash report and log file below.
the specs are NeoForge 21.1.72, Journeymap 6.0.0 beta28.

### Mod Loader

NeoForge

### Minecraft Version

1.21.x

### Version

6.0.0

### Relevant log output

[crash-2024-10-27_20.27.45-client.txt](https://github.com/user-attachments/files/17533672/crash-2024-10-27_20.27.45-client.txt)
[latest.log](https://github.com/user-attachments/files/17533673/latest.log)

**Comment by mysticdrew** [comment]
You are using journeymap for 1.21.3, but running mc 1.21.1

**Comment by Bentleybear179** [comment]
The 1.21.3 update appears to be labelled as 1.21.1 compatible on curseforge. Is this changeable? I noticed this issue earlier.
