### ISSUE TITLE
[1.20.2-5.9.21]: Pixelmon Interaction Causing Blurred Sprites

### ISSUE THREAD

**Issue by Chilled-Maple** [TeamJM/journeymap#818]
### What happened?

When using the latest version available of JourneyMaps for Forge [1.20.2-5.9.21] with the latest Pixelmon version [1.20.2-9.2.9] there seems to be an issue involving the sprites of the Pokémon with mob icons enabled. When a Pokémon is sent out of its Pokéball or spawns naturally, or otherwise has its mob icon loaded onto the JourneyMap map, the sprite for the Pokémon both on the map and in the player's party or other GUIs, such as the PC or the Daycare, becomes blurred. The sprites will not blur until they are loaded onto the map. When JourneyMap is not installed, sending a Pokémon out of its ball or otherwise being near wild Pokémon does not blur their sprite. This issue persits until the player's instance is closed as saving and closing the world, or disconnecting and reconnecting, does not solve the issue. Below are some images of what a sprite looks like before and after the blur occurs.

To recreate:
1. Install the latest versions of JourneyMap [1.20.2-5.9.21] for Forge, and Pixelmon [1.20.2-9.2.9]
2. Load into a world (singleplayer or multiplayer)
3. Select your starter and then ensure mob icons are enabled for JourneyMap
5. Note the sprite icon on the left side of the screen prior to sending out the Pokémon
6. Send out your Pokémon using the 'R' key (default keybind to send out Pokémon in Pixelmon)
7. Note the sprite icon on the left side of the screen after sending out the Pokémon is now blurred

Pre-Map Loaded Blurring of the Sprite:
![image](https://github.com/user-attachments/assets/8f920bca-ee60-464b-a10c-b6ea4f932d07)

Post-Map Loaded Blurring of the Sprite:
![image](https://github.com/user-attachments/assets/a222fe51-d5fe-4c19-91fd-6cc266bd82fb)

### Mod Loader

Forge

### Minecraft Version

1.20.2

### Version

5.9.x

### Relevant log output

[journeymap.log](https://github.com/user-attachments/files/17550748/journeymap.log)

**Comment by mysticdrew** [comment]
1.20.2 is long out of support. 
If the problem still occurs when pixelmon is on a 1.21+ we can address it then.
