### ISSUE TITLE
[Bug]: Info slots do not render when using Journeymap with the latest Fabulously Optimized Modpack for 1.21.3

### ISSUE THREAD

**Issue by Chromeyyy** [TeamJM/journeymap#820]
### What happened?

As the title says.

### Mod Loader

Fabric

### Minecraft Version

1.21.x

### Version

6.0.0

**Comment by mysticdrew** [comment]
provide a link to said modpack please

**Comment by mysticdrew** [comment]
Disable Immediately Fast and see if that resolves it please.

**Comment by Chromeyyy** [comment]
Yeah it works. A lot of mods have incompatibility issues this update and idk why. Thanks m8

**Comment by Chromeyyy** [comment]
Also, when i use automap, the entire game turns black. font becomes black and tooltips become black. all textures are dark and i cant see anything. have to restart the game to remove this weird effect.

**Comment by mysticdrew** [comment]
> Also, when i use automap, the entire game turns black. font becomes black and tooltips become black. all textures are dark and i cant see anything. have to restart the game to remove this weird effect. Also after some time, the game crashes.

is this with only journeymap? 
Likely another mod incompatibility issue. I would need to know what mod.

**Comment by mysticdrew** [comment]
I pushed beta.29, it fixes the Immediately fast issues. 
If the black issue still persists, please create a new issue regarding it.
