### ISSUE TITLE
[Bug]: [1.21.x] Waypoint tp-ed to always immediately repositioned higher so that it can be open to the sky

### ISSUE THREAD

**Issue by Bumblebee202111** [TeamJM/journeymap#822]
### What happened?
See the title.
Both the waypoint position and the destination of current tp are changed unexpectedly.
"Tp" = JM waypoint teleport, not the command
Tested artifacts:
journeymap-1.21.3-6.0.0-beta.29+neoforge
journeymap-1.21.3-6.0.0-beta.28+neoforge
> Edit: 
journeymap-1.21.1-6.0.0-beta.28+neoforge
journeymap-1.20.6-5.10.0-neoforge (NO BUG)

And this bug happpens in both my exisiting MC instance and a "clean" test instance.
Sorry my English is bad and I don't use Discord.

### Mod Loader

NeoForge

### Minecraft Version

1.21.x

### Version

6.0.0

**Comment by Bumblebee202111** [comment]
> I am sorry, I do not really understand what is happening. I tested a bunch of waypoint teleporting and all seemed normal.
Like if there is any non-air block above a waypoint, when you try to teleport to it, journey map will choose the position just above the highest non-air block as the new waypoint position and overwrite the old one, so the waypoint is higher now even though you don't actively modify it. The steps are easy, maybe I just didn't decribe it well. If you test and see no problems with journeymap-1.21.3-6.0.0-beta.29+neoforge, I guess it's the problem of myself and not a bug of the mod.
> I need video or screenshots to explain better I think.
Sry not convienient now, might further verify and post later
> What do you mean by a "clean" test instance? Meaning no mods other than journeymap?
Yep

**Comment by mysticdrew** [comment]
How are you creating the waypoint? 

Yes generally when you create a waypoint from either doubleclicking, rightclicking, or pressing B on the fullscreen map it auto selects the top most block to create the waypoint, this is intended. You can adjust the Y value in the screen that pops up to create the waypoint.

**Comment by mysticdrew** [comment]
When you right click to teleport on the fullscreen map, it makes an attempt to put you above the top most block so you do not teleport into the middle of the block and suffocate.

**Comment by Bumblebee202111** [comment]
> on the fullscreen map

No I didn't. I created them from my feet.

> When you right click to teleport on the fullscreen map, it makes an attempt to put you above the top most block so you do not teleport into the middle of the block and suffocate.

I knew

> However, if you teleport to a waypoint, no matter where you have the y level, it will teleport you to that waypoint's y level, even if in the middle of the block.

No it didn't. :(

Screenshots are below. I also found that there is very small chance that the bug don't reproduce.

1-Original-waypoint
![1-Original-waypoint](https://github.com/user-attachments/assets/7a820f7a-c25d-48d7-b6ab-36c099f8ad15)

2-How-I-tp (same when I tp from waypoint list)
![2-How-I-tp](https://github.com/user-attachments/assets/09c14b78-fdd1-4bb3-b544-c7112896ef06)

3-View-downward-after-tp
![3-View-downward-after-tp](https://github.com/user-attachments/assets/d561389c-f1a9-4965-918f-d3f8837b8226)

4-waypoint-auto-changed-after-tp
![4-waypoint-auto-changed-after-tp](https://github.com/user-attachments/assets/4e00d953-669f-42d0-99b8-ea0729c652bb)

I'm downloading older versions to check if it is a thing since then. I didn't remember it ever happened earlier.

**Comment by Bumblebee202111** [comment]
I can confirm this bug is introduced in 6.0.0-x as journeymap-1.20.6-5.10.0-neoforge works normally but journeymap-1.21.1-6.0.0-beta.28+neoforge does not.

**Comment by mysticdrew** [comment]
I found the issue and looking at the code, it should have been an issue in 5.8.5+, not sure why it is not.

**Comment by mysticdrew** [comment]
fixed in 6.0.0-beta.30
