### ISSUE TITLE
[Bug]: replace with description

### ISSUE THREAD

**Issue by TRO-Gama** [TeamJM/journeymap#823]
### What happened?

so i had this strange bug where my waypoint displayed as red and green square, i saw a similar issue on reddit with no soluce unfortunatelly, i'm running journey map on version 5.10 i  believe

### Mod Loader

Forge

### Minecraft Version

1.20.1

### Version

other (please list)

**Comment by mysticdrew** [comment]
![image](https://github.com/user-attachments/assets/2f4bff0a-240f-43f7-9138-04799c3cf72c)
