### ISSUE TITLE
[Bug]: Font Scaling not working for 1.21.1

### ISSUE THREAD

**Issue by gomicat** [TeamJM/journeymap#828]
### What happened?

Basically this. I am running my PC's resolution at 2k to 4k and when using the map the font is itty bitty hah. I went into options and used the font scale slider and turned it all the way up to 3, and the text size did not seem to increase. 

### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Version

6.0.0

**Comment by mysticdrew** [comment]
What font and what slider? We have several font sliders

**Comment by gomicat** [comment]
I did finally find a separate slider and it worked out ok, whoops! The initial problem was trying to run it with iris+sodium vs just fabric. :)

**Comment by mysticdrew** [comment]
Ahh great. 
I'll close this now, take care.
