### ISSUE TITLE
[Bug]: Automapping doesn't work

### ISSUE THREAD

**Issue by jpeaglesandkatz** [TeamJM/journeymap#829]
### What happened?

1.21.1 Automapping does not work... Clicking the 'wand' and choosing 'All'does nothing.... 
This is on a standard All the Mods 10 pack btw.

### Mod Loader

NeoForge

### Minecraft Version

1.21.x

### Version

6.0.0

**Comment by jpeaglesandkatz** [comment]
> any logs? What beta version are you on?

Sorry... 
journeymap-neoforge-1.21.1-6.0.0-beta.29.jar
default ATM10 latest release... neoforge 21.1.77

This is the client log.. If you need my server log, let me know.. Thanks
[latest.log](https://github.com/user-attachments/files/17791193/latest.log)

**Comment by jpeaglesandkatz** [comment]
Well..... ok then... Well I am connecting to my server so that would explain why it is not working....  Haven't tested this single player on this version... Not sure why it is not working on multiplayer but hopefully then, that will come in the future... It is kind of useless seeing half your map black and invisible ....

**Comment by mysticdrew** [comment]
Automap reads the files on disk. 
That is not possible when in mutliplayer since the region files are on the server, not the client. 
There is  no way I would ever start sending the whole world from the server to the client. 

The button should be disabled in multiplayer though. 
If you have access to the server files, you can load up the world in singleplayer to automap it. 

https://teamjm.github.io/journeymap-docs/latest/Tools%20and%20Customisation/multiplayer-server/

**Comment by jpeaglesandkatz** [comment]
> Automap reads the files on disk. That is not possible when in mutliplayer since the region files are on the server, not the client. There is no way I would ever start sending the whole world from the server to the client.
> 
> The button should be disabled in multiplayer though. If you have access to the server files, you can load up the world in singleplayer to automap it.
> 
> https://teamjm.github.io/journeymap-docs/latest/Tools%20and%20Customisation/multiplayer-server/

Gotcha.. yeah I figured that was the reason.. Although in case of  a LAN server that wouldn't be much of an issue most of the times (speed / data transferred should be ok)...   But I can understand why you wouldn't invest time in making that happen.

I have done what you suggested.. Just load the world in SP... Automap.. I assume I can transfer it back to my server later and copy over the data files from the client into the correct mp/ folder and that would work...

Sorry for not stating more clearly in my OP that it was about a server game.
