### ISSUE TITLE
[1.12.2] Fullscreen Map keys erroneously conflict with main interface keys

### ISSUE THREAD

**Issue by MentalMouse** [TeamJM/journeymap#83]
#### JourneyMap Version:

1.12.2-5.5.3

#### Forge Version:

1.12.2-14.23.5.2768

#### Describe the problem in repeatable steps:

When selecting key controls with the options screen, keys for use within the pop-up map are marked as conflicting with keys used in the main game interface, including the same keys used as waypoint/minimap commands.  These are not actual conflicts because they are restricted to a different mode, but the extra conflict markers make it that much harder to sort out genuine conflicts over those keys.

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

none.

**Comment by NickelHub** [comment]
That is not a bug in JourneyMap. That is more a bug in Minecraft not distinguishing between different modes. This is actually a thing across mods not only JourneyMap.

**Comment by mysticdrew** [comment]
Not a journeymap issue.
