### ISSUE TITLE
FPS drop on latest version

### ISSUE THREAD

**Issue by dheoxic** [TeamJM/journeymap#835]
### What happened?

20-30% FPS drop. Gets worse [almost 50%] if you load/unload resource packs [any resource pack]. 

### Mod Loader

NeoForge

### Minecraft Version

1.21.x

### Version

6.0.0

**Comment by mysticdrew** [comment]
"latest version" ?

**Comment by NickCloudAT** [comment]
Can reproduce, Journeymap version 1.21.3-6.0.0-beta.30

**Comment by mysticdrew** [comment]
6.0.0-beta.31
Will fix this issue, it should be available on CF/MR sometime in the next 15-20 minutes
