### ISSUE TITLE
[Crash]: JourneyMap for newest version does not work

### ISSUE THREAD

**Issue by hvrtfvl** [TeamJM/journeymap#837]
### What happened?

So the newest update of the map for forge simply does not work. First I tried to run it with the newest forge version, it crashed. In the requirements it said it needs forge 54.0.0, so I went ahead and downloaded that one. I thought my issue would be fixed but it still crashed. Anyone else also experiencing this? 

### Mod Loader

Forge

### Minecraft Version

1.21.x

### Version

6.0.0

**Comment by mysticdrew** [comment]
update beta.32

**Comment by hvrtfvl** [comment]
> update to beta.32

how do i do that?
