### ISSUE TITLE
1.12.2 waypoint manager getting stuck

### ISSUE THREAD

**Issue by jusitnboggs** [TeamJM/journeymap#84]
#### JourneyMap Version:

`JM 1.12.2-5.5.3
last time I used 5.5.2 it was happening as well.
#### Forge Version:

`Example: 1.12.2-14.23.5.2807`

#### Describe the problem in repeatable steps:

When going through the waypoint manager viewing the different Dimensions it gets stuck on one called planet which I am guessing comes from adv rocketry.

**Comment by mysticdrew** [comment]
Is this still an issue with JM 5.5.4?

**Comment by jusitnboggs** [comment]
Sorry took a short break from MC 

I using journeymap-1.12.2-5.5.5b7 and it is still getting stuck. Should I try 5.5.4?

**Comment by mysticdrew** [comment]
What mod is "planet" from?

**Comment by jusitnboggs** [comment]
Advanced Rocketry
    On Saturday, July 6, 2019, 10:16:13 AM PDT, mysticdrew <notifications@github.com> wrote:  
 
 
What mod is "planet" from?

**Comment by mysticdrew** [comment]
This was resolved with beta 8. Please test with the latest beta (currently 9).
