### ISSUE TITLE
[Bug]: bug found with waypoint icon texture (rombus, X, etc)

### ISSUE THREAD

**Issue by gitterbitter-cert** [TeamJM/journeymap#842]
### What happened?

(file version: 5.9.18) I've been playing with journeymap for a while and, there's this thing that has been annoying me since I started using this mod. The bug I am trying to report is the icon texture being a square instead of the usual one. It appears as a square, with a line down the middle, with each triangular side being one green and one red, as seen in the following screenshot:
![Screenshot 2024-12-13 184234](https://github.com/user-attachments/assets/9e2dccc5-5c2d-4491-ab00-498296d07952)

### Mod Loader

Forge

### Minecraft Version

1.21.4

### Version

6.0.0-beta.x - Specify Beta version

**Comment by mysticdrew** [comment]
Update your issue with the correct versions. 
Second, do not paste contents of logs. Upload the files directly.

**Comment by gitterbitter-cert** [comment]
yeah mate, sorry about that. i tried to upload the version of it but, even when i changed it (like said in requirements) it still shows that texture.
