### ISSUE TITLE
[Bug]: 1.20.1 Toolbar background only uses "begin" image

### ISSUE THREAD

**Issue by DedMaxim** [TeamJM/journeymap#844]
### What happened?

I want to make my own JM theme for my modpack. However, I never done it before and, as an exercise, I decided to re-add Vault theme myself. I extracted old theme from 1.7.10 version and also 2 updated versions from 1.21.4, 6.0.0 version of the mod. For some reason, no matter width and height values, "begin" texture gets stretched the whole size of the toolbar:
![image](https://github.com/user-attachments/assets/240a11fb-9336-4624-978b-a55a84a38f04)

This is the case with default Purist theme as well, if alpha is set to 1 for "begin" texture. This also affects both old and new versions of the Vault theme. Looks fine with flat theme but that is expected:
![image](https://github.com/user-attachments/assets/9f7bcfbb-0b5a-4d7a-845f-c7c7434d35ee)

All 3 themes:
[vault_themes.zip](https://github.com/user-attachments/files/18137059/vault_themes.zip)

Environment:
Windows 10 22h2
Minecraft 1.20.1
Forge 47.3.5
Journeymap 5.10.3

### Mod Loader

Forge

### Minecraft Version

1.20.1

### Version

5.10.0

**Comment by mysticdrew** [comment]
This a known issue and fix will not be backported. 
There are technical reasons
