### ISSUE TITLE
[Crash]: Instant crash when using as forge (runtime) runtime dependency on plain forge-mdk (1.20.1-47.3.0)

### ISSUE THREAD

**Issue by clyce** [TeamJM/journeymap#845]
### What happened?

1. unzip forge-1.20.1-47.3.0-mdk
2. add `flatDir {dir 'libs'}` into build.gradle->`repostories`
3. set `runtimeOnly fg.deobf("flat:journeymap:${project.journeymap_version}-forge")` in dependencies
4. put `journeymap-1.20.1-5.X.X-forge.jar` into `libs` (Tried out 5.9.20, 5.9.9, 5.9.8)
5. Start the `forgegradle runs -> runClient` task
6. Instantly crash with the error logs attached

### Mod Loader

Forge

### Minecraft Version

1.20.1

### Version

5.9.x

### Relevant log output

[latest.log](https://github.com/user-attachments/files/18141245/latest.log)

the `journeymap/journeymap.log` and `crash-reports/{}.txt` is not generated.

**Comment by mysticdrew** [comment]
you need to disable refmaps indev

**Comment by mysticdrew** [comment]
```
            // needed for deps with mixins.
          properties 'mixin.env.disableRefMap': 'true'
            property 'mixin.debug.export', 'true'
            property 'mixin.env.refMapRemappingFile', "${buildDir}/createSrgToMcp/output.srg"
```
in your run config for forge I think.

**Comment by clyce** [comment]
OK solved, thank you!
