### ISSUE TITLE
[Bug][1.21.4]: JourneyMap and VulkanMod break terrain rendering

### ISSUE THREAD

**Issue by Joniprog** [TeamJM/journeymap#848]
### What happened?

I installed JourneyMap 6.0.0-beta.32, VulkanMod 0.5.2 and Fabric API 0.112.2 (nothing else) and entered the game. I then observed that the terrain was completely absent. This is consistently reproducible on my machine.

![2024-12-22_17 18 47](https://github.com/user-attachments/assets/93c79e00-5185-4986-b036-2cc51b58ef4e)

### Mod Loader

Fabric

### Minecraft Version

1.21.4

### Version

6.0.0-beta.x - Specify Beta version

**Comment by mysticdrew** [comment]
Oops didn't mean to close it. 
Known issue, I'll working with vulkanmod's dev on resolving this

**Comment by mysticdrew** [comment]
VulkanMod dev released a new version that will fix the issues
