### ISSUE TITLE
[Bug] Topografic config suggestion for next update

### ISSUE THREAD

**Issue by DragonflySara** [TeamJM/journeymap#85]
Mysticdrew asked me to add this to github. Hope my info helps you all improve.
---
  
#### JourneyMap Version:

JourneyMap 1.12.2-5.5.3

#### Forge Version:

Forge 14.23.5.2768

#### Describe the problem in repeatable steps:

1. If you open journeymap.topo.config and set "showContour": "false", curently the pixels where the contour would be turn invisible.
2. If we are trying to create a heightmap by doing this, the problem is made even worse, however, this may be an easy fix.
3. If this setting made it so every block was the color selected for it's height, including the "contour" then a height map would be exactly what a grey scale selection would create, The if the contour was set to true, the outside of each color selection would be set to the countour colors. 

This would mean the contour true image would appear as it does not, but the contour false image would not have the transparent lines.

#### Admin Edit
Setting contour lines to false in the configs caused the topo map to not map and spammed NPE.

**Comment by mysticdrew** [comment]
Is this what you're looking for? (Contour disabled in configs)
![](http://puu.sh/Da4UL/98ad121d97.png)

with contour enabled in the configs
![](http://puu.sh/Da50o/ee70ee8940.png)

Initially when I set contour to false in the configs, it did not map. It just spammed a bunch of NPE.

**Comment by mysticdrew** [comment]
Fixed for 5.5.5

**Comment by DragonflySara** [comment]
Perfect. Thank you so much.
