### ISSUE TITLE
[Bug]: Hotkeys override/block in-game keys

### ISSUE THREAD

**Issue by Irmitya** [TeamJM/journeymap#850]
### What happened?

`journeymap-fabric-1.21.4-6.0.0-beta.32`
I was using Minecraft `1.20.4`, then I updated today. 
Now, when a hotkey elsewhere is reused for Journeymap, the hotkey will not work for the other thing. 

For example, [Swap Item] as {F}, is JourneyMap's [Follow Player]. Items can't be swapped using {F} outside of the inventory. 
Setting [Follow Player] to {E}, the [Open Inventory] key, you then can't open the inventory.

### Mod Loader

Fabric

### Minecraft Version

1.21.4

### Version

6.0.0-beta.x - Specify Beta version

**Comment by mysticdrew** [comment]
this is not a journeymap issue, this is a vanilla minecraft issue. 
Conflicting keys only work for the very last action they are registered. 
you probably had amecs installed previously which allowed multiple actions per keybind. 

You will need to use emecs or too many shortcuts to fix this.
