### ISSUE TITLE
[Feature Request] Alternate waypoint textures

### ISSUE THREAD

**Issue by SextupleTap** [TeamJM/journeymap#87]
This new feature would make it so that when you make a waypoint, you also have the ability to select a texture for it (what icon it is, and then the current icon in journey map will be the default), that's basically it! You could also add your own waypoint textures for large varieties of icons to help specify locations even more than just by reading their names. Most likely the default icon would still be the only one at first, it's just users would have to ability to put in more waypoint icons, good for Modpack purposes or some extreme adventuring.

_Maybe, you could also potentially select whether the color you have selected will mask onto the waypoint or not (for if you have wayoints that are pre colored), this one isn't as big for me though._

**Comment by mysticdrew** [comment]
So, as of journeymap 5.8.0 beta8, addons can do this. This will eventually be included in Journeymap proper, but I need to rewrite the waypoint UI, and it will be included when we get to waypoint grouping. 
I am going to close this for cleanup. But, this will be implemented. In a version post 5.8.0.
