### ISSUE TITLE
[1.12.2] Web map auto-center disables on focus-loss

### ISSUE THREAD

**Issue by Inve1951** [TeamJM/journeymap#90]
#### JourneyMap Version:

`1.12.2-5.5.4b7`

#### Forge Version:

`1.12.2-14.23.5.2796`

#### Describe the problem in repeatable steps:

1. Enable web map and open it in browser
2. Hit the auto-center button
3. Give window focus to the game
4. Move in-game

E: Web map doesn't re-center on updates

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

none

#### Known workaround:

Click the auto-center button another time.
<br>
There also is no visual indication whether it's enabled/working while unfocused.

**Comment by mysticdrew** [comment]
I added a visual indication whether it is following or not. 

I did not notice any random unfollowing of the player though. Keep in mind, when you drag the map in the browser it automatically sets it to unfollowing. 

This will be in 5.5.5 Beta 6.
