### ISSUE TITLE
[Feature Request] Lock cave mode for minimap and display multiple vertical chunks at once

### ISSUE THREAD

**Issue by Lalarian** [TeamJM/journeymap#91]
Hello!

I could use the folloing feature very much: Lock the minimap on a special vertical chunk, so I can fly over the world and identify where there are underground structures. At the moment the minimap always switches to surface mode (I even tried disabling the auto Night/Day feature, but this probably is just for daytime related changes).
And it would be even better if there was a merge mode, that displayed a specified range of vertical chunks together, like for example chunks 0 to 6 so I can monitor the whole underground.
It woudl be great if you could add these parameter sets :)
Thnak you!

**Comment by mysticdrew** [comment]
Sounds like you want an x-ray mod.. we are not it.

**Comment by Lalarian** [comment]
I don't raaly know,  what exactly you mean with x-ray. But what I needed to do, was trimming a very old map (from early beta times) of me and some friends of mine, so that there is a chance for freshly generated chunks closeby to the centre, where our old hours are located. It's too annoying having to go very far away, for having a chance for modern resources, including mod packs, that haven't been there when all those chunks have once been generated. So I wanted to fly over the world and to use worldedit for removing all chunks, that had no structures on top or below surface. In the current state this is not practiable with journeymap, because you can only see a vertical part of each chunk.

So, what I suggest is nothing but the addition of a selectable parameter for already existing features.

**Comment by mysticdrew** [comment]
"you can't have it set to cave mode while being above the surface" you are correct and that is intentional and will not change for now. I will discuss it with techbrew when I get a chance, he has the ultimate say in it.

**Comment by Lalarian** [comment]
I do not exactly understand why not. I don't think it has ever been a good pratice to artifically limit software capabilitites, especially when it comes down to very little effort for a huge benefit in usefulness. What is the reason to no implent this?

**Comment by mysticdrew** [comment]
If you can map out all the caves without going into the caves, that is what the x-ray mods do.. Cheating. 

Please do not tell me what is very little effort, you have no idea what it would take to implement this feature.

I get you have a non-cheat use case for this, but this feature would be abused like crazy.

**Comment by Lalarian** [comment]
I do not need to see 'naturally' generated caves. It's all about known undergound structures, like all the branch mines and such that have been built by us. I do not want to see anything, that Journey Map doesn't already show anyway. It just doesn't show it the moment when I need it (because it's switching from cave mode to surface mode automatically when I am on the surface or higher.)

**Comment by mysticdrew** [comment]
Oooh, I see what you're saying now. Thanks for explaining a bit clearer. 

Fullscreen has this feature already, when you hover over the cave mapping there is a slider for which v-chunk to see. I wonder why the mini-map does not have this, I will look into it and see if it something I can implement.

**Comment by Lalarian** [comment]
Thank you!
Just one hint, on how you could place this:
As  user I was searching for an option like "Lock to cave mode" in "MiniMap Presets 1/2, next to  "Show Day/Night". So I think this could be an adequate place for implenting this feature. This feature also would require to show the vertical chunks 1 to 4 simultaneously, as of the use case.

**Comment by mysticdrew** [comment]
![image](https://user-images.githubusercontent.com/5459941/210154176-4d500364-0e87-4b8d-84aa-1fadd36a9d3a.png)
![image](https://user-images.githubusercontent.com/5459941/210154179-42c5dfe1-7ddd-428d-84f6-1bc3a86cbf7d.png)

This is added for the next release. 
Ability to select map type and if underground is selected, ability to lock the slice. 
However, it is impossible to display multiple vertical chunks. The way underground mapping is done, is we compress a vertical slice, which 16 blocks for each slice from the bottom to the top of the world.

**Comment by mysticdrew** [comment]
Cleaning up the issue tracker
Closing as this is completed for JourneyMap v6 when it is released.
