### ISSUE TITLE
[Feature Request] Expanding sorting system for waypoints.

### ISSUE THREAD

**Issue by MastaNub** [TeamJM/journeymap#92]
Currently we can only sort our waypoints by either distance or their names. I would greatly appeciate expanding sorting system by adding custom sorting because having a lot of waypoints is painful.
-Sorting by colours.
-Moving each individual waypoint with arrows (kinda like resource packs).
-Creating categories, which could have a dropdown (something like channel categories on discord /shrug).
-Disabling categories.
-Syncing waypoint colours. 
It's been a year since #28 do something about it 😦

**Comment by Fevix** [comment]
I'd expand even further on this: 
Allow us to set a 'master' waypoint for a group of waypoints, then when you get close enough, the sub-points show up and the master hides

For example, on giant maps, you could have a single waypoint for a City in the distance, but as you get close to the city, the City waypoint vanishes, replaced with various waypoints for shops, rentable areas in the city, landmarks, etc. 

Alternatively, this could be done by letting us select a min/max distance for each waypoint individually, though this would add more steps for the end user.

**Comment by mysticdrew** [comment]
@MastaNub it has been a year, but you are not our boss. You can ask, but do not tell us what to do! We do this for free as a hobby. 

It has been planned for waypoint grouping. It was started with 5.6.0 but there were some serious bugs with that beta version then real life happened to both us developers and we had no time to work on it. Modpacks were adding that very buggy beta to their production releases and causing a huge headache for us and them. Don't add beta mods to packs.. so it was pulled. We still plan on adding waypoint grouping in the future. But you will get it when we have time to implement it. Right now I have some time for small bug fixes and small features. 

However, in a month from now I will have no time for mod development so I will not take on the task of rewriting the waypoint system. Maybe at the end of summer or if Techbrew finds time before then, he can do it. But he is extremely busy with life.
