### ISSUE TITLE
[Feature Request] Add Dimensions to Info Slots

### ISSUE THREAD

**Issue by jaxmacky** [TeamJM/journeymap#93]
journeymap-1.12.2-5.5.4
 forge-14.23.5.2815

1. Add the ability to display what Dimension a player is in on the mini map via Info Slot

**Comment by mysticdrew** [comment]
What do you mean "Info Slot"? Do you mean below the mini-map?

**Comment by jaxmacky** [comment]
![Journey Map Info Slot](https://user-images.githubusercontent.com/8409769/55354092-719f5c00-548a-11e9-99b2-85b3ca8824c2.png)

Yes, below/above the mini map. Having Dimensions as an option to display in a given "Info Slot" as a lot of modpacks have multiple Dimensions.

**Comment by mysticdrew** [comment]
how about this? 
![Mini-map location](https://puu.sh/D8HhH/1641e9d8a4.png)

**Comment by mysticdrew** [comment]
This will be added in 5.5.5
