### ISSUE TITLE
 Waypoints not cycling

### ISSUE THREAD

**Issue by Notlucky101** [TeamJM/journeymap#94]
ok when I open  journey map and select waypoint,  I click on the dimension button and  start  going through the dimensions,  when I get to dimension  planet, that when things start to go wrong.  When I dimension planet then goes to the dim Aether,  after that it goes back to the planet and then stops. It does cycle back.
However when I close  waypoints and come back It will go through the same process

**Comment by mysticdrew** [comment]
- Not proper format please address.
