### ISSUE TITLE
[Feature Request] Add keybind for toggling Waypoint Beacons

### ISSUE THREAD

**Issue by ryankhart** [TeamJM/journeymap#95]
#### JourneyMap Version:

journeymap-1.12.2-5.5.4

#### Forge Version:

1.12.2 forge-14.23.5.2781

#### Describe the requested feature:

I want to be able to toggle the Journymap waypoint beacons on or off with the press of a customized keybind. When I press this key, I would expect it to either show or hide the waypoint markers overlayed on my screen as I explore the world.

This would be helpful for when I am at my base with no need to see these waypoint beacons. They can distract from what I am looking at, like a wall of storage drawers. I would prefer not to have all my waypoint icons floating in front of me as I browse that wall.

**Comment by mysticdrew** [comment]
Good Idea!

**Comment by mysticdrew** [comment]
Added in JM 5.5.5 for release.

**Comment by ryankhart** [comment]
Sweet! I'm looking forward to getting to use it. You're quick!
