### ISSUE TITLE
[1.12.2] Web map does not show chunks at long distances from spawn

### ISSUE THREAD

**Issue by bitbyte2015** [TeamJM/journeymap#98]
#### JourneyMap Version:

Example: 1.12.2-5.5.4

#### Forge Version:

1.12.2-14.23.5.2768

#### Describe the problem in repeatable steps:

1. Travel a long distance from spawn (around 92k in the +x direction)
2. Open web map
3. Notice that it is empty past 92k

![image](https://user-images.githubusercontent.com/36325823/55601586-2eade480-5727-11e9-9dfb-04f48ad9d0eb.png)

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

No logged info of importance

**Comment by mysticdrew** [comment]
known issue, the webmap is being rebuilt.
